[manager]
cwd = { fg = "#00c5c7" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffe700" }
find_position = { fg = "#ff2c70" }

marker_copied = { fg = "#3ad900", bg = "#3ad900" }
marker_cut = { fg = "#d90429", bg = "#d90429" }
marker_selected = { fg = "#ffe700", bg = "#ffe700" }

tab_inactive = { fg = "#c7c7c7" }
tab_active = { fg = "#1e1e3f", bg = "#c7c7c7"}

count_copied = { fg = "#1e1e3f", bg = "#3ad900" }
count_cut = { fg = "#1e1e3f", bg = "#d90429" }
count_selected = { fg = "#1e1e3f", bg = "#ffe700" }

border_style = { fg = "#6943ff" }

[mode]
normal_main = { fg = "#1e1e3f", bg = "#6943ff", bold = true }
normal_alt = { fg = "#6943ff", bg = "#f1d000" }

select_alt = { fg = "#ff2c70", bg = "#f1d000" }
select_main = { fg = "#1e1e3f", bg = "#ff2c70", bold = true }

unset_main = { fg = "#1e1e3f", bg = "#d90429", bold = true }
unset_alt = { fg = "#d90429", bg = "#f1d000" }

[status]
perm_exec = { fg = "#3ad900" }
perm_read = { fg = "#ffe700" }
perm_sep = { fg = "#00c5c7" }
perm_type = { fg = "#6943ff" }
perm_write = { fg = "#d90429" }

progress_error = { fg = "#d90429", bg = "#1e1e3f" }
progress_label = { fg = "#c7c7c7", bg = "#1e1e3f" }
progress_normal = { fg = "#c7c7c7", bg = "#1e1e3f" }

[pick]
active = { fg = "#ff2c70" }
border = { fg = "#6943ff" }
inactive = { fg = "#c7c7c7" }

[task]
title = { fg = "#6943ff" }
border = { fg = "#6943ff" }
hovered = { fg = "#c7c7c7", bg = "#f1d000" }

[input]
border = { fg = "#6943ff" }
selected = { bg = "#f1d000" }

[help]
desc = { fg = "#c7c7c7" }
on = { fg = "#00c5c7" }
run = { fg = "#ff2c70" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f1d000", bg = "#c7c7c7" }

[which]
mask = { bg = "#f1d000" }
desc = { fg = "#c7c7c7" }
cand = { fg = "#00c5c7" }
rest = { fg = "#79e8fb" }

separator_style = { fg = "#6871ff" }

[notify]
title_info = { fg = "#00c5c7" }
title_warn = { fg = "#ffe700" }
title_warn = { fg = "#d90429" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00c5c7" },
  { mime = "{audio, video}/*", fg = "#ffe700" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#3ad900" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6943ff" },
  { mime = "*", fg = "#c7c7c7" },
]


