[manager]
cwd = { fg = "#398bc6" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#a06e3b" }
find_position = { fg = "#955ae7" }

marker_copied = { fg = "#2a9292", bg = "#2a9292" }
marker_cut = { fg = "#be4678", bg = "#be4678" }
marker_selected = { fg = "#a06e3b", bg = "#a06e3b" }

tab_inactive = { fg = "#585260" }
tab_active = { fg = "#efecf4", bg = "#585260"}

count_copied = { fg = "#efecf4", bg = "#2a9292" }
count_cut = { fg = "#efecf4", bg = "#be4678" }
count_selected = { fg = "#efecf4", bg = "#a06e3b" }

border_style = { fg = "#576ddb" }

[mode]
normal_main = { fg = "#efecf4", bg = "#576ddb", bold = true }
normal_alt = { fg = "#576ddb", bg = "#8b8792" }

select_alt = { fg = "#955ae7", bg = "#8b8792" }
select_main = { fg = "#efecf4", bg = "#955ae7", bold = true }

unset_main = { fg = "#efecf4", bg = "#be4678", bold = true }
unset_alt = { fg = "#be4678", bg = "#8b8792" }

[status]
perm_exec = { fg = "#2a9292" }
perm_read = { fg = "#a06e3b" }
perm_sep = { fg = "#398bc6" }
perm_type = { fg = "#576ddb" }
perm_write = { fg = "#be4678" }

progress_error = { fg = "#be4678", bg = "#efecf4" }
progress_label = { fg = "#585260", bg = "#efecf4" }
progress_normal = { fg = "#585260", bg = "#efecf4" }

[pick]
active = { fg = "#955ae7" }
border = { fg = "#576ddb" }
inactive = { fg = "#585260" }

[task]
title = { fg = "#576ddb" }
border = { fg = "#576ddb" }
hovered = { fg = "#585260", bg = "#8b8792" }

[input]
border = { fg = "#576ddb" }
selected = { bg = "#8b8792" }

[help]
desc = { fg = "#585260" }
on = { fg = "#398bc6" }
run = { fg = "#955ae7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#8b8792", bg = "#585260" }

[which]
mask = { bg = "#8b8792" }
desc = { fg = "#585260" }
cand = { fg = "#398bc6" }
rest = { fg = "#bf40bf" }

separator_style = { fg = "#655f6d" }

[notify]
title_info = { fg = "#398bc6" }
title_warn = { fg = "#a06e3b" }
title_warn = { fg = "#be4678" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#398bc6" },
  { mime = "{audio, video}/*", fg = "#a06e3b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2a9292" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#576ddb" },
  { mime = "*", fg = "#585260" },
]


