[manager]
cwd = { fg = "#59e1e3" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fac29a" }
find_position = { fg = "#ee64ac" }

marker_copied = { fg = "#29d398", bg = "#29d398" }
marker_cut = { fg = "#e95678", bg = "#e95678" }
marker_selected = { fg = "#fac29a", bg = "#fac29a" }

tab_inactive = { fg = "#cbced0" }
tab_active = { fg = "#1c1e26", bg = "#cbced0"}

count_copied = { fg = "#1c1e26", bg = "#29d398" }
count_cut = { fg = "#1c1e26", bg = "#e95678" }
count_selected = { fg = "#1c1e26", bg = "#fac29a" }

border_style = { fg = "#26bbd9" }

[mode]
normal_main = { fg = "#1c1e26", bg = "#26bbd9", bold = true }
normal_alt = { fg = "#26bbd9", bg = "#2e303e" }

select_alt = { fg = "#ee64ac", bg = "#2e303e" }
select_main = { fg = "#1c1e26", bg = "#ee64ac", bold = true }

unset_main = { fg = "#1c1e26", bg = "#e95678", bold = true }
unset_alt = { fg = "#e95678", bg = "#2e303e" }

[status]
perm_exec = { fg = "#29d398" }
perm_read = { fg = "#fac29a" }
perm_sep = { fg = "#59e1e3" }
perm_type = { fg = "#26bbd9" }
perm_write = { fg = "#e95678" }

progress_error = { fg = "#e95678", bg = "#1c1e26" }
progress_label = { fg = "#cbced0", bg = "#1c1e26" }
progress_normal = { fg = "#cbced0", bg = "#1c1e26" }

[pick]
active = { fg = "#ee64ac" }
border = { fg = "#26bbd9" }
inactive = { fg = "#cbced0" }

[task]
title = { fg = "#26bbd9" }
border = { fg = "#26bbd9" }
hovered = { fg = "#cbced0", bg = "#2e303e" }

[input]
border = { fg = "#26bbd9" }
selected = { bg = "#2e303e" }

[help]
desc = { fg = "#cbced0" }
on = { fg = "#59e1e3" }
run = { fg = "#ee64ac" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2e303e", bg = "#cbced0" }

[which]
mask = { bg = "#2e303e" }
desc = { fg = "#cbced0" }
cand = { fg = "#59e1e3" }
rest = { fg = "#f09383" }

separator_style = { fg = "#9da0a2" }

[notify]
title_info = { fg = "#59e1e3" }
title_warn = { fg = "#fac29a" }
title_warn = { fg = "#e95678" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#59e1e3" },
  { mime = "{audio, video}/*", fg = "#fac29a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#29d398" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#26bbd9" },
  { mime = "*", fg = "#cbced0" },
]


