[manager]
cwd = { fg = "#1d8991" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c29461" }
find_position = { fg = "#5e2180" }

marker_copied = { fg = "#2e916d", bg = "#2e916d" }
marker_cut = { fg = "#df2d52", bg = "#df2d52" }
marker_selected = { fg = "#c29461", bg = "#c29461" }

tab_inactive = { fg = "#564448" }
tab_active = { fg = "#feedf3", bg = "#564448"}

count_copied = { fg = "#feedf3", bg = "#2e916d" }
count_cut = { fg = "#feedf3", bg = "#df2d52" }
count_selected = { fg = "#feedf3", bg = "#c29461" }

border_style = { fg = "#006e93" }

[mode]
normal_main = { fg = "#feedf3", bg = "#006e93", bold = true }
normal_alt = { fg = "#006e93", bg = "#e0ccd1" }

select_alt = { fg = "#5e2180", bg = "#e0ccd1" }
select_main = { fg = "#feedf3", bg = "#5e2180", bold = true }

unset_main = { fg = "#feedf3", bg = "#df2d52", bold = true }
unset_alt = { fg = "#df2d52", bg = "#e0ccd1" }

[status]
perm_exec = { fg = "#2e916d" }
perm_read = { fg = "#c29461" }
perm_sep = { fg = "#1d8991" }
perm_type = { fg = "#006e93" }
perm_write = { fg = "#df2d52" }

progress_error = { fg = "#df2d52", bg = "#feedf3" }
progress_label = { fg = "#564448", bg = "#feedf3" }
progress_normal = { fg = "#564448", bg = "#feedf3" }

[pick]
active = { fg = "#5e2180" }
border = { fg = "#006e93" }
inactive = { fg = "#564448" }

[task]
title = { fg = "#006e93" }
border = { fg = "#006e93" }
hovered = { fg = "#564448", bg = "#45475a" }

[input]
border = { fg = "#006e93" }
selected = { bg = "#e0ccd1" }

[help]
desc = { fg = "#564448" }
on = { fg = "#1d8991" }
run = { fg = "#5e2180" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e0ccd1", bg = "#564448" }

[which]
mask = { bg = "#e0ccd1" }
desc = { fg = "#564448" }
cand = { fg = "#1d8991" }
rest = { fg = "#ba0d35" }

separator_style = { fg = "#665055" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1d8991" },
  { mime = "{audio, video}/*", fg = "#c29461" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2e916d" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#006e93", bold = true },
  { mime = "*", fg = "#564448" },
]


