[mgr]
cwd = { fg = "#aaaaaa" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#e78a53" }
find_position = { fg = "#999999" }

marker_copied = { fg = "#fbcb97", bg = "#fbcb97" }
marker_cut = { fg = "#5f8787", bg = "#5f8787" }
marker_selected = { fg = "#e78a53", bg = "#e78a53" }

tab_inactive = { fg = "#c1c1c1" }
tab_active = { fg = "#000000", bg = "#c1c1c1"}

count_copied = { fg = "#000000", bg = "#fbcb97" }
count_cut = { fg = "#000000", bg = "#5f8787" }
count_selected = { fg = "#000000", bg = "#e78a53" }

border_style = { fg = "#888888" }

[mode]
normal_main = { fg = "#000000", bg = "#888888", bold = true }
normal_alt = { fg = "#888888", bg = "#222222" }

select_alt = { fg = "#999999", bg = "#222222" }
select_main = { fg = "#000000", bg = "#999999", bold = true }

unset_main = { fg = "#000000", bg = "#5f8787", bold = true }
unset_alt = { fg = "#5f8787", bg = "#222222" }

[status]
perm_exec = { fg = "#fbcb97" }
perm_read = { fg = "#e78a53" }
perm_sep = { fg = "#aaaaaa" }
perm_type = { fg = "#888888" }
perm_write = { fg = "#5f8787" }

progress_error = { fg = "#5f8787", bg = "#000000" }
progress_label = { fg = "#c1c1c1", bg = "#000000" }
progress_normal = { fg = "#c1c1c1", bg = "#000000" }

[pick]
active = { fg = "#999999" }
border = { fg = "#888888" }
inactive = { fg = "#c1c1c1" }

[task]
title = { fg = "#888888" }
border = { fg = "#888888" }
hovered = { fg = "#c1c1c1", bg = "#222222" }

[input]
border = { fg = "#888888" }
selected = { bg = "#222222" }

[help]
desc = { fg = "#c1c1c1" }
on = { fg = "#aaaaaa" }
run = { fg = "#999999" }
hovered = { reversed = true, bold = true }
footer = { fg = "#222222", bg = "#c1c1c1" }

[which]
mask = { bg = "#222222" }
desc = { fg = "#c1c1c1" }
cand = { fg = "#aaaaaa" }
rest = { fg = "#444444" }

separator_style = { fg = "#999999" }

[notify]
title_info = { fg = "#aaaaaa" }
title_warn = { fg = "#e78a53" }
title_warn = { fg = "#5f8787" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#aaaaaa" },
  { mime = "{audio, video}/*", fg = "#e78a53" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#fbcb97" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#888888" },
  { mime = "*", fg = "#c1c1c1" },
]


