[mgr]
cwd = { fg = "#629755" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#bbb529" }
find_position = { fg = "#cc7832" }

marker_copied = { fg = "#6a8759", bg = "#6a8759" }
marker_cut = { fg = "#4eade5", bg = "#4eade5" }
marker_selected = { fg = "#bbb529", bg = "#bbb529" }

tab_inactive = { fg = "#a9b7c6" }
tab_active = { fg = "#2b2b2b", bg = "#a9b7c6"}

count_copied = { fg = "#2b2b2b", bg = "#6a8759" }
count_cut = { fg = "#2b2b2b", bg = "#4eade5" }
count_selected = { fg = "#2b2b2b", bg = "#bbb529" }

border_style = { fg = "#9876aa" }

[mode]
normal_main = { fg = "#2b2b2b", bg = "#9876aa", bold = true }
normal_alt = { fg = "#9876aa", bg = "#323232" }

select_alt = { fg = "#cc7832", bg = "#323232" }
select_main = { fg = "#2b2b2b", bg = "#cc7832", bold = true }

unset_main = { fg = "#2b2b2b", bg = "#4eade5", bold = true }
unset_alt = { fg = "#4eade5", bg = "#323232" }

[status]
perm_exec = { fg = "#6a8759" }
perm_read = { fg = "#bbb529" }
perm_sep = { fg = "#629755" }
perm_type = { fg = "#9876aa" }
perm_write = { fg = "#4eade5" }

progress_error = { fg = "#4eade5", bg = "#2b2b2b" }
progress_label = { fg = "#a9b7c6", bg = "#2b2b2b" }
progress_normal = { fg = "#a9b7c6", bg = "#2b2b2b" }

[pick]
active = { fg = "#cc7832" }
border = { fg = "#9876aa" }
inactive = { fg = "#a9b7c6" }

[task]
title = { fg = "#9876aa" }
border = { fg = "#9876aa" }
hovered = { fg = "#a9b7c6", bg = "#323232" }

[input]
border = { fg = "#9876aa" }
selected = { bg = "#323232" }

[help]
desc = { fg = "#a9b7c6" }
on = { fg = "#629755" }
run = { fg = "#cc7832" }
hovered = { reversed = true, bold = true }
footer = { fg = "#323232", bg = "#a9b7c6" }

[which]
mask = { bg = "#323232" }
desc = { fg = "#a9b7c6" }
cand = { fg = "#629755" }
rest = { fg = "#808080" }

separator_style = { fg = "#a4a3a3" }

[notify]
title_info = { fg = "#629755" }
title_warn = { fg = "#bbb529" }
title_warn = { fg = "#4eade5" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#629755" },
  { mime = "{audio, video}/*", fg = "#bbb529" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6a8759" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#9876aa" },
  { mime = "*", fg = "#a9b7c6" },
]


