[mgr]
cwd = { fg = "#1081d6" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#1dd361" }
find_position = { fg = "#0f7ddb" }

marker_copied = { fg = "#f3bd09", bg = "#f3bd09" }
marker_cut = { fg = "#d6dbe5", bg = "#d6dbe5" }
marker_selected = { fg = "#1dd361", bg = "#1dd361" }

tab_inactive = { fg = "#4e5ab7" }
tab_active = { fg = "#1f1f1f", bg = "#4e5ab7"}

count_copied = { fg = "#1f1f1f", bg = "#f3bd09" }
count_cut = { fg = "#1f1f1f", bg = "#d6dbe5" }
count_selected = { fg = "#1f1f1f", bg = "#1dd361" }

border_style = { fg = "#5350b9" }

[mode]
normal_main = { fg = "#1f1f1f", bg = "#5350b9", bold = true }
normal_alt = { fg = "#5350b9", bg = "#2dc55e" }

select_alt = { fg = "#0f7ddb", bg = "#2dc55e" }
select_main = { fg = "#1f1f1f", bg = "#0f7ddb", bold = true }

unset_main = { fg = "#1f1f1f", bg = "#d6dbe5", bold = true }
unset_alt = { fg = "#d6dbe5", bg = "#2dc55e" }

[status]
perm_exec = { fg = "#f3bd09" }
perm_read = { fg = "#1dd361" }
perm_sep = { fg = "#1081d6" }
perm_type = { fg = "#5350b9" }
perm_write = { fg = "#d6dbe5" }

progress_error = { fg = "#d6dbe5", bg = "#1f1f1f" }
progress_label = { fg = "#4e5ab7", bg = "#1f1f1f" }
progress_normal = { fg = "#4e5ab7", bg = "#1f1f1f" }

[pick]
active = { fg = "#0f7ddb" }
border = { fg = "#5350b9" }
inactive = { fg = "#4e5ab7" }

[task]
title = { fg = "#5350b9" }
border = { fg = "#5350b9" }
hovered = { fg = "#4e5ab7", bg = "#2dc55e" }

[input]
border = { fg = "#5350b9" }
selected = { bg = "#2dc55e" }

[help]
desc = { fg = "#4e5ab7" }
on = { fg = "#1081d6" }
run = { fg = "#0f7ddb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2dc55e", bg = "#4e5ab7" }

[which]
mask = { bg = "#2dc55e" }
desc = { fg = "#4e5ab7" }
cand = { fg = "#1081d6" }
rest = { fg = "#ffffff" }

separator_style = { fg = "#2a84d2" }

[notify]
title_info = { fg = "#1081d6" }
title_warn = { fg = "#1dd361" }
title_warn = { fg = "#d6dbe5" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1081d6" },
  { mime = "{audio, video}/*", fg = "#1dd361" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#f3bd09" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#5350b9" },
  { mime = "*", fg = "#4e5ab7" },
]


