[mgr]
cwd = { fg = "#7c9cae" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#b99353" }
find_position = { fg = "#b98eb2" }

marker_copied = { fg = "#83a471", bg = "#83a471" }
marker_cut = { fg = "#d88568", bg = "#d88568" }
marker_selected = { fg = "#b99353", bg = "#b99353" }

tab_inactive = { fg = "#cccccc" }
tab_active = { fg = "#1a1a1a", bg = "#cccccc"}

count_copied = { fg = "#1a1a1a", bg = "#83a471" }
count_cut = { fg = "#1a1a1a", bg = "#d88568" }
count_selected = { fg = "#1a1a1a", bg = "#b99353" }

border_style = { fg = "#8eccdd" }

[mode]
normal_main = { fg = "#1a1a1a", bg = "#8eccdd", bold = true }
normal_alt = { fg = "#8eccdd", bg = "#1d414d" }

select_alt = { fg = "#b98eb2", bg = "#1d414d" }
select_main = { fg = "#1a1a1a", bg = "#b98eb2", bold = true }

unset_main = { fg = "#1a1a1a", bg = "#d88568", bold = true }
unset_alt = { fg = "#d88568", bg = "#1d414d" }

[status]
perm_exec = { fg = "#83a471" }
perm_read = { fg = "#b99353" }
perm_sep = { fg = "#7c9cae" }
perm_type = { fg = "#8eccdd" }
perm_write = { fg = "#d88568" }

progress_error = { fg = "#d88568", bg = "#1a1a1a" }
progress_label = { fg = "#cccccc", bg = "#1a1a1a" }
progress_normal = { fg = "#cccccc", bg = "#1a1a1a" }

[pick]
active = { fg = "#b98eb2" }
border = { fg = "#8eccdd" }
inactive = { fg = "#cccccc" }

[task]
title = { fg = "#8eccdd" }
border = { fg = "#8eccdd" }
hovered = { fg = "#cccccc", bg = "#1d414d" }

[input]
border = { fg = "#8eccdd" }
selected = { bg = "#1d414d" }

[help]
desc = { fg = "#cccccc" }
on = { fg = "#7c9cae" }
run = { fg = "#b98eb2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#1d414d", bg = "#cccccc" }

[which]
mask = { bg = "#1d414d" }
desc = { fg = "#cccccc" }
cand = { fg = "#7c9cae" }
rest = { fg = "#8b6c37" }

separator_style = { fg = "#b8b8b8" }

[notify]
title_info = { fg = "#7c9cae" }
title_warn = { fg = "#b99353" }
title_warn = { fg = "#d88568" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#7c9cae" },
  { mime = "{audio, video}/*", fg = "#b99353" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#83a471" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#8eccdd" },
  { mime = "*", fg = "#cccccc" },
]


