[manager]
cwd = { fg = "#78b4b4" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#d8b56d" }
find_position = { fg = "#86cacd" }

marker_copied = { fg = "#99c899", bg = "#99c899" }
marker_cut = { fg = "#c88c8c", bg = "#c88c8c" }
marker_selected = { fg = "#d8b56d", bg = "#d8b56d" }

tab_inactive = { fg = "#dedee7" }
tab_active = { fg = "#222222", bg = "#dedee7"}

count_copied = { fg = "#222222", bg = "#99c899" }
count_cut = { fg = "#222222", bg = "#c88c8c" }
count_selected = { fg = "#222222", bg = "#d8b56d" }

border_style = { fg = "#537c9c" }

[mode]
normal_main = { fg = "#222222", bg = "#537c9c", bold = true }
normal_alt = { fg = "#537c9c", bg = "#555d55" }

select_alt = { fg = "#86cacd", bg = "#555d55" }
select_main = { fg = "#222222", bg = "#86cacd", bold = true }

unset_main = { fg = "#222222", bg = "#c88c8c", bold = true }
unset_alt = { fg = "#c88c8c", bg = "#555d55" }

[status]
perm_exec = { fg = "#99c899" }
perm_read = { fg = "#d8b56d" }
perm_sep = { fg = "#78b4b4" }
perm_type = { fg = "#537c9c" }
perm_write = { fg = "#c88c8c" }

progress_error = { fg = "#c88c8c", bg = "#222222" }
progress_label = { fg = "#dedee7", bg = "#222222" }
progress_normal = { fg = "#dedee7", bg = "#222222" }

[pick]
active = { fg = "#86cacd" }
border = { fg = "#537c9c" }
inactive = { fg = "#dedee7" }

[task]
title = { fg = "#537c9c" }
border = { fg = "#537c9c" }
hovered = { fg = "#dedee7", bg = "#555d55" }

[input]
border = { fg = "#537c9c" }
selected = { bg = "#555d55" }

[help]
desc = { fg = "#dedee7" }
on = { fg = "#78b4b4" }
run = { fg = "#86cacd" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555d55", bg = "#dedee7" }

[which]
mask = { bg = "#555d55" }
desc = { fg = "#dedee7" }
cand = { fg = "#78b4b4" }
rest = { fg = "#704f4f" }

separator_style = { fg = "#5a5a5a" }

[notify]
title_info = { fg = "#78b4b4" }
title_warn = { fg = "#d8b56d" }
title_warn = { fg = "#c88c8c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#78b4b4" },
  { mime = "{audio, video}/*", fg = "#d8b56d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#99c899" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#537c9c" },
  { mime = "*", fg = "#dedee7" },
]


