[manager]
cwd = { fg = "#b5e4f4" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fded02" }
find_position = { fg = "#a16a94" }

marker_copied = { fg = "#01a252", bg = "#01a252" }
marker_cut = { fg = "#db2d20", bg = "#db2d20" }
marker_selected = { fg = "#fded02", bg = "#fded02" }

tab_inactive = { fg = "#a5a2a2" }
tab_active = { fg = "#090300", bg = "#a5a2a2"}

count_copied = { fg = "#090300", bg = "#01a252" }
count_cut = { fg = "#090300", bg = "#db2d20" }
count_selected = { fg = "#090300", bg = "#fded02" }

border_style = { fg = "#01a0e4" }

[mode]
normal_main = { fg = "#090300", bg = "#01a0e4", bold = true }
normal_alt = { fg = "#01a0e4", bg = "#4a4543" }

select_alt = { fg = "#a16a94", bg = "#4a4543" }
select_main = { fg = "#090300", bg = "#a16a94", bold = true }

unset_main = { fg = "#090300", bg = "#db2d20", bold = true }
unset_alt = { fg = "#db2d20", bg = "#4a4543" }

[status]
perm_exec = { fg = "#01a252" }
perm_read = { fg = "#fded02" }
perm_sep = { fg = "#b5e4f4" }
perm_type = { fg = "#01a0e4" }
perm_write = { fg = "#db2d20" }

progress_error = { fg = "#db2d20", bg = "#090300" }
progress_label = { fg = "#a5a2a2", bg = "#090300" }
progress_normal = { fg = "#a5a2a2", bg = "#090300" }

[pick]
active = { fg = "#a16a94" }
border = { fg = "#01a0e4" }
inactive = { fg = "#a5a2a2" }

[task]
title = { fg = "#01a0e4" }
border = { fg = "#01a0e4" }
hovered = { fg = "#a5a2a2", bg = "#45475a" }

[input]
border = { fg = "#01a0e4" }
selected = { bg = "#4a4543" }

[help]
desc = { fg = "#a5a2a2" }
on = { fg = "#b5e4f4" }
run = { fg = "#a16a94" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4a4543", bg = "#a5a2a2" }

[which]
mask = { bg = "#4a4543" }
desc = { fg = "#a5a2a2" }
cand = { fg = "#b5e4f4" }
rest = { fg = "#cdab53" }

separator_style = { fg = "#807d7c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#b5e4f4" },
  { mime = "{audio, video}/*", fg = "#fded02" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#01a252" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#01a0e4", bold = true },
  { mime = "*", fg = "#a5a2a2" },
]


