[mgr]
cwd = { fg = "#b900b1" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#955ae7" }
find_position = { fg = "#8991bb" }

marker_copied = { fg = "#05cb0d", bg = "#05cb0d" }
marker_cut = { fg = "#00d9e9", bg = "#00d9e9" }
marker_selected = { fg = "#955ae7", bg = "#955ae7" }

tab_inactive = { fg = "#ffeeff" }
tab_active = { fg = "#1e0528", bg = "#ffeeff"}

count_copied = { fg = "#1e0528", bg = "#05cb0d" }
count_cut = { fg = "#1e0528", bg = "#00d9e9" }
count_selected = { fg = "#1e0528", bg = "#955ae7" }

border_style = { fg = "#550068" }

[mode]
normal_main = { fg = "#1e0528", bg = "#550068", bold = true }
normal_alt = { fg = "#550068", bg = "#331354" }

select_alt = { fg = "#8991bb", bg = "#331354" }
select_main = { fg = "#1e0528", bg = "#8991bb", bold = true }

unset_main = { fg = "#1e0528", bg = "#00d9e9", bold = true }
unset_alt = { fg = "#00d9e9", bg = "#331354" }

[status]
perm_exec = { fg = "#05cb0d" }
perm_read = { fg = "#955ae7" }
perm_sep = { fg = "#b900b1" }
perm_type = { fg = "#550068" }
perm_write = { fg = "#00d9e9" }

progress_error = { fg = "#00d9e9", bg = "#1e0528" }
progress_label = { fg = "#ffeeff", bg = "#1e0528" }
progress_normal = { fg = "#ffeeff", bg = "#1e0528" }

[pick]
active = { fg = "#8991bb" }
border = { fg = "#550068" }
inactive = { fg = "#ffeeff" }

[task]
title = { fg = "#550068" }
border = { fg = "#550068" }
hovered = { fg = "#ffeeff", bg = "#331354" }

[input]
border = { fg = "#550068" }
selected = { bg = "#331354" }

[help]
desc = { fg = "#ffeeff" }
on = { fg = "#b900b1" }
run = { fg = "#8991bb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#331354", bg = "#ffeeff" }

[which]
mask = { bg = "#331354" }
desc = { fg = "#ffeeff" }
cand = { fg = "#b900b1" }
rest = { fg = "#4d6fff" }

separator_style = { fg = "#873582" }

[notify]
title_info = { fg = "#b900b1" }
title_warn = { fg = "#955ae7" }
title_warn = { fg = "#00d9e9" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#b900b1" },
  { mime = "{audio, video}/*", fg = "#955ae7" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#05cb0d" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#550068" },
  { mime = "*", fg = "#ffeeff" },
]


