[manager]
cwd = { fg = "#005500" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#007700" }
find_position = { fg = "#00bb00" }

marker_copied = { fg = "#00bb00", bg = "#00bb00" }
marker_cut = { fg = "#007700", bg = "#007700" }
marker_selected = { fg = "#007700", bg = "#007700" }

tab_inactive = { fg = "#00bb00" }
tab_active = { fg = "#001100", bg = "#00bb00"}

count_copied = { fg = "#001100", bg = "#00bb00" }
count_cut = { fg = "#001100", bg = "#007700" }
count_selected = { fg = "#001100", bg = "#007700" }

border_style = { fg = "#009900" }

[mode]
normal_main = { fg = "#001100", bg = "#009900", bold = true }
normal_alt = { fg = "#009900", bg = "#005500" }

select_alt = { fg = "#00bb00", bg = "#005500" }
select_main = { fg = "#001100", bg = "#00bb00", bold = true }

unset_main = { fg = "#001100", bg = "#007700", bold = true }
unset_alt = { fg = "#007700", bg = "#005500" }

[status]
perm_exec = { fg = "#00bb00" }
perm_read = { fg = "#007700" }
perm_sep = { fg = "#005500" }
perm_type = { fg = "#009900" }
perm_write = { fg = "#007700" }

progress_error = { fg = "#007700", bg = "#001100" }
progress_label = { fg = "#00bb00", bg = "#001100" }
progress_normal = { fg = "#00bb00", bg = "#001100" }

[pick]
active = { fg = "#00bb00" }
border = { fg = "#009900" }
inactive = { fg = "#00bb00" }

[task]
title = { fg = "#009900" }
border = { fg = "#009900" }
hovered = { fg = "#00bb00", bg = "#005500" }

[input]
border = { fg = "#009900" }
selected = { bg = "#005500" }

[help]
desc = { fg = "#00bb00" }
on = { fg = "#005500" }
run = { fg = "#00bb00" }
hovered = { reversed = true, bold = true }
footer = { fg = "#005500", bg = "#00bb00" }

[which]
mask = { bg = "#005500" }
desc = { fg = "#00bb00" }
cand = { fg = "#005500" }
rest = { fg = "#005500" }

separator_style = { fg = "#009900" }

[notify]
title_info = { fg = "#005500" }
title_warn = { fg = "#007700" }
title_warn = { fg = "#007700" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#005500" },
  { mime = "{audio, video}/*", fg = "#007700" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00bb00" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#009900" },
  { mime = "*", fg = "#00bb00" },
]


