[manager]
cwd = { fg = "#2aa889" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#edb443" }
find_position = { fg = "#888ca6" }

marker_copied = { fg = "#33859e", bg = "#33859e" }
marker_cut = { fg = "#c23127", bg = "#c23127" }
marker_selected = { fg = "#edb443", bg = "#edb443" }

tab_inactive = { fg = "#599cab" }
tab_active = { fg = "#0c1014", bg = "#599cab"}

count_copied = { fg = "#0c1014", bg = "#33859e" }
count_cut = { fg = "#0c1014", bg = "#c23127" }
count_selected = { fg = "#0c1014", bg = "#edb443" }

border_style = { fg = "#195466" }

[mode]
normal_main = { fg = "#0c1014", bg = "#195466", bold = true }
normal_alt = { fg = "#195466", bg = "#091f2e" }

select_alt = { fg = "#888ca6", bg = "#091f2e" }
select_main = { fg = "#0c1014", bg = "#888ca6", bold = true }

unset_main = { fg = "#0c1014", bg = "#c23127", bold = true }
unset_alt = { fg = "#c23127", bg = "#091f2e" }

[status]
perm_exec = { fg = "#33859e" }
perm_read = { fg = "#edb443" }
perm_sep = { fg = "#2aa889" }
perm_type = { fg = "#195466" }
perm_write = { fg = "#c23127" }

progress_error = { fg = "#c23127", bg = "#0c1014" }
progress_label = { fg = "#599cab", bg = "#0c1014" }
progress_normal = { fg = "#599cab", bg = "#0c1014" }

[pick]
active = { fg = "#888ca6" }
border = { fg = "#195466" }
inactive = { fg = "#599cab" }

[task]
title = { fg = "#195466" }
border = { fg = "#195466" }
hovered = { fg = "#599cab", bg = "#45475a" }

[input]
border = { fg = "#195466" }
selected = { bg = "#091f2e" }

[help]
desc = { fg = "#599cab" }
on = { fg = "#2aa889" }
run = { fg = "#888ca6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#091f2e", bg = "#599cab" }

[which]
mask = { bg = "#091f2e" }
desc = { fg = "#599cab" }
cand = { fg = "#2aa889" }
rest = { fg = "#4e5166" }

separator_style = { fg = "#245361" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2aa889" },
  { mime = "{audio, video}/*", fg = "#edb443" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#33859e" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#195466", bold = true },
  { mime = "*", fg = "#599cab" },
]


