[manager]
cwd = { fg = "#00a0be" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#438288" }
find_position = { fg = "#b21889" }

marker_copied = { fg = "#df0002", bg = "#df0002" }
marker_cut = { fg = "#b21889", bg = "#b21889" }
marker_selected = { fg = "#438288", bg = "#438288" }

tab_inactive = { fg = "#939599" }
tab_active = { fg = "#282b35", bg = "#939599"}

count_copied = { fg = "#282b35", bg = "#df0002" }
count_cut = { fg = "#282b35", bg = "#b21889" }
count_selected = { fg = "#282b35", bg = "#438288" }

border_style = { fg = "#790ead" }

[mode]
normal_main = { fg = "#282b35", bg = "#790ead", bold = true }
normal_alt = { fg = "#790ead", bg = "#53555d" }

select_alt = { fg = "#b21889", bg = "#53555d" }
select_main = { fg = "#282b35", bg = "#b21889", bold = true }

unset_main = { fg = "#282b35", bg = "#b21889", bold = true }
unset_alt = { fg = "#b21889", bg = "#53555d" }

[status]
perm_exec = { fg = "#df0002" }
perm_read = { fg = "#438288" }
perm_sep = { fg = "#00a0be" }
perm_type = { fg = "#790ead" }
perm_write = { fg = "#b21889" }

progress_error = { fg = "#b21889", bg = "#282b35" }
progress_label = { fg = "#939599", bg = "#282b35" }
progress_normal = { fg = "#939599", bg = "#282b35" }

[pick]
active = { fg = "#b21889" }
border = { fg = "#790ead" }
inactive = { fg = "#939599" }

[task]
title = { fg = "#790ead" }
border = { fg = "#790ead" }
hovered = { fg = "#939599", bg = "#53555d" }

[input]
border = { fg = "#790ead" }
selected = { bg = "#53555d" }

[help]
desc = { fg = "#939599" }
on = { fg = "#00a0be" }
run = { fg = "#b21889" }
hovered = { reversed = true, bold = true }
footer = { fg = "#53555d", bg = "#939599" }

[which]
mask = { bg = "#53555d" }
desc = { fg = "#939599" }
cand = { fg = "#00a0be" }
rest = { fg = "#c77c48" }

separator_style = { fg = "#7e8086" }

[notify]
title_info = { fg = "#00a0be" }
title_warn = { fg = "#438288" }
title_warn = { fg = "#b21889" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00a0be" },
  { mime = "{audio, video}/*", fg = "#438288" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#df0002" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#790ead" },
  { mime = "*", fg = "#939599" },
]


