[manager]
cwd = { fg = "#acddfd" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fecb6e" }
find_position = { fg = "#ba8cfc" }

marker_copied = { fg = "#32ccdc", bg = "#32ccdc" }
marker_cut = { fg = "#fd886b", bg = "#fd886b" }
marker_selected = { fg = "#fecb6e", bg = "#fecb6e" }

tab_inactive = { fg = "#d0d0d0" }
tab_active = { fg = "#181818", bg = "#d0d0d0"}

count_copied = { fg = "#181818", bg = "#32ccdc" }
count_cut = { fg = "#181818", bg = "#fd886b" }
count_selected = { fg = "#181818", bg = "#fecb6e" }

border_style = { fg = "#20bcfc" }

[mode]
normal_main = { fg = "#181818", bg = "#20bcfc", bold = true }
normal_alt = { fg = "#20bcfc", bg = "#464646" }

select_alt = { fg = "#ba8cfc", bg = "#464646" }
select_main = { fg = "#181818", bg = "#ba8cfc", bold = true }

unset_main = { fg = "#181818", bg = "#fd886b", bold = true }
unset_alt = { fg = "#fd886b", bg = "#464646" }

[status]
perm_exec = { fg = "#32ccdc" }
perm_read = { fg = "#fecb6e" }
perm_sep = { fg = "#acddfd" }
perm_type = { fg = "#20bcfc" }
perm_write = { fg = "#fd886b" }

progress_error = { fg = "#fd886b", bg = "#181818" }
progress_label = { fg = "#d0d0d0", bg = "#181818" }
progress_normal = { fg = "#d0d0d0", bg = "#181818" }

[pick]
active = { fg = "#ba8cfc" }
border = { fg = "#20bcfc" }
inactive = { fg = "#d0d0d0" }

[task]
title = { fg = "#20bcfc" }
border = { fg = "#20bcfc" }
hovered = { fg = "#d0d0d0", bg = "#45475a" }

[input]
border = { fg = "#20bcfc" }
selected = { bg = "#464646" }

[help]
desc = { fg = "#d0d0d0" }
on = { fg = "#acddfd" }
run = { fg = "#ba8cfc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#464646", bg = "#d0d0d0" }

[which]
mask = { bg = "#464646" }
desc = { fg = "#d0d0d0" }
cand = { fg = "#acddfd" }
rest = { fg = "#b15f4a" }

separator_style = { fg = "#b9b9b9" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#acddfd" },
  { mime = "{audio, video}/*", fg = "#fecb6e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#32ccdc" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#20bcfc", bold = true },
  { mime = "*", fg = "#d0d0d0" },
]


