[manager]
cwd = { fg = "#5b9d48" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#a5980d" }
find_position = { fg = "#5f9182" }

marker_copied = { fg = "#7d9726", bg = "#7d9726" }
marker_cut = { fg = "#ba6236", bg = "#ba6236" }
marker_selected = { fg = "#a5980d", bg = "#a5980d" }

tab_inactive = { fg = "#929181" }
tab_active = { fg = "#22221b", bg = "#929181"}

count_copied = { fg = "#22221b", bg = "#7d9726" }
count_cut = { fg = "#22221b", bg = "#ba6236" }
count_selected = { fg = "#22221b", bg = "#a5980d" }

border_style = { fg = "#36a166" }

[mode]
normal_main = { fg = "#22221b", bg = "#36a166", bold = true }
normal_alt = { fg = "#36a166", bg = "#5f5e4e" }

select_alt = { fg = "#5f9182", bg = "#5f5e4e" }
select_main = { fg = "#22221b", bg = "#5f9182", bold = true }

unset_main = { fg = "#22221b", bg = "#ba6236", bold = true }
unset_alt = { fg = "#ba6236", bg = "#5f5e4e" }

[status]
perm_exec = { fg = "#7d9726" }
perm_read = { fg = "#a5980d" }
perm_sep = { fg = "#5b9d48" }
perm_type = { fg = "#36a166" }
perm_write = { fg = "#ba6236" }

progress_error = { fg = "#ba6236", bg = "#22221b" }
progress_label = { fg = "#929181", bg = "#22221b" }
progress_normal = { fg = "#929181", bg = "#22221b" }

[pick]
active = { fg = "#5f9182" }
border = { fg = "#36a166" }
inactive = { fg = "#929181" }

[task]
title = { fg = "#36a166" }
border = { fg = "#36a166" }
hovered = { fg = "#929181", bg = "#5f5e4e" }

[input]
border = { fg = "#36a166" }
selected = { bg = "#5f5e4e" }

[help]
desc = { fg = "#929181" }
on = { fg = "#5b9d48" }
run = { fg = "#5f9182" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5f5e4e", bg = "#929181" }

[which]
mask = { bg = "#5f5e4e" }
desc = { fg = "#929181" }
cand = { fg = "#5b9d48" }
rest = { fg = "#9d6c7c" }

separator_style = { fg = "#878573" }

[notify]
title_info = { fg = "#5b9d48" }
title_warn = { fg = "#a5980d" }
title_warn = { fg = "#ba6236" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5b9d48" },
  { mime = "{audio, video}/*", fg = "#a5980d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7d9726" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#36a166" },
  { mime = "*", fg = "#929181" },
]


