[manager]
cwd = { fg = "#86b3b3" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#aab386" }
find_position = { fg = "#b386b2" }

marker_copied = { fg = "#87b386", bg = "#87b386" }
marker_cut = { fg = "#b38686", bg = "#b38686" }
marker_selected = { fg = "#aab386", bg = "#aab386" }

tab_inactive = { fg = "#b0c5c8" }
tab_active = { fg = "#485867", bg = "#b0c5c8"}

count_copied = { fg = "#485867", bg = "#87b386" }
count_cut = { fg = "#485867", bg = "#b38686" }
count_selected = { fg = "#485867", bg = "#aab386" }

border_style = { fg = "#868cb3" }

[mode]
normal_main = { fg = "#485867", bg = "#868cb3", bold = true }
normal_alt = { fg = "#868cb3", bg = "#6d828e" }

select_alt = { fg = "#b386b2", bg = "#6d828e" }
select_main = { fg = "#485867", bg = "#b386b2", bold = true }

unset_main = { fg = "#485867", bg = "#b38686", bold = true }
unset_alt = { fg = "#b38686", bg = "#6d828e" }

[status]
perm_exec = { fg = "#87b386" }
perm_read = { fg = "#aab386" }
perm_sep = { fg = "#86b3b3" }
perm_type = { fg = "#868cb3" }
perm_write = { fg = "#b38686" }

progress_error = { fg = "#b38686", bg = "#485867" }
progress_label = { fg = "#b0c5c8", bg = "#485867" }
progress_normal = { fg = "#b0c5c8", bg = "#485867" }

[pick]
active = { fg = "#b386b2" }
border = { fg = "#868cb3" }
inactive = { fg = "#b0c5c8" }

[task]
title = { fg = "#868cb3" }
border = { fg = "#868cb3" }
hovered = { fg = "#b0c5c8", bg = "#45475a" }

[input]
border = { fg = "#868cb3" }
selected = { bg = "#6d828e" }

[help]
desc = { fg = "#b0c5c8" }
on = { fg = "#86b3b3" }
run = { fg = "#b386b2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#6d828e", bg = "#b0c5c8" }

[which]
mask = { bg = "#6d828e" }
desc = { fg = "#b0c5c8" }
cand = { fg = "#86b3b3" }
rest = { fg = "#b39f9f" }

separator_style = { fg = "#98afb5" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#86b3b3" },
  { mime = "{audio, video}/*", fg = "#aab386" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#87b386" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#868cb3", bold = true },
  { mime = "*", fg = "#b0c5c8" },
]


