[manager]
cwd = { fg = "#2bbac5" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#e5c07b" }
find_position = { fg = "#d55fde" }

marker_copied = { fg = "#89ca78", bg = "#89ca78" }
marker_cut = { fg = "#ef596f", bg = "#ef596f" }
marker_selected = { fg = "#e5c07b", bg = "#e5c07b" }

tab_inactive = { fg = "#abb2bf" }
tab_active = { fg = "#000000", bg = "#abb2bf"}

count_copied = { fg = "#000000", bg = "#89ca78" }
count_cut = { fg = "#000000", bg = "#ef596f" }
count_selected = { fg = "#000000", bg = "#e5c07b" }

border_style = { fg = "#61afef" }

[mode]
normal_main = { fg = "#000000", bg = "#61afef", bold = true }
normal_alt = { fg = "#61afef", bg = "#2c313a" }

select_alt = { fg = "#d55fde", bg = "#2c313a" }
select_main = { fg = "#000000", bg = "#d55fde", bold = true }

unset_main = { fg = "#000000", bg = "#ef596f", bold = true }
unset_alt = { fg = "#ef596f", bg = "#2c313a" }

[status]
perm_exec = { fg = "#89ca78" }
perm_read = { fg = "#e5c07b" }
perm_sep = { fg = "#2bbac5" }
perm_type = { fg = "#61afef" }
perm_write = { fg = "#ef596f" }

progress_error = { fg = "#ef596f", bg = "#000000" }
progress_label = { fg = "#abb2bf", bg = "#000000" }
progress_normal = { fg = "#abb2bf", bg = "#000000" }

[pick]
active = { fg = "#d55fde" }
border = { fg = "#61afef" }
inactive = { fg = "#abb2bf" }

[task]
title = { fg = "#61afef" }
border = { fg = "#61afef" }
hovered = { fg = "#abb2bf", bg = "#2c313a" }

[input]
border = { fg = "#61afef" }
selected = { bg = "#2c313a" }

[help]
desc = { fg = "#abb2bf" }
on = { fg = "#2bbac5" }
run = { fg = "#d55fde" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2c313a", bg = "#abb2bf" }

[which]
mask = { bg = "#2c313a" }
desc = { fg = "#abb2bf" }
cand = { fg = "#2bbac5" }
rest = { fg = "#be5046" }

separator_style = { fg = "#565c64" }

[notify]
title_info = { fg = "#2bbac5" }
title_warn = { fg = "#e5c07b" }
title_warn = { fg = "#ef596f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2bbac5" },
  { mime = "{audio, video}/*", fg = "#e5c07b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#89ca78" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#61afef" },
  { mime = "*", fg = "#abb2bf" },
]


