[manager]
cwd = { fg = "#2aa198" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#b58900" }
find_position = { fg = "#6c71c4" }

marker_copied = { fg = "#859900", bg = "#859900" }
marker_cut = { fg = "#dc322f", bg = "#dc322f" }
marker_selected = { fg = "#b58900", bg = "#b58900" }

tab_inactive = { fg = "#586e75" }
tab_active = { fg = "#fdf6e3", bg = "#586e75"}

count_copied = { fg = "#fdf6e3", bg = "#859900" }
count_cut = { fg = "#fdf6e3", bg = "#dc322f" }
count_selected = { fg = "#fdf6e3", bg = "#b58900" }

border_style = { fg = "#268bd2" }

[mode]
normal_main = { fg = "#fdf6e3", bg = "#268bd2", bold = true }
normal_alt = { fg = "#268bd2", bg = "#93a1a1" }

select_alt = { fg = "#6c71c4", bg = "#93a1a1" }
select_main = { fg = "#fdf6e3", bg = "#6c71c4", bold = true }

unset_main = { fg = "#fdf6e3", bg = "#dc322f", bold = true }
unset_alt = { fg = "#dc322f", bg = "#93a1a1" }

[status]
perm_exec = { fg = "#859900" }
perm_read = { fg = "#b58900" }
perm_sep = { fg = "#2aa198" }
perm_type = { fg = "#268bd2" }
perm_write = { fg = "#dc322f" }

progress_error = { fg = "#dc322f", bg = "#fdf6e3" }
progress_label = { fg = "#586e75", bg = "#fdf6e3" }
progress_normal = { fg = "#586e75", bg = "#fdf6e3" }

[pick]
active = { fg = "#6c71c4" }
border = { fg = "#268bd2" }
inactive = { fg = "#586e75" }

[task]
title = { fg = "#268bd2" }
border = { fg = "#268bd2" }
hovered = { fg = "#586e75", bg = "#93a1a1" }

[input]
border = { fg = "#268bd2" }
selected = { bg = "#93a1a1" }

[help]
desc = { fg = "#586e75" }
on = { fg = "#2aa198" }
run = { fg = "#6c71c4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#93a1a1", bg = "#586e75" }

[which]
mask = { bg = "#93a1a1" }
desc = { fg = "#586e75" }
cand = { fg = "#2aa198" }
rest = { fg = "#d33682" }

separator_style = { fg = "#657b83" }

[notify]
title_info = { fg = "#2aa198" }
title_warn = { fg = "#b58900" }
title_warn = { fg = "#dc322f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2aa198" },
  { mime = "{audio, video}/*", fg = "#b58900" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#859900" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#268bd2" },
  { mime = "*", fg = "#586e75" },
]


