[mgr]
cwd = { fg = "#93e0e3" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffff00" }
find_position = { fg = "#ff1493" }

marker_copied = { fg = "#61ce3c", bg = "#61ce3c" }
marker_cut = { fg = "#ff0000", bg = "#ff0000" }
marker_selected = { fg = "#ffff00", bg = "#ffff00" }

tab_inactive = { fg = "#dcdccc" }
tab_active = { fg = "#000000", bg = "#dcdccc"}

count_copied = { fg = "#000000", bg = "#61ce3c" }
count_cut = { fg = "#000000", bg = "#ff0000" }
count_selected = { fg = "#000000", bg = "#ffff00" }

border_style = { fg = "#4c83ff" }

[mode]
normal_main = { fg = "#000000", bg = "#4c83ff", bold = true }
normal_alt = { fg = "#4c83ff", bg = "#383838" }

select_alt = { fg = "#ff1493", bg = "#383838" }
select_main = { fg = "#000000", bg = "#ff1493", bold = true }

unset_main = { fg = "#000000", bg = "#ff0000", bold = true }
unset_alt = { fg = "#ff0000", bg = "#383838" }

[status]
perm_exec = { fg = "#61ce3c" }
perm_read = { fg = "#ffff00" }
perm_sep = { fg = "#93e0e3" }
perm_type = { fg = "#4c83ff" }
perm_write = { fg = "#ff0000" }

progress_error = { fg = "#ff0000", bg = "#000000" }
progress_label = { fg = "#dcdccc", bg = "#000000" }
progress_normal = { fg = "#dcdccc", bg = "#000000" }

[pick]
active = { fg = "#ff1493" }
border = { fg = "#4c83ff" }
inactive = { fg = "#dcdccc" }

[task]
title = { fg = "#4c83ff" }
border = { fg = "#4c83ff" }
hovered = { fg = "#dcdccc", bg = "#383838" }

[input]
border = { fg = "#4c83ff" }
selected = { bg = "#383838" }

[help]
desc = { fg = "#dcdccc" }
on = { fg = "#93e0e3" }
run = { fg = "#ff1493" }
hovered = { reversed = true, bold = true }
footer = { fg = "#383838", bg = "#dcdccc" }

[which]
mask = { bg = "#383838" }
desc = { fg = "#dcdccc" }
cand = { fg = "#93e0e3" }
rest = { fg = "#ff8c00" }

separator_style = { fg = "#8b8989" }

[notify]
title_info = { fg = "#93e0e3" }
title_warn = { fg = "#ffff00" }
title_error = { fg = "#ff0000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#93e0e3" },
  { mime = "{audio, video}/*", fg = "#ffff00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#61ce3c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#4c83ff" },
  { mime = "*", fg = "#dcdccc" },
]


