[mgr]
cwd = { fg = "#a28662" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c0a179" }
find_position = { fg = "#a28662" }

marker_copied = { fg = "#927a60", bg = "#927a60" }
marker_cut = { fg = "#887254", bg = "#887254" }
marker_selected = { fg = "#c0a179", bg = "#c0a179" }

tab_inactive = { fg = "#c0a179" }
tab_active = { fg = "#120f09", bg = "#c0a179"}

count_copied = { fg = "#120f09", bg = "#927a60" }
count_cut = { fg = "#120f09", bg = "#887254" }
count_selected = { fg = "#120f09", bg = "#c0a179" }

border_style = { fg = "#d6b891" }

[mode]
normal_main = { fg = "#120f09", bg = "#d6b891", bold = true }
normal_alt = { fg = "#d6b891", bg = "#35291d" }

select_alt = { fg = "#a28662", bg = "#35291d" }
select_main = { fg = "#120f09", bg = "#a28662", bold = true }

unset_main = { fg = "#120f09", bg = "#887254", bold = true }
unset_alt = { fg = "#887254", bg = "#35291d" }

[status]
perm_exec = { fg = "#927a60" }
perm_read = { fg = "#c0a179" }
perm_sep = { fg = "#a28662" }
perm_type = { fg = "#d6b891" }
perm_write = { fg = "#887254" }

progress_error = { fg = "#887254", bg = "#120f09" }
progress_label = { fg = "#c0a179", bg = "#120f09" }
progress_normal = { fg = "#c0a179", bg = "#120f09" }

[pick]
active = { fg = "#a28662" }
border = { fg = "#d6b891" }
inactive = { fg = "#c0a179" }

[task]
title = { fg = "#d6b891" }
border = { fg = "#d6b891" }
hovered = { fg = "#c0a179", bg = "#35291d" }

[input]
border = { fg = "#d6b891" }
selected = { bg = "#35291d" }

[help]
desc = { fg = "#c0a179" }
on = { fg = "#a28662" }
run = { fg = "#a28662" }
hovered = { reversed = true, bold = true }
footer = { fg = "#35291d", bg = "#c0a179" }

[which]
mask = { bg = "#35291d" }
desc = { fg = "#c0a179" }
cand = { fg = "#a28662" }
rest = { fg = "#887254" }

separator_style = { fg = "#a28662" }

[notify]
title_info = { fg = "#a28662" }
title_warn = { fg = "#c0a179" }
title_error = { fg = "#887254" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#a28662" },
  { mime = "{audio, video}/*", fg = "#c0a179" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#927a60" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#d6b891" },
  { mime = "*", fg = "#c0a179" },
]


