[manager]
cwd = { fg = "#5ebaa5" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#dbb774" }
find_position = { fg = "#d390e7" }

marker_copied = { fg = "#a1bf78", bg = "#a1bf78" }
marker_cut = { fg = "#e77171", bg = "#e77171" }
marker_selected = { fg = "#dbb774", bg = "#dbb774" }

tab_inactive = { fg = "#b7bec9" }
tab_active = { fg = "#262729", bg = "#b7bec9"}

count_copied = { fg = "#262729", bg = "#a1bf78" }
count_cut = { fg = "#262729", bg = "#e77171" }
count_selected = { fg = "#262729", bg = "#dbb774" }

border_style = { fg = "#73b3e7" }

[mode]
normal_main = { fg = "#262729", bg = "#73b3e7", bold = true }
normal_alt = { fg = "#73b3e7", bg = "#b7bec9" }

select_alt = { fg = "#d390e7", bg = "#b7bec9" }
select_main = { fg = "#262729", bg = "#d390e7", bold = true }

unset_main = { fg = "#262729", bg = "#e77171", bold = true }
unset_alt = { fg = "#e77171", bg = "#b7bec9" }

[status]
perm_exec = { fg = "#a1bf78" }
perm_read = { fg = "#dbb774" }
perm_sep = { fg = "#5ebaa5" }
perm_type = { fg = "#73b3e7" }
perm_write = { fg = "#e77171" }

progress_error = { fg = "#e77171", bg = "#262729" }
progress_label = { fg = "#b7bec9", bg = "#262729" }
progress_normal = { fg = "#b7bec9", bg = "#262729" }

[pick]
active = { fg = "#d390e7" }
border = { fg = "#73b3e7" }
inactive = { fg = "#b7bec9" }

[task]
title = { fg = "#73b3e7" }
border = { fg = "#73b3e7" }
hovered = { fg = "#b7bec9", bg = "#45475a" }

[input]
border = { fg = "#73b3e7" }
selected = { bg = "#b7bec9" }

[help]
desc = { fg = "#b7bec9" }
on = { fg = "#5ebaa5" }
run = { fg = "#d390e7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#b7bec9", bg = "#b7bec9" }

[which]
mask = { bg = "#b7bec9" }
desc = { fg = "#b7bec9" }
cand = { fg = "#5ebaa5" }
rest = { fg = "#5ebaa5" }

separator_style = { fg = "#73b3e7" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5ebaa5" },
  { mime = "{audio, video}/*", fg = "#dbb774" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a1bf78" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#73b3e7", bold = true },
  { mime = "*", fg = "#b7bec9" },
]


