[manager]
cwd = { fg = "#86c1b9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f7ca88" }
find_position = { fg = "#ba8baf" }

marker_copied = { fg = "#a1b56c", bg = "#a1b56c" }
marker_cut = { fg = "#ab4642", bg = "#ab4642" }
marker_selected = { fg = "#f7ca88", bg = "#f7ca88" }

tab_inactive = { fg = "#d8d8d8" }
tab_active = { fg = "#181818", bg = "#d8d8d8"}

count_copied = { fg = "#181818", bg = "#a1b56c" }
count_cut = { fg = "#181818", bg = "#ab4642" }
count_selected = { fg = "#181818", bg = "#f7ca88" }

border_style = { fg = "#7cafc2" }

[mode]
normal_main = { fg = "#181818", bg = "#7cafc2", bold = true }
normal_alt = { fg = "#7cafc2", bg = "#383838" }

select_alt = { fg = "#ba8baf", bg = "#383838" }
select_main = { fg = "#181818", bg = "#ba8baf", bold = true }

unset_main = { fg = "#181818", bg = "#ab4642", bold = true }
unset_alt = { fg = "#ab4642", bg = "#383838" }

[status]
perm_exec = { fg = "#a1b56c" }
perm_read = { fg = "#f7ca88" }
perm_sep = { fg = "#86c1b9" }
perm_type = { fg = "#7cafc2" }
perm_write = { fg = "#ab4642" }

progress_error = { fg = "#ab4642", bg = "#181818" }
progress_label = { fg = "#d8d8d8", bg = "#181818" }
progress_normal = { fg = "#d8d8d8", bg = "#181818" }

[pick]
active = { fg = "#ba8baf" }
border = { fg = "#7cafc2" }
inactive = { fg = "#d8d8d8" }

[task]
title = { fg = "#7cafc2" }
border = { fg = "#7cafc2" }
hovered = { fg = "#d8d8d8", bg = "#45475a" }

[input]
border = { fg = "#7cafc2" }
selected = { bg = "#383838" }

[help]
desc = { fg = "#d8d8d8" }
on = { fg = "#86c1b9" }
run = { fg = "#ba8baf" }
hovered = { reversed = true, bold = true }
footer = { fg = "#383838", bg = "#d8d8d8" }

[which]
mask = { bg = "#383838" }
desc = { fg = "#d8d8d8" }
cand = { fg = "#86c1b9" }
rest = { fg = "#a16946" }

separator_style = { fg = "#b8b8b8" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#86c1b9" },
  { mime = "{audio, video}/*", fg = "#f7ca88" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a1b56c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7cafc2", bold = true },
  { mime = "*", fg = "#d8d8d8" },
]


