[manager]
cwd = { fg = "#8aabac" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#aca98a" }
find_position = { fg = "#ac8aac" }

marker_copied = { fg = "#8aac8b", bg = "#8aac8b" }
marker_cut = { fg = "#ac8a8c", bg = "#ac8a8c" }
marker_selected = { fg = "#aca98a", bg = "#aca98a" }

tab_inactive = { fg = "#cacaca" }
tab_active = { fg = "#0f0f0f", bg = "#cacaca"}

count_copied = { fg = "#0f0f0f", bg = "#8aac8b" }
count_cut = { fg = "#0f0f0f", bg = "#ac8a8c" }
count_selected = { fg = "#0f0f0f", bg = "#aca98a" }

border_style = { fg = "#8f8aac" }

[mode]
normal_main = { fg = "#0f0f0f", bg = "#8f8aac", bold = true }
normal_alt = { fg = "#8f8aac", bg = "#262626" }

select_alt = { fg = "#ac8aac", bg = "#262626" }
select_main = { fg = "#0f0f0f", bg = "#ac8aac", bold = true }

unset_main = { fg = "#0f0f0f", bg = "#ac8a8c", bold = true }
unset_alt = { fg = "#ac8a8c", bg = "#262626" }

[status]
perm_exec = { fg = "#8aac8b" }
perm_read = { fg = "#aca98a" }
perm_sep = { fg = "#8aabac" }
perm_type = { fg = "#8f8aac" }
perm_write = { fg = "#ac8a8c" }

progress_error = { fg = "#ac8a8c", bg = "#0f0f0f" }
progress_label = { fg = "#cacaca", bg = "#0f0f0f" }
progress_normal = { fg = "#cacaca", bg = "#0f0f0f" }

[pick]
active = { fg = "#ac8aac" }
border = { fg = "#8f8aac" }
inactive = { fg = "#cacaca" }

[task]
title = { fg = "#8f8aac" }
border = { fg = "#8f8aac" }
hovered = { fg = "#cacaca", bg = "#262626" }

[input]
border = { fg = "#8f8aac" }
selected = { bg = "#262626" }

[help]
desc = { fg = "#cacaca" }
on = { fg = "#8aabac" }
run = { fg = "#ac8aac" }
hovered = { reversed = true, bold = true }
footer = { fg = "#262626", bg = "#cacaca" }

[which]
mask = { bg = "#262626" }
desc = { fg = "#cacaca" }
cand = { fg = "#8aabac" }
rest = { fg = "#ac8a8c" }

separator_style = { fg = "#4c4c4c" }

[notify]
title_info = { fg = "#8aabac" }
title_warn = { fg = "#aca98a" }
title_warn = { fg = "#ac8a8c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8aabac" },
  { mime = "{audio, video}/*", fg = "#aca98a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8aac8b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#8f8aac" },
  { mime = "*", fg = "#cacaca" },
]


