[manager]
cwd = { fg = "#73cef4" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffc24b" }
find_position = { fg = "#d3b987" }

marker_copied = { fg = "#c9d05c", bg = "#c9d05c" }
marker_cut = { fg = "#f43753", bg = "#f43753" }
marker_selected = { fg = "#ffc24b", bg = "#ffc24b" }

tab_inactive = { fg = "#eeeeee" }
tab_active = { fg = "#282828", bg = "#eeeeee"}

count_copied = { fg = "#282828", bg = "#c9d05c" }
count_cut = { fg = "#282828", bg = "#f43753" }
count_selected = { fg = "#282828", bg = "#ffc24b" }

border_style = { fg = "#b3deef" }

[mode]
normal_main = { fg = "#282828", bg = "#b3deef", bold = true }
normal_alt = { fg = "#b3deef", bg = "#484848" }

select_alt = { fg = "#d3b987", bg = "#484848" }
select_main = { fg = "#282828", bg = "#d3b987", bold = true }

unset_main = { fg = "#282828", bg = "#f43753", bold = true }
unset_alt = { fg = "#f43753", bg = "#484848" }

[status]
perm_exec = { fg = "#c9d05c" }
perm_read = { fg = "#ffc24b" }
perm_sep = { fg = "#73cef4" }
perm_type = { fg = "#b3deef" }
perm_write = { fg = "#f43753" }

progress_error = { fg = "#f43753", bg = "#282828" }
progress_label = { fg = "#eeeeee", bg = "#282828" }
progress_normal = { fg = "#eeeeee", bg = "#282828" }

[pick]
active = { fg = "#d3b987" }
border = { fg = "#b3deef" }
inactive = { fg = "#eeeeee" }

[task]
title = { fg = "#b3deef" }
border = { fg = "#b3deef" }
hovered = { fg = "#eeeeee", bg = "#45475a" }

[input]
border = { fg = "#b3deef" }
selected = { bg = "#484848" }

[help]
desc = { fg = "#eeeeee" }
on = { fg = "#73cef4" }
run = { fg = "#d3b987" }
hovered = { reversed = true, bold = true }
footer = { fg = "#484848", bg = "#eeeeee" }

[which]
mask = { bg = "#484848" }
desc = { fg = "#eeeeee" }
cand = { fg = "#73cef4" }
rest = { fg = "#a16946" }

separator_style = { fg = "#b8b8b8" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#73cef4" },
  { mime = "{audio, video}/*", fg = "#ffc24b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#c9d05c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#b3deef", bold = true },
  { mime = "*", fg = "#eeeeee" },
]


