[manager]
cwd = { fg = "#3fb2b9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fce380" }
find_position = { fg = "#756b8a" }

marker_copied = { fg = "#73d8ad", bg = "#73d8ad" }
marker_cut = { fg = "#fb6953", bg = "#fb6953" }
marker_selected = { fg = "#fce380", bg = "#fce380" }

tab_inactive = { fg = "#c7dbdd" }
tab_active = { fg = "#0e3c46", bg = "#c7dbdd"}

count_copied = { fg = "#0e3c46", bg = "#73d8ad" }
count_cut = { fg = "#0e3c46", bg = "#fb6953" }
count_selected = { fg = "#0e3c46", bg = "#fce380" }

border_style = { fg = "#46bddd" }

[mode]
normal_main = { fg = "#0e3c46", bg = "#46bddd", bold = true }
normal_alt = { fg = "#46bddd", bg = "#2a5054" }

select_alt = { fg = "#756b8a", bg = "#2a5054" }
select_main = { fg = "#0e3c46", bg = "#756b8a", bold = true }

unset_main = { fg = "#0e3c46", bg = "#fb6953", bold = true }
unset_alt = { fg = "#fb6953", bg = "#2a5054" }

[status]
perm_exec = { fg = "#73d8ad" }
perm_read = { fg = "#fce380" }
perm_sep = { fg = "#3fb2b9" }
perm_type = { fg = "#46bddd" }
perm_write = { fg = "#fb6953" }

progress_error = { fg = "#fb6953", bg = "#0e3c46" }
progress_label = { fg = "#c7dbdd", bg = "#0e3c46" }
progress_normal = { fg = "#c7dbdd", bg = "#0e3c46" }

[pick]
active = { fg = "#756b8a" }
border = { fg = "#46bddd" }
inactive = { fg = "#c7dbdd" }

[task]
title = { fg = "#46bddd" }
border = { fg = "#46bddd" }
hovered = { fg = "#c7dbdd", bg = "#2a5054" }

[input]
border = { fg = "#46bddd" }
selected = { bg = "#2a5054" }

[help]
desc = { fg = "#c7dbdd" }
on = { fg = "#3fb2b9" }
run = { fg = "#756b8a" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2a5054", bg = "#c7dbdd" }

[which]
mask = { bg = "#2a5054" }
desc = { fg = "#c7dbdd" }
cand = { fg = "#3fb2b9" }
rest = { fg = "#9b647b" }

separator_style = { fg = "#9dc8cd" }

[notify]
title_info = { fg = "#3fb2b9" }
title_warn = { fg = "#fce380" }
title_warn = { fg = "#fb6953" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3fb2b9" },
  { mime = "{audio, video}/*", fg = "#fce380" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#73d8ad" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#46bddd" },
  { mime = "*", fg = "#c7dbdd" },
]


