[mgr]
cwd = { fg = "#5dd7b9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffcc1b" }
find_position = { fg = "#9a70a4" }

marker_copied = { fg = "#7fc06e", bg = "#7fc06e" }
marker_cut = { fg = "#ff5a67", bg = "#ff5a67" }
marker_selected = { fg = "#ffcc1b", bg = "#ffcc1b" }

tab_inactive = { fg = "#a1a19a" }
tab_active = { fg = "#002635", bg = "#a1a19a"}

count_copied = { fg = "#002635", bg = "#7fc06e" }
count_cut = { fg = "#002635", bg = "#ff5a67" }
count_selected = { fg = "#002635", bg = "#ffcc1b" }

border_style = { fg = "#14747e" }

[mode]
normal_main = { fg = "#002635", bg = "#14747e", bold = true }
normal_alt = { fg = "#14747e", bg = "#517f8d" }

select_alt = { fg = "#9a70a4", bg = "#517f8d" }
select_main = { fg = "#002635", bg = "#9a70a4", bold = true }

unset_main = { fg = "#002635", bg = "#ff5a67", bold = true }
unset_alt = { fg = "#ff5a67", bg = "#517f8d" }

[status]
perm_exec = { fg = "#7fc06e" }
perm_read = { fg = "#ffcc1b" }
perm_sep = { fg = "#5dd7b9" }
perm_type = { fg = "#14747e" }
perm_write = { fg = "#ff5a67" }

progress_error = { fg = "#ff5a67", bg = "#002635" }
progress_label = { fg = "#a1a19a", bg = "#002635" }
progress_normal = { fg = "#a1a19a", bg = "#002635" }

[pick]
active = { fg = "#9a70a4" }
border = { fg = "#14747e" }
inactive = { fg = "#a1a19a" }

[task]
title = { fg = "#14747e" }
border = { fg = "#14747e" }
hovered = { fg = "#a1a19a", bg = "#517f8d" }

[input]
border = { fg = "#14747e" }
selected = { bg = "#517f8d" }

[help]
desc = { fg = "#a1a19a" }
on = { fg = "#5dd7b9" }
run = { fg = "#9a70a4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#517f8d", bg = "#a1a19a" }

[which]
mask = { bg = "#517f8d" }
desc = { fg = "#a1a19a" }
cand = { fg = "#5dd7b9" }
rest = { fg = "#c43060" }

separator_style = { fg = "#869696" }

[notify]
title_info = { fg = "#5dd7b9" }
title_warn = { fg = "#ffcc1b" }
title_warn = { fg = "#ff5a67" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5dd7b9" },
  { mime = "{audio, video}/*", fg = "#ffcc1b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7fc06e" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#14747e" },
  { mime = "*", fg = "#a1a19a" },
]


