[mgr]
cwd = { fg = "#0dd9d6" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffb627" }
find_position = { fg = "#f15ee3" }

marker_copied = { fg = "#02d849", bg = "#02d849" }
marker_cut = { fg = "#f11235", bg = "#f11235" }
marker_selected = { fg = "#ffb627", bg = "#ffb627" }

tab_inactive = { fg = "#f8f8f2" }
tab_active = { fg = "#232629", bg = "#f8f8f2"}

count_copied = { fg = "#232629", bg = "#02d849" }
count_cut = { fg = "#232629", bg = "#f11235" }
count_selected = { fg = "#232629", bg = "#ffb627" }

border_style = { fg = "#00a6fb" }

[mode]
normal_main = { fg = "#232629", bg = "#00a6fb", bold = true }
normal_alt = { fg = "#00a6fb", bg = "#484e54" }

select_alt = { fg = "#f15ee3", bg = "#484e54" }
select_main = { fg = "#232629", bg = "#f15ee3", bold = true }

unset_main = { fg = "#232629", bg = "#f11235", bold = true }
unset_alt = { fg = "#f11235", bg = "#484e54" }

[status]
perm_exec = { fg = "#02d849" }
perm_read = { fg = "#ffb627" }
perm_sep = { fg = "#0dd9d6" }
perm_type = { fg = "#00a6fb" }
perm_write = { fg = "#f11235" }

progress_error = { fg = "#f11235", bg = "#232629" }
progress_label = { fg = "#f8f8f2", bg = "#232629" }
progress_normal = { fg = "#f8f8f2", bg = "#232629" }

[pick]
active = { fg = "#f15ee3" }
border = { fg = "#00a6fb" }
inactive = { fg = "#f8f8f2" }

[task]
title = { fg = "#00a6fb" }
border = { fg = "#00a6fb" }
hovered = { fg = "#f8f8f2", bg = "#484e54" }

[input]
border = { fg = "#00a6fb" }
selected = { bg = "#484e54" }

[help]
desc = { fg = "#f8f8f2" }
on = { fg = "#0dd9d6" }
run = { fg = "#f15ee3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#484e54", bg = "#f8f8f2" }

[which]
mask = { bg = "#484e54" }
desc = { fg = "#f8f8f2" }
cand = { fg = "#0dd9d6" }
rest = { fg = "#b27701" }

separator_style = { fg = "#c0c0bd" }

[notify]
title_info = { fg = "#0dd9d6" }
title_warn = { fg = "#ffb627" }
title_warn = { fg = "#f11235" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0dd9d6" },
  { mime = "{audio, video}/*", fg = "#ffb627" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#02d849" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#00a6fb" },
  { mime = "*", fg = "#f8f8f2" },
]


