[manager]
cwd = { fg = "#8eaee0" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ae81ff" }
find_position = { fg = "#7aa5ff" }

marker_copied = { fg = "#6dfedf", bg = "#6dfedf" }
marker_cut = { fg = "#a0a0c5", bg = "#a0a0c5" }
marker_selected = { fg = "#ae81ff", bg = "#ae81ff" }

tab_inactive = { fg = "#f1eff8" }
tab_active = { fg = "#292a44", bg = "#f1eff8"}

count_copied = { fg = "#292a44", bg = "#6dfedf" }
count_cut = { fg = "#292a44", bg = "#a0a0c5" }
count_selected = { fg = "#292a44", bg = "#ae81ff" }

border_style = { fg = "#2de0a7" }

[mode]
normal_main = { fg = "#292a44", bg = "#2de0a7", bold = true }
normal_alt = { fg = "#2de0a7", bg = "#383a62" }

select_alt = { fg = "#7aa5ff", bg = "#383a62" }
select_main = { fg = "#292a44", bg = "#7aa5ff", bold = true }

unset_main = { fg = "#292a44", bg = "#a0a0c5", bold = true }
unset_alt = { fg = "#a0a0c5", bg = "#383a62" }

[status]
perm_exec = { fg = "#6dfedf" }
perm_read = { fg = "#ae81ff" }
perm_sep = { fg = "#8eaee0" }
perm_type = { fg = "#2de0a7" }
perm_write = { fg = "#a0a0c5" }

progress_error = { fg = "#a0a0c5", bg = "#292a44" }
progress_label = { fg = "#f1eff8", bg = "#292a44" }
progress_normal = { fg = "#f1eff8", bg = "#292a44" }

[pick]
active = { fg = "#7aa5ff" }
border = { fg = "#2de0a7" }
inactive = { fg = "#f1eff8" }

[task]
title = { fg = "#2de0a7" }
border = { fg = "#2de0a7" }
hovered = { fg = "#f1eff8", bg = "#383a62" }

[input]
border = { fg = "#2de0a7" }
selected = { bg = "#383a62" }

[help]
desc = { fg = "#f1eff8" }
on = { fg = "#8eaee0" }
run = { fg = "#7aa5ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#383a62", bg = "#f1eff8" }

[which]
mask = { bg = "#383a62" }
desc = { fg = "#f1eff8" }
cand = { fg = "#8eaee0" }
rest = { fg = "#ff79c6" }

separator_style = { fg = "#a0a0c5" }

[notify]
title_info = { fg = "#8eaee0" }
title_warn = { fg = "#ae81ff" }
title_warn = { fg = "#a0a0c5" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8eaee0" },
  { mime = "{audio, video}/*", fg = "#ae81ff" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6dfedf" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#2de0a7" },
  { mime = "*", fg = "#f1eff8" },
]


