[mgr]
cwd = { fg = "#4cad83" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffd15e" }
find_position = { fg = "#1b825f" }

marker_copied = { fg = "#8cd97c", bg = "#8cd97c" }
marker_cut = { fg = "#ff662a", bg = "#ff662a" }
marker_selected = { fg = "#ffd15e", bg = "#ffd15e" }

tab_inactive = { fg = "#818175" }
tab_active = { fg = "#1a1a2f", bg = "#818175"}

count_copied = { fg = "#1a1a2f", bg = "#8cd97c" }
count_cut = { fg = "#1a1a2f", bg = "#ff662a" }
count_selected = { fg = "#1a1a2f", bg = "#ffd15e" }

border_style = { fg = "#2b926f" }

[mode]
normal_main = { fg = "#1a1a2f", bg = "#2b926f", bold = true }
normal_alt = { fg = "#2b926f", bg = "#2a2a3f" }

select_alt = { fg = "#1b825f", bg = "#2a2a3f" }
select_main = { fg = "#1a1a2f", bg = "#1b825f", bold = true }

unset_main = { fg = "#1a1a2f", bg = "#ff662a", bold = true }
unset_alt = { fg = "#ff662a", bg = "#2a2a3f" }

[status]
perm_exec = { fg = "#8cd97c" }
perm_read = { fg = "#ffd15e" }
perm_sep = { fg = "#4cad83" }
perm_type = { fg = "#2b926f" }
perm_write = { fg = "#ff662a" }

progress_error = { fg = "#ff662a", bg = "#1a1a2f" }
progress_label = { fg = "#818175", bg = "#1a1a2f" }
progress_normal = { fg = "#818175", bg = "#1a1a2f" }

[pick]
active = { fg = "#1b825f" }
border = { fg = "#2b926f" }
inactive = { fg = "#818175" }

[task]
title = { fg = "#2b926f" }
border = { fg = "#2b926f" }
hovered = { fg = "#818175", bg = "#2a2a3f" }

[input]
border = { fg = "#2b926f" }
selected = { bg = "#2a2a3f" }

[help]
desc = { fg = "#818175" }
on = { fg = "#4cad83" }
run = { fg = "#1b825f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2a2a3f", bg = "#818175" }

[which]
mask = { bg = "#2a2a3f" }
desc = { fg = "#818175" }
cand = { fg = "#4cad83" }
rest = { fg = "#b4d97c" }

separator_style = { fg = "#515155" }

[notify]
title_info = { fg = "#4cad83" }
title_warn = { fg = "#ffd15e" }
title_warn = { fg = "#ff662a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4cad83" },
  { mime = "{audio, video}/*", fg = "#ffd15e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8cd97c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#2b926f" },
  { mime = "*", fg = "#818175" },
]


