[manager]
cwd = { fg = "#69a9a7" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#dcb16c" }
find_position = { fg = "#bb99b4" }

marker_copied = { fg = "#a3b367", bg = "#a3b367" }
marker_cut = { fg = "#d57e85", bg = "#d57e85" }
marker_selected = { fg = "#dcb16c", bg = "#dcb16c" }

tab_inactive = { fg = "#8b8198" }
tab_active = { fg = "#fbf1f2", bg = "#8b8198"}

count_copied = { fg = "#fbf1f2", bg = "#a3b367" }
count_cut = { fg = "#fbf1f2", bg = "#d57e85" }
count_selected = { fg = "#fbf1f2", bg = "#dcb16c" }

border_style = { fg = "#7297b9" }

[mode]
normal_main = { fg = "#fbf1f2", bg = "#7297b9", bold = true }
normal_alt = { fg = "#7297b9", bg = "#d8d5dd" }

select_alt = { fg = "#bb99b4", bg = "#d8d5dd" }
select_main = { fg = "#fbf1f2", bg = "#bb99b4", bold = true }

unset_main = { fg = "#fbf1f2", bg = "#d57e85", bold = true }
unset_alt = { fg = "#d57e85", bg = "#d8d5dd" }

[status]
perm_exec = { fg = "#a3b367" }
perm_read = { fg = "#dcb16c" }
perm_sep = { fg = "#69a9a7" }
perm_type = { fg = "#7297b9" }
perm_write = { fg = "#d57e85" }

progress_error = { fg = "#d57e85", bg = "#fbf1f2" }
progress_label = { fg = "#8b8198", bg = "#fbf1f2" }
progress_normal = { fg = "#8b8198", bg = "#fbf1f2" }

[pick]
active = { fg = "#bb99b4" }
border = { fg = "#7297b9" }
inactive = { fg = "#8b8198" }

[task]
title = { fg = "#7297b9" }
border = { fg = "#7297b9" }
hovered = { fg = "#8b8198", bg = "#d8d5dd" }

[input]
border = { fg = "#7297b9" }
selected = { bg = "#d8d5dd" }

[help]
desc = { fg = "#8b8198" }
on = { fg = "#69a9a7" }
run = { fg = "#bb99b4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d8d5dd", bg = "#8b8198" }

[which]
mask = { bg = "#d8d5dd" }
desc = { fg = "#8b8198" }
cand = { fg = "#69a9a7" }
rest = { fg = "#baa58c" }

separator_style = { fg = "#a59daf" }

[notify]
title_info = { fg = "#69a9a7" }
title_warn = { fg = "#dcb16c" }
title_warn = { fg = "#d57e85" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#69a9a7" },
  { mime = "{audio, video}/*", fg = "#dcb16c" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a3b367" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7297b9" },
  { mime = "*", fg = "#8b8198" },
]


