[manager]
cwd = { fg = "#66cccc" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffcc66" }
find_position = { fg = "#cc99cc" }

marker_copied = { fg = "#99cc99", bg = "#99cc99" }
marker_cut = { fg = "#f2777a", bg = "#f2777a" }
marker_selected = { fg = "#ffcc66", bg = "#ffcc66" }

tab_inactive = { fg = "#d3d0c8" }
tab_active = { fg = "#2d2d2d", bg = "#d3d0c8"}

count_copied = { fg = "#2d2d2d", bg = "#99cc99" }
count_cut = { fg = "#2d2d2d", bg = "#f2777a" }
count_selected = { fg = "#2d2d2d", bg = "#ffcc66" }

border_style = { fg = "#6699cc" }

[mode]
normal_main = { fg = "#2d2d2d", bg = "#6699cc", bold = true }
normal_alt = { fg = "#6699cc", bg = "#515151" }

select_alt = { fg = "#cc99cc", bg = "#515151" }
select_main = { fg = "#2d2d2d", bg = "#cc99cc", bold = true }

unset_main = { fg = "#2d2d2d", bg = "#f2777a", bold = true }
unset_alt = { fg = "#f2777a", bg = "#515151" }

[status]
perm_exec = { fg = "#99cc99" }
perm_read = { fg = "#ffcc66" }
perm_sep = { fg = "#66cccc" }
perm_type = { fg = "#6699cc" }
perm_write = { fg = "#f2777a" }

progress_error = { fg = "#f2777a", bg = "#2d2d2d" }
progress_label = { fg = "#d3d0c8", bg = "#2d2d2d" }
progress_normal = { fg = "#d3d0c8", bg = "#2d2d2d" }

[pick]
active = { fg = "#cc99cc" }
border = { fg = "#6699cc" }
inactive = { fg = "#d3d0c8" }

[task]
title = { fg = "#6699cc" }
border = { fg = "#6699cc" }
hovered = { fg = "#d3d0c8", bg = "#45475a" }

[input]
border = { fg = "#6699cc" }
selected = { bg = "#515151" }

[help]
desc = { fg = "#d3d0c8" }
on = { fg = "#66cccc" }
run = { fg = "#cc99cc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#515151", bg = "#d3d0c8" }

[which]
mask = { bg = "#515151" }
desc = { fg = "#d3d0c8" }
cand = { fg = "#66cccc" }
rest = { fg = "#d27b53" }

separator_style = { fg = "#a09f93" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#66cccc" },
  { mime = "{audio, video}/*", fg = "#ffcc66" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#99cc99" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6699cc", bold = true },
  { mime = "*", fg = "#d3d0c8" },
]


