[manager]
cwd = { fg = "#007a72" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#9d6f00" }
find_position = { fg = "#4e66b6" }

marker_copied = { fg = "#637200", bg = "#637200" }
marker_cut = { fg = "#d02023", bg = "#d02023" }
marker_selected = { fg = "#9d6f00", bg = "#9d6f00" }

tab_inactive = { fg = "#474747" }
tab_active = { fg = "#f1f1f1", bg = "#474747"}

count_copied = { fg = "#f1f1f1", bg = "#637200" }
count_cut = { fg = "#f1f1f1", bg = "#d02023" }
count_selected = { fg = "#f1f1f1", bg = "#9d6f00" }

border_style = { fg = "#0073b5" }

[mode]
normal_main = { fg = "#f1f1f1", bg = "#0073b5", bold = true }
normal_alt = { fg = "#0073b5", bg = "#d4d4d4" }

select_alt = { fg = "#4e66b6", bg = "#d4d4d4" }
select_main = { fg = "#f1f1f1", bg = "#4e66b6", bold = true }

unset_main = { fg = "#f1f1f1", bg = "#d02023", bold = true }
unset_alt = { fg = "#d02023", bg = "#d4d4d4" }

[status]
perm_exec = { fg = "#637200" }
perm_read = { fg = "#9d6f00" }
perm_sep = { fg = "#007a72" }
perm_type = { fg = "#0073b5" }
perm_write = { fg = "#d02023" }

progress_error = { fg = "#d02023", bg = "#f1f1f1" }
progress_label = { fg = "#474747", bg = "#f1f1f1" }
progress_normal = { fg = "#474747", bg = "#f1f1f1" }

[pick]
active = { fg = "#4e66b6" }
border = { fg = "#0073b5" }
inactive = { fg = "#474747" }

[task]
title = { fg = "#0073b5" }
border = { fg = "#0073b5" }
hovered = { fg = "#474747", bg = "#d4d4d4" }

[input]
border = { fg = "#0073b5" }
selected = { bg = "#d4d4d4" }

[help]
desc = { fg = "#474747" }
on = { fg = "#007a72" }
run = { fg = "#4e66b6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d4d4d4", bg = "#474747" }

[which]
mask = { bg = "#d4d4d4" }
desc = { fg = "#474747" }
cand = { fg = "#007a72" }
rest = { fg = "#c42775" }

separator_style = { fg = "#5e5e5e" }

[notify]
title_info = { fg = "#007a72" }
title_warn = { fg = "#9d6f00" }
title_warn = { fg = "#d02023" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#007a72" },
  { mime = "{audio, video}/*", fg = "#9d6f00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#637200" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0073b5" },
  { mime = "*", fg = "#474747" },
]


