[mgr]
cwd = { fg = "#0184bc" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c18401" }
find_position = { fg = "#a626a4" }

marker_copied = { fg = "#50a14f", bg = "#50a14f" }
marker_cut = { fg = "#ca1243", bg = "#ca1243" }
marker_selected = { fg = "#c18401", bg = "#c18401" }

tab_inactive = { fg = "#383a42" }
tab_active = { fg = "#fafafa", bg = "#383a42"}

count_copied = { fg = "#fafafa", bg = "#50a14f" }
count_cut = { fg = "#fafafa", bg = "#ca1243" }
count_selected = { fg = "#fafafa", bg = "#c18401" }

border_style = { fg = "#4078f2" }

[mode]
normal_main = { fg = "#fafafa", bg = "#4078f2", bold = true }
normal_alt = { fg = "#4078f2", bg = "#e5e5e6" }

select_alt = { fg = "#a626a4", bg = "#e5e5e6" }
select_main = { fg = "#fafafa", bg = "#a626a4", bold = true }

unset_main = { fg = "#fafafa", bg = "#ca1243", bold = true }
unset_alt = { fg = "#ca1243", bg = "#e5e5e6" }

[status]
perm_exec = { fg = "#50a14f" }
perm_read = { fg = "#c18401" }
perm_sep = { fg = "#0184bc" }
perm_type = { fg = "#4078f2" }
perm_write = { fg = "#ca1243" }

progress_error = { fg = "#ca1243", bg = "#fafafa" }
progress_label = { fg = "#383a42", bg = "#fafafa" }
progress_normal = { fg = "#383a42", bg = "#fafafa" }

[pick]
active = { fg = "#a626a4" }
border = { fg = "#4078f2" }
inactive = { fg = "#383a42" }

[task]
title = { fg = "#4078f2" }
border = { fg = "#4078f2" }
hovered = { fg = "#383a42", bg = "#e5e5e6" }

[input]
border = { fg = "#4078f2" }
selected = { bg = "#e5e5e6" }

[help]
desc = { fg = "#383a42" }
on = { fg = "#0184bc" }
run = { fg = "#a626a4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e5e5e6", bg = "#383a42" }

[which]
mask = { bg = "#e5e5e6" }
desc = { fg = "#383a42" }
cand = { fg = "#0184bc" }
rest = { fg = "#986801" }

separator_style = { fg = "#696c77" }

[notify]
title_info = { fg = "#0184bc" }
title_warn = { fg = "#c18401" }
title_warn = { fg = "#ca1243" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0184bc" },
  { mime = "{audio, video}/*", fg = "#c18401" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#50a14f" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#4078f2" },
  { mime = "*", fg = "#383a42" },
]


