[manager]
cwd = { fg = "#ffaf00" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#afd700" }
find_position = { fg = "#00afaf" }

marker_copied = { fg = "#af87d7", bg = "#af87d7" }
marker_cut = { fg = "#585858", bg = "#585858" }
marker_selected = { fg = "#afd700", bg = "#afd700" }

tab_inactive = { fg = "#808080" }
tab_active = { fg = "#1c1c1c", bg = "#808080"}

count_copied = { fg = "#1c1c1c", bg = "#af87d7" }
count_cut = { fg = "#1c1c1c", bg = "#585858" }
count_selected = { fg = "#1c1c1c", bg = "#afd700" }

border_style = { fg = "#ff5faf" }

[mode]
normal_main = { fg = "#1c1c1c", bg = "#ff5faf", bold = true }
normal_alt = { fg = "#ff5faf", bg = "#5faf00" }

select_alt = { fg = "#00afaf", bg = "#5faf00" }
select_main = { fg = "#1c1c1c", bg = "#00afaf", bold = true }

unset_main = { fg = "#1c1c1c", bg = "#585858", bold = true }
unset_alt = { fg = "#585858", bg = "#5faf00" }

[status]
perm_exec = { fg = "#af87d7" }
perm_read = { fg = "#afd700" }
perm_sep = { fg = "#ffaf00" }
perm_type = { fg = "#ff5faf" }
perm_write = { fg = "#585858" }

progress_error = { fg = "#585858", bg = "#1c1c1c" }
progress_label = { fg = "#808080", bg = "#1c1c1c" }
progress_normal = { fg = "#808080", bg = "#1c1c1c" }

[pick]
active = { fg = "#00afaf" }
border = { fg = "#ff5faf" }
inactive = { fg = "#808080" }

[task]
title = { fg = "#ff5faf" }
border = { fg = "#ff5faf" }
hovered = { fg = "#808080", bg = "#45475a" }

[input]
border = { fg = "#ff5faf" }
selected = { bg = "#5faf00" }

[help]
desc = { fg = "#808080" }
on = { fg = "#ffaf00" }
run = { fg = "#00afaf" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5faf00", bg = "#808080" }

[which]
mask = { bg = "#5faf00" }
desc = { fg = "#808080" }
cand = { fg = "#ffaf00" }
rest = { fg = "#5f8787" }

separator_style = { fg = "#5fafd7" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#ffaf00" },
  { mime = "{audio, video}/*", fg = "#afd700" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#af87d7" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#ff5faf", bold = true },
  { mime = "*", fg = "#808080" },
]


