[mgr]
cwd = { fg = "#149bda" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#dc8a0e" }
find_position = { fg = "#bb60ea" }

marker_copied = { fg = "#17ad98", bg = "#17ad98" }
marker_cut = { fg = "#d8137f", bg = "#d8137f" }
marker_selected = { fg = "#dc8a0e", bg = "#dc8a0e" }

tab_inactive = { fg = "#bcbabe" }
tab_active = { fg = "#2e2a31", bg = "#bcbabe"}

count_copied = { fg = "#2e2a31", bg = "#17ad98" }
count_cut = { fg = "#2e2a31", bg = "#d8137f" }
count_selected = { fg = "#2e2a31", bg = "#dc8a0e" }

border_style = { fg = "#796af5" }

[mode]
normal_main = { fg = "#2e2a31", bg = "#796af5", bold = true }
normal_alt = { fg = "#796af5", bg = "#666369" }

select_alt = { fg = "#bb60ea", bg = "#666369" }
select_main = { fg = "#2e2a31", bg = "#bb60ea", bold = true }

unset_main = { fg = "#2e2a31", bg = "#d8137f", bold = true }
unset_alt = { fg = "#d8137f", bg = "#666369" }

[status]
perm_exec = { fg = "#17ad98" }
perm_read = { fg = "#dc8a0e" }
perm_sep = { fg = "#149bda" }
perm_type = { fg = "#796af5" }
perm_write = { fg = "#d8137f" }

progress_error = { fg = "#d8137f", bg = "#2e2a31" }
progress_label = { fg = "#bcbabe", bg = "#2e2a31" }
progress_normal = { fg = "#bcbabe", bg = "#2e2a31" }

[pick]
active = { fg = "#bb60ea" }
border = { fg = "#796af5" }
inactive = { fg = "#bcbabe" }

[task]
title = { fg = "#796af5" }
border = { fg = "#796af5" }
hovered = { fg = "#bcbabe", bg = "#666369" }

[input]
border = { fg = "#796af5" }
selected = { bg = "#666369" }

[help]
desc = { fg = "#bcbabe" }
on = { fg = "#149bda" }
run = { fg = "#bb60ea" }
hovered = { reversed = true, bold = true }
footer = { fg = "#666369", bg = "#bcbabe" }

[which]
mask = { bg = "#666369" }
desc = { fg = "#bcbabe" }
cand = { fg = "#149bda" }
rest = { fg = "#c720ca" }

separator_style = { fg = "#9f9da2" }

[notify]
title_info = { fg = "#149bda" }
title_warn = { fg = "#dc8a0e" }
title_warn = { fg = "#d8137f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#149bda" },
  { mime = "{audio, video}/*", fg = "#dc8a0e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#17ad98" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#796af5" },
  { mime = "*", fg = "#bcbabe" },
]


