[manager]
cwd = { fg = "#86e1fc" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffc777" }
find_position = { fg = "#fca7ea" }

marker_copied = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut = { fg = "#ff757f", bg = "#ff757f" }
marker_selected = { fg = "#ffc777", bg = "#ffc777" }

tab_inactive = { fg = "#3b4261" }
tab_active = { fg = "#222436", bg = "#3b4261"}

count_copied = { fg = "#222436", bg = "#c3e88d" }
count_cut = { fg = "#222436", bg = "#ff757f" }
count_selected = { fg = "#222436", bg = "#ffc777" }

border_style = { fg = "#82aaff" }

[mode]
normal_main = { fg = "#222436", bg = "#82aaff", bold = true }
normal_alt = { fg = "#82aaff", bg = "#2d3f76" }

select_alt = { fg = "#fca7ea", bg = "#2d3f76" }
select_main = { fg = "#222436", bg = "#fca7ea", bold = true }

unset_main = { fg = "#222436", bg = "#ff757f", bold = true }
unset_alt = { fg = "#ff757f", bg = "#2d3f76" }

[status]
perm_exec = { fg = "#c3e88d" }
perm_read = { fg = "#ffc777" }
perm_sep = { fg = "#86e1fc" }
perm_type = { fg = "#82aaff" }
perm_write = { fg = "#ff757f" }

progress_error = { fg = "#ff757f", bg = "#222436" }
progress_label = { fg = "#3b4261", bg = "#222436" }
progress_normal = { fg = "#3b4261", bg = "#222436" }

[pick]
active = { fg = "#fca7ea" }
border = { fg = "#82aaff" }
inactive = { fg = "#3b4261" }

[task]
title = { fg = "#82aaff" }
border = { fg = "#82aaff" }
hovered = { fg = "#3b4261", bg = "#45475a" }

[input]
border = { fg = "#82aaff" }
selected = { bg = "#2d3f76" }

[help]
desc = { fg = "#3b4261" }
on = { fg = "#86e1fc" }
run = { fg = "#fca7ea" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2d3f76", bg = "#3b4261" }

[which]
mask = { bg = "#2d3f76" }
desc = { fg = "#3b4261" }
cand = { fg = "#86e1fc" }
rest = { fg = "#c53b53" }

separator_style = { fg = "#828bb8" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#86e1fc" },
  { mime = "{audio, video}/*", fg = "#ffc777" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#c3e88d" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#82aaff", bold = true },
  { mime = "*", fg = "#3b4261" },
]


