[mgr]
cwd = { fg = "#2155d6" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ff669b" }
find_position = { fg = "#6916b6" }

marker_copied = { fg = "#0073a8", bg = "#0073a8" }
marker_cut = { fg = "#f43979", bg = "#f43979" }
marker_selected = { fg = "#ff669b", bg = "#ff669b" }

tab_inactive = { fg = "#313145" }
tab_active = { fg = "#efefef", bg = "#313145"}

count_copied = { fg = "#efefef", bg = "#0073a8" }
count_cut = { fg = "#efefef", bg = "#f43979" }
count_selected = { fg = "#efefef", bg = "#ff669b" }

border_style = { fg = "#471397" }

[mode]
normal_main = { fg = "#efefef", bg = "#471397", bold = true }
normal_alt = { fg = "#471397", bg = "#9e9eaf" }

select_alt = { fg = "#6916b6", bg = "#9e9eaf" }
select_main = { fg = "#efefef", bg = "#6916b6", bold = true }

unset_main = { fg = "#efefef", bg = "#f43979", bold = true }
unset_alt = { fg = "#f43979", bg = "#9e9eaf" }

[status]
perm_exec = { fg = "#0073a8" }
perm_read = { fg = "#ff669b" }
perm_sep = { fg = "#2155d6" }
perm_type = { fg = "#471397" }
perm_write = { fg = "#f43979" }

progress_error = { fg = "#f43979", bg = "#efefef" }
progress_label = { fg = "#313145", bg = "#efefef" }
progress_normal = { fg = "#313145", bg = "#efefef" }

[pick]
active = { fg = "#6916b6" }
border = { fg = "#471397" }
inactive = { fg = "#313145" }

[task]
title = { fg = "#471397" }
border = { fg = "#471397" }
hovered = { fg = "#313145", bg = "#9e9eaf" }

[input]
border = { fg = "#471397" }
selected = { bg = "#9e9eaf" }

[help]
desc = { fg = "#313145" }
on = { fg = "#2155d6" }
run = { fg = "#6916b6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#9e9eaf", bg = "#313145" }

[which]
mask = { bg = "#9e9eaf" }
desc = { fg = "#313145" }
cand = { fg = "#2155d6" }
rest = { fg = "#8d17a5" }

separator_style = { fg = "#505063" }

[notify]
title_info = { fg = "#2155d6" }
title_warn = { fg = "#ff669b" }
title_warn = { fg = "#f43979" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2155d6" },
  { mime = "{audio, video}/*", fg = "#ff669b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#0073a8" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#471397" },
  { mime = "*", fg = "#313145" },
]


