[manager]
cwd = { fg = "#329ca2" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#cfad25" }
find_position = { fg = "#6e6582" }

marker_copied = { fg = "#6ca38c", bg = "#6ca38c" }
marker_cut = { fg = "#cf432e", bg = "#cf432e" }
marker_selected = { fg = "#cfad25", bg = "#cfad25" }

tab_inactive = { fg = "#385156" }
tab_active = { fg = "#e9f1ef", bg = "#385156"}

count_copied = { fg = "#e9f1ef", bg = "#6ca38c" }
count_cut = { fg = "#e9f1ef", bg = "#cf432e" }
count_selected = { fg = "#e9f1ef", bg = "#cfad25" }

border_style = { fg = "#39aac9" }

[mode]
normal_main = { fg = "#e9f1ef", bg = "#39aac9", bold = true }
normal_alt = { fg = "#39aac9", bg = "#90b7b6" }

select_alt = { fg = "#6e6582", bg = "#90b7b6" }
select_main = { fg = "#e9f1ef", bg = "#6e6582", bold = true }

unset_main = { fg = "#e9f1ef", bg = "#cf432e", bold = true }
unset_alt = { fg = "#cf432e", bg = "#90b7b6" }

[status]
perm_exec = { fg = "#6ca38c" }
perm_read = { fg = "#cfad25" }
perm_sep = { fg = "#329ca2" }
perm_type = { fg = "#39aac9" }
perm_write = { fg = "#cf432e" }

progress_error = { fg = "#cf432e", bg = "#e9f1ef" }
progress_label = { fg = "#385156", bg = "#e9f1ef" }
progress_normal = { fg = "#385156", bg = "#e9f1ef" }

[pick]
active = { fg = "#6e6582" }
border = { fg = "#39aac9" }
inactive = { fg = "#385156" }

[task]
title = { fg = "#39aac9" }
border = { fg = "#39aac9" }
hovered = { fg = "#385156", bg = "#90b7b6" }

[input]
border = { fg = "#39aac9" }
selected = { bg = "#90b7b6" }

[help]
desc = { fg = "#385156" }
on = { fg = "#329ca2" }
run = { fg = "#6e6582" }
hovered = { reversed = true, bold = true }
footer = { fg = "#90b7b6", bg = "#385156" }

[which]
mask = { bg = "#90b7b6" }
desc = { fg = "#385156" }
cand = { fg = "#329ca2" }
rest = { fg = "#865369" }

separator_style = { fg = "#4b5b5f" }

[notify]
title_info = { fg = "#329ca2" }
title_warn = { fg = "#cfad25" }
title_warn = { fg = "#cf432e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#329ca2" },
  { mime = "{audio, video}/*", fg = "#cfad25" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6ca38c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#39aac9" },
  { mime = "*", fg = "#385156" },
]


