[mgr]
cwd = { fg = "#9ccfd8" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ebbcba" }
find_position = { fg = "#f6c177" }

marker_copied = { fg = "#31748f", bg = "#31748f" }
marker_cut = { fg = "#eb6f92", bg = "#eb6f92" }
marker_selected = { fg = "#ebbcba", bg = "#ebbcba" }

tab_inactive = { fg = "#e0def4" }
tab_active = { fg = "#191724", bg = "#e0def4"}

count_copied = { fg = "#191724", bg = "#31748f" }
count_cut = { fg = "#191724", bg = "#eb6f92" }
count_selected = { fg = "#191724", bg = "#ebbcba" }

border_style = { fg = "#c4a7e7" }

[mode]
normal_main = { fg = "#191724", bg = "#c4a7e7", bold = true }
normal_alt = { fg = "#c4a7e7", bg = "#26233a" }

select_alt = { fg = "#f6c177", bg = "#26233a" }
select_main = { fg = "#191724", bg = "#f6c177", bold = true }

unset_main = { fg = "#191724", bg = "#eb6f92", bold = true }
unset_alt = { fg = "#eb6f92", bg = "#26233a" }

[status]
perm_exec = { fg = "#31748f" }
perm_read = { fg = "#ebbcba" }
perm_sep = { fg = "#9ccfd8" }
perm_type = { fg = "#c4a7e7" }
perm_write = { fg = "#eb6f92" }

progress_error = { fg = "#eb6f92", bg = "#191724" }
progress_label = { fg = "#e0def4", bg = "#191724" }
progress_normal = { fg = "#e0def4", bg = "#191724" }

[pick]
active = { fg = "#f6c177" }
border = { fg = "#c4a7e7" }
inactive = { fg = "#e0def4" }

[task]
title = { fg = "#c4a7e7" }
border = { fg = "#c4a7e7" }
hovered = { fg = "#e0def4", bg = "#26233a" }

[input]
border = { fg = "#c4a7e7" }
selected = { bg = "#26233a" }

[help]
desc = { fg = "#e0def4" }
on = { fg = "#9ccfd8" }
run = { fg = "#f6c177" }
hovered = { reversed = true, bold = true }
footer = { fg = "#26233a", bg = "#e0def4" }

[which]
mask = { bg = "#26233a" }
desc = { fg = "#e0def4" }
cand = { fg = "#9ccfd8" }
rest = { fg = "#524f67" }

separator_style = { fg = "#908caa" }

[notify]
title_info = { fg = "#9ccfd8" }
title_warn = { fg = "#ebbcba" }
title_warn = { fg = "#eb6f92" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#9ccfd8" },
  { mime = "{audio, video}/*", fg = "#ebbcba" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#31748f" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#c4a7e7" },
  { mime = "*", fg = "#e0def4" },
]


