[manager]
cwd = { fg = "#a2d6f5" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffdc61" }
find_position = { fg = "#c8a0d2" }

marker_copied = { fg = "#a0d2c8", bg = "#a0d2c8" }
marker_cut = { fg = "#fa8480", bg = "#fa8480" }
marker_selected = { fg = "#ffdc61", bg = "#ffdc61" }

tab_inactive = { fg = "#383838" }
tab_active = { fg = "#f8f8f8", bg = "#383838"}

count_copied = { fg = "#f8f8f8", bg = "#a0d2c8" }
count_cut = { fg = "#f8f8f8", bg = "#fa8480" }
count_selected = { fg = "#f8f8f8", bg = "#ffdc61" }

border_style = { fg = "#a0a7d2" }

[mode]
normal_main = { fg = "#f8f8f8", bg = "#a0a7d2", bold = true }
normal_alt = { fg = "#a0a7d2", bg = "#d8d8d8" }

select_alt = { fg = "#c8a0d2", bg = "#d8d8d8" }
select_main = { fg = "#f8f8f8", bg = "#c8a0d2", bold = true }

unset_main = { fg = "#f8f8f8", bg = "#fa8480", bold = true }
unset_alt = { fg = "#fa8480", bg = "#d8d8d8" }

[status]
perm_exec = { fg = "#a0d2c8" }
perm_read = { fg = "#ffdc61" }
perm_sep = { fg = "#a2d6f5" }
perm_type = { fg = "#a0a7d2" }
perm_write = { fg = "#fa8480" }

progress_error = { fg = "#fa8480", bg = "#f8f8f8" }
progress_label = { fg = "#383838", bg = "#f8f8f8" }
progress_normal = { fg = "#383838", bg = "#f8f8f8" }

[pick]
active = { fg = "#c8a0d2" }
border = { fg = "#a0a7d2" }
inactive = { fg = "#383838" }

[task]
title = { fg = "#a0a7d2" }
border = { fg = "#a0a7d2" }
hovered = { fg = "#383838", bg = "#d8d8d8" }

[input]
border = { fg = "#a0a7d2" }
selected = { bg = "#d8d8d8" }

[help]
desc = { fg = "#383838" }
on = { fg = "#a2d6f5" }
run = { fg = "#c8a0d2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d8d8d8", bg = "#383838" }

[which]
mask = { bg = "#d8d8d8" }
desc = { fg = "#383838" }
cand = { fg = "#a2d6f5" }
rest = { fg = "#d2b2a0" }

separator_style = { fg = "#585858" }

[notify]
title_info = { fg = "#a2d6f5" }
title_warn = { fg = "#ffdc61" }
title_warn = { fg = "#fa8480" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#a2d6f5" },
  { mime = "{audio, video}/*", fg = "#ffdc61" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a0d2c8" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#a0a7d2" },
  { mime = "*", fg = "#383838" },
]


