[manager]
cwd = { fg = "#0ef0f0" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f3e877" }
find_position = { fg = "#f10596" }

marker_copied = { fg = "#59f176", bg = "#59f176" }
marker_cut = { fg = "#ff4242", bg = "#ff4242" }
marker_selected = { fg = "#f3e877", bg = "#f3e877" }

tab_inactive = { fg = "#d0d0fa" }
tab_active = { fg = "#00002a", bg = "#d0d0fa"}

count_copied = { fg = "#00002a", bg = "#59f176" }
count_cut = { fg = "#00002a", bg = "#ff4242" }
count_selected = { fg = "#00002a", bg = "#f3e877" }

border_style = { fg = "#66b0ff" }

[mode]
normal_main = { fg = "#00002a", bg = "#66b0ff", bold = true }
normal_alt = { fg = "#66b0ff", bg = "#30305a" }

select_alt = { fg = "#f10596", bg = "#30305a" }
select_main = { fg = "#00002a", bg = "#f10596", bold = true }

unset_main = { fg = "#00002a", bg = "#ff4242", bold = true }
unset_alt = { fg = "#ff4242", bg = "#30305a" }

[status]
perm_exec = { fg = "#59f176" }
perm_read = { fg = "#f3e877" }
perm_sep = { fg = "#0ef0f0" }
perm_type = { fg = "#66b0ff" }
perm_write = { fg = "#ff4242" }

progress_error = { fg = "#ff4242", bg = "#00002a" }
progress_label = { fg = "#d0d0fa", bg = "#00002a" }
progress_normal = { fg = "#d0d0fa", bg = "#00002a" }

[pick]
active = { fg = "#f10596" }
border = { fg = "#66b0ff" }
inactive = { fg = "#d0d0fa" }

[task]
title = { fg = "#66b0ff" }
border = { fg = "#66b0ff" }
hovered = { fg = "#d0d0fa", bg = "#45475a" }

[input]
border = { fg = "#66b0ff" }
selected = { bg = "#30305a" }

[help]
desc = { fg = "#d0d0fa" }
on = { fg = "#0ef0f0" }
run = { fg = "#f10596" }
hovered = { reversed = true, bold = true }
footer = { fg = "#30305a", bg = "#d0d0fa" }

[which]
mask = { bg = "#30305a" }
desc = { fg = "#d0d0fa" }
cand = { fg = "#0ef0f0" }
rest = { fg = "#f003ef" }

separator_style = { fg = "#b0b0da" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0ef0f0" },
  { mime = "{audio, video}/*", fg = "#f3e877" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#59f176" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#66b0ff", bold = true },
  { mime = "*", fg = "#d0d0fa" },
]


