[mgr]
cwd = { fg = "#62c0be" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#bfac4e" }
find_position = { fg = "#b39be0" }

marker_copied = { fg = "#56c16f", bg = "#56c16f" }
marker_cut = { fg = "#ce7e8e", bg = "#ce7e8e" }
marker_selected = { fg = "#bfac4e", bg = "#bfac4e" }

tab_inactive = { fg = "#dcdcdc" }
tab_active = { fg = "#00211f", bg = "#dcdcdc"}

count_copied = { fg = "#00211f", bg = "#56c16f" }
count_cut = { fg = "#00211f", bg = "#ce7e8e" }
count_selected = { fg = "#00211f", bg = "#bfac4e" }

border_style = { fg = "#88b0da" }

[mode]
normal_main = { fg = "#00211f", bg = "#88b0da", bold = true }
normal_alt = { fg = "#88b0da", bg = "#005453" }

select_alt = { fg = "#b39be0", bg = "#005453" }
select_main = { fg = "#00211f", bg = "#b39be0", bold = true }

unset_main = { fg = "#00211f", bg = "#ce7e8e", bold = true }
unset_alt = { fg = "#ce7e8e", bg = "#005453" }

[status]
perm_exec = { fg = "#56c16f" }
perm_read = { fg = "#bfac4e" }
perm_sep = { fg = "#62c0be" }
perm_type = { fg = "#88b0da" }
perm_write = { fg = "#ce7e8e" }

progress_error = { fg = "#ce7e8e", bg = "#00211f" }
progress_label = { fg = "#dcdcdc", bg = "#00211f" }
progress_normal = { fg = "#dcdcdc", bg = "#00211f" }

[pick]
active = { fg = "#b39be0" }
border = { fg = "#88b0da" }
inactive = { fg = "#dcdcdc" }

[task]
title = { fg = "#88b0da" }
border = { fg = "#88b0da" }
hovered = { fg = "#dcdcdc", bg = "#005453" }

[input]
border = { fg = "#88b0da" }
selected = { bg = "#005453" }

[help]
desc = { fg = "#dcdcdc" }
on = { fg = "#62c0be" }
run = { fg = "#b39be0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#005453", bg = "#dcdcdc" }

[which]
mask = { bg = "#005453" }
desc = { fg = "#dcdcdc" }
cand = { fg = "#62c0be" }
rest = { fg = "#d89aba" }

separator_style = { fg = "#c3c3c3" }

[notify]
title_info = { fg = "#62c0be" }
title_warn = { fg = "#bfac4e" }
title_warn = { fg = "#ce7e8e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#62c0be" },
  { mime = "{audio, video}/*", fg = "#bfac4e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#56c16f" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#88b0da" },
  { mime = "*", fg = "#dcdcdc" },
]


