[mgr]
cwd = { fg = "#85ad85" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffaf00" }
find_position = { fg = "#d485ad" }

marker_copied = { fg = "#afaf00", bg = "#afaf00" }
marker_cut = { fg = "#d75f5f", bg = "#d75f5f" }
marker_selected = { fg = "#ffaf00", bg = "#ffaf00" }

tab_inactive = { fg = "#dab997" }
tab_active = { fg = "#262626", bg = "#dab997"}

count_copied = { fg = "#262626", bg = "#afaf00" }
count_cut = { fg = "#262626", bg = "#d75f5f" }
count_selected = { fg = "#262626", bg = "#ffaf00" }

border_style = { fg = "#83adad" }

[mode]
normal_main = { fg = "#262626", bg = "#83adad", bold = true }
normal_alt = { fg = "#83adad", bg = "#4e4e4e" }

select_alt = { fg = "#d485ad", bg = "#4e4e4e" }
select_main = { fg = "#262626", bg = "#d485ad", bold = true }

unset_main = { fg = "#262626", bg = "#d75f5f", bold = true }
unset_alt = { fg = "#d75f5f", bg = "#4e4e4e" }

[status]
perm_exec = { fg = "#afaf00" }
perm_read = { fg = "#ffaf00" }
perm_sep = { fg = "#85ad85" }
perm_type = { fg = "#83adad" }
perm_write = { fg = "#d75f5f" }

progress_error = { fg = "#d75f5f", bg = "#262626" }
progress_label = { fg = "#dab997", bg = "#262626" }
progress_normal = { fg = "#dab997", bg = "#262626" }

[pick]
active = { fg = "#d485ad" }
border = { fg = "#83adad" }
inactive = { fg = "#dab997" }

[task]
title = { fg = "#83adad" }
border = { fg = "#83adad" }
hovered = { fg = "#dab997", bg = "#4e4e4e" }

[input]
border = { fg = "#83adad" }
selected = { bg = "#4e4e4e" }

[help]
desc = { fg = "#dab997" }
on = { fg = "#85ad85" }
run = { fg = "#d485ad" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4e4e4e", bg = "#dab997" }

[which]
mask = { bg = "#4e4e4e" }
desc = { fg = "#dab997" }
cand = { fg = "#85ad85" }
rest = { fg = "#d65d0e" }

separator_style = { fg = "#949494" }

[notify]
title_info = { fg = "#85ad85" }
title_warn = { fg = "#ffaf00" }
title_warn = { fg = "#d75f5f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#85ad85" },
  { mime = "{audio, video}/*", fg = "#ffaf00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#afaf00" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#83adad" },
  { mime = "*", fg = "#dab997" },
]


