[manager]
cwd = { fg = "#afc4db" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f9ee98" }
find_position = { fg = "#9b859d" }

marker_copied = { fg = "#54be0d", bg = "#54be0d" }
marker_cut = { fg = "#cf6a4c", bg = "#cf6a4c" }
marker_selected = { fg = "#f9ee98", bg = "#f9ee98" }

tab_inactive = { fg = "#8a8986" }
tab_active = { fg = "#28211c", bg = "#8a8986"}

count_copied = { fg = "#28211c", bg = "#54be0d" }
count_cut = { fg = "#28211c", bg = "#cf6a4c" }
count_selected = { fg = "#28211c", bg = "#f9ee98" }

border_style = { fg = "#5ea6ea" }

[mode]
normal_main = { fg = "#28211c", bg = "#5ea6ea", bold = true }
normal_alt = { fg = "#5ea6ea", bg = "#5e5d5c" }

select_alt = { fg = "#9b859d", bg = "#5e5d5c" }
select_main = { fg = "#28211c", bg = "#9b859d", bold = true }

unset_main = { fg = "#28211c", bg = "#cf6a4c", bold = true }
unset_alt = { fg = "#cf6a4c", bg = "#5e5d5c" }

[status]
perm_exec = { fg = "#54be0d" }
perm_read = { fg = "#f9ee98" }
perm_sep = { fg = "#afc4db" }
perm_type = { fg = "#5ea6ea" }
perm_write = { fg = "#cf6a4c" }

progress_error = { fg = "#cf6a4c", bg = "#28211c" }
progress_label = { fg = "#8a8986", bg = "#28211c" }
progress_normal = { fg = "#8a8986", bg = "#28211c" }

[pick]
active = { fg = "#9b859d" }
border = { fg = "#5ea6ea" }
inactive = { fg = "#8a8986" }

[task]
title = { fg = "#5ea6ea" }
border = { fg = "#5ea6ea" }
hovered = { fg = "#8a8986", bg = "#5e5d5c" }

[input]
border = { fg = "#5ea6ea" }
selected = { bg = "#5e5d5c" }

[help]
desc = { fg = "#8a8986" }
on = { fg = "#afc4db" }
run = { fg = "#9b859d" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5e5d5c", bg = "#8a8986" }

[which]
mask = { bg = "#5e5d5c" }
desc = { fg = "#8a8986" }
cand = { fg = "#afc4db" }
rest = { fg = "#937121" }

separator_style = { fg = "#797977" }

[notify]
title_info = { fg = "#afc4db" }
title_warn = { fg = "#f9ee98" }
title_warn = { fg = "#cf6a4c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#afc4db" },
  { mime = "{audio, video}/*", fg = "#f9ee98" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#54be0d" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#5ea6ea" },
  { mime = "*", fg = "#8a8986" },
]


