[manager]
cwd = { fg = "#673ab7" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ff6f00" }
find_position = { fg = "#be95ff" }

marker_copied = { fg = "#0f62fe", bg = "#0f62fe" }
marker_cut = { fg = "#ff7eb6", bg = "#ff7eb6" }
marker_selected = { fg = "#ff6f00", bg = "#ff6f00" }

tab_inactive = { fg = "#393939" }
tab_active = { fg = "#f2f4f8", bg = "#393939"}

count_copied = { fg = "#f2f4f8", bg = "#0f62fe" }
count_cut = { fg = "#f2f4f8", bg = "#ff7eb6" }
count_selected = { fg = "#f2f4f8", bg = "#ff6f00" }

border_style = { fg = "#42be65" }

[mode]
normal_main = { fg = "#f2f4f8", bg = "#42be65", bold = true }
normal_alt = { fg = "#42be65", bg = "#525252" }

select_alt = { fg = "#be95ff", bg = "#525252" }
select_main = { fg = "#f2f4f8", bg = "#be95ff", bold = true }

unset_main = { fg = "#f2f4f8", bg = "#ff7eb6", bold = true }
unset_alt = { fg = "#ff7eb6", bg = "#525252" }

[status]
perm_exec = { fg = "#0f62fe" }
perm_read = { fg = "#ff6f00" }
perm_sep = { fg = "#673ab7" }
perm_type = { fg = "#42be65" }
perm_write = { fg = "#ff7eb6" }

progress_error = { fg = "#ff7eb6", bg = "#f2f4f8" }
progress_label = { fg = "#393939", bg = "#f2f4f8" }
progress_normal = { fg = "#393939", bg = "#f2f4f8" }

[pick]
active = { fg = "#be95ff" }
border = { fg = "#42be65" }
inactive = { fg = "#393939" }

[task]
title = { fg = "#42be65" }
border = { fg = "#42be65" }
hovered = { fg = "#393939", bg = "#45475a" }

[input]
border = { fg = "#42be65" }
selected = { bg = "#525252" }

[help]
desc = { fg = "#393939" }
on = { fg = "#673ab7" }
run = { fg = "#be95ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#525252", bg = "#393939" }

[which]
mask = { bg = "#525252" }
desc = { fg = "#393939" }
cand = { fg = "#673ab7" }
rest = { fg = "#37474f" }

separator_style = { fg = "#262626" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#673ab7" },
  { mime = "{audio, video}/*", fg = "#ff6f00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#0f62fe" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#42be65", bold = true },
  { mime = "*", fg = "#393939" },
]


