[manager]
cwd = { fg = "#66d9ef" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fdb11f" }
find_position = { fg = "#9bc0c8" }

marker_copied = { fg = "#499180", bg = "#499180" }
marker_cut = { fg = "#ff4658", bg = "#ff4658" }
marker_selected = { fg = "#fdb11f", bg = "#fdb11f" }

tab_inactive = { fg = "#c7c7a5" }
tab_active = { fg = "#171e1f", bg = "#c7c7a5"}

count_copied = { fg = "#171e1f", bg = "#499180" }
count_cut = { fg = "#171e1f", bg = "#ff4658" }
count_selected = { fg = "#171e1f", bg = "#fdb11f" }

border_style = { fg = "#498091" }

[mode]
normal_main = { fg = "#171e1f", bg = "#498091", bold = true }
normal_alt = { fg = "#498091", bg = "#373c3d" }

select_alt = { fg = "#9bc0c8", bg = "#373c3d" }
select_main = { fg = "#171e1f", bg = "#9bc0c8", bold = true }

unset_main = { fg = "#171e1f", bg = "#ff4658", bold = true }
unset_alt = { fg = "#ff4658", bg = "#373c3d" }

[status]
perm_exec = { fg = "#499180" }
perm_read = { fg = "#fdb11f" }
perm_sep = { fg = "#66d9ef" }
perm_type = { fg = "#498091" }
perm_write = { fg = "#ff4658" }

progress_error = { fg = "#ff4658", bg = "#171e1f" }
progress_label = { fg = "#c7c7a5", bg = "#171e1f" }
progress_normal = { fg = "#c7c7a5", bg = "#171e1f" }

[pick]
active = { fg = "#9bc0c8" }
border = { fg = "#498091" }
inactive = { fg = "#c7c7a5" }

[task]
title = { fg = "#498091" }
border = { fg = "#498091" }
hovered = { fg = "#c7c7a5", bg = "#373c3d" }

[input]
border = { fg = "#498091" }
selected = { bg = "#373c3d" }

[help]
desc = { fg = "#c7c7a5" }
on = { fg = "#66d9ef" }
run = { fg = "#9bc0c8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#373c3d", bg = "#c7c7a5" }

[which]
mask = { bg = "#373c3d" }
desc = { fg = "#c7c7a5" }
cand = { fg = "#66d9ef" }
rest = { fg = "#d27b53" }

separator_style = { fg = "#818f80" }

[notify]
title_info = { fg = "#66d9ef" }
title_warn = { fg = "#fdb11f" }
title_warn = { fg = "#ff4658" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#66d9ef" },
  { mime = "{audio, video}/*", fg = "#fdb11f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#499180" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#498091" },
  { mime = "*", fg = "#c7c7a5" },
]


