[manager]
cwd = { fg = "#40dfff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f29df2" }
find_position = { fg = "#7e5ce6" }

marker_copied = { fg = "#4595e6", bg = "#4595e6" }
marker_cut = { fg = "#a82ee6", bg = "#a82ee6" }
marker_selected = { fg = "#f29df2", bg = "#f29df2" }

tab_inactive = { fg = "#b08ae6" }
tab_active = { fg = "#000000", bg = "#b08ae6"}

count_copied = { fg = "#000000", bg = "#4595e6" }
count_cut = { fg = "#000000", bg = "#a82ee6" }
count_selected = { fg = "#000000", bg = "#f29df2" }

border_style = { fg = "#4136d9" }

[mode]
normal_main = { fg = "#000000", bg = "#4136d9", bold = true }
normal_alt = { fg = "#4136d9", bg = "#432d59" }

select_alt = { fg = "#7e5ce6", bg = "#432d59" }
select_main = { fg = "#000000", bg = "#7e5ce6", bold = true }

unset_main = { fg = "#000000", bg = "#a82ee6", bold = true }
unset_alt = { fg = "#a82ee6", bg = "#432d59" }

[status]
perm_exec = { fg = "#4595e6" }
perm_read = { fg = "#f29df2" }
perm_sep = { fg = "#40dfff" }
perm_type = { fg = "#4136d9" }
perm_write = { fg = "#a82ee6" }

progress_error = { fg = "#a82ee6", bg = "#000000" }
progress_label = { fg = "#b08ae6", bg = "#000000" }
progress_normal = { fg = "#b08ae6", bg = "#000000" }

[pick]
active = { fg = "#7e5ce6" }
border = { fg = "#4136d9" }
inactive = { fg = "#b08ae6" }

[task]
title = { fg = "#4136d9" }
border = { fg = "#4136d9" }
hovered = { fg = "#b08ae6", bg = "#45475a" }

[input]
border = { fg = "#4136d9" }
selected = { bg = "#432d59" }

[help]
desc = { fg = "#b08ae6" }
on = { fg = "#40dfff" }
run = { fg = "#7e5ce6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#432d59", bg = "#b08ae6" }

[which]
mask = { bg = "#432d59" }
desc = { fg = "#b08ae6" }
cand = { fg = "#40dfff" }
rest = { fg = "#a886bf" }

separator_style = { fg = "#00ff00" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#40dfff" },
  { mime = "{audio, video}/*", fg = "#f29df2" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#4595e6" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#4136d9", bold = true },
  { mime = "*", fg = "#b08ae6" },
]


