[manager]
cwd = { fg = "#3d97b8" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c38418" }
find_position = { fg = "#6666ea" }

marker_copied = { fg = "#7b9726", bg = "#7b9726" }
marker_cut = { fg = "#f22c40", bg = "#f22c40" }
marker_selected = { fg = "#c38418", bg = "#c38418" }

tab_inactive = { fg = "#a8a19f" }
tab_active = { fg = "#1b1918", bg = "#a8a19f"}

count_copied = { fg = "#1b1918", bg = "#7b9726" }
count_cut = { fg = "#1b1918", bg = "#f22c40" }
count_selected = { fg = "#1b1918", bg = "#c38418" }

border_style = { fg = "#407ee7" }

[mode]
normal_main = { fg = "#1b1918", bg = "#407ee7", bold = true }
normal_alt = { fg = "#407ee7", bg = "#68615e" }

select_alt = { fg = "#6666ea", bg = "#68615e" }
select_main = { fg = "#1b1918", bg = "#6666ea", bold = true }

unset_main = { fg = "#1b1918", bg = "#f22c40", bold = true }
unset_alt = { fg = "#f22c40", bg = "#68615e" }

[status]
perm_exec = { fg = "#7b9726" }
perm_read = { fg = "#c38418" }
perm_sep = { fg = "#3d97b8" }
perm_type = { fg = "#407ee7" }
perm_write = { fg = "#f22c40" }

progress_error = { fg = "#f22c40", bg = "#1b1918" }
progress_label = { fg = "#a8a19f", bg = "#1b1918" }
progress_normal = { fg = "#a8a19f", bg = "#1b1918" }

[pick]
active = { fg = "#6666ea" }
border = { fg = "#407ee7" }
inactive = { fg = "#a8a19f" }

[task]
title = { fg = "#407ee7" }
border = { fg = "#407ee7" }
hovered = { fg = "#a8a19f", bg = "#45475a" }

[input]
border = { fg = "#407ee7" }
selected = { bg = "#68615e" }

[help]
desc = { fg = "#a8a19f" }
on = { fg = "#3d97b8" }
run = { fg = "#6666ea" }
hovered = { reversed = true, bold = true }
footer = { fg = "#68615e", bg = "#a8a19f" }

[which]
mask = { bg = "#68615e" }
desc = { fg = "#a8a19f" }
cand = { fg = "#3d97b8" }
rest = { fg = "#c33ff3" }

separator_style = { fg = "#9c9491" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3d97b8" },
  { mime = "{audio, video}/*", fg = "#c38418" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7b9726" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#407ee7", bold = true },
  { mime = "*", fg = "#a8a19f" },
]


