[manager]
cwd = { fg = "#70e1e8" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ebbf83" }
find_position = { fg = "#b62d65" }

marker_copied = { fg = "#8bd49c", bg = "#8bd49c" }
marker_cut = { fg = "#d95468", bg = "#d95468" }
marker_selected = { fg = "#ebbf83", bg = "#ebbf83" }

tab_inactive = { fg = "#d8e2ec" }
tab_active = { fg = "#171d23", bg = "#d8e2ec"}

count_copied = { fg = "#171d23", bg = "#8bd49c" }
count_cut = { fg = "#171d23", bg = "#d95468" }
count_selected = { fg = "#171d23", bg = "#ebbf83" }

border_style = { fg = "#539afc" }

[mode]
normal_main = { fg = "#171d23", bg = "#539afc", bold = true }
normal_alt = { fg = "#539afc", bg = "#28323a" }

select_alt = { fg = "#b62d65", bg = "#28323a" }
select_main = { fg = "#171d23", bg = "#b62d65", bold = true }

unset_main = { fg = "#171d23", bg = "#d95468", bold = true }
unset_alt = { fg = "#d95468", bg = "#28323a" }

[status]
perm_exec = { fg = "#8bd49c" }
perm_read = { fg = "#ebbf83" }
perm_sep = { fg = "#70e1e8" }
perm_type = { fg = "#539afc" }
perm_write = { fg = "#d95468" }

progress_error = { fg = "#d95468", bg = "#171d23" }
progress_label = { fg = "#d8e2ec", bg = "#171d23" }
progress_normal = { fg = "#d8e2ec", bg = "#171d23" }

[pick]
active = { fg = "#b62d65" }
border = { fg = "#539afc" }
inactive = { fg = "#d8e2ec" }

[task]
title = { fg = "#539afc" }
border = { fg = "#539afc" }
hovered = { fg = "#d8e2ec", bg = "#28323a" }

[input]
border = { fg = "#539afc" }
selected = { bg = "#28323a" }

[help]
desc = { fg = "#d8e2ec" }
on = { fg = "#70e1e8" }
run = { fg = "#b62d65" }
hovered = { reversed = true, bold = true }
footer = { fg = "#28323a", bg = "#d8e2ec" }

[which]
mask = { bg = "#28323a" }
desc = { fg = "#d8e2ec" }
cand = { fg = "#70e1e8" }
rest = { fg = "#dd9d82" }

separator_style = { fg = "#b7c5d3" }

[notify]
title_info = { fg = "#70e1e8" }
title_warn = { fg = "#ebbf83" }
title_warn = { fg = "#d95468" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#70e1e8" },
  { mime = "{audio, video}/*", fg = "#ebbf83" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8bd49c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#539afc" },
  { mime = "*", fg = "#d8e2ec" },
]


