[manager]
cwd = { fg = "#02abea" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fbf305" }
find_position = { fg = "#4700a5" }

marker_copied = { fg = "#1fb714", bg = "#1fb714" }
marker_cut = { fg = "#dd0907", bg = "#dd0907" }
marker_selected = { fg = "#fbf305", bg = "#fbf305" }

tab_inactive = { fg = "#c0c0c0" }
tab_active = { fg = "#000000", bg = "#c0c0c0"}

count_copied = { fg = "#000000", bg = "#1fb714" }
count_cut = { fg = "#000000", bg = "#dd0907" }
count_selected = { fg = "#000000", bg = "#fbf305" }

border_style = { fg = "#0000d3" }

[mode]
normal_main = { fg = "#000000", bg = "#0000d3", bold = true }
normal_alt = { fg = "#0000d3", bg = "#404040" }

select_alt = { fg = "#4700a5", bg = "#404040" }
select_main = { fg = "#000000", bg = "#4700a5", bold = true }

unset_main = { fg = "#000000", bg = "#dd0907", bold = true }
unset_alt = { fg = "#dd0907", bg = "#404040" }

[status]
perm_exec = { fg = "#1fb714" }
perm_read = { fg = "#fbf305" }
perm_sep = { fg = "#02abea" }
perm_type = { fg = "#0000d3" }
perm_write = { fg = "#dd0907" }

progress_error = { fg = "#dd0907", bg = "#000000" }
progress_label = { fg = "#c0c0c0", bg = "#000000" }
progress_normal = { fg = "#c0c0c0", bg = "#000000" }

[pick]
active = { fg = "#4700a5" }
border = { fg = "#0000d3" }
inactive = { fg = "#c0c0c0" }

[task]
title = { fg = "#0000d3" }
border = { fg = "#0000d3" }
hovered = { fg = "#c0c0c0", bg = "#45475a" }

[input]
border = { fg = "#0000d3" }
selected = { bg = "#404040" }

[help]
desc = { fg = "#c0c0c0" }
on = { fg = "#02abea" }
run = { fg = "#4700a5" }
hovered = { reversed = true, bold = true }
footer = { fg = "#404040", bg = "#c0c0c0" }

[which]
mask = { bg = "#404040" }
desc = { fg = "#c0c0c0" }
cand = { fg = "#02abea" }
rest = { fg = "#90713a" }

separator_style = { fg = "#808080" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#02abea" },
  { mime = "{audio, video}/*", fg = "#fbf305" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#1fb714" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0000d3", bold = true },
  { mime = "*", fg = "#c0c0c0" },
]


