[mgr]
cwd = { fg = "#01716f" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#645a00" }
find_position = { fg = "#6645c2" }

marker_copied = { fg = "#0c680c", bg = "#0c680c" }
marker_cut = { fg = "#ac1f35", bg = "#ac1f35" }
marker_selected = { fg = "#645a00", bg = "#645a00" }

tab_inactive = { fg = "#292929" }
tab_active = { fg = "#fdf9f5", bg = "#292929"}

count_copied = { fg = "#fdf9f5", bg = "#0c680c" }
count_cut = { fg = "#fdf9f5", bg = "#ac1f35" }
count_selected = { fg = "#fdf9f5", bg = "#645a00" }

border_style = { fg = "#0158ad" }

[mode]
normal_main = { fg = "#fdf9f5", bg = "#0158ad", bold = true }
normal_alt = { fg = "#0158ad", bg = "#ffeada" }

select_alt = { fg = "#6645c2", bg = "#ffeada" }
select_main = { fg = "#fdf9f5", bg = "#6645c2", bold = true }

unset_main = { fg = "#fdf9f5", bg = "#ac1f35", bold = true }
unset_alt = { fg = "#ac1f35", bg = "#ffeada" }

[status]
perm_exec = { fg = "#0c680c" }
perm_read = { fg = "#645a00" }
perm_sep = { fg = "#01716f" }
perm_type = { fg = "#0158ad" }
perm_write = { fg = "#ac1f35" }

progress_error = { fg = "#ac1f35", bg = "#fdf9f5" }
progress_label = { fg = "#292929", bg = "#fdf9f5" }
progress_normal = { fg = "#292929", bg = "#fdf9f5" }

[pick]
active = { fg = "#6645c2" }
border = { fg = "#0158ad" }
inactive = { fg = "#292929" }

[task]
title = { fg = "#0158ad" }
border = { fg = "#0158ad" }
hovered = { fg = "#292929", bg = "#ffeada" }

[input]
border = { fg = "#0158ad" }
selected = { bg = "#ffeada" }

[help]
desc = { fg = "#292929" }
on = { fg = "#01716f" }
run = { fg = "#6645c2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#ffeada", bg = "#292929" }

[which]
mask = { bg = "#ffeada" }
desc = { fg = "#292929" }
cand = { fg = "#01716f" }
rest = { fg = "#a81a66" }

separator_style = { fg = "#404040" }

[notify]
title_info = { fg = "#01716f" }
title_warn = { fg = "#645a00" }
title_warn = { fg = "#ac1f35" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#01716f" },
  { mime = "{audio, video}/*", fg = "#645a00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#0c680c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0158ad" },
  { mime = "*", fg = "#292929" },
]


