[mgr]
cwd = { fg = "#80b1d3" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#dca060" }
find_position = { fg = "#756bb1" }

marker_copied = { fg = "#31a354", bg = "#31a354" }
marker_cut = { fg = "#e31a1c", bg = "#e31a1c" }
marker_selected = { fg = "#dca060", bg = "#dca060" }

tab_inactive = { fg = "#b7b8b9" }
tab_active = { fg = "#0c0d0e", bg = "#b7b8b9"}

count_copied = { fg = "#0c0d0e", bg = "#31a354" }
count_cut = { fg = "#0c0d0e", bg = "#e31a1c" }
count_selected = { fg = "#0c0d0e", bg = "#dca060" }

border_style = { fg = "#3182bd" }

[mode]
normal_main = { fg = "#0c0d0e", bg = "#3182bd", bold = true }
normal_alt = { fg = "#3182bd", bg = "#515253" }

select_alt = { fg = "#756bb1", bg = "#515253" }
select_main = { fg = "#0c0d0e", bg = "#756bb1", bold = true }

unset_main = { fg = "#0c0d0e", bg = "#e31a1c", bold = true }
unset_alt = { fg = "#e31a1c", bg = "#515253" }

[status]
perm_exec = { fg = "#31a354" }
perm_read = { fg = "#dca060" }
perm_sep = { fg = "#80b1d3" }
perm_type = { fg = "#3182bd" }
perm_write = { fg = "#e31a1c" }

progress_error = { fg = "#e31a1c", bg = "#0c0d0e" }
progress_label = { fg = "#b7b8b9", bg = "#0c0d0e" }
progress_normal = { fg = "#b7b8b9", bg = "#0c0d0e" }

[pick]
active = { fg = "#756bb1" }
border = { fg = "#3182bd" }
inactive = { fg = "#b7b8b9" }

[task]
title = { fg = "#3182bd" }
border = { fg = "#3182bd" }
hovered = { fg = "#b7b8b9", bg = "#515253" }

[input]
border = { fg = "#3182bd" }
selected = { bg = "#515253" }

[help]
desc = { fg = "#b7b8b9" }
on = { fg = "#80b1d3" }
run = { fg = "#756bb1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#515253", bg = "#b7b8b9" }

[which]
mask = { bg = "#515253" }
desc = { fg = "#b7b8b9" }
cand = { fg = "#80b1d3" }
rest = { fg = "#b15928" }

separator_style = { fg = "#959697" }

[notify]
title_info = { fg = "#80b1d3" }
title_warn = { fg = "#dca060" }
title_warn = { fg = "#e31a1c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#80b1d3" },
  { mime = "{audio, video}/*", fg = "#dca060" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#31a354" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#3182bd" },
  { mime = "*", fg = "#b7b8b9" },
]


