[manager]
cwd = { fg = "#9fbbf3" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#d7a65f" }
find_position = { fg = "#a485dd" }

marker_copied = { fg = "#95c561", bg = "#95c561" }
marker_cut = { fg = "#ee6d85", bg = "#ee6d85" }
marker_selected = { fg = "#d7a65f", bg = "#d7a65f" }

tab_inactive = { fg = "#a0a8cd" }
tab_active = { fg = "#11121d", bg = "#a0a8cd"}

count_copied = { fg = "#11121d", bg = "#95c561" }
count_cut = { fg = "#11121d", bg = "#ee6d85" }
count_selected = { fg = "#11121d", bg = "#d7a65f" }

border_style = { fg = "#7199ee" }

[mode]
normal_main = { fg = "#11121d", bg = "#7199ee", bold = true }
normal_alt = { fg = "#7199ee", bg = "#212234" }

select_alt = { fg = "#a485dd", bg = "#212234" }
select_main = { fg = "#11121d", bg = "#a485dd", bold = true }

unset_main = { fg = "#11121d", bg = "#ee6d85", bold = true }
unset_alt = { fg = "#ee6d85", bg = "#212234" }

[status]
perm_exec = { fg = "#95c561" }
perm_read = { fg = "#d7a65f" }
perm_sep = { fg = "#9fbbf3" }
perm_type = { fg = "#7199ee" }
perm_write = { fg = "#ee6d85" }

progress_error = { fg = "#ee6d85", bg = "#11121d" }
progress_label = { fg = "#a0a8cd", bg = "#11121d" }
progress_normal = { fg = "#a0a8cd", bg = "#11121d" }

[pick]
active = { fg = "#a485dd" }
border = { fg = "#7199ee" }
inactive = { fg = "#a0a8cd" }

[task]
title = { fg = "#7199ee" }
border = { fg = "#7199ee" }
hovered = { fg = "#a0a8cd", bg = "#212234" }

[input]
border = { fg = "#7199ee" }
selected = { bg = "#212234" }

[help]
desc = { fg = "#a0a8cd" }
on = { fg = "#9fbbf3" }
run = { fg = "#a485dd" }
hovered = { reversed = true, bold = true }
footer = { fg = "#212234", bg = "#a0a8cd" }

[which]
mask = { bg = "#212234" }
desc = { fg = "#a0a8cd" }
cand = { fg = "#9fbbf3" }
rest = { fg = "#773440" }

separator_style = { fg = "#4a5057" }

[notify]
title_info = { fg = "#9fbbf3" }
title_warn = { fg = "#d7a65f" }
title_warn = { fg = "#ee6d85" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#9fbbf3" },
  { mime = "{audio, video}/*", fg = "#d7a65f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#95c561" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7199ee" },
  { mime = "*", fg = "#a0a8cd" },
]


