[manager]
cwd = { fg = "#a485dd" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#7199ee" }
find_position = { fg = "#ee6d85" }

marker_copied = { fg = "#d7a65f", bg = "#d7a65f" }
marker_cut = { fg = "#a485dd", bg = "#a485dd" }
marker_selected = { fg = "#7199ee", bg = "#7199ee" }

tab_inactive = { fg = "#abb2bf" }
tab_active = { fg = "#11121d", bg = "#abb2bf"}

count_copied = { fg = "#11121d", bg = "#d7a65f" }
count_cut = { fg = "#11121d", bg = "#a485dd" }
count_selected = { fg = "#11121d", bg = "#7199ee" }

border_style = { fg = "#95c561" }

[mode]
normal_main = { fg = "#11121d", bg = "#95c561", bold = true }
normal_alt = { fg = "#95c561", bg = "#43444f" }

select_alt = { fg = "#ee6d85", bg = "#43444f" }
select_main = { fg = "#11121d", bg = "#ee6d85", bold = true }

unset_main = { fg = "#11121d", bg = "#a485dd", bold = true }
unset_alt = { fg = "#a485dd", bg = "#43444f" }

[status]
perm_exec = { fg = "#d7a65f" }
perm_read = { fg = "#7199ee" }
perm_sep = { fg = "#a485dd" }
perm_type = { fg = "#95c561" }
perm_write = { fg = "#a485dd" }

progress_error = { fg = "#a485dd", bg = "#11121d" }
progress_label = { fg = "#abb2bf", bg = "#11121d" }
progress_normal = { fg = "#abb2bf", bg = "#11121d" }

[pick]
active = { fg = "#ee6d85" }
border = { fg = "#95c561" }
inactive = { fg = "#abb2bf" }

[task]
title = { fg = "#95c561" }
border = { fg = "#95c561" }
hovered = { fg = "#abb2bf", bg = "#45475a" }

[input]
border = { fg = "#95c561" }
selected = { bg = "#43444f" }

[help]
desc = { fg = "#abb2bf" }
on = { fg = "#a485dd" }
run = { fg = "#ee6d85" }
hovered = { reversed = true, bold = true }
footer = { fg = "#43444f", bg = "#abb2bf" }

[which]
mask = { bg = "#43444f" }
desc = { fg = "#abb2bf" }
cand = { fg = "#a485dd" }
rest = { fg = "#773440" }

separator_style = { fg = "#1b1c27" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#a485dd" },
  { mime = "{audio, video}/*", fg = "#7199ee" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#d7a65f" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#95c561", bold = true },
  { mime = "*", fg = "#abb2bf" },
]


