[manager]
cwd = { fg = "#26c6da" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#80deea" }
find_position = { fg = "#00acc1" }

marker_copied = { fg = "#4dd0e1", bg = "#4dd0e1" }
marker_cut = { fg = "#16c1d9", bg = "#16c1d9" }
marker_selected = { fg = "#80deea", bg = "#80deea" }

tab_inactive = { fg = "#095b67" }
tab_active = { fg = "#021012", bg = "#095b67"}

count_copied = { fg = "#021012", bg = "#4dd0e1" }
count_cut = { fg = "#021012", bg = "#16c1d9" }
count_selected = { fg = "#021012", bg = "#80deea" }

border_style = { fg = "#00bcd4" }

[mode]
normal_main = { fg = "#021012", bg = "#00bcd4", bold = true }
normal_alt = { fg = "#00bcd4", bg = "#041f23" }

select_alt = { fg = "#00acc1", bg = "#041f23" }
select_main = { fg = "#021012", bg = "#00acc1", bold = true }

unset_main = { fg = "#021012", bg = "#16c1d9", bold = true }
unset_alt = { fg = "#16c1d9", bg = "#041f23" }

[status]
perm_exec = { fg = "#4dd0e1" }
perm_read = { fg = "#80deea" }
perm_sep = { fg = "#26c6da" }
perm_type = { fg = "#00bcd4" }
perm_write = { fg = "#16c1d9" }

progress_error = { fg = "#16c1d9", bg = "#021012" }
progress_label = { fg = "#095b67", bg = "#021012" }
progress_normal = { fg = "#095b67", bg = "#021012" }

[pick]
active = { fg = "#00acc1" }
border = { fg = "#00bcd4" }
inactive = { fg = "#095b67" }

[task]
title = { fg = "#00bcd4" }
border = { fg = "#00bcd4" }
hovered = { fg = "#095b67", bg = "#041f23" }

[input]
border = { fg = "#00bcd4" }
selected = { bg = "#041f23" }

[help]
desc = { fg = "#095b67" }
on = { fg = "#26c6da" }
run = { fg = "#00acc1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#041f23", bg = "#095b67" }

[which]
mask = { bg = "#041f23" }
desc = { fg = "#095b67" }
cand = { fg = "#26c6da" }
rest = { fg = "#0097a7" }

separator_style = { fg = "#064048" }

[notify]
title_info = { fg = "#26c6da" }
title_warn = { fg = "#80deea" }
title_warn = { fg = "#16c1d9" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#26c6da" },
  { mime = "{audio, video}/*", fg = "#80deea" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#4dd0e1" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#00bcd4" },
  { mime = "*", fg = "#095b67" },
]


