[mgr]
cwd = { fg = "#159393" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#bb8a35" }
find_position = { fg = "#7b59c0" }

marker_copied = { fg = "#918b3b", bg = "#918b3b" }
marker_cut = { fg = "#ca402b", bg = "#ca402b" }
marker_selected = { fg = "#bb8a35", bg = "#bb8a35" }

tab_inactive = { fg = "#695d69" }
tab_active = { fg = "#f7f3f7", bg = "#695d69"}

count_copied = { fg = "#f7f3f7", bg = "#918b3b" }
count_cut = { fg = "#f7f3f7", bg = "#ca402b" }
count_selected = { fg = "#f7f3f7", bg = "#bb8a35" }

border_style = { fg = "#516aec" }

[mode]
normal_main = { fg = "#f7f3f7", bg = "#516aec", bold = true }
normal_alt = { fg = "#516aec", bg = "#ab9bab" }

select_alt = { fg = "#7b59c0", bg = "#ab9bab" }
select_main = { fg = "#f7f3f7", bg = "#7b59c0", bold = true }

unset_main = { fg = "#f7f3f7", bg = "#ca402b", bold = true }
unset_alt = { fg = "#ca402b", bg = "#ab9bab" }

[status]
perm_exec = { fg = "#918b3b" }
perm_read = { fg = "#bb8a35" }
perm_sep = { fg = "#159393" }
perm_type = { fg = "#516aec" }
perm_write = { fg = "#ca402b" }

progress_error = { fg = "#ca402b", bg = "#f7f3f7" }
progress_label = { fg = "#695d69", bg = "#f7f3f7" }
progress_normal = { fg = "#695d69", bg = "#f7f3f7" }

[pick]
active = { fg = "#7b59c0" }
border = { fg = "#516aec" }
inactive = { fg = "#695d69" }

[task]
title = { fg = "#516aec" }
border = { fg = "#516aec" }
hovered = { fg = "#695d69", bg = "#ab9bab" }

[input]
border = { fg = "#516aec" }
selected = { bg = "#ab9bab" }

[help]
desc = { fg = "#695d69" }
on = { fg = "#159393" }
run = { fg = "#7b59c0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#ab9bab", bg = "#695d69" }

[which]
mask = { bg = "#ab9bab" }
desc = { fg = "#695d69" }
cand = { fg = "#159393" }
rest = { fg = "#cc33cc" }

separator_style = { fg = "#776977" }

[notify]
title_info = { fg = "#159393" }
title_warn = { fg = "#bb8a35" }
title_warn = { fg = "#ca402b" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#159393" },
  { mime = "{audio, video}/*", fg = "#bb8a35" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#918b3b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#516aec" },
  { mime = "*", fg = "#695d69" },
]


