[manager]
cwd = { fg = "#75a738" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#a88339" }
find_position = { fg = "#8868b3" }

marker_copied = { fg = "#18974e", bg = "#18974e" }
marker_cut = { fg = "#c35359", bg = "#c35359" }
marker_selected = { fg = "#a88339", bg = "#a88339" }

tab_inactive = { fg = "#948e48" }
tab_active = { fg = "#201602", bg = "#948e48"}

count_copied = { fg = "#201602", bg = "#18974e" }
count_cut = { fg = "#201602", bg = "#c35359" }
count_selected = { fg = "#201602", bg = "#a88339" }

border_style = { fg = "#477ca1" }

[mode]
normal_main = { fg = "#201602", bg = "#477ca1", bold = true }
normal_alt = { fg = "#477ca1", bg = "#5f5b17" }

select_alt = { fg = "#8868b3", bg = "#5f5b17" }
select_main = { fg = "#201602", bg = "#8868b3", bold = true }

unset_main = { fg = "#201602", bg = "#c35359", bold = true }
unset_alt = { fg = "#c35359", bg = "#5f5b17" }

[status]
perm_exec = { fg = "#18974e" }
perm_read = { fg = "#a88339" }
perm_sep = { fg = "#75a738" }
perm_type = { fg = "#477ca1" }
perm_write = { fg = "#c35359" }

progress_error = { fg = "#c35359", bg = "#201602" }
progress_label = { fg = "#948e48", bg = "#201602" }
progress_normal = { fg = "#948e48", bg = "#201602" }

[pick]
active = { fg = "#8868b3" }
border = { fg = "#477ca1" }
inactive = { fg = "#948e48" }

[task]
title = { fg = "#477ca1" }
border = { fg = "#477ca1" }
hovered = { fg = "#948e48", bg = "#5f5b17" }

[input]
border = { fg = "#477ca1" }
selected = { bg = "#5f5b17" }

[help]
desc = { fg = "#948e48" }
on = { fg = "#75a738" }
run = { fg = "#8868b3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5f5b17", bg = "#948e48" }

[which]
mask = { bg = "#5f5b17" }
desc = { fg = "#948e48" }
cand = { fg = "#75a738" }
rest = { fg = "#b3588e" }

separator_style = { fg = "#86813b" }

[notify]
title_info = { fg = "#75a738" }
title_warn = { fg = "#a88339" }
title_warn = { fg = "#c35359" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#75a738" },
  { mime = "{audio, video}/*", fg = "#a88339" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#18974e" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#477ca1" },
  { mime = "*", fg = "#948e48" },
]


