[mgr]
cwd = { fg = "#12cfc0" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ddb26f" }
find_position = { fg = "#e1a3ee" }

marker_copied = { fg = "#acc267", bg = "#acc267" }
marker_cut = { fg = "#fb9fb1", bg = "#fb9fb1" }
marker_selected = { fg = "#ddb26f", bg = "#ddb26f" }

tab_inactive = { fg = "#d0d0d0" }
tab_active = { fg = "#151515", bg = "#d0d0d0"}

count_copied = { fg = "#151515", bg = "#acc267" }
count_cut = { fg = "#151515", bg = "#fb9fb1" }
count_selected = { fg = "#151515", bg = "#ddb26f" }

border_style = { fg = "#6fc2ef" }

[mode]
normal_main = { fg = "#151515", bg = "#6fc2ef", bold = true }
normal_alt = { fg = "#6fc2ef", bg = "#303030" }

select_alt = { fg = "#e1a3ee", bg = "#303030" }
select_main = { fg = "#151515", bg = "#e1a3ee", bold = true }

unset_main = { fg = "#151515", bg = "#fb9fb1", bold = true }
unset_alt = { fg = "#fb9fb1", bg = "#303030" }

[status]
perm_exec = { fg = "#acc267" }
perm_read = { fg = "#ddb26f" }
perm_sep = { fg = "#12cfc0" }
perm_type = { fg = "#6fc2ef" }
perm_write = { fg = "#fb9fb1" }

progress_error = { fg = "#fb9fb1", bg = "#151515" }
progress_label = { fg = "#d0d0d0", bg = "#151515" }
progress_normal = { fg = "#d0d0d0", bg = "#151515" }

[pick]
active = { fg = "#e1a3ee" }
border = { fg = "#6fc2ef" }
inactive = { fg = "#d0d0d0" }

[task]
title = { fg = "#6fc2ef" }
border = { fg = "#6fc2ef" }
hovered = { fg = "#d0d0d0", bg = "#303030" }

[input]
border = { fg = "#6fc2ef" }
selected = { bg = "#303030" }

[help]
desc = { fg = "#d0d0d0" }
on = { fg = "#12cfc0" }
run = { fg = "#e1a3ee" }
hovered = { reversed = true, bold = true }
footer = { fg = "#303030", bg = "#d0d0d0" }

[which]
mask = { bg = "#303030" }
desc = { fg = "#d0d0d0" }
cand = { fg = "#12cfc0" }
rest = { fg = "#deaf8f" }

separator_style = { fg = "#b0b0b0" }

[notify]
title_info = { fg = "#12cfc0" }
title_warn = { fg = "#ddb26f" }
title_warn = { fg = "#fb9fb1" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#12cfc0" },
  { mime = "{audio, video}/*", fg = "#ddb26f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#acc267" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6fc2ef" },
  { mime = "*", fg = "#d0d0d0" },
]


