[manager]
cwd = { fg = "#b02f30" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#a03b1e" }
find_position = { fg = "#c59820" }

marker_copied = { fg = "#237986", bg = "#237986" }
marker_cut = { fg = "#2a5491", bg = "#2a5491" }
marker_selected = { fg = "#a03b1e", bg = "#a03b1e" }

tab_inactive = { fg = "#9ea7a6" }
tab_active = { fg = "#232c31", bg = "#9ea7a6"}

count_copied = { fg = "#232c31", bg = "#237986" }
count_cut = { fg = "#232c31", bg = "#2a5491" }
count_selected = { fg = "#232c31", bg = "#a03b1e" }

border_style = { fg = "#484d79" }

[mode]
normal_main = { fg = "#232c31", bg = "#484d79", bold = true }
normal_alt = { fg = "#484d79", bg = "#2a343a" }

select_alt = { fg = "#c59820", bg = "#2a343a" }
select_main = { fg = "#232c31", bg = "#c59820", bold = true }

unset_main = { fg = "#232c31", bg = "#2a5491", bold = true }
unset_alt = { fg = "#2a5491", bg = "#2a343a" }

[status]
perm_exec = { fg = "#237986" }
perm_read = { fg = "#a03b1e" }
perm_sep = { fg = "#b02f30" }
perm_type = { fg = "#484d79" }
perm_write = { fg = "#2a5491" }

progress_error = { fg = "#2a5491", bg = "#232c31" }
progress_label = { fg = "#9ea7a6", bg = "#232c31" }
progress_normal = { fg = "#9ea7a6", bg = "#232c31" }

[pick]
active = { fg = "#c59820" }
border = { fg = "#484d79" }
inactive = { fg = "#9ea7a6" }

[task]
title = { fg = "#484d79" }
border = { fg = "#484d79" }
hovered = { fg = "#9ea7a6", bg = "#2a343a" }

[input]
border = { fg = "#484d79" }
selected = { bg = "#2a343a" }

[help]
desc = { fg = "#9ea7a6" }
on = { fg = "#b02f30" }
run = { fg = "#c59820" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2a343a", bg = "#9ea7a6" }

[which]
mask = { bg = "#2a343a" }
desc = { fg = "#9ea7a6" }
cand = { fg = "#b02f30" }
rest = { fg = "#c98344" }

separator_style = { fg = "#84898c" }

[notify]
title_info = { fg = "#b02f30" }
title_warn = { fg = "#a03b1e" }
title_warn = { fg = "#2a5491" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#b02f30" },
  { mime = "{audio, video}/*", fg = "#a03b1e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#237986" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#484d79" },
  { mime = "*", fg = "#9ea7a6" },
]


