[manager]
cwd = { fg = "#c57d42" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#307878" }
find_position = { fg = "#d7ab54" }

marker_copied = { fg = "#71983b", bg = "#71983b" }
marker_cut = { fg = "#cc5450", bg = "#cc5450" }
marker_selected = { fg = "#307878", bg = "#307878" }

tab_inactive = { fg = "#dbdbdb" }
tab_active = { fg = "#232323", bg = "#dbdbdb"}

count_copied = { fg = "#232323", bg = "#71983b" }
count_cut = { fg = "#232323", bg = "#cc5450" }
count_selected = { fg = "#232323", bg = "#307878" }

border_style = { fg = "#376388" }

[mode]
normal_main = { fg = "#232323", bg = "#376388", bold = true }
normal_alt = { fg = "#376388", bg = "#4e4e4e" }

select_alt = { fg = "#d7ab54", bg = "#4e4e4e" }
select_main = { fg = "#232323", bg = "#d7ab54", bold = true }

unset_main = { fg = "#232323", bg = "#cc5450", bold = true }
unset_alt = { fg = "#cc5450", bg = "#4e4e4e" }

[status]
perm_exec = { fg = "#71983b" }
perm_read = { fg = "#307878" }
perm_sep = { fg = "#c57d42" }
perm_type = { fg = "#376388" }
perm_write = { fg = "#cc5450" }

progress_error = { fg = "#cc5450", bg = "#232323" }
progress_label = { fg = "#dbdbdb", bg = "#232323" }
progress_normal = { fg = "#dbdbdb", bg = "#232323" }

[pick]
active = { fg = "#d7ab54" }
border = { fg = "#376388" }
inactive = { fg = "#dbdbdb" }

[task]
title = { fg = "#376388" }
border = { fg = "#376388" }
hovered = { fg = "#dbdbdb", bg = "#45475a" }

[input]
border = { fg = "#376388" }
selected = { bg = "#4e4e4e" }

[help]
desc = { fg = "#dbdbdb" }
on = { fg = "#c57d42" }
run = { fg = "#d7ab54" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4e4e4e", bg = "#dbdbdb" }

[which]
mask = { bg = "#4e4e4e" }
desc = { fg = "#dbdbdb" }
cand = { fg = "#c57d42" }
rest = { fg = "#6d6d6d" }

separator_style = { fg = "#e4e4e4" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#c57d42" },
  { mime = "{audio, video}/*", fg = "#307878" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#71983b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#376388", bold = true },
  { mime = "*", fg = "#dbdbdb" },
]


