[manager]
cwd = { fg = "#7dcfff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#e0af68" }
find_position = { fg = "#bb9af7" }

marker_copied = { fg = "#41a6b5", bg = "#41a6b5" }
marker_cut = { fg = "#f7768e", bg = "#f7768e" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

tab_inactive = { fg = "#787c99" }
tab_active = { fg = "#24283b", bg = "#787c99"}

count_copied = { fg = "#24283b", bg = "#41a6b5" }
count_cut = { fg = "#24283b", bg = "#f7768e" }
count_selected = { fg = "#24283b", bg = "#e0af68" }

border_style = { fg = "#7aa2f7" }

[mode]
normal_main = { fg = "#24283b", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#343a52" }

select_alt = { fg = "#bb9af7", bg = "#343a52" }
select_main = { fg = "#24283b", bg = "#bb9af7", bold = true }

unset_main = { fg = "#24283b", bg = "#f7768e", bold = true }
unset_alt = { fg = "#f7768e", bg = "#343a52" }

[status]
perm_exec = { fg = "#41a6b5" }
perm_read = { fg = "#e0af68" }
perm_sep = { fg = "#7dcfff" }
perm_type = { fg = "#7aa2f7" }
perm_write = { fg = "#f7768e" }

progress_error = { fg = "#f7768e", bg = "#24283b" }
progress_label = { fg = "#787c99", bg = "#24283b" }
progress_normal = { fg = "#787c99", bg = "#24283b" }

[pick]
active = { fg = "#bb9af7" }
border = { fg = "#7aa2f7" }
inactive = { fg = "#787c99" }

[task]
title = { fg = "#7aa2f7" }
border = { fg = "#7aa2f7" }
hovered = { fg = "#787c99", bg = "#45475a" }

[input]
border = { fg = "#7aa2f7" }
selected = { bg = "#343a52" }

[help]
desc = { fg = "#787c99" }
on = { fg = "#7dcfff" }
run = { fg = "#bb9af7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#343a52", bg = "#787c99" }

[which]
mask = { bg = "#343a52" }
desc = { fg = "#787c99" }
cand = { fg = "#7dcfff" }
rest = { fg = "#d18616" }

separator_style = { fg = "#787c99" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#7dcfff" },
  { mime = "{audio, video}/*", fg = "#e0af68" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#41a6b5" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7aa2f7", bold = true },
  { mime = "*", fg = "#787c99" },
]


