[manager]
cwd = { fg = "#689d6a" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#d79921" }
find_position = { fg = "#b16286" }

marker_copied = { fg = "#98971a", bg = "#98971a" }
marker_cut = { fg = "#cc241d", bg = "#cc241d" }
marker_selected = { fg = "#d79921", bg = "#d79921" }

tab_inactive = { fg = "#ebdbb2" }
tab_active = { fg = "#282828", bg = "#ebdbb2"}

count_copied = { fg = "#282828", bg = "#98971a" }
count_cut = { fg = "#282828", bg = "#cc241d" }
count_selected = { fg = "#282828", bg = "#d79921" }

border_style = { fg = "#458588" }

[mode]
normal_main = { fg = "#282828", bg = "#458588", bold = true }
normal_alt = { fg = "#458588", bg = "#504945" }

select_alt = { fg = "#b16286", bg = "#504945" }
select_main = { fg = "#282828", bg = "#b16286", bold = true }

unset_main = { fg = "#282828", bg = "#cc241d", bold = true }
unset_alt = { fg = "#cc241d", bg = "#504945" }

[status]
perm_exec = { fg = "#98971a" }
perm_read = { fg = "#d79921" }
perm_sep = { fg = "#689d6a" }
perm_type = { fg = "#458588" }
perm_write = { fg = "#cc241d" }

progress_error = { fg = "#cc241d", bg = "#282828" }
progress_label = { fg = "#ebdbb2", bg = "#282828" }
progress_normal = { fg = "#ebdbb2", bg = "#282828" }

[pick]
active = { fg = "#b16286" }
border = { fg = "#458588" }
inactive = { fg = "#ebdbb2" }

[task]
title = { fg = "#458588" }
border = { fg = "#458588" }
hovered = { fg = "#ebdbb2", bg = "#504945" }

[input]
border = { fg = "#458588" }
selected = { bg = "#504945" }

[help]
desc = { fg = "#ebdbb2" }
on = { fg = "#689d6a" }
run = { fg = "#b16286" }
hovered = { reversed = true, bold = true }
footer = { fg = "#504945", bg = "#ebdbb2" }

[which]
mask = { bg = "#504945" }
desc = { fg = "#ebdbb2" }
cand = { fg = "#689d6a" }
rest = { fg = "#9d0006" }

separator_style = { fg = "#928374" }

[notify]
title_info = { fg = "#689d6a" }
title_warn = { fg = "#d79921" }
title_warn = { fg = "#cc241d" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#689d6a" },
  { mime = "{audio, video}/*", fg = "#d79921" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#98971a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#458588" },
  { mime = "*", fg = "#ebdbb2" },
]


