[manager]
cwd = { fg = "#95e6cb" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffb454" }
find_position = { fg = "#d2a6ff" }

marker_copied = { fg = "#b8cc52", bg = "#b8cc52" }
marker_cut = { fg = "#f07178", bg = "#f07178" }
marker_selected = { fg = "#ffb454", bg = "#ffb454" }

tab_inactive = { fg = "#e6e1cf" }
tab_active = { fg = "#0f1419", bg = "#e6e1cf"}

count_copied = { fg = "#0f1419", bg = "#b8cc52" }
count_cut = { fg = "#0f1419", bg = "#f07178" }
count_selected = { fg = "#0f1419", bg = "#ffb454" }

border_style = { fg = "#59c2ff" }

[mode]
normal_main = { fg = "#0f1419", bg = "#59c2ff", bold = true }
normal_alt = { fg = "#59c2ff", bg = "#272d38" }

select_alt = { fg = "#d2a6ff", bg = "#272d38" }
select_main = { fg = "#0f1419", bg = "#d2a6ff", bold = true }

unset_main = { fg = "#0f1419", bg = "#f07178", bold = true }
unset_alt = { fg = "#f07178", bg = "#272d38" }

[status]
perm_exec = { fg = "#b8cc52" }
perm_read = { fg = "#ffb454" }
perm_sep = { fg = "#95e6cb" }
perm_type = { fg = "#59c2ff" }
perm_write = { fg = "#f07178" }

progress_error = { fg = "#f07178", bg = "#0f1419" }
progress_label = { fg = "#e6e1cf", bg = "#0f1419" }
progress_normal = { fg = "#e6e1cf", bg = "#0f1419" }

[pick]
active = { fg = "#d2a6ff" }
border = { fg = "#59c2ff" }
inactive = { fg = "#e6e1cf" }

[task]
title = { fg = "#59c2ff" }
border = { fg = "#59c2ff" }
hovered = { fg = "#e6e1cf", bg = "#45475a" }

[input]
border = { fg = "#59c2ff" }
selected = { bg = "#272d38" }

[help]
desc = { fg = "#e6e1cf" }
on = { fg = "#95e6cb" }
run = { fg = "#d2a6ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#272d38", bg = "#e6e1cf" }

[which]
mask = { bg = "#272d38" }
desc = { fg = "#e6e1cf" }
cand = { fg = "#95e6cb" }
rest = { fg = "#e6b673" }

separator_style = { fg = "#bfbdb6" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#95e6cb" },
  { mime = "{audio, video}/*", fg = "#ffb454" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#b8cc52" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#59c2ff", bold = true },
  { mime = "*", fg = "#e6e1cf" },
]


