[manager]
cwd = { fg = "#847f9e" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ce943e" }
find_position = { fg = "#8d5968" }

marker_copied = { fg = "#7a894a", bg = "#7a894a" }
marker_cut = { fg = "#a75045", bg = "#a75045" }
marker_selected = { fg = "#ce943e", bg = "#ce943e" }

tab_inactive = { fg = "#473731" }
tab_active = { fg = "#efeae8", bg = "#473731"}

count_copied = { fg = "#efeae8", bg = "#7a894a" }
count_cut = { fg = "#efeae8", bg = "#a75045" }
count_selected = { fg = "#efeae8", bg = "#ce943e" }

border_style = { fg = "#625574" }

[mode]
normal_main = { fg = "#efeae8", bg = "#625574", bold = true }
normal_alt = { fg = "#625574", bg = "#d0c1bb" }

select_alt = { fg = "#8d5968", bg = "#d0c1bb" }
select_main = { fg = "#efeae8", bg = "#8d5968", bold = true }

unset_main = { fg = "#efeae8", bg = "#a75045", bold = true }
unset_alt = { fg = "#a75045", bg = "#d0c1bb" }

[status]
perm_exec = { fg = "#7a894a" }
perm_read = { fg = "#ce943e" }
perm_sep = { fg = "#847f9e" }
perm_type = { fg = "#625574" }
perm_write = { fg = "#a75045" }

progress_error = { fg = "#a75045", bg = "#efeae8" }
progress_label = { fg = "#473731", bg = "#efeae8" }
progress_normal = { fg = "#473731", bg = "#efeae8" }

[pick]
active = { fg = "#8d5968" }
border = { fg = "#625574" }
inactive = { fg = "#473731" }

[task]
title = { fg = "#625574" }
border = { fg = "#625574" }
hovered = { fg = "#473731", bg = "#45475a" }

[input]
border = { fg = "#625574" }
selected = { bg = "#d0c1bb" }

[help]
desc = { fg = "#473731" }
on = { fg = "#847f9e" }
run = { fg = "#8d5968" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d0c1bb", bg = "#473731" }

[which]
mask = { bg = "#d0c1bb" }
desc = { fg = "#473731" }
cand = { fg = "#847f9e" }
rest = { fg = "#b07158" }

separator_style = { fg = "#59453d" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#847f9e" },
  { mime = "{audio, video}/*", fg = "#ce943e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7a894a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#625574", bold = true },
  { mime = "*", fg = "#473731" },
]


