[manager]
cwd = { fg = "#06989a" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c4a000" }
find_position = { fg = "#75507b" }

marker_copied = { fg = "#4e9a06", bg = "#4e9a06" }
marker_cut = { fg = "#cc0000", bg = "#cc0000" }
marker_selected = { fg = "#c4a000", bg = "#c4a000" }

tab_inactive = { fg = "#d3d7cf" }
tab_active = { fg = "#2e3436", bg = "#d3d7cf"}

count_copied = { fg = "#2e3436", bg = "#4e9a06" }
count_cut = { fg = "#2e3436", bg = "#cc0000" }
count_selected = { fg = "#2e3436", bg = "#c4a000" }

border_style = { fg = "#3465a4" }

[mode]
normal_main = { fg = "#2e3436", bg = "#3465a4", bold = true }
normal_alt = { fg = "#3465a4", bg = "#fce94f" }

select_alt = { fg = "#75507b", bg = "#fce94f" }
select_main = { fg = "#2e3436", bg = "#75507b", bold = true }

unset_main = { fg = "#2e3436", bg = "#cc0000", bold = true }
unset_alt = { fg = "#cc0000", bg = "#fce94f" }

[status]
perm_exec = { fg = "#4e9a06" }
perm_read = { fg = "#c4a000" }
perm_sep = { fg = "#06989a" }
perm_type = { fg = "#3465a4" }
perm_write = { fg = "#cc0000" }

progress_error = { fg = "#cc0000", bg = "#2e3436" }
progress_label = { fg = "#d3d7cf", bg = "#2e3436" }
progress_normal = { fg = "#d3d7cf", bg = "#2e3436" }

[pick]
active = { fg = "#75507b" }
border = { fg = "#3465a4" }
inactive = { fg = "#d3d7cf" }

[task]
title = { fg = "#3465a4" }
border = { fg = "#3465a4" }
hovered = { fg = "#d3d7cf", bg = "#45475a" }

[input]
border = { fg = "#3465a4" }
selected = { bg = "#fce94f" }

[help]
desc = { fg = "#d3d7cf" }
on = { fg = "#06989a" }
run = { fg = "#75507b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#fce94f", bg = "#d3d7cf" }

[which]
mask = { bg = "#fce94f" }
desc = { fg = "#d3d7cf" }
cand = { fg = "#06989a" }
rest = { fg = "#34e2e2" }

separator_style = { fg = "#729fcf" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#06989a" },
  { mime = "{audio, video}/*", fg = "#c4a000" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#4e9a06" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#3465a4", bold = true },
  { mime = "*", fg = "#d3d7cf" },
]


