[manager]
cwd = { fg = "#42fff9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c9d364" }
find_position = { fg = "#ea5ce2" }

marker_copied = { fg = "#06ea61", bg = "#06ea61" }
marker_cut = { fg = "#b53b50", bg = "#b53b50" }
marker_selected = { fg = "#c9d364", bg = "#c9d364" }

tab_inactive = { fg = "#28292a" }
tab_active = { fg = "#dddfe0", bg = "#28292a"}

count_copied = { fg = "#dddfe0", bg = "#06ea61" }
count_cut = { fg = "#dddfe0", bg = "#b53b50" }
count_selected = { fg = "#dddfe0", bg = "#c9d364" }

border_style = { fg = "#03aeff" }

[mode]
normal_main = { fg = "#dddfe0", bg = "#03aeff", bold = true }
normal_alt = { fg = "#03aeff", bg = "#c1c3c4" }

select_alt = { fg = "#ea5ce2", bg = "#c1c3c4" }
select_main = { fg = "#dddfe0", bg = "#ea5ce2", bold = true }

unset_main = { fg = "#dddfe0", bg = "#b53b50", bold = true }
unset_alt = { fg = "#b53b50", bg = "#c1c3c4" }

[status]
perm_exec = { fg = "#06ea61" }
perm_read = { fg = "#c9d364" }
perm_sep = { fg = "#42fff9" }
perm_type = { fg = "#03aeff" }
perm_write = { fg = "#b53b50" }

progress_error = { fg = "#b53b50", bg = "#dddfe0" }
progress_label = { fg = "#28292a", bg = "#dddfe0" }
progress_normal = { fg = "#28292a", bg = "#dddfe0" }

[pick]
active = { fg = "#ea5ce2" }
border = { fg = "#03aeff" }
inactive = { fg = "#28292a" }

[task]
title = { fg = "#03aeff" }
border = { fg = "#03aeff" }
hovered = { fg = "#28292a", bg = "#45475a" }

[input]
border = { fg = "#03aeff" }
selected = { bg = "#c1c3c4" }

[help]
desc = { fg = "#28292a" }
on = { fg = "#42fff9" }
run = { fg = "#ea5ce2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#c1c3c4", bg = "#28292a" }

[which]
mask = { bg = "#c1c3c4" }
desc = { fg = "#28292a" }
cand = { fg = "#42fff9" }
rest = { fg = "#cd6320" }

separator_style = { fg = "#474849" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#42fff9" },
  { mime = "{audio, video}/*", fg = "#c9d364" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#06ea61" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#03aeff", bold = true },
  { mime = "*", fg = "#28292a" },
]


