[manager]
cwd = { fg = "#96d0ff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c69026" }
find_position = { fg = "#e275ad" }

marker_copied = { fg = "#57ab5a", bg = "#57ab5a" }
marker_cut = { fg = "#f47067", bg = "#f47067" }
marker_selected = { fg = "#c69026", bg = "#c69026" }

tab_inactive = { fg = "#909dab" }
tab_active = { fg = "#1c2128", bg = "#909dab"}

count_copied = { fg = "#1c2128", bg = "#57ab5a" }
count_cut = { fg = "#1c2128", bg = "#f47067" }
count_selected = { fg = "#1c2128", bg = "#c69026" }

border_style = { fg = "#539bf5" }

[mode]
normal_main = { fg = "#1c2128", bg = "#539bf5", bold = true }
normal_alt = { fg = "#539bf5", bg = "#444c56" }

select_alt = { fg = "#e275ad", bg = "#444c56" }
select_main = { fg = "#1c2128", bg = "#e275ad", bold = true }

unset_main = { fg = "#1c2128", bg = "#f47067", bold = true }
unset_alt = { fg = "#f47067", bg = "#444c56" }

[status]
perm_exec = { fg = "#57ab5a" }
perm_read = { fg = "#c69026" }
perm_sep = { fg = "#96d0ff" }
perm_type = { fg = "#539bf5" }
perm_write = { fg = "#f47067" }

progress_error = { fg = "#f47067", bg = "#1c2128" }
progress_label = { fg = "#909dab", bg = "#1c2128" }
progress_normal = { fg = "#909dab", bg = "#1c2128" }

[pick]
active = { fg = "#e275ad" }
border = { fg = "#539bf5" }
inactive = { fg = "#909dab" }

[task]
title = { fg = "#539bf5" }
border = { fg = "#539bf5" }
hovered = { fg = "#909dab", bg = "#45475a" }

[input]
border = { fg = "#539bf5" }
selected = { bg = "#444c56" }

[help]
desc = { fg = "#909dab" }
on = { fg = "#96d0ff" }
run = { fg = "#e275ad" }
hovered = { reversed = true, bold = true }
footer = { fg = "#444c56", bg = "#909dab" }

[which]
mask = { bg = "#444c56" }
desc = { fg = "#909dab" }
cand = { fg = "#96d0ff" }
rest = { fg = "#ae5622" }

separator_style = { fg = "#768390" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#96d0ff" },
  { mime = "{audio, video}/*", fg = "#c69026" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#57ab5a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#539bf5", bold = true },
  { mime = "*", fg = "#909dab" },
]


