[manager]
cwd = { fg = "#3d94a5" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#eebb00" }
find_position = { fg = "#883e9f" }

marker_copied = { fg = "#63d932", bg = "#63d932" }
marker_cut = { fg = "#ee2e00", bg = "#ee2e00" }
marker_selected = { fg = "#eebb00", bg = "#eebb00" }

tab_inactive = { fg = "#ffda51" }
tab_active = { fg = "#101600", bg = "#ffda51"}

count_copied = { fg = "#101600", bg = "#63d932" }
count_cut = { fg = "#101600", bg = "#ee2e00" }
count_selected = { fg = "#101600", bg = "#eebb00" }

border_style = { fg = "#5b4a9f" }

[mode]
normal_main = { fg = "#101600", bg = "#5b4a9f", bold = true }
normal_alt = { fg = "#5b4a9f", bg = "#242604" }

select_alt = { fg = "#883e9f", bg = "#242604" }
select_main = { fg = "#101600", bg = "#883e9f", bold = true }

unset_main = { fg = "#101600", bg = "#ee2e00", bold = true }
unset_alt = { fg = "#ee2e00", bg = "#242604" }

[status]
perm_exec = { fg = "#63d932" }
perm_read = { fg = "#eebb00" }
perm_sep = { fg = "#3d94a5" }
perm_type = { fg = "#5b4a9f" }
perm_write = { fg = "#ee2e00" }

progress_error = { fg = "#ee2e00", bg = "#101600" }
progress_label = { fg = "#ffda51", bg = "#101600" }
progress_normal = { fg = "#ffda51", bg = "#101600" }

[pick]
active = { fg = "#883e9f" }
border = { fg = "#5b4a9f" }
inactive = { fg = "#ffda51" }

[task]
title = { fg = "#5b4a9f" }
border = { fg = "#5b4a9f" }
hovered = { fg = "#ffda51", bg = "#45475a" }

[input]
border = { fg = "#5b4a9f" }
selected = { bg = "#242604" }

[help]
desc = { fg = "#ffda51" }
on = { fg = "#3d94a5" }
run = { fg = "#883e9f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#242604", bg = "#ffda51" }

[which]
mask = { bg = "#242604" }
desc = { fg = "#ffda51" }
cand = { fg = "#3d94a5" }
rest = { fg = "#a928b9" }

separator_style = { fg = "#ffd129" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3d94a5" },
  { mime = "{audio, video}/*", fg = "#eebb00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#63d932" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#5b4a9f", bold = true },
  { mime = "*", fg = "#ffda51" },
]


