[manager]
cwd = { fg = "#83b7e5" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#e0a557" }
find_position = { fg = "#c792ea" }

marker_copied = { fg = "#78c06e", bg = "#78c06e" }
marker_cut = { fg = "#6e98e1", bg = "#6e98e1" }
marker_selected = { fg = "#e0a557", bg = "#e0a557" }

tab_inactive = { fg = "#959dcb" }
tab_active = { fg = "#292d3e", bg = "#959dcb"}

count_copied = { fg = "#292d3e", bg = "#78c06e" }
count_cut = { fg = "#292d3e", bg = "#6e98e1" }
count_selected = { fg = "#292d3e", bg = "#e0a557" }

border_style = { fg = "#82aaff" }

[mode]
normal_main = { fg = "#292d3e", bg = "#82aaff", bold = true }
normal_alt = { fg = "#82aaff", bg = "#5c598b" }

select_alt = { fg = "#c792ea", bg = "#5c598b" }
select_main = { fg = "#292d3e", bg = "#c792ea", bold = true }

unset_main = { fg = "#292d3e", bg = "#6e98e1", bold = true }
unset_alt = { fg = "#6e98e1", bg = "#5c598b" }

[status]
perm_exec = { fg = "#78c06e" }
perm_read = { fg = "#e0a557" }
perm_sep = { fg = "#83b7e5" }
perm_type = { fg = "#82aaff" }
perm_write = { fg = "#6e98e1" }

progress_error = { fg = "#6e98e1", bg = "#292d3e" }
progress_label = { fg = "#959dcb", bg = "#292d3e" }
progress_normal = { fg = "#959dcb", bg = "#292d3e" }

[pick]
active = { fg = "#c792ea" }
border = { fg = "#82aaff" }
inactive = { fg = "#959dcb" }

[task]
title = { fg = "#82aaff" }
border = { fg = "#82aaff" }
hovered = { fg = "#959dcb", bg = "#45475a" }

[input]
border = { fg = "#82aaff" }
selected = { bg = "#5c598b" }

[help]
desc = { fg = "#959dcb" }
on = { fg = "#83b7e5" }
run = { fg = "#c792ea" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5c598b", bg = "#959dcb" }

[which]
mask = { bg = "#5c598b" }
desc = { fg = "#959dcb" }
cand = { fg = "#83b7e5" }
rest = { fg = "#ff5370" }

separator_style = { fg = "#8796b0" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#83b7e5" },
  { mime = "{audio, video}/*", fg = "#e0a557" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#78c06e" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#82aaff", bold = true },
  { mime = "*", fg = "#959dcb" },
]


