[mgr]
cwd = { fg = "#29adff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fff024" }
find_position = { fg = "#ff77a8" }

marker_copied = { fg = "#00e756", bg = "#00e756" }
marker_cut = { fg = "#ff004d", bg = "#ff004d" }
marker_selected = { fg = "#fff024", bg = "#fff024" }

tab_inactive = { fg = "#5f574f" }
tab_active = { fg = "#000000", bg = "#5f574f"}

count_copied = { fg = "#000000", bg = "#00e756" }
count_cut = { fg = "#000000", bg = "#ff004d" }
count_selected = { fg = "#000000", bg = "#fff024" }

border_style = { fg = "#83769c" }

[mode]
normal_main = { fg = "#000000", bg = "#83769c", bold = true }
normal_alt = { fg = "#83769c", bg = "#7e2553" }

select_alt = { fg = "#ff77a8", bg = "#7e2553" }
select_main = { fg = "#000000", bg = "#ff77a8", bold = true }

unset_main = { fg = "#000000", bg = "#ff004d", bold = true }
unset_alt = { fg = "#ff004d", bg = "#7e2553" }

[status]
perm_exec = { fg = "#00e756" }
perm_read = { fg = "#fff024" }
perm_sep = { fg = "#29adff" }
perm_type = { fg = "#83769c" }
perm_write = { fg = "#ff004d" }

progress_error = { fg = "#ff004d", bg = "#000000" }
progress_label = { fg = "#5f574f", bg = "#000000" }
progress_normal = { fg = "#5f574f", bg = "#000000" }

[pick]
active = { fg = "#ff77a8" }
border = { fg = "#83769c" }
inactive = { fg = "#5f574f" }

[task]
title = { fg = "#83769c" }
border = { fg = "#83769c" }
hovered = { fg = "#5f574f", bg = "#7e2553" }

[input]
border = { fg = "#83769c" }
selected = { bg = "#7e2553" }

[help]
desc = { fg = "#5f574f" }
on = { fg = "#29adff" }
run = { fg = "#ff77a8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#7e2553", bg = "#5f574f" }

[which]
mask = { bg = "#7e2553" }
desc = { fg = "#5f574f" }
cand = { fg = "#29adff" }
rest = { fg = "#ffccaa" }

separator_style = { fg = "#ab5236" }

[notify]
title_info = { fg = "#29adff" }
title_warn = { fg = "#fff024" }
title_warn = { fg = "#ff004d" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#29adff" },
  { mime = "{audio, video}/*", fg = "#fff024" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00e756" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#83769c" },
  { mime = "*", fg = "#5f574f" },
]


