[mgr]
cwd = { fg = "#8ba59b" }

find_keyword = { bold = true, fg = "#fac03b" }
find_position = { fg = "#8f4673" }

marker_copied = { fg = "#95c085", bg = "#95c085" }
marker_cut = { fg = "#fb543f", bg = "#fb543f" }
marker_selected = { fg = "#fac03b", bg = "#fac03b" }

count_copied = { fg = "#1d2021", bg = "#95c085" }
count_cut = { fg = "#1d2021", bg = "#fb543f" }
count_selected = { fg = "#1d2021", bg = "#fac03b" }

border_style = { fg = "#0d6678" }

[tabs]
active = { fg = "#1d2021", bg = "#0d6678"}
inactive = { fg = "#0d6678", bg = #32302f" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1d2021", bg = "#0d6678", bold = true }
normal_alt = { fg = "#0d6678", bg = "#504945" }

select_alt = { fg = "#8f4673", bg = "#504945" }
select_main = { fg = "#1d2021", bg = "#8f4673", bold = true }

unset_main = { fg = "#1d2021", bg = "#fb543f", bold = true }
unset_alt = { fg = "#fb543f", bg = "#504945" }

[status]
perm_exec = { fg = "#95c085" }
perm_read = { fg = "#fac03b" }
perm_sep = { fg = "#8ba59b" }
perm_type = { fg = "#0d6678" }
perm_write = { fg = "#fb543f" }

progress_error = { fg = "#fb543f", bg = "#1d2021" }
progress_label = { fg = "#a89984", bg = "#1d2021" }
progress_normal = { fg = "#a89984", bg = "#1d2021" }

[pick]
active = { fg = "#8f4673" }
border = { fg = "#0d6678" }
inactive = { fg = "#a89984" }

[task]
title = { fg = "#0d6678" }
border = { fg = "#0d6678" }
hovered = { fg = "#a89984", bg = "#504945" }

[input]
border = { fg = "#0d6678" }
selected = { bg = "#504945" }

[help]
desc = { fg = "#a89984" }
on = { fg = "#8ba59b" }
run = { fg = "#8f4673" }
hovered = { reversed = true, bold = true }
footer = { fg = "#504945", bg = "#a89984" }

[which]
mask = { bg = "#504945" }
desc = { fg = "#a89984" }
cand = { fg = "#8ba59b" }
rest = { fg = "#a87322" }

separator_style = { fg = "#928374" }

[notify]
title_info = { fg = "#8ba59b" }
title_warn = { fg = "#fac03b" }
title_error = { fg = "#fb543f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8ba59b" },
  { mime = "{audio, video}/*", fg = "#fac03b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#95c085" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0d6678" },
  { mime = "*", fg = "#a89984" },
]

