[mgr]
cwd = { fg = "#4c505e" }

find_keyword = { bold = true, fg = "#4c505e" }
find_position = { fg = "#5a4a78" }

marker_copied = { fg = "#485e30", bg = "#485e30" }
marker_cut = { fg = "#8c4351", bg = "#8c4351" }
marker_selected = { fg = "#4c505e", bg = "#4c505e" }

count_copied = { fg = "#fbfbfd", bg = "#485e30" }
count_cut = { fg = "#fbfbfd", bg = "#8c4351" }
count_selected = { fg = "#fbfbfd", bg = "#4c505e" }

border_style = { fg = "#34548a" }

[tabs]
active = { fg = "#fbfbfd", bg = "#34548a"}
inactive = { fg = "#34548a", bg = "#f6f6f8" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fbfbfd", bg = "#34548a", bold = true }
normal_alt = { fg = "#34548a", bg = "#edeff6" }

select_alt = { fg = "#5a4a78", bg = "#edeff6" }
select_main = { fg = "#fbfbfd", bg = "#5a4a78", bold = true }

unset_main = { fg = "#fbfbfd", bg = "#8c4351", bold = true }
unset_alt = { fg = "#8c4351", bg = "#edeff6" }

[status]
perm_exec = { fg = "#485e30" }
perm_read = { fg = "#4c505e" }
perm_sep = { fg = "#4c505e" }
perm_type = { fg = "#34548a" }
perm_write = { fg = "#8c4351" }

progress_error = { fg = "#8c4351", bg = "#fbfbfd" }
progress_label = { fg = "#343b59", bg = "#fbfbfd" }
progress_normal = { fg = "#343b59", bg = "#fbfbfd" }

[pick]
active = { fg = "#5a4a78" }
border = { fg = "#34548a" }
inactive = { fg = "#343b59" }

[task]
title = { fg = "#34548a" }
border = { fg = "#34548a" }
hovered = { fg = "#343b59", bg = "#edeff6" }

[input]
border = { fg = "#34548a" }
selected = { bg = "#edeff6" }

[help]
desc = { fg = "#343b59" }
on = { fg = "#4c505e" }
run = { fg = "#5a4a78" }
hovered = { reversed = true, bold = true }
footer = { fg = "#edeff6", bg = "#343b59" }

[which]
mask = { bg = "#edeff6" }
desc = { fg = "#343b59" }
cand = { fg = "#4c505e" }
rest = { fg = "#5a4a78" }

separator_style = { fg = "#4c505e" }

[notify]
title_info = { fg = "#4c505e" }
title_warn = { fg = "#4c505e" }
title_error = { fg = "#8c4351" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4c505e" },
  { mime = "{audio, video}/*", fg = "#4c505e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#485e30" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#34548a" },
  { mime = "*", fg = "#343b59" },
]

