[mgr]
cwd = { fg = "#95e6cb" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffd173" }
find_position = { fg = "#d4bfff" }

marker_copied = { fg = "#d5ff80", bg = "#d5ff80" }
marker_cut = { fg = "#f28779", bg = "#f28779" }
marker_selected = { fg = "#ffd173", bg = "#ffd173" }

tab_inactive = { fg = "#cccac2" }
tab_active = { fg = "#1f2430", bg = "#cccac2"}

count_copied = { fg = "#1f2430", bg = "#d5ff80" }
count_cut = { fg = "#1f2430", bg = "#f28779" }
count_selected = { fg = "#1f2430", bg = "#ffd173" }

border_style = { fg = "#73d0ff" }

[mode]
normal_main = { fg = "#1f2430", bg = "#73d0ff", bold = true }
normal_alt = { fg = "#73d0ff", bg = "#323844" }

select_alt = { fg = "#d4bfff", bg = "#323844" }
select_main = { fg = "#1f2430", bg = "#d4bfff", bold = true }

unset_main = { fg = "#1f2430", bg = "#f28779", bold = true }
unset_alt = { fg = "#f28779", bg = "#323844" }

[status]
perm_exec = { fg = "#d5ff80" }
perm_read = { fg = "#ffd173" }
perm_sep = { fg = "#95e6cb" }
perm_type = { fg = "#73d0ff" }
perm_write = { fg = "#f28779" }

progress_error = { fg = "#f28779", bg = "#1f2430" }
progress_label = { fg = "#cccac2", bg = "#1f2430" }
progress_normal = { fg = "#cccac2", bg = "#1f2430" }

[pick]
active = { fg = "#d4bfff" }
border = { fg = "#73d0ff" }
inactive = { fg = "#cccac2" }

[task]
title = { fg = "#73d0ff" }
border = { fg = "#73d0ff" }
hovered = { fg = "#cccac2", bg = "#323844" }

[input]
border = { fg = "#73d0ff" }
selected = { bg = "#323844" }

[help]
desc = { fg = "#cccac2" }
on = { fg = "#95e6cb" }
run = { fg = "#d4bfff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#323844", bg = "#cccac2" }

[which]
mask = { bg = "#323844" }
desc = { fg = "#cccac2" }
cand = { fg = "#95e6cb" }
rest = { fg = "#f27983" }

separator_style = { fg = "#707a8c" }

[notify]
title_info = { fg = "#95e6cb" }
title_warn = { fg = "#ffd173" }
title_error = { fg = "#f28779" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#95e6cb" },
  { mime = "{audio, video}/*", fg = "#ffd173" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#d5ff80" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#73d0ff" },
  { mime = "*", fg = "#cccac2" },
]


