[mgr]
cwd = { fg = "#9aedfe" }

find_keyword = { bold = true, fg = "#f3f99d" }
find_position = { fg = "#ff6ac1" }

marker_copied = { fg = "#5af78e", bg = "#5af78e" }
marker_cut = { fg = "#ff5c57", bg = "#ff5c57" }
marker_selected = { fg = "#f3f99d", bg = "#f3f99d" }

count_copied = { fg = "#282a36", bg = "#5af78e" }
count_cut = { fg = "#282a36", bg = "#ff5c57" }
count_selected = { fg = "#282a36", bg = "#f3f99d" }

border_style = { fg = "#57c7ff" }

[tabs]
active = { fg = "#282a36", bg = "#57c7ff"}
inactive = { fg = "#57c7ff", bg = #34353e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#282a36", bg = "#57c7ff", bold = true }
normal_alt = { fg = "#57c7ff", bg = "#43454f" }

select_alt = { fg = "#ff6ac1", bg = "#43454f" }
select_main = { fg = "#282a36", bg = "#ff6ac1", bold = true }

unset_main = { fg = "#282a36", bg = "#ff5c57", bold = true }
unset_alt = { fg = "#ff5c57", bg = "#43454f" }

[status]
perm_exec = { fg = "#5af78e" }
perm_read = { fg = "#f3f99d" }
perm_sep = { fg = "#9aedfe" }
perm_type = { fg = "#57c7ff" }
perm_write = { fg = "#ff5c57" }

progress_error = { fg = "#ff5c57", bg = "#282a36" }
progress_label = { fg = "#e2e4e5", bg = "#282a36" }
progress_normal = { fg = "#e2e4e5", bg = "#282a36" }

[pick]
active = { fg = "#ff6ac1" }
border = { fg = "#57c7ff" }
inactive = { fg = "#e2e4e5" }

[task]
title = { fg = "#57c7ff" }
border = { fg = "#57c7ff" }
hovered = { fg = "#e2e4e5", bg = "#43454f" }

[input]
border = { fg = "#57c7ff" }
selected = { bg = "#43454f" }

[help]
desc = { fg = "#e2e4e5" }
on = { fg = "#9aedfe" }
run = { fg = "#ff6ac1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#43454f", bg = "#e2e4e5" }

[which]
mask = { bg = "#43454f" }
desc = { fg = "#e2e4e5" }
cand = { fg = "#9aedfe" }
rest = { fg = "#b2643c" }

separator_style = { fg = "#a5a5a9" }

[notify]
title_info = { fg = "#9aedfe" }
title_warn = { fg = "#f3f99d" }
title_error = { fg = "#ff5c57" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#9aedfe" },
  { mime = "{audio, video}/*", fg = "#f3f99d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5af78e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#57c7ff" },
  { mime = "*", fg = "#e2e4e5" },
]

