[mgr]
cwd = { fg = "#0087af" }

find_keyword = { bold = true, fg = "#d75f00" }
find_position = { fg = "#8700af" }

marker_copied = { fg = "#008700", bg = "#008700" }
marker_cut = { fg = "#d70000", bg = "#d70000" }
marker_selected = { fg = "#d75f00", bg = "#d75f00" }

count_copied = { fg = "#eeeeee", bg = "#008700" }
count_cut = { fg = "#eeeeee", bg = "#d70000" }
count_selected = { fg = "#eeeeee", bg = "#d75f00" }

border_style = { fg = "#005f87" }

[tabs]
active = { fg = "#eeeeee", bg = "#005f87"}
inactive = { fg = "#005f87", bg = #c4c4c4" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#eeeeee", bg = "#005f87", bold = true }
normal_alt = { fg = "#005f87", bg = "#9e9e9e" }

select_alt = { fg = "#8700af", bg = "#9e9e9e" }
select_main = { fg = "#eeeeee", bg = "#8700af", bold = true }

unset_main = { fg = "#eeeeee", bg = "#d70000", bold = true }
unset_alt = { fg = "#d70000", bg = "#9e9e9e" }

[status]
perm_exec = { fg = "#008700" }
perm_read = { fg = "#d75f00" }
perm_sep = { fg = "#0087af" }
perm_type = { fg = "#005f87" }
perm_write = { fg = "#d70000" }

progress_error = { fg = "#d70000", bg = "#eeeeee" }
progress_label = { fg = "#5e5e5e", bg = "#eeeeee" }
progress_normal = { fg = "#5e5e5e", bg = "#eeeeee" }

[pick]
active = { fg = "#8700af" }
border = { fg = "#005f87" }
inactive = { fg = "#5e5e5e" }

[task]
title = { fg = "#005f87" }
border = { fg = "#005f87" }
hovered = { fg = "#5e5e5e", bg = "#9e9e9e" }

[input]
border = { fg = "#005f87" }
selected = { bg = "#9e9e9e" }

[help]
desc = { fg = "#5e5e5e" }
on = { fg = "#0087af" }
run = { fg = "#8700af" }
hovered = { reversed = true, bold = true }
footer = { fg = "#9e9e9e", bg = "#5e5e5e" }

[which]
mask = { bg = "#9e9e9e" }
desc = { fg = "#5e5e5e" }
cand = { fg = "#0087af" }
rest = { fg = "#af0000" }

separator_style = { fg = "#6b6b6b" }

[notify]
title_info = { fg = "#0087af" }
title_warn = { fg = "#d75f00" }
title_error = { fg = "#d70000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0087af" },
  { mime = "{audio, video}/*", fg = "#d75f00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#008700" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#005f87" },
  { mime = "*", fg = "#5e5e5e" },
]

