[mgr]
cwd = { fg = "#00ffff" }

find_keyword = { bold = true, fg = "#ffff00" }
find_position = { fg = "#ff00ff" }

marker_copied = { fg = "#00ff00", bg = "#00ff00" }
marker_cut = { fg = "#ff0000", bg = "#ff0000" }
marker_selected = { fg = "#ffff00", bg = "#ffff00" }

count_copied = { fg = "#000000", bg = "#00ff00" }
count_cut = { fg = "#000000", bg = "#ff0000" }
count_selected = { fg = "#000000", bg = "#ffff00" }

border_style = { fg = "#0000ff" }

[tabs]
active = { fg = "#000000", bg = "#0000ff"}
inactive = { fg = "#0000ff", bg = "#2a2a2a" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#000000", bg = "#0000ff", bold = true }
normal_alt = { fg = "#0000ff", bg = "#555555" }

select_alt = { fg = "#ff00ff", bg = "#555555" }
select_main = { fg = "#000000", bg = "#ff00ff", bold = true }

unset_main = { fg = "#000000", bg = "#ff0000", bold = true }
unset_alt = { fg = "#ff0000", bg = "#555555" }

[status]
perm_exec = { fg = "#00ff00" }
perm_read = { fg = "#ffff00" }
perm_sep = { fg = "#00ffff" }
perm_type = { fg = "#0000ff" }
perm_write = { fg = "#ff0000" }

progress_error = { fg = "#ff0000", bg = "#000000" }
progress_label = { fg = "#c0c0c0", bg = "#000000" }
progress_normal = { fg = "#c0c0c0", bg = "#000000" }

[pick]
active = { fg = "#ff00ff" }
border = { fg = "#0000ff" }
inactive = { fg = "#c0c0c0" }

[task]
title = { fg = "#0000ff" }
border = { fg = "#0000ff" }
hovered = { fg = "#c0c0c0", bg = "#555555" }

[input]
border = { fg = "#0000ff" }
selected = { bg = "#555555" }

[help]
desc = { fg = "#c0c0c0" }
on = { fg = "#00ffff" }
run = { fg = "#ff00ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555555", bg = "#c0c0c0" }

[which]
mask = { bg = "#555555" }
desc = { fg = "#c0c0c0" }
cand = { fg = "#00ffff" }
rest = { fg = "#008000" }

separator_style = { fg = "#a1a1a1" }

[notify]
title_info = { fg = "#00ffff" }
title_warn = { fg = "#ffff00" }
title_error = { fg = "#ff0000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00ffff" },
  { mime = "{audio, video}/*", fg = "#ffff00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00ff00" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0000ff" },
  { mime = "*", fg = "#c0c0c0" },
]

