[mgr]
cwd = { fg = "#c8c874" }

find_keyword = { bold = true, fg = "#e6a3dc" }
find_position = { fg = "#e0af85" }

marker_copied = { fg = "#80c990", bg = "#80c990" }
marker_cut = { fg = "#efa6a2", bg = "#efa6a2" }
marker_selected = { fg = "#e6a3dc", bg = "#e6a3dc" }

count_copied = { fg = "#101010", bg = "#80c990" }
count_cut = { fg = "#101010", bg = "#efa6a2" }
count_selected = { fg = "#101010", bg = "#e6a3dc" }

border_style = { fg = "#50cacd" }

[tabs]
active = { fg = "#101010", bg = "#50cacd"}
inactive = { fg = "#50cacd", bg = "#454545" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#101010", bg = "#50cacd", bold = true }
normal_alt = { fg = "#50cacd", bg = "#454545" }

select_alt = { fg = "#e0af85", bg = "#454545" }
select_main = { fg = "#101010", bg = "#e0af85", bold = true }

unset_main = { fg = "#101010", bg = "#efa6a2", bold = true }
unset_alt = { fg = "#efa6a2", bg = "#454545" }

[status]
perm_exec = { fg = "#80c990" }
perm_read = { fg = "#e6a3dc" }
perm_sep = { fg = "#c8c874" }
perm_type = { fg = "#50cacd" }
perm_write = { fg = "#efa6a2" }

progress_error = { fg = "#efa6a2", bg = "#101010" }
progress_label = { fg = "#c0c0c0", bg = "#101010" }
progress_normal = { fg = "#c0c0c0", bg = "#101010" }

[pick]
active = { fg = "#e0af85" }
border = { fg = "#50cacd" }
inactive = { fg = "#c0c0c0" }

[task]
title = { fg = "#50cacd" }
border = { fg = "#50cacd" }
hovered = { fg = "#c0c0c0", bg = "#454545" }

[input]
border = { fg = "#50cacd" }
selected = { bg = "#454545" }

[help]
desc = { fg = "#c0c0c0" }
on = { fg = "#c8c874" }
run = { fg = "#e0af85" }
hovered = { reversed = true, bold = true }
footer = { fg = "#454545", bg = "#c0c0c0" }

[which]
mask = { bg = "#454545" }
desc = { fg = "#c0c0c0" }
cand = { fg = "#c8c874" }
rest = { fg = "#808080" }

separator_style = { fg = "#808080" }

[notify]
title_info = { fg = "#c8c874" }
title_warn = { fg = "#e6a3dc" }
title_error = { fg = "#efa6a2" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#c8c874" },
  { mime = "{audio, video}/*", fg = "#e6a3dc" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#80c990" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#50cacd" },
  { mime = "*", fg = "#c0c0c0" },
]

