[mgr]
cwd = { fg = "#75b5aa" }

find_keyword = { bold = true, fg = "#f4bf75" }
find_position = { fg = "#aa759f" }

marker_copied = { fg = "#90a959", bg = "#90a959" }
marker_cut = { fg = "#ac4142", bg = "#ac4142" }
marker_selected = { fg = "#f4bf75", bg = "#f4bf75" }

count_copied = { fg = "#f5f5f5", bg = "#90a959" }
count_cut = { fg = "#f5f5f5", bg = "#ac4142" }
count_selected = { fg = "#f5f5f5", bg = "#f4bf75" }

border_style = { fg = "#6a9fb5" }

[tabs]
active = { fg = "#f5f5f5", bg = "#6a9fb5"}
inactive = { fg = "#6a9fb5", bg = #e0e0e0" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f5f5f5", bg = "#6a9fb5", bold = true }
normal_alt = { fg = "#6a9fb5", bg = "#d0d0d0" }

select_alt = { fg = "#aa759f", bg = "#d0d0d0" }
select_main = { fg = "#f5f5f5", bg = "#aa759f", bold = true }

unset_main = { fg = "#f5f5f5", bg = "#ac4142", bold = true }
unset_alt = { fg = "#ac4142", bg = "#d0d0d0" }

[status]
perm_exec = { fg = "#90a959" }
perm_read = { fg = "#f4bf75" }
perm_sep = { fg = "#75b5aa" }
perm_type = { fg = "#6a9fb5" }
perm_write = { fg = "#ac4142" }

progress_error = { fg = "#ac4142", bg = "#f5f5f5" }
progress_label = { fg = "#303030", bg = "#f5f5f5" }
progress_normal = { fg = "#303030", bg = "#f5f5f5" }

[pick]
active = { fg = "#aa759f" }
border = { fg = "#6a9fb5" }
inactive = { fg = "#303030" }

[task]
title = { fg = "#6a9fb5" }
border = { fg = "#6a9fb5" }
hovered = { fg = "#303030", bg = "#d0d0d0" }

[input]
border = { fg = "#6a9fb5" }
selected = { bg = "#d0d0d0" }

[help]
desc = { fg = "#303030" }
on = { fg = "#75b5aa" }
run = { fg = "#aa759f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d0d0d0", bg = "#303030" }

[which]
mask = { bg = "#d0d0d0" }
desc = { fg = "#303030" }
cand = { fg = "#75b5aa" }
rest = { fg = "#8f5536" }

separator_style = { fg = "#505050" }

[notify]
title_info = { fg = "#75b5aa" }
title_warn = { fg = "#f4bf75" }
title_error = { fg = "#ac4142" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#75b5aa" },
  { mime = "{audio, video}/*", fg = "#f4bf75" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#90a959" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6a9fb5" },
  { mime = "*", fg = "#303030" },
]

