[mgr]
cwd = { fg = "#00998f" }

find_keyword = { bold = true, fg = "#ad8200" }
find_position = { fg = "#9e57c2" }

marker_copied = { fg = "#31861f", bg = "#31861f" }
marker_cut = { fg = "#d03e3e", bg = "#d03e3e" }
marker_selected = { fg = "#ad8200", bg = "#ad8200" }

count_copied = { fg = "#ffffff", bg = "#31861f" }
count_cut = { fg = "#ffffff", bg = "#d03e3e" }
count_selected = { fg = "#ffffff", bg = "#ad8200" }

border_style = { fg = "#3173c5" }

[tabs]
active = { fg = "#ffffff", bg = "#3173c5"}
inactive = { fg = "#3173c5", bg = "#eeeeee" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#3173c5", bold = true }
normal_alt = { fg = "#3173c5", bg = "#cccccc" }

select_alt = { fg = "#9e57c2", bg = "#cccccc" }
select_main = { fg = "#ffffff", bg = "#9e57c2", bold = true }

unset_main = { fg = "#ffffff", bg = "#d03e3e", bold = true }
unset_alt = { fg = "#d03e3e", bg = "#cccccc" }

[status]
perm_exec = { fg = "#31861f" }
perm_read = { fg = "#ad8200" }
perm_sep = { fg = "#00998f" }
perm_type = { fg = "#3173c5" }
perm_write = { fg = "#d03e3e" }

progress_error = { fg = "#d03e3e", bg = "#ffffff" }
progress_label = { fg = "#444444", bg = "#ffffff" }
progress_normal = { fg = "#444444", bg = "#ffffff" }

[pick]
active = { fg = "#9e57c2" }
border = { fg = "#3173c5" }
inactive = { fg = "#444444" }

[task]
title = { fg = "#3173c5" }
border = { fg = "#3173c5" }
hovered = { fg = "#444444", bg = "#cccccc" }

[input]
border = { fg = "#3173c5" }
selected = { bg = "#cccccc" }

[help]
desc = { fg = "#444444" }
on = { fg = "#00998f" }
run = { fg = "#9e57c2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#cccccc", bg = "#444444" }

[which]
mask = { bg = "#cccccc" }
desc = { fg = "#444444" }
cand = { fg = "#00998f" }
rest = { fg = "#895025" }

separator_style = { fg = "#767676" }

[notify]
title_info = { fg = "#00998f" }
title_warn = { fg = "#ad8200" }
title_error = { fg = "#d03e3e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00998f" },
  { mime = "{audio, video}/*", fg = "#ad8200" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#31861f" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3173c5" },
  { mime = "*", fg = "#444444" },
]

