[mgr]
cwd = { fg = "#bed6ff" }

find_keyword = { bold = true, fg = "#ffc66d" }
find_position = { fg = "#d197d9" }

marker_copied = { fg = "#a5c261", bg = "#a5c261" }
marker_cut = { fg = "#d25252", bg = "#d25252" }
marker_selected = { fg = "#ffc66d", bg = "#ffc66d" }

count_copied = { fg = "#2d2d2d", bg = "#a5c261" }
count_cut = { fg = "#2d2d2d", bg = "#d25252" }
count_selected = { fg = "#2d2d2d", bg = "#ffc66d" }

border_style = { fg = "#6c99bb" }

[tabs]
active = { fg = "#2d2d2d", bg = "#6c99bb"}
inactive = { fg = "#6c99bb", bg = #393939" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2d2d2d", bg = "#6c99bb", bold = true }
normal_alt = { fg = "#6c99bb", bg = "#515151" }

select_alt = { fg = "#d197d9", bg = "#515151" }
select_main = { fg = "#2d2d2d", bg = "#d197d9", bold = true }

unset_main = { fg = "#2d2d2d", bg = "#d25252", bold = true }
unset_alt = { fg = "#d25252", bg = "#515151" }

[status]
perm_exec = { fg = "#a5c261" }
perm_read = { fg = "#ffc66d" }
perm_sep = { fg = "#bed6ff" }
perm_type = { fg = "#6c99bb" }
perm_write = { fg = "#d25252" }

progress_error = { fg = "#d25252", bg = "#2d2d2d" }
progress_label = { fg = "#cccccc", bg = "#2d2d2d" }
progress_normal = { fg = "#cccccc", bg = "#2d2d2d" }

[pick]
active = { fg = "#d197d9" }
border = { fg = "#6c99bb" }
inactive = { fg = "#cccccc" }

[task]
title = { fg = "#6c99bb" }
border = { fg = "#6c99bb" }
hovered = { fg = "#cccccc", bg = "#515151" }

[input]
border = { fg = "#6c99bb" }
selected = { bg = "#515151" }

[help]
desc = { fg = "#cccccc" }
on = { fg = "#bed6ff" }
run = { fg = "#d197d9" }
hovered = { reversed = true, bold = true }
footer = { fg = "#515151", bg = "#cccccc" }

[which]
mask = { bg = "#515151" }
desc = { fg = "#cccccc" }
cand = { fg = "#bed6ff" }
rest = { fg = "#f97394" }

separator_style = { fg = "#b4b7b4" }

[notify]
title_info = { fg = "#bed6ff" }
title_warn = { fg = "#ffc66d" }
title_error = { fg = "#d25252" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#bed6ff" },
  { mime = "{audio, video}/*", fg = "#ffc66d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a5c261" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6c99bb" },
  { mime = "*", fg = "#cccccc" },
]

