[mgr]
cwd = { fg = "#339d9b" }

find_keyword = { bold = true, fg = "#bf8700" }
find_position = { fg = "#a475f9" }

marker_copied = { fg = "#2da44e", bg = "#2da44e" }
marker_cut = { fg = "#fa4549", bg = "#fa4549" }
marker_selected = { fg = "#bf8700", bg = "#bf8700" }

count_copied = { fg = "#eaeef2", bg = "#2da44e" }
count_cut = { fg = "#eaeef2", bg = "#fa4549" }
count_selected = { fg = "#eaeef2", bg = "#bf8700" }

border_style = { fg = "#218bff" }

[tabs]
active = { fg = "#eaeef2", bg = "#218bff"}
inactive = { fg = "#218bff", bg = #d0d7de" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#eaeef2", bg = "#218bff", bold = true }
normal_alt = { fg = "#218bff", bg = "#afb8c1" }

select_alt = { fg = "#a475f9", bg = "#afb8c1" }
select_main = { fg = "#eaeef2", bg = "#a475f9", bold = true }

unset_main = { fg = "#eaeef2", bg = "#fa4549", bold = true }
unset_alt = { fg = "#fa4549", bg = "#afb8c1" }

[status]
perm_exec = { fg = "#2da44e" }
perm_read = { fg = "#bf8700" }
perm_sep = { fg = "#339d9b" }
perm_type = { fg = "#218bff" }
perm_write = { fg = "#fa4549" }

progress_error = { fg = "#fa4549", bg = "#eaeef2" }
progress_label = { fg = "#424a53", bg = "#eaeef2" }
progress_normal = { fg = "#424a53", bg = "#eaeef2" }

[pick]
active = { fg = "#a475f9" }
border = { fg = "#218bff" }
inactive = { fg = "#424a53" }

[task]
title = { fg = "#218bff" }
border = { fg = "#218bff" }
hovered = { fg = "#424a53", bg = "#afb8c1" }

[input]
border = { fg = "#218bff" }
selected = { bg = "#afb8c1" }

[help]
desc = { fg = "#424a53" }
on = { fg = "#339d9b" }
run = { fg = "#a475f9" }
hovered = { reversed = true, bold = true }
footer = { fg = "#afb8c1", bg = "#424a53" }

[which]
mask = { bg = "#afb8c1" }
desc = { fg = "#424a53" }
cand = { fg = "#339d9b" }
rest = { fg = "#4d2d00" }

separator_style = { fg = "#6e7781" }

[notify]
title_info = { fg = "#339d9b" }
title_warn = { fg = "#bf8700" }
title_error = { fg = "#fa4549" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#339d9b" },
  { mime = "{audio, video}/*", fg = "#bf8700" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2da44e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#218bff" },
  { mime = "*", fg = "#424a53" },
]

