[mgr]
cwd = { fg = "#5fb3b3" }

find_keyword = { bold = true, fg = "#fac863" }
find_position = { fg = "#c594c5" }

marker_copied = { fg = "#99c794", bg = "#99c794" }
marker_cut = { fg = "#ec5f67", bg = "#ec5f67" }
marker_selected = { fg = "#fac863", bg = "#fac863" }

count_copied = { fg = "#1b2b34", bg = "#99c794" }
count_cut = { fg = "#1b2b34", bg = "#ec5f67" }
count_selected = { fg = "#1b2b34", bg = "#fac863" }

border_style = { fg = "#6699cc" }

[tabs]
active = { fg = "#1b2b34", bg = "#6699cc"}
inactive = { fg = "#6699cc", bg = "#343d46" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1b2b34", bg = "#6699cc", bold = true }
normal_alt = { fg = "#6699cc", bg = "#4f5b66" }

select_alt = { fg = "#c594c5", bg = "#4f5b66" }
select_main = { fg = "#1b2b34", bg = "#c594c5", bold = true }

unset_main = { fg = "#1b2b34", bg = "#ec5f67", bold = true }
unset_alt = { fg = "#ec5f67", bg = "#4f5b66" }

[status]
perm_exec = { fg = "#99c794" }
perm_read = { fg = "#fac863" }
perm_sep = { fg = "#5fb3b3" }
perm_type = { fg = "#6699cc" }
perm_write = { fg = "#ec5f67" }

progress_error = { fg = "#ec5f67", bg = "#1b2b34" }
progress_label = { fg = "#c0c5ce", bg = "#1b2b34" }
progress_normal = { fg = "#c0c5ce", bg = "#1b2b34" }

[pick]
active = { fg = "#c594c5" }
border = { fg = "#6699cc" }
inactive = { fg = "#c0c5ce" }

[task]
title = { fg = "#6699cc" }
border = { fg = "#6699cc" }
hovered = { fg = "#c0c5ce", bg = "#4f5b66" }

[input]
border = { fg = "#6699cc" }
selected = { bg = "#4f5b66" }

[help]
desc = { fg = "#c0c5ce" }
on = { fg = "#5fb3b3" }
run = { fg = "#c594c5" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4f5b66", bg = "#c0c5ce" }

[which]
mask = { bg = "#4f5b66" }
desc = { fg = "#c0c5ce" }
cand = { fg = "#5fb3b3" }
rest = { fg = "#ab7967" }

separator_style = { fg = "#a7adba" }

[notify]
title_info = { fg = "#5fb3b3" }
title_warn = { fg = "#fac863" }
title_error = { fg = "#ec5f67" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5fb3b3" },
  { mime = "{audio, video}/*", fg = "#fac863" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#99c794" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6699cc" },
  { mime = "*", fg = "#c0c5ce" },
]

