[mgr]
cwd = { fg = "#f2c38f" }

find_keyword = { bold = true, fg = "#a8ce93" }
find_position = { fg = "#9a93e1" }

marker_copied = { fg = "#7fc1ca", bg = "#7fc1ca" }
marker_cut = { fg = "#83afe5", bg = "#83afe5" }
marker_selected = { fg = "#a8ce93", bg = "#a8ce93" }

count_copied = { fg = "#3c4c55", bg = "#7fc1ca" }
count_cut = { fg = "#3c4c55", bg = "#83afe5" }
count_selected = { fg = "#3c4c55", bg = "#a8ce93" }

border_style = { fg = "#83afe5" }

[tabs]
active = { fg = "#3c4c55", bg = "#83afe5"}
inactive = { fg = "#83afe5", bg = "#556873" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#3c4c55", bg = "#83afe5", bold = true }
normal_alt = { fg = "#83afe5", bg = "#6a7d89" }

select_alt = { fg = "#9a93e1", bg = "#6a7d89" }
select_main = { fg = "#3c4c55", bg = "#9a93e1", bold = true }

unset_main = { fg = "#3c4c55", bg = "#83afe5", bold = true }
unset_alt = { fg = "#83afe5", bg = "#6a7d89" }

[status]
perm_exec = { fg = "#7fc1ca" }
perm_read = { fg = "#a8ce93" }
perm_sep = { fg = "#f2c38f" }
perm_type = { fg = "#83afe5" }
perm_write = { fg = "#83afe5" }

progress_error = { fg = "#83afe5", bg = "#3c4c55" }
progress_label = { fg = "#c5d4dd", bg = "#3c4c55" }
progress_normal = { fg = "#c5d4dd", bg = "#3c4c55" }

[pick]
active = { fg = "#9a93e1" }
border = { fg = "#83afe5" }
inactive = { fg = "#c5d4dd" }

[task]
title = { fg = "#83afe5" }
border = { fg = "#83afe5" }
hovered = { fg = "#c5d4dd", bg = "#6a7d89" }

[input]
border = { fg = "#83afe5" }
selected = { bg = "#6a7d89" }

[help]
desc = { fg = "#c5d4dd" }
on = { fg = "#f2c38f" }
run = { fg = "#9a93e1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#6a7d89", bg = "#c5d4dd" }

[which]
mask = { bg = "#6a7d89" }
desc = { fg = "#c5d4dd" }
cand = { fg = "#f2c38f" }
rest = { fg = "#f2c38f" }

separator_style = { fg = "#899ba6" }

[notify]
title_info = { fg = "#f2c38f" }
title_warn = { fg = "#a8ce93" }
title_error = { fg = "#83afe5" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#f2c38f" },
  { mime = "{audio, video}/*", fg = "#a8ce93" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7fc1ca" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#83afe5" },
  { mime = "*", fg = "#c5d4dd" },
]

