[mgr]
cwd = { fg = "#9c5fce" }

find_keyword = { bold = true, fg = "#a84a73" }
find_position = { fg = "#78a38f" }

marker_copied = { fg = "#c965bf", bg = "#c965bf" }
marker_cut = { fg = "#877bb6", bg = "#877bb6" }
marker_selected = { fg = "#a84a73", bg = "#a84a73" }

count_copied = { fg = "#241b26", bg = "#c965bf" }
count_cut = { fg = "#241b26", bg = "#877bb6" }
count_selected = { fg = "#241b26", bg = "#a84a73" }

border_style = { fg = "#6a9eb5" }

[tabs]
active = { fg = "#241b26", bg = "#6a9eb5"}
inactive = { fg = "#6a9eb5", bg = "#2f2a3f" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#241b26", bg = "#6a9eb5", bold = true }
normal_alt = { fg = "#6a9eb5", bg = "#46354a" }

select_alt = { fg = "#78a38f", bg = "#46354a" }
select_main = { fg = "#241b26", bg = "#78a38f", bold = true }

unset_main = { fg = "#241b26", bg = "#877bb6", bold = true }
unset_alt = { fg = "#877bb6", bg = "#46354a" }

[status]
perm_exec = { fg = "#c965bf" }
perm_read = { fg = "#a84a73" }
perm_sep = { fg = "#9c5fce" }
perm_type = { fg = "#6a9eb5" }
perm_write = { fg = "#877bb6" }

progress_error = { fg = "#877bb6", bg = "#241b26" }
progress_label = { fg = "#eed5d9", bg = "#241b26" }
progress_normal = { fg = "#eed5d9", bg = "#241b26" }

[pick]
active = { fg = "#78a38f" }
border = { fg = "#6a9eb5" }
inactive = { fg = "#eed5d9" }

[task]
title = { fg = "#6a9eb5" }
border = { fg = "#6a9eb5" }
hovered = { fg = "#eed5d9", bg = "#46354a" }

[input]
border = { fg = "#6a9eb5" }
selected = { bg = "#46354a" }

[help]
desc = { fg = "#eed5d9" }
on = { fg = "#9c5fce" }
run = { fg = "#78a38f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#46354a", bg = "#eed5d9" }

[which]
mask = { bg = "#46354a" }
desc = { fg = "#eed5d9" }
cand = { fg = "#9c5fce" }
rest = { fg = "#a3a079" }

separator_style = { fg = "#7e5f83" }

[notify]
title_info = { fg = "#9c5fce" }
title_warn = { fg = "#a84a73" }
title_error = { fg = "#877bb6" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#9c5fce" },
  { mime = "{audio, video}/*", fg = "#a84a73" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#c965bf" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6a9eb5" },
  { mime = "*", fg = "#eed5d9" },
]

