[mgr]
cwd = { fg = "#3971ed" }

find_keyword = { bold = true, fg = "#fba922" }
find_position = { fg = "#a36ac7" }

marker_copied = { fg = "#198844", bg = "#198844" }
marker_cut = { fg = "#cc342b", bg = "#cc342b" }
marker_selected = { fg = "#fba922", bg = "#fba922" }

count_copied = { fg = "#1d1f21", bg = "#198844" }
count_cut = { fg = "#1d1f21", bg = "#cc342b" }
count_selected = { fg = "#1d1f21", bg = "#fba922" }

border_style = { fg = "#3971ed" }

[tabs]
active = { fg = "#1d1f21", bg = "#3971ed"}
inactive = { fg = "#3971ed", bg = #282a2e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1d1f21", bg = "#3971ed", bold = true }
normal_alt = { fg = "#3971ed", bg = "#373b41" }

select_alt = { fg = "#a36ac7", bg = "#373b41" }
select_main = { fg = "#1d1f21", bg = "#a36ac7", bold = true }

unset_main = { fg = "#1d1f21", bg = "#cc342b", bold = true }
unset_alt = { fg = "#cc342b", bg = "#373b41" }

[status]
perm_exec = { fg = "#198844" }
perm_read = { fg = "#fba922" }
perm_sep = { fg = "#3971ed" }
perm_type = { fg = "#3971ed" }
perm_write = { fg = "#cc342b" }

progress_error = { fg = "#cc342b", bg = "#1d1f21" }
progress_label = { fg = "#c5c8c6", bg = "#1d1f21" }
progress_normal = { fg = "#c5c8c6", bg = "#1d1f21" }

[pick]
active = { fg = "#a36ac7" }
border = { fg = "#3971ed" }
inactive = { fg = "#c5c8c6" }

[task]
title = { fg = "#3971ed" }
border = { fg = "#3971ed" }
hovered = { fg = "#c5c8c6", bg = "#373b41" }

[input]
border = { fg = "#3971ed" }
selected = { bg = "#373b41" }

[help]
desc = { fg = "#c5c8c6" }
on = { fg = "#3971ed" }
run = { fg = "#a36ac7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#373b41", bg = "#c5c8c6" }

[which]
mask = { bg = "#373b41" }
desc = { fg = "#c5c8c6" }
cand = { fg = "#3971ed" }
rest = { fg = "#3971ed" }

separator_style = { fg = "#b4b7b4" }

[notify]
title_info = { fg = "#3971ed" }
title_warn = { fg = "#fba922" }
title_error = { fg = "#cc342b" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3971ed" },
  { mime = "{audio, video}/*", fg = "#fba922" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#198844" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3971ed" },
  { mime = "*", fg = "#c5c8c6" },
]

