[mgr]
cwd = { fg = "#95aec7" }

find_keyword = { bold = true, fg = "#aec795" }
find_position = { fg = "#c795ae" }

marker_copied = { fg = "#95c7ae", bg = "#95c7ae" }
marker_cut = { fg = "#c7ae95", bg = "#c7ae95" }
marker_selected = { fg = "#aec795", bg = "#aec795" }

count_copied = { fg = "#1c2023", bg = "#95c7ae" }
count_cut = { fg = "#1c2023", bg = "#c7ae95" }
count_selected = { fg = "#1c2023", bg = "#aec795" }

border_style = { fg = "#ae95c7" }

[tabs]
active = { fg = "#1c2023", bg = "#ae95c7"}
inactive = { fg = "#ae95c7", bg = "#393f45" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1c2023", bg = "#ae95c7", bold = true }
normal_alt = { fg = "#ae95c7", bg = "#565e65" }

select_alt = { fg = "#c795ae", bg = "#565e65" }
select_main = { fg = "#1c2023", bg = "#c795ae", bold = true }

unset_main = { fg = "#1c2023", bg = "#c7ae95", bold = true }
unset_alt = { fg = "#c7ae95", bg = "#565e65" }

[status]
perm_exec = { fg = "#95c7ae" }
perm_read = { fg = "#aec795" }
perm_sep = { fg = "#95aec7" }
perm_type = { fg = "#ae95c7" }
perm_write = { fg = "#c7ae95" }

progress_error = { fg = "#c7ae95", bg = "#1c2023" }
progress_label = { fg = "#c7ccd1", bg = "#1c2023" }
progress_normal = { fg = "#c7ccd1", bg = "#1c2023" }

[pick]
active = { fg = "#c795ae" }
border = { fg = "#ae95c7" }
inactive = { fg = "#c7ccd1" }

[task]
title = { fg = "#ae95c7" }
border = { fg = "#ae95c7" }
hovered = { fg = "#c7ccd1", bg = "#565e65" }

[input]
border = { fg = "#ae95c7" }
selected = { bg = "#565e65" }

[help]
desc = { fg = "#c7ccd1" }
on = { fg = "#95aec7" }
run = { fg = "#c795ae" }
hovered = { reversed = true, bold = true }
footer = { fg = "#565e65", bg = "#c7ccd1" }

[which]
mask = { bg = "#565e65" }
desc = { fg = "#c7ccd1" }
cand = { fg = "#95aec7" }
rest = { fg = "#c79595" }

separator_style = { fg = "#adb3ba" }

[notify]
title_info = { fg = "#95aec7" }
title_warn = { fg = "#aec795" }
title_error = { fg = "#c7ae95" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#95aec7" },
  { mime = "{audio, video}/*", fg = "#aec795" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#95c7ae" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#ae95c7" },
  { mime = "*", fg = "#c7ccd1" },
]

