[mgr]
cwd = { fg = "#3e6968" }

find_keyword = { bold = true, fg = "#166775" }
find_position = { fg = "#5a4a78" }

marker_copied = { fg = "#485e30", bg = "#485e30" }
marker_cut = { fg = "#343b58", bg = "#343b58" }
marker_selected = { fg = "#166775", bg = "#166775" }

count_copied = { fg = "#d5d6db", bg = "#485e30" }
count_cut = { fg = "#d5d6db", bg = "#343b58" }
count_selected = { fg = "#d5d6db", bg = "#166775" }

border_style = { fg = "#34548a" }

[tabs]
active = { fg = "#d5d6db", bg = "#34548a"}
inactive = { fg = "#34548a", bg = #cbccd1" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#d5d6db", bg = "#34548a", bold = true }
normal_alt = { fg = "#34548a", bg = "#dfe0e5" }

select_alt = { fg = "#5a4a78", bg = "#dfe0e5" }
select_main = { fg = "#d5d6db", bg = "#5a4a78", bold = true }

unset_main = { fg = "#d5d6db", bg = "#343b58", bold = true }
unset_alt = { fg = "#343b58", bg = "#dfe0e5" }

[status]
perm_exec = { fg = "#485e30" }
perm_read = { fg = "#166775" }
perm_sep = { fg = "#3e6968" }
perm_type = { fg = "#34548a" }
perm_write = { fg = "#343b58" }

progress_error = { fg = "#343b58", bg = "#d5d6db" }
progress_label = { fg = "#343b59", bg = "#d5d6db" }
progress_normal = { fg = "#343b59", bg = "#d5d6db" }

[pick]
active = { fg = "#5a4a78" }
border = { fg = "#34548a" }
inactive = { fg = "#343b59" }

[task]
title = { fg = "#34548a" }
border = { fg = "#34548a" }
hovered = { fg = "#343b59", bg = "#dfe0e5" }

[input]
border = { fg = "#34548a" }
selected = { bg = "#dfe0e5" }

[help]
desc = { fg = "#343b59" }
on = { fg = "#3e6968" }
run = { fg = "#5a4a78" }
hovered = { reversed = true, bold = true }
footer = { fg = "#dfe0e5", bg = "#343b59" }

[which]
mask = { bg = "#dfe0e5" }
desc = { fg = "#343b59" }
cand = { fg = "#3e6968" }
rest = { fg = "#8c4351" }

separator_style = { fg = "#4c505e" }

[notify]
title_info = { fg = "#3e6968" }
title_warn = { fg = "#166775" }
title_error = { fg = "#343b58" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3e6968" },
  { mime = "{audio, video}/*", fg = "#166775" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#485e30" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#34548a" },
  { mime = "*", fg = "#343b59" },
]

