[mgr]
cwd = { fg = "#568bbf" }

find_keyword = { bold = true, fg = "#8bbf56" }
find_position = { fg = "#bf568b" }

marker_copied = { fg = "#56bf8b", bg = "#56bf8b" }
marker_cut = { fg = "#bf8b56", bg = "#bf8b56" }
marker_selected = { fg = "#8bbf56", bg = "#8bbf56" }

count_copied = { fg = "#0b1c2c", bg = "#56bf8b" }
count_cut = { fg = "#0b1c2c", bg = "#bf8b56" }
count_selected = { fg = "#0b1c2c", bg = "#8bbf56" }

border_style = { fg = "#8b56bf" }

[tabs]
active = { fg = "#0b1c2c", bg = "#8b56bf"}
inactive = { fg = "#8b56bf", bg = "#223b54" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#0b1c2c", bg = "#8b56bf", bold = true }
normal_alt = { fg = "#8b56bf", bg = "#405c79" }

select_alt = { fg = "#bf568b", bg = "#405c79" }
select_main = { fg = "#0b1c2c", bg = "#bf568b", bold = true }

unset_main = { fg = "#0b1c2c", bg = "#bf8b56", bold = true }
unset_alt = { fg = "#bf8b56", bg = "#405c79" }

[status]
perm_exec = { fg = "#56bf8b" }
perm_read = { fg = "#8bbf56" }
perm_sep = { fg = "#568bbf" }
perm_type = { fg = "#8b56bf" }
perm_write = { fg = "#bf8b56" }

progress_error = { fg = "#bf8b56", bg = "#0b1c2c" }
progress_label = { fg = "#cbd6e2", bg = "#0b1c2c" }
progress_normal = { fg = "#cbd6e2", bg = "#0b1c2c" }

[pick]
active = { fg = "#bf568b" }
border = { fg = "#8b56bf" }
inactive = { fg = "#cbd6e2" }

[task]
title = { fg = "#8b56bf" }
border = { fg = "#8b56bf" }
hovered = { fg = "#cbd6e2", bg = "#405c79" }

[input]
border = { fg = "#8b56bf" }
selected = { bg = "#405c79" }

[help]
desc = { fg = "#cbd6e2" }
on = { fg = "#568bbf" }
run = { fg = "#bf568b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#405c79", bg = "#cbd6e2" }

[which]
mask = { bg = "#405c79" }
desc = { fg = "#cbd6e2" }
cand = { fg = "#568bbf" }
rest = { fg = "#bf5656" }

separator_style = { fg = "#aabcce" }

[notify]
title_info = { fg = "#568bbf" }
title_warn = { fg = "#8bbf56" }
title_error = { fg = "#bf8b56" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#568bbf" },
  { mime = "{audio, video}/*", fg = "#8bbf56" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#56bf8b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#8b56bf" },
  { mime = "*", fg = "#cbd6e2" },
]

