[mgr]
cwd = { fg = "#36d3ff" }

find_keyword = { bold = true, fg = "#fff018" }
find_position = { fg = "#9036ff" }

marker_copied = { fg = "#30a860", bg = "#30a860" }
marker_cut = { fg = "#d80000", bg = "#d80000" }
marker_selected = { fg = "#fff018", bg = "#fff018" }

count_copied = { fg = "#f0f0f0", bg = "#30a860" }
count_cut = { fg = "#f0f0f0", bg = "#d80000" }
count_selected = { fg = "#f0f0f0", bg = "#fff018" }

border_style = { fg = "#365eff" }

[tabs]
active = { fg = "#f0f0f0", bg = "#365eff"}
inactive = { fg = "#365eff", bg = #d6d6d6" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f0f0f0", bg = "#365eff", bold = true }
normal_alt = { fg = "#365eff", bg = "#bdbdbd" }

select_alt = { fg = "#9036ff", bg = "#bdbdbd" }
select_main = { fg = "#f0f0f0", bg = "#9036ff", bold = true }

unset_main = { fg = "#f0f0f0", bg = "#d80000", bold = true }
unset_alt = { fg = "#d80000", bg = "#bdbdbd" }

[status]
perm_exec = { fg = "#30a860" }
perm_read = { fg = "#fff018" }
perm_sep = { fg = "#36d3ff" }
perm_type = { fg = "#365eff" }
perm_write = { fg = "#d80000" }

progress_error = { fg = "#d80000", bg = "#f0f0f0" }
progress_label = { fg = "#4c383b", bg = "#f0f0f0" }
progress_normal = { fg = "#4c383b", bg = "#f0f0f0" }

[pick]
active = { fg = "#9036ff" }
border = { fg = "#365eff" }
inactive = { fg = "#4c383b" }

[task]
title = { fg = "#365eff" }
border = { fg = "#365eff" }
hovered = { fg = "#4c383b", bg = "#bdbdbd" }

[input]
border = { fg = "#365eff" }
selected = { bg = "#bdbdbd" }

[help]
desc = { fg = "#4c383b" }
on = { fg = "#36d3ff" }
run = { fg = "#9036ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#bdbdbd", bg = "#4c383b" }

[which]
mask = { bg = "#bdbdbd" }
desc = { fg = "#4c383b" }
cand = { fg = "#36d3ff" }
rest = { fg = "#140c0d" }

separator_style = { fg = "#605758" }

[notify]
title_info = { fg = "#36d3ff" }
title_warn = { fg = "#fff018" }
title_error = { fg = "#d80000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#36d3ff" },
  { mime = "{audio, video}/*", fg = "#fff018" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#30a860" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#365eff" },
  { mime = "*", fg = "#4c383b" },
]

