[mgr]
cwd = { fg = "#8abeb7" }

find_keyword = { bold = true, fg = "#f0c674" }
find_position = { fg = "#b294bb" }

marker_copied = { fg = "#b5bd68", bg = "#b5bd68" }
marker_cut = { fg = "#cc6666", bg = "#cc6666" }
marker_selected = { fg = "#f0c674", bg = "#f0c674" }

count_copied = { fg = "#1d1f21", bg = "#b5bd68" }
count_cut = { fg = "#1d1f21", bg = "#cc6666" }
count_selected = { fg = "#1d1f21", bg = "#f0c674" }

border_style = { fg = "#81a2be" }

[tabs]
active = { fg = "#1d1f21", bg = "#81a2be"}
inactive = { fg = "#81a2be", bg = "#282a2e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1d1f21", bg = "#81a2be", bold = true }
normal_alt = { fg = "#81a2be", bg = "#373b41" }

select_alt = { fg = "#b294bb", bg = "#373b41" }
select_main = { fg = "#1d1f21", bg = "#b294bb", bold = true }

unset_main = { fg = "#1d1f21", bg = "#cc6666", bold = true }
unset_alt = { fg = "#cc6666", bg = "#373b41" }

[status]
perm_exec = { fg = "#b5bd68" }
perm_read = { fg = "#f0c674" }
perm_sep = { fg = "#8abeb7" }
perm_type = { fg = "#81a2be" }
perm_write = { fg = "#cc6666" }

progress_error = { fg = "#cc6666", bg = "#1d1f21" }
progress_label = { fg = "#c5c8c6", bg = "#1d1f21" }
progress_normal = { fg = "#c5c8c6", bg = "#1d1f21" }

[pick]
active = { fg = "#b294bb" }
border = { fg = "#81a2be" }
inactive = { fg = "#c5c8c6" }

[task]
title = { fg = "#81a2be" }
border = { fg = "#81a2be" }
hovered = { fg = "#c5c8c6", bg = "#373b41" }

[input]
border = { fg = "#81a2be" }
selected = { bg = "#373b41" }

[help]
desc = { fg = "#c5c8c6" }
on = { fg = "#8abeb7" }
run = { fg = "#b294bb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#373b41", bg = "#c5c8c6" }

[which]
mask = { bg = "#373b41" }
desc = { fg = "#c5c8c6" }
cand = { fg = "#8abeb7" }
rest = { fg = "#a3685a" }

separator_style = { fg = "#b4b7b4" }

[notify]
title_info = { fg = "#8abeb7" }
title_warn = { fg = "#f0c674" }
title_error = { fg = "#cc6666" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8abeb7" },
  { mime = "{audio, video}/*", fg = "#f0c674" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#b5bd68" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#81a2be" },
  { mime = "*", fg = "#c5c8c6" },
]

