[mgr]
cwd = { fg = "#6a9589" }

find_keyword = { bold = true, fg = "#c0a36e" }
find_position = { fg = "#957fb8" }

marker_copied = { fg = "#76946a", bg = "#76946a" }
marker_cut = { fg = "#c34043", bg = "#c34043" }
marker_selected = { fg = "#c0a36e", bg = "#c0a36e" }

count_copied = { fg = "#1f1f28", bg = "#76946a" }
count_cut = { fg = "#1f1f28", bg = "#c34043" }
count_selected = { fg = "#1f1f28", bg = "#c0a36e" }

border_style = { fg = "#7e9cd8" }

[tabs]
active = { fg = "#1f1f28", bg = "#7e9cd8"}
inactive = { fg = "#7e9cd8", bg = #16161d" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1f1f28", bg = "#7e9cd8", bold = true }
normal_alt = { fg = "#7e9cd8", bg = "#223249" }

select_alt = { fg = "#957fb8", bg = "#223249" }
select_main = { fg = "#1f1f28", bg = "#957fb8", bold = true }

unset_main = { fg = "#1f1f28", bg = "#c34043", bold = true }
unset_alt = { fg = "#c34043", bg = "#223249" }

[status]
perm_exec = { fg = "#76946a" }
perm_read = { fg = "#c0a36e" }
perm_sep = { fg = "#6a9589" }
perm_type = { fg = "#7e9cd8" }
perm_write = { fg = "#c34043" }

progress_error = { fg = "#c34043", bg = "#1f1f28" }
progress_label = { fg = "#dcd7ba", bg = "#1f1f28" }
progress_normal = { fg = "#dcd7ba", bg = "#1f1f28" }

[pick]
active = { fg = "#957fb8" }
border = { fg = "#7e9cd8" }
inactive = { fg = "#dcd7ba" }

[task]
title = { fg = "#7e9cd8" }
border = { fg = "#7e9cd8" }
hovered = { fg = "#dcd7ba", bg = "#223249" }

[input]
border = { fg = "#7e9cd8" }
selected = { bg = "#223249" }

[help]
desc = { fg = "#dcd7ba" }
on = { fg = "#6a9589" }
run = { fg = "#957fb8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#223249", bg = "#dcd7ba" }

[which]
mask = { bg = "#223249" }
desc = { fg = "#dcd7ba" }
cand = { fg = "#6a9589" }
rest = { fg = "#d27e99" }

separator_style = { fg = "#727169" }

[notify]
title_info = { fg = "#6a9589" }
title_warn = { fg = "#c0a36e" }
title_error = { fg = "#c34043" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#6a9589" },
  { mime = "{audio, video}/*", fg = "#c0a36e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#76946a" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#7e9cd8" },
  { mime = "*", fg = "#dcd7ba" },
]

