[mgr]
cwd = { fg = "#83a598" }

find_keyword = { bold = true, fg = "#a07e3b" }
find_position = { fg = "#d75f5f" }

marker_copied = { fg = "#528b8b", bg = "#528b8b" }
marker_cut = { fg = "#83a598", bg = "#83a598" }
marker_selected = { fg = "#a07e3b", bg = "#a07e3b" }

count_copied = { fg = "#282c34", bg = "#528b8b" }
count_cut = { fg = "#282c34", bg = "#83a598" }
count_selected = { fg = "#282c34", bg = "#a07e3b" }

border_style = { fg = "#83a598" }

[tabs]
active = { fg = "#282c34", bg = "#83a598"}
inactive = { fg = "#83a598", bg = #2c323b" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#282c34", bg = "#83a598", bold = true }
normal_alt = { fg = "#83a598", bg = "#3e4451" }

select_alt = { fg = "#d75f5f", bg = "#3e4451" }
select_main = { fg = "#282c34", bg = "#d75f5f", bold = true }

unset_main = { fg = "#282c34", bg = "#83a598", bold = true }
unset_alt = { fg = "#83a598", bg = "#3e4451" }

[status]
perm_exec = { fg = "#528b8b" }
perm_read = { fg = "#a07e3b" }
perm_sep = { fg = "#83a598" }
perm_type = { fg = "#83a598" }
perm_write = { fg = "#83a598" }

progress_error = { fg = "#83a598", bg = "#282c34" }
progress_label = { fg = "#a89984", bg = "#282c34" }
progress_normal = { fg = "#a89984", bg = "#282c34" }

[pick]
active = { fg = "#d75f5f" }
border = { fg = "#83a598" }
inactive = { fg = "#a89984" }

[task]
title = { fg = "#83a598" }
border = { fg = "#83a598" }
hovered = { fg = "#a89984", bg = "#3e4451" }

[input]
border = { fg = "#83a598" }
selected = { bg = "#3e4451" }

[help]
desc = { fg = "#a89984" }
on = { fg = "#83a598" }
run = { fg = "#d75f5f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e4451", bg = "#a89984" }

[which]
mask = { bg = "#3e4451" }
desc = { fg = "#a89984" }
cand = { fg = "#83a598" }
rest = { fg = "#a87322" }

separator_style = { fg = "#928374" }

[notify]
title_info = { fg = "#83a598" }
title_warn = { fg = "#a07e3b" }
title_error = { fg = "#83a598" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#83a598" },
  { mime = "{audio, video}/*", fg = "#a07e3b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#528b8b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#83a598" },
  { mime = "*", fg = "#a89984" },
]

