[mgr]
cwd = { fg = "#087767" }

find_keyword = { bold = true, fg = "#876500" }
find_position = { fg = "#7b4ecb" }

marker_copied = { fg = "#557301", bg = "#557301" }
marker_cut = { fg = "#af4947", bg = "#af4947" }
marker_selected = { fg = "#876500", bg = "#876500" }

count_copied = { fg = "#ffffff", bg = "#557301" }
count_cut = { fg = "#ffffff", bg = "#af4947" }
count_selected = { fg = "#ffffff", bg = "#876500" }

border_style = { fg = "#186daa" }

[tabs]
active = { fg = "#ffffff", bg = "#186daa"}
inactive = { fg = "#186daa", bg = #ededed" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#186daa", bold = true }
normal_alt = { fg = "#186daa", bg = "#dbdbdb" }

select_alt = { fg = "#7b4ecb", bg = "#dbdbdb" }
select_main = { fg = "#ffffff", bg = "#7b4ecb", bold = true }

unset_main = { fg = "#ffffff", bg = "#af4947", bold = true }
unset_alt = { fg = "#af4947", bg = "#dbdbdb" }

[status]
perm_exec = { fg = "#557301" }
perm_read = { fg = "#876500" }
perm_sep = { fg = "#087767" }
perm_type = { fg = "#186daa" }
perm_write = { fg = "#af4947" }

progress_error = { fg = "#af4947", bg = "#ffffff" }
progress_label = { fg = "#555555", bg = "#ffffff" }
progress_normal = { fg = "#555555", bg = "#ffffff" }

[pick]
active = { fg = "#7b4ecb" }
border = { fg = "#186daa" }
inactive = { fg = "#555555" }

[task]
title = { fg = "#186daa" }
border = { fg = "#186daa" }
hovered = { fg = "#555555", bg = "#dbdbdb" }

[input]
border = { fg = "#186daa" }
selected = { bg = "#dbdbdb" }

[help]
desc = { fg = "#555555" }
on = { fg = "#087767" }
run = { fg = "#7b4ecb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#dbdbdb", bg = "#555555" }

[which]
mask = { bg = "#dbdbdb" }
desc = { fg = "#555555" }
cand = { fg = "#087767" }
rest = { fg = "#a93e93" }

separator_style = { fg = "#636363" }

[notify]
title_info = { fg = "#087767" }
title_warn = { fg = "#876500" }
title_error = { fg = "#af4947" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#087767" },
  { mime = "{audio, video}/*", fg = "#876500" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#557301" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#186daa" },
  { mime = "*", fg = "#555555" },
]

