[mgr]
cwd = { fg = "#8ea4a2" }

find_keyword = { bold = true, fg = "#c4b28a" }
find_position = { fg = "#a292a3" }

marker_copied = { fg = "#8a9a7b", bg = "#8a9a7b" }
marker_cut = { fg = "#c4746e", bg = "#c4746e" }
marker_selected = { fg = "#c4b28a", bg = "#c4b28a" }

count_copied = { fg = "#181616", bg = "#8a9a7b" }
count_cut = { fg = "#181616", bg = "#c4746e" }
count_selected = { fg = "#181616", bg = "#c4b28a" }

border_style = { fg = "#8ba4b0" }

[tabs]
active = { fg = "#181616", bg = "#8ba4b0"}
inactive = { fg = "#8ba4b0", bg = #282727" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#181616", bg = "#8ba4b0", bold = true }
normal_alt = { fg = "#8ba4b0", bg = "#393836" }

select_alt = { fg = "#a292a3", bg = "#393836" }
select_main = { fg = "#181616", bg = "#a292a3", bold = true }

unset_main = { fg = "#181616", bg = "#c4746e", bold = true }
unset_alt = { fg = "#c4746e", bg = "#393836" }

[status]
perm_exec = { fg = "#8a9a7b" }
perm_read = { fg = "#c4b28a" }
perm_sep = { fg = "#8ea4a2" }
perm_type = { fg = "#8ba4b0" }
perm_write = { fg = "#c4746e" }

progress_error = { fg = "#c4746e", bg = "#181616" }
progress_label = { fg = "#c5c9c5", bg = "#181616" }
progress_normal = { fg = "#c5c9c5", bg = "#181616" }

[pick]
active = { fg = "#a292a3" }
border = { fg = "#8ba4b0" }
inactive = { fg = "#c5c9c5" }

[task]
title = { fg = "#8ba4b0" }
border = { fg = "#8ba4b0" }
hovered = { fg = "#c5c9c5", bg = "#393836" }

[input]
border = { fg = "#8ba4b0" }
selected = { bg = "#393836" }

[help]
desc = { fg = "#c5c9c5" }
on = { fg = "#8ea4a2" }
run = { fg = "#a292a3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#393836", bg = "#c5c9c5" }

[which]
mask = { bg = "#393836" }
desc = { fg = "#c5c9c5" }
cand = { fg = "#8ea4a2" }
rest = { fg = "#b98d7b" }

separator_style = { fg = "#737c73" }

[notify]
title_info = { fg = "#8ea4a2" }
title_warn = { fg = "#c4b28a" }
title_error = { fg = "#c4746e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8ea4a2" },
  { mime = "{audio, video}/*", fg = "#c4b28a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8a9a7b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#8ba4b0" },
  { mime = "*", fg = "#c5c9c5" },
]

