[mgr]
cwd = { fg = "#00a8a8" }

find_keyword = { bold = true, fg = "#a85400" }
find_position = { fg = "#a800a8" }

marker_copied = { fg = "#00a800", bg = "#00a800" }
marker_cut = { fg = "#a80000", bg = "#a80000" }
marker_selected = { fg = "#a85400", bg = "#a85400" }

count_copied = { fg = "#fcfcfc", bg = "#00a800" }
count_cut = { fg = "#fcfcfc", bg = "#a80000" }
count_selected = { fg = "#fcfcfc", bg = "#a85400" }

border_style = { fg = "#0000a8" }

[tabs]
active = { fg = "#fcfcfc", bg = "#0000a8"}
inactive = { fg = "#0000a8", bg = "#e0e0e0" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fcfcfc", bg = "#0000a8", bold = true }
normal_alt = { fg = "#0000a8", bg = "#c4c4c4" }

select_alt = { fg = "#a800a8", bg = "#c4c4c4" }
select_main = { fg = "#fcfcfc", bg = "#a800a8", bold = true }

unset_main = { fg = "#fcfcfc", bg = "#a80000", bold = true }
unset_alt = { fg = "#a80000", bg = "#c4c4c4" }

[status]
perm_exec = { fg = "#00a800" }
perm_read = { fg = "#a85400" }
perm_sep = { fg = "#00a8a8" }
perm_type = { fg = "#0000a8" }
perm_write = { fg = "#a80000" }

progress_error = { fg = "#a80000", bg = "#fcfcfc" }
progress_label = { fg = "#545454", bg = "#fcfcfc" }
progress_normal = { fg = "#545454", bg = "#fcfcfc" }

[pick]
active = { fg = "#a800a8" }
border = { fg = "#0000a8" }
inactive = { fg = "#545454" }

[task]
title = { fg = "#0000a8" }
border = { fg = "#0000a8" }
hovered = { fg = "#545454", bg = "#c4c4c4" }

[input]
border = { fg = "#0000a8" }
selected = { bg = "#c4c4c4" }

[help]
desc = { fg = "#545454" }
on = { fg = "#00a8a8" }
run = { fg = "#a800a8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#c4c4c4", bg = "#545454" }

[which]
mask = { bg = "#c4c4c4" }
desc = { fg = "#545454" }
cand = { fg = "#00a8a8" }
rest = { fg = "#54fc54" }

separator_style = { fg = "#7e7e7e" }

[notify]
title_info = { fg = "#00a8a8" }
title_warn = { fg = "#a85400" }
title_error = { fg = "#a80000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00a8a8" },
  { mime = "{audio, video}/*", fg = "#a85400" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00a800" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0000a8" },
  { mime = "*", fg = "#545454" },
]

