[mgr]
cwd = { fg = "#3aa99f" }

find_keyword = { bold = true, fg = "#d0a215" }
find_position = { fg = "#8b7ec8" }

marker_copied = { fg = "#879a39", bg = "#879a39" }
marker_cut = { fg = "#d14d41", bg = "#d14d41" }
marker_selected = { fg = "#d0a215", bg = "#d0a215" }

count_copied = { fg = "#100f0f", bg = "#879a39" }
count_cut = { fg = "#100f0f", bg = "#d14d41" }
count_selected = { fg = "#100f0f", bg = "#d0a215" }

border_style = { fg = "#4385be" }

[tabs]
active = { fg = "#100f0f", bg = "#4385be"}
inactive = { fg = "#4385be", bg = "#1c1b1a" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#100f0f", bg = "#4385be", bold = true }
normal_alt = { fg = "#4385be", bg = "#282726" }

select_alt = { fg = "#8b7ec8", bg = "#282726" }
select_main = { fg = "#100f0f", bg = "#8b7ec8", bold = true }

unset_main = { fg = "#100f0f", bg = "#d14d41", bold = true }
unset_alt = { fg = "#d14d41", bg = "#282726" }

[status]
perm_exec = { fg = "#879a39" }
perm_read = { fg = "#d0a215" }
perm_sep = { fg = "#3aa99f" }
perm_type = { fg = "#4385be" }
perm_write = { fg = "#d14d41" }

progress_error = { fg = "#d14d41", bg = "#100f0f" }
progress_label = { fg = "#cecdc3", bg = "#100f0f" }
progress_normal = { fg = "#cecdc3", bg = "#100f0f" }

[pick]
active = { fg = "#8b7ec8" }
border = { fg = "#4385be" }
inactive = { fg = "#cecdc3" }

[task]
title = { fg = "#4385be" }
border = { fg = "#4385be" }
hovered = { fg = "#cecdc3", bg = "#282726" }

[input]
border = { fg = "#4385be" }
selected = { bg = "#282726" }

[help]
desc = { fg = "#cecdc3" }
on = { fg = "#3aa99f" }
run = { fg = "#8b7ec8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#282726", bg = "#cecdc3" }

[which]
mask = { bg = "#282726" }
desc = { fg = "#cecdc3" }
cand = { fg = "#3aa99f" }
rest = { fg = "#ce5d97" }

separator_style = { fg = "#878580" }

[notify]
title_info = { fg = "#3aa99f" }
title_warn = { fg = "#d0a215" }
title_error = { fg = "#d14d41" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3aa99f" },
  { mime = "{audio, video}/*", fg = "#d0a215" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#879a39" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#4385be" },
  { mime = "*", fg = "#cecdc3" },
]

