[mgr]
cwd = { fg = "#24a8b4" }

find_keyword = { bold = true, fg = "#efb993" }
find_position = { fg = "#b072d1" }

marker_copied = { fg = "#efaf8e", bg = "#efaf8e" }
marker_cut = { fg = "#e93c58", bg = "#e93c58" }
marker_selected = { fg = "#efb993", bg = "#efb993" }

count_copied = { fg = "#1c1e26", bg = "#efaf8e" }
count_cut = { fg = "#1c1e26", bg = "#e93c58" }
count_selected = { fg = "#1c1e26", bg = "#efb993" }

border_style = { fg = "#df5273" }

[tabs]
active = { fg = "#1c1e26", bg = "#df5273"}
inactive = { fg = "#df5273", bg = "#232530" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1c1e26", bg = "#df5273", bold = true }
normal_alt = { fg = "#df5273", bg = "#2e303e" }

select_alt = { fg = "#b072d1", bg = "#2e303e" }
select_main = { fg = "#1c1e26", bg = "#b072d1", bold = true }

unset_main = { fg = "#1c1e26", bg = "#e93c58", bold = true }
unset_alt = { fg = "#e93c58", bg = "#2e303e" }

[status]
perm_exec = { fg = "#efaf8e" }
perm_read = { fg = "#efb993" }
perm_sep = { fg = "#24a8b4" }
perm_type = { fg = "#df5273" }
perm_write = { fg = "#e93c58" }

progress_error = { fg = "#e93c58", bg = "#1c1e26" }
progress_label = { fg = "#cbced0", bg = "#1c1e26" }
progress_normal = { fg = "#cbced0", bg = "#1c1e26" }

[pick]
active = { fg = "#b072d1" }
border = { fg = "#df5273" }
inactive = { fg = "#cbced0" }

[task]
title = { fg = "#df5273" }
border = { fg = "#df5273" }
hovered = { fg = "#cbced0", bg = "#2e303e" }

[input]
border = { fg = "#df5273" }
selected = { bg = "#2e303e" }

[help]
desc = { fg = "#cbced0" }
on = { fg = "#24a8b4" }
run = { fg = "#b072d1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2e303e", bg = "#cbced0" }

[which]
mask = { bg = "#2e303e" }
desc = { fg = "#cbced0" }
cand = { fg = "#24a8b4" }
rest = { fg = "#e4a382" }

separator_style = { fg = "#9da0a2" }

[notify]
title_info = { fg = "#24a8b4" }
title_warn = { fg = "#efb993" }
title_error = { fg = "#e93c58" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#24a8b4" },
  { mime = "{audio, video}/*", fg = "#efb993" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#efaf8e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#df5273" },
  { mime = "*", fg = "#cbced0" },
]

