[mgr]
cwd = { fg = "#8af5ff" }

find_keyword = { bold = true, fg = "#ff9470" }
find_position = { fg = "#e799ff" }

marker_copied = { fg = "#98c379", bg = "#98c379" }
marker_cut = { fg = "#fa7883", bg = "#fa7883" }
marker_selected = { fg = "#ff9470", bg = "#ff9470" }

count_copied = { fg = "#000000", bg = "#98c379" }
count_cut = { fg = "#000000", bg = "#fa7883" }
count_selected = { fg = "#000000", bg = "#ff9470" }

border_style = { fg = "#6bb8ff" }

[tabs]
active = { fg = "#000000", bg = "#6bb8ff"}
inactive = { fg = "#6bb8ff", bg = #282828" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#000000", bg = "#6bb8ff", bold = true }
normal_alt = { fg = "#6bb8ff", bg = "#585858" }

select_alt = { fg = "#e799ff", bg = "#585858" }
select_main = { fg = "#000000", bg = "#e799ff", bold = true }

unset_main = { fg = "#000000", bg = "#fa7883", bold = true }
unset_alt = { fg = "#fa7883", bg = "#585858" }

[status]
perm_exec = { fg = "#98c379" }
perm_read = { fg = "#ff9470" }
perm_sep = { fg = "#8af5ff" }
perm_type = { fg = "#6bb8ff" }
perm_write = { fg = "#fa7883" }

progress_error = { fg = "#fa7883", bg = "#000000" }
progress_label = { fg = "#ffffff", bg = "#000000" }
progress_normal = { fg = "#ffffff", bg = "#000000" }

[pick]
active = { fg = "#e799ff" }
border = { fg = "#6bb8ff" }
inactive = { fg = "#ffffff" }

[task]
title = { fg = "#6bb8ff" }
border = { fg = "#6bb8ff" }
hovered = { fg = "#ffffff", bg = "#585858" }

[input]
border = { fg = "#6bb8ff" }
selected = { bg = "#585858" }

[help]
desc = { fg = "#ffffff" }
on = { fg = "#8af5ff" }
run = { fg = "#e799ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#585858", bg = "#ffffff" }

[which]
mask = { bg = "#585858" }
desc = { fg = "#ffffff" }
cand = { fg = "#8af5ff" }
rest = { fg = "#b3684f" }

separator_style = { fg = "#c8c8c8" }

[notify]
title_info = { fg = "#8af5ff" }
title_warn = { fg = "#ff9470" }
title_error = { fg = "#fa7883" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8af5ff" },
  { mime = "{audio, video}/*", fg = "#ff9470" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#98c379" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6bb8ff" },
  { mime = "*", fg = "#ffffff" },
]

