[mgr]
cwd = { fg = "#52cbb0" }

find_keyword = { bold = true, fg = "#e4b51c" }
find_position = { fg = "#a363d5" }

marker_copied = { fg = "#7cc844", bg = "#7cc844" }
marker_cut = { fg = "#ef5253", bg = "#ef5253" }
marker_selected = { fg = "#e4b51c", bg = "#e4b51c" }

count_copied = { fg = "#f5f7fa", bg = "#7cc844" }
count_cut = { fg = "#f5f7fa", bg = "#ef5253" }
count_selected = { fg = "#f5f7fa", bg = "#e4b51c" }

border_style = { fg = "#33b5e1" }

[tabs]
active = { fg = "#f5f7fa", bg = "#33b5e1"}
inactive = { fg = "#33b5e1", bg = #e8e9ed" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f5f7fa", bg = "#33b5e1", bold = true }
normal_alt = { fg = "#33b5e1", bg = "#a6afb8" }

select_alt = { fg = "#a363d5", bg = "#a6afb8" }
select_main = { fg = "#f5f7fa", bg = "#a363d5", bold = true }

unset_main = { fg = "#f5f7fa", bg = "#ef5253", bold = true }
unset_alt = { fg = "#ef5253", bg = "#a6afb8" }

[status]
perm_exec = { fg = "#7cc844" }
perm_read = { fg = "#e4b51c" }
perm_sep = { fg = "#52cbb0" }
perm_type = { fg = "#33b5e1" }
perm_write = { fg = "#ef5253" }

progress_error = { fg = "#ef5253", bg = "#f5f7fa" }
progress_label = { fg = "#586875", bg = "#f5f7fa" }
progress_normal = { fg = "#586875", bg = "#f5f7fa" }

[pick]
active = { fg = "#a363d5" }
border = { fg = "#33b5e1" }
inactive = { fg = "#586875" }

[task]
title = { fg = "#33b5e1" }
border = { fg = "#33b5e1" }
hovered = { fg = "#586875", bg = "#a6afb8" }

[input]
border = { fg = "#33b5e1" }
selected = { bg = "#a6afb8" }

[help]
desc = { fg = "#586875" }
on = { fg = "#52cbb0" }
run = { fg = "#a363d5" }
hovered = { reversed = true, bold = true }
footer = { fg = "#a6afb8", bg = "#586875" }

[which]
mask = { bg = "#a6afb8" }
desc = { fg = "#586875" }
cand = { fg = "#52cbb0" }
rest = { fg = "#d73c9a" }

separator_style = { fg = "#667581" }

[notify]
title_info = { fg = "#52cbb0" }
title_warn = { fg = "#e4b51c" }
title_error = { fg = "#ef5253" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#52cbb0" },
  { mime = "{audio, video}/*", fg = "#e4b51c" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7cc844" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#33b5e1" },
  { mime = "*", fg = "#586875" },
]

