[mgr]
cwd = { fg = "#708387" }

find_keyword = { bold = true, fg = "#e6db74" }
find_position = { fg = "#9e6ffe" }

marker_copied = { fg = "#a6e22e", bg = "#a6e22e" }
marker_cut = { fg = "#f92672", bg = "#f92672" }
marker_selected = { fg = "#e6db74", bg = "#e6db74" }

count_copied = { fg = "#212121", bg = "#a6e22e" }
count_cut = { fg = "#212121", bg = "#f92672" }
count_selected = { fg = "#212121", bg = "#e6db74" }

border_style = { fg = "#66d9ef" }

[tabs]
active = { fg = "#212121", bg = "#66d9ef"}
inactive = { fg = "#66d9ef", bg = "#303030" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#212121", bg = "#66d9ef", bold = true }
normal_alt = { fg = "#66d9ef", bg = "#353535" }

select_alt = { fg = "#9e6ffe", bg = "#353535" }
select_main = { fg = "#212121", bg = "#9e6ffe", bold = true }

unset_main = { fg = "#212121", bg = "#f92672", bold = true }
unset_alt = { fg = "#f92672", bg = "#353535" }

[status]
perm_exec = { fg = "#a6e22e" }
perm_read = { fg = "#e6db74" }
perm_sep = { fg = "#708387" }
perm_type = { fg = "#66d9ef" }
perm_write = { fg = "#f92672" }

progress_error = { fg = "#f92672", bg = "#212121" }
progress_label = { fg = "#cdcdcd", bg = "#212121" }
progress_normal = { fg = "#cdcdcd", bg = "#212121" }

[pick]
active = { fg = "#9e6ffe" }
border = { fg = "#66d9ef" }
inactive = { fg = "#cdcdcd" }

[task]
title = { fg = "#66d9ef" }
border = { fg = "#66d9ef" }
hovered = { fg = "#cdcdcd", bg = "#353535" }

[input]
border = { fg = "#66d9ef" }
selected = { bg = "#353535" }

[help]
desc = { fg = "#cdcdcd" }
on = { fg = "#708387" }
run = { fg = "#9e6ffe" }
hovered = { reversed = true, bold = true }
footer = { fg = "#353535", bg = "#cdcdcd" }

[which]
mask = { bg = "#353535" }
desc = { fg = "#cdcdcd" }
cand = { fg = "#708387" }
rest = { fg = "#e8b882" }

separator_style = { fg = "#707070" }

[notify]
title_info = { fg = "#708387" }
title_warn = { fg = "#e6db74" }
title_error = { fg = "#f92672" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#708387" },
  { mime = "{audio, video}/*", fg = "#e6db74" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a6e22e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#66d9ef" },
  { mime = "*", fg = "#cdcdcd" },
]

