[mgr]
cwd = { fg = "#64878f" }

find_keyword = { bold = true, fg = "#efa16b" }
find_position = { fg = "#b74989" }

marker_copied = { fg = "#95c76f", bg = "#95c76f" }
marker_cut = { fg = "#f84547", bg = "#f84547" }
marker_selected = { fg = "#efa16b", bg = "#efa16b" }

count_copied = { fg = "#292c36", bg = "#95c76f" }
count_cut = { fg = "#292c36", bg = "#f84547" }
count_selected = { fg = "#292c36", bg = "#efa16b" }

border_style = { fg = "#8485ce" }

[tabs]
active = { fg = "#292c36", bg = "#8485ce"}
inactive = { fg = "#8485ce", bg = #333344" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#292c36", bg = "#8485ce", bold = true }
normal_alt = { fg = "#8485ce", bg = "#474160" }

select_alt = { fg = "#b74989", bg = "#474160" }
select_main = { fg = "#292c36", bg = "#b74989", bold = true }

unset_main = { fg = "#292c36", bg = "#f84547", bold = true }
unset_alt = { fg = "#f84547", bg = "#474160" }

[status]
perm_exec = { fg = "#95c76f" }
perm_read = { fg = "#efa16b" }
perm_sep = { fg = "#64878f" }
perm_type = { fg = "#8485ce" }
perm_write = { fg = "#f84547" }

progress_error = { fg = "#f84547", bg = "#292c36" }
progress_label = { fg = "#d8d8d8", bg = "#292c36" }
progress_normal = { fg = "#d8d8d8", bg = "#292c36" }

[pick]
active = { fg = "#b74989" }
border = { fg = "#8485ce" }
inactive = { fg = "#d8d8d8" }

[task]
title = { fg = "#8485ce" }
border = { fg = "#8485ce" }
hovered = { fg = "#d8d8d8", bg = "#474160" }

[input]
border = { fg = "#8485ce" }
selected = { bg = "#474160" }

[help]
desc = { fg = "#d8d8d8" }
on = { fg = "#64878f" }
run = { fg = "#b74989" }
hovered = { reversed = true, bold = true }
footer = { fg = "#474160", bg = "#d8d8d8" }

[which]
mask = { bg = "#474160" }
desc = { fg = "#d8d8d8" }
cand = { fg = "#64878f" }
rest = { fg = "#986841" }

separator_style = { fg = "#b8b8b8" }

[notify]
title_info = { fg = "#64878f" }
title_warn = { fg = "#efa16b" }
title_error = { fg = "#f84547" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#64878f" },
  { mime = "{audio, video}/*", fg = "#efa16b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#95c76f" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#8485ce" },
  { mime = "*", fg = "#d8d8d8" },
]

