[mgr]
cwd = { fg = "#80cbc4" }

find_keyword = { bold = true, fg = "#ffcc00" }
find_position = { fg = "#82aaff" }

marker_copied = { fg = "#8bd649", bg = "#8bd649" }
marker_cut = { fg = "#ec5f67", bg = "#ec5f67" }
marker_selected = { fg = "#ffcc00", bg = "#ffcc00" }

count_copied = { fg = "#263238", bg = "#8bd649" }
count_cut = { fg = "#263238", bg = "#ec5f67" }
count_selected = { fg = "#263238", bg = "#ffcc00" }

border_style = { fg = "#89ddff" }

[tabs]
active = { fg = "#263238", bg = "#89ddff"}
inactive = { fg = "#89ddff", bg = "#2c393f" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#263238", bg = "#89ddff", bold = true }
normal_alt = { fg = "#89ddff", bg = "#37474f" }

select_alt = { fg = "#82aaff", bg = "#37474f" }
select_main = { fg = "#263238", bg = "#82aaff", bold = true }

unset_main = { fg = "#263238", bg = "#ec5f67", bold = true }
unset_alt = { fg = "#ec5f67", bg = "#37474f" }

[status]
perm_exec = { fg = "#8bd649" }
perm_read = { fg = "#ffcc00" }
perm_sep = { fg = "#80cbc4" }
perm_type = { fg = "#89ddff" }
perm_write = { fg = "#ec5f67" }

progress_error = { fg = "#ec5f67", bg = "#263238" }
progress_label = { fg = "#cdd3de", bg = "#263238" }
progress_normal = { fg = "#cdd3de", bg = "#263238" }

[pick]
active = { fg = "#82aaff" }
border = { fg = "#89ddff" }
inactive = { fg = "#cdd3de" }

[task]
title = { fg = "#89ddff" }
border = { fg = "#89ddff" }
hovered = { fg = "#cdd3de", bg = "#37474f" }

[input]
border = { fg = "#89ddff" }
selected = { bg = "#37474f" }

[help]
desc = { fg = "#cdd3de" }
on = { fg = "#80cbc4" }
run = { fg = "#82aaff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#37474f", bg = "#cdd3de" }

[which]
mask = { bg = "#37474f" }
desc = { fg = "#cdd3de" }
cand = { fg = "#80cbc4" }
rest = { fg = "#ec5f67" }

separator_style = { fg = "#c9ccd3" }

[notify]
title_info = { fg = "#80cbc4" }
title_warn = { fg = "#ffcc00" }
title_error = { fg = "#ec5f67" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#80cbc4" },
  { mime = "{audio, video}/*", fg = "#ffcc00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8bd649" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#89ddff" },
  { mime = "*", fg = "#cdd3de" },
]

