[mgr]
cwd = { fg = "#2d8f6f" }

find_keyword = { bold = true, fg = "#8a8a0f" }
find_position = { fg = "#6b6bb8" }

marker_copied = { fg = "#568c3b", bg = "#568c3b" }
marker_cut = { fg = "#d22d72", bg = "#d22d72" }
marker_selected = { fg = "#8a8a0f", bg = "#8a8a0f" }

count_copied = { fg = "#ebf8ff", bg = "#568c3b" }
count_cut = { fg = "#ebf8ff", bg = "#d22d72" }
count_selected = { fg = "#ebf8ff", bg = "#8a8a0f" }

border_style = { fg = "#257fad" }

[tabs]
active = { fg = "#ebf8ff", bg = "#257fad"}
inactive = { fg = "#257fad", bg = #c1e4f6" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ebf8ff", bg = "#257fad", bold = true }
normal_alt = { fg = "#257fad", bg = "#7ea2b4" }

select_alt = { fg = "#6b6bb8", bg = "#7ea2b4" }
select_main = { fg = "#ebf8ff", bg = "#6b6bb8", bold = true }

unset_main = { fg = "#ebf8ff", bg = "#d22d72", bold = true }
unset_alt = { fg = "#d22d72", bg = "#7ea2b4" }

[status]
perm_exec = { fg = "#568c3b" }
perm_read = { fg = "#8a8a0f" }
perm_sep = { fg = "#2d8f6f" }
perm_type = { fg = "#257fad" }
perm_write = { fg = "#d22d72" }

progress_error = { fg = "#d22d72", bg = "#ebf8ff" }
progress_label = { fg = "#516d7b", bg = "#ebf8ff" }
progress_normal = { fg = "#516d7b", bg = "#ebf8ff" }

[pick]
active = { fg = "#6b6bb8" }
border = { fg = "#257fad" }
inactive = { fg = "#516d7b" }

[task]
title = { fg = "#257fad" }
border = { fg = "#257fad" }
hovered = { fg = "#516d7b", bg = "#7ea2b4" }

[input]
border = { fg = "#257fad" }
selected = { bg = "#7ea2b4" }

[help]
desc = { fg = "#516d7b" }
on = { fg = "#2d8f6f" }
run = { fg = "#6b6bb8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#7ea2b4", bg = "#516d7b" }

[which]
mask = { bg = "#7ea2b4" }
desc = { fg = "#516d7b" }
cand = { fg = "#2d8f6f" }
rest = { fg = "#b72dd2" }

separator_style = { fg = "#5a7b8c" }

[notify]
title_info = { fg = "#2d8f6f" }
title_warn = { fg = "#8a8a0f" }
title_error = { fg = "#d22d72" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2d8f6f" },
  { mime = "{audio, video}/*", fg = "#8a8a0f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#568c3b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#257fad" },
  { mime = "*", fg = "#516d7b" },
]

