[mgr]
cwd = { fg = "#21c992" }

find_keyword = { bold = true, fg = "#e1b31a" }
find_position = { fg = "#b46ee0" }

marker_copied = { fg = "#5db129", bg = "#5db129" }
marker_cut = { fg = "#e15d67", bg = "#e15d67" }
marker_selected = { fg = "#e1b31a", bg = "#e1b31a" }

count_copied = { fg = "#222222", bg = "#5db129" }
count_cut = { fg = "#222222", bg = "#e15d67" }
count_selected = { fg = "#222222", bg = "#e1b31a" }

border_style = { fg = "#00a3f2" }

[tabs]
active = { fg = "#222222", bg = "#00a3f2"}
inactive = { fg = "#00a3f2", bg = #303030" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#222222", bg = "#00a3f2", bold = true }
normal_alt = { fg = "#00a3f2", bg = "#555555" }

select_alt = { fg = "#b46ee0", bg = "#555555" }
select_main = { fg = "#222222", bg = "#b46ee0", bold = true }

unset_main = { fg = "#222222", bg = "#e15d67", bold = true }
unset_alt = { fg = "#e15d67", bg = "#555555" }

[status]
perm_exec = { fg = "#5db129" }
perm_read = { fg = "#e1b31a" }
perm_sep = { fg = "#21c992" }
perm_type = { fg = "#00a3f2" }
perm_write = { fg = "#e15d67" }

progress_error = { fg = "#e15d67", bg = "#222222" }
progress_label = { fg = "#c0c0c0", bg = "#222222" }
progress_normal = { fg = "#c0c0c0", bg = "#222222" }

[pick]
active = { fg = "#b46ee0" }
border = { fg = "#00a3f2" }
inactive = { fg = "#c0c0c0" }

[task]
title = { fg = "#00a3f2" }
border = { fg = "#00a3f2" }
hovered = { fg = "#c0c0c0", bg = "#555555" }

[input]
border = { fg = "#00a3f2" }
selected = { bg = "#555555" }

[help]
desc = { fg = "#c0c0c0" }
on = { fg = "#21c992" }
run = { fg = "#b46ee0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555555", bg = "#c0c0c0" }

[which]
mask = { bg = "#555555" }
desc = { fg = "#c0c0c0" }
cand = { fg = "#21c992" }
rest = { fg = "#b87d28" }

separator_style = { fg = "#898989" }

[notify]
title_info = { fg = "#21c992" }
title_warn = { fg = "#e1b31a" }
title_error = { fg = "#e15d67" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#21c992" },
  { mime = "{audio, video}/*", fg = "#e1b31a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5db129" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#00a3f2" },
  { mime = "*", fg = "#c0c0c0" },
]

