[mgr]
cwd = { fg = "#2a9d9a" }

find_keyword = { bold = true, fg = "#bb8009" }
find_position = { fg = "#a371f7" }

marker_copied = { fg = "#2ea043", bg = "#2ea043" }
marker_cut = { fg = "#f85149", bg = "#f85149" }
marker_selected = { fg = "#bb8009", bg = "#bb8009" }

count_copied = { fg = "#161b22", bg = "#2ea043" }
count_cut = { fg = "#161b22", bg = "#f85149" }
count_selected = { fg = "#161b22", bg = "#bb8009" }

border_style = { fg = "#388bfd" }

[tabs]
active = { fg = "#161b22", bg = "#388bfd"}
inactive = { fg = "#388bfd", bg = "#30363d" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#161b22", bg = "#388bfd", bold = true }
normal_alt = { fg = "#388bfd", bg = "#484f58" }

select_alt = { fg = "#a371f7", bg = "#484f58" }
select_main = { fg = "#161b22", bg = "#a371f7", bold = true }

unset_main = { fg = "#161b22", bg = "#f85149", bold = true }
unset_alt = { fg = "#f85149", bg = "#484f58" }

[status]
perm_exec = { fg = "#2ea043" }
perm_read = { fg = "#bb8009" }
perm_sep = { fg = "#2a9d9a" }
perm_type = { fg = "#388bfd" }
perm_write = { fg = "#f85149" }

progress_error = { fg = "#f85149", bg = "#161b22" }
progress_label = { fg = "#c9d1d9", bg = "#161b22" }
progress_normal = { fg = "#c9d1d9", bg = "#161b22" }

[pick]
active = { fg = "#a371f7" }
border = { fg = "#388bfd" }
inactive = { fg = "#c9d1d9" }

[task]
title = { fg = "#388bfd" }
border = { fg = "#388bfd" }
hovered = { fg = "#c9d1d9", bg = "#484f58" }

[input]
border = { fg = "#388bfd" }
selected = { bg = "#484f58" }

[help]
desc = { fg = "#c9d1d9" }
on = { fg = "#2a9d9a" }
run = { fg = "#a371f7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#484f58", bg = "#c9d1d9" }

[which]
mask = { bg = "#484f58" }
desc = { fg = "#c9d1d9" }
cand = { fg = "#2a9d9a" }
rest = { fg = "#3d2f00" }

separator_style = { fg = "#8b949e" }

[notify]
title_info = { fg = "#2a9d9a" }
title_warn = { fg = "#bb8009" }
title_error = { fg = "#f85149" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2a9d9a" },
  { mime = "{audio, video}/*", fg = "#bb8009" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2ea043" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#388bfd" },
  { mime = "*", fg = "#c9d1d9" },
]

