[mgr]
cwd = { fg = "#008080" }

find_keyword = { bold = true, fg = "#808000" }
find_position = { fg = "#800080" }

marker_copied = { fg = "#008000", bg = "#008000" }
marker_cut = { fg = "#800000", bg = "#800000" }
marker_selected = { fg = "#808000", bg = "#808000" }

count_copied = { fg = "#ffffff", bg = "#008000" }
count_cut = { fg = "#ffffff", bg = "#800000" }
count_selected = { fg = "#ffffff", bg = "#808000" }

border_style = { fg = "#000080" }

[tabs]
active = { fg = "#ffffff", bg = "#000080"}
inactive = { fg = "#000080", bg = #eaeaea" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#000080", bold = true }
normal_alt = { fg = "#000080", bg = "#d5d5d5" }

select_alt = { fg = "#800080", bg = "#d5d5d5" }
select_main = { fg = "#ffffff", bg = "#800080", bold = true }

unset_main = { fg = "#ffffff", bg = "#800000", bold = true }
unset_alt = { fg = "#800000", bg = "#d5d5d5" }

[status]
perm_exec = { fg = "#008000" }
perm_read = { fg = "#808000" }
perm_sep = { fg = "#008080" }
perm_type = { fg = "#000080" }
perm_write = { fg = "#800000" }

progress_error = { fg = "#800000", bg = "#ffffff" }
progress_label = { fg = "#808080", bg = "#ffffff" }
progress_normal = { fg = "#808080", bg = "#ffffff" }

[pick]
active = { fg = "#800080" }
border = { fg = "#000080" }
inactive = { fg = "#808080" }

[task]
title = { fg = "#000080" }
border = { fg = "#000080" }
hovered = { fg = "#808080", bg = "#d5d5d5" }

[input]
border = { fg = "#000080" }
selected = { bg = "#d5d5d5" }

[help]
desc = { fg = "#808080" }
on = { fg = "#008080" }
run = { fg = "#800080" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d5d5d5", bg = "#808080" }

[which]
mask = { bg = "#d5d5d5" }
desc = { fg = "#808080" }
cand = { fg = "#008080" }
rest = { fg = "#00ff00" }

separator_style = { fg = "#a0a0a0" }

[notify]
title_info = { fg = "#008080" }
title_warn = { fg = "#808000" }
title_error = { fg = "#800000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#008080" },
  { mime = "{audio, video}/*", fg = "#808000" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#008000" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#000080" },
  { mime = "*", fg = "#808080" },
]

