[mgr]
cwd = { fg = "#61d6d6" }

find_keyword = { bold = true, fg = "#f9f1a5" }
find_position = { fg = "#b4009e" }

marker_copied = { fg = "#16c60c", bg = "#16c60c" }
marker_cut = { fg = "#e74856", bg = "#e74856" }
marker_selected = { fg = "#f9f1a5", bg = "#f9f1a5" }

count_copied = { fg = "#0c0c0c", bg = "#16c60c" }
count_cut = { fg = "#0c0c0c", bg = "#e74856" }
count_selected = { fg = "#0c0c0c", bg = "#f9f1a5" }

border_style = { fg = "#3b78ff" }

[tabs]
active = { fg = "#0c0c0c", bg = "#3b78ff"}
inactive = { fg = "#3b78ff", bg = "#2f2f2f" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#0c0c0c", bg = "#3b78ff", bold = true }
normal_alt = { fg = "#3b78ff", bg = "#535353" }

select_alt = { fg = "#b4009e", bg = "#535353" }
select_main = { fg = "#0c0c0c", bg = "#b4009e", bold = true }

unset_main = { fg = "#0c0c0c", bg = "#e74856", bold = true }
unset_alt = { fg = "#e74856", bg = "#535353" }

[status]
perm_exec = { fg = "#16c60c" }
perm_read = { fg = "#f9f1a5" }
perm_sep = { fg = "#61d6d6" }
perm_type = { fg = "#3b78ff" }
perm_write = { fg = "#e74856" }

progress_error = { fg = "#e74856", bg = "#0c0c0c" }
progress_label = { fg = "#cccccc", bg = "#0c0c0c" }
progress_normal = { fg = "#cccccc", bg = "#0c0c0c" }

[pick]
active = { fg = "#b4009e" }
border = { fg = "#3b78ff" }
inactive = { fg = "#cccccc" }

[task]
title = { fg = "#3b78ff" }
border = { fg = "#3b78ff" }
hovered = { fg = "#cccccc", bg = "#535353" }

[input]
border = { fg = "#3b78ff" }
selected = { bg = "#535353" }

[help]
desc = { fg = "#cccccc" }
on = { fg = "#61d6d6" }
run = { fg = "#b4009e" }
hovered = { reversed = true, bold = true }
footer = { fg = "#535353", bg = "#cccccc" }

[which]
mask = { bg = "#535353" }
desc = { fg = "#cccccc" }
cand = { fg = "#61d6d6" }
rest = { fg = "#13a10e" }

separator_style = { fg = "#b9b9b9" }

[notify]
title_info = { fg = "#61d6d6" }
title_warn = { fg = "#f9f1a5" }
title_error = { fg = "#e74856" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#61d6d6" },
  { mime = "{audio, video}/*", fg = "#f9f1a5" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#16c60c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3b78ff" },
  { mime = "*", fg = "#cccccc" },
]

