[mgr]
cwd = { fg = "#00b3c2" }

find_keyword = { bold = true, fg = "#9ca748" }
find_position = { fg = "#a48fe1" }

marker_copied = { fg = "#50b584", bg = "#50b584" }
marker_cut = { fg = "#df7f78", bg = "#df7f78" }
marker_selected = { fg = "#9ca748", bg = "#9ca748" }

count_copied = { fg = "#181b1f", bg = "#50b584" }
count_cut = { fg = "#181b1f", bg = "#df7f78" }
count_selected = { fg = "#181b1f", bg = "#9ca748" }

border_style = { fg = "#61a3e6" }

[tabs]
active = { fg = "#181b1f", bg = "#61a3e6"}
inactive = { fg = "#61a3e6", bg = "#24272b" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#181b1f", bg = "#61a3e6", bold = true }
normal_alt = { fg = "#61a3e6", bg = "#3e4044" }

select_alt = { fg = "#a48fe1", bg = "#3e4044" }
select_main = { fg = "#181b1f", bg = "#a48fe1", bold = true }

unset_main = { fg = "#181b1f", bg = "#df7f78", bold = true }
unset_alt = { fg = "#df7f78", bg = "#3e4044" }

[status]
perm_exec = { fg = "#50b584" }
perm_read = { fg = "#9ca748" }
perm_sep = { fg = "#00b3c2" }
perm_type = { fg = "#61a3e6" }
perm_write = { fg = "#df7f78" }

progress_error = { fg = "#df7f78", bg = "#181b1f" }
progress_label = { fg = "#cecece", bg = "#181b1f" }
progress_normal = { fg = "#cecece", bg = "#181b1f" }

[pick]
active = { fg = "#a48fe1" }
border = { fg = "#61a3e6" }
inactive = { fg = "#cecece" }

[task]
title = { fg = "#61a3e6" }
border = { fg = "#61a3e6" }
hovered = { fg = "#cecece", bg = "#3e4044" }

[input]
border = { fg = "#61a3e6" }
selected = { bg = "#3e4044" }

[help]
desc = { fg = "#cecece" }
on = { fg = "#00b3c2" }
run = { fg = "#a48fe1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e4044", bg = "#cecece" }

[which]
mask = { bg = "#3e4044" }
desc = { fg = "#cecece" }
cand = { fg = "#00b3c2" }
rest = { fg = "#d080b6" }

separator_style = { fg = "#9e9e9e" }

[notify]
title_info = { fg = "#00b3c2" }
title_warn = { fg = "#9ca748" }
title_error = { fg = "#df7f78" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00b3c2" },
  { mime = "{audio, video}/*", fg = "#9ca748" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#50b584" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#61a3e6" },
  { mime = "*", fg = "#cecece" },
]

