[mgr]
cwd = { fg = "#1ba595" }

find_keyword = { bold = true, fg = "#f19d1a" }
find_position = { fg = "#be4264" }

marker_copied = { fg = "#88b92d", bg = "#88b92d" }
marker_cut = { fg = "#d72638", bg = "#d72638" }
marker_selected = { fg = "#f19d1a", bg = "#f19d1a" }

count_copied = { fg = "#1d2021", bg = "#88b92d" }
count_cut = { fg = "#1d2021", bg = "#d72638" }
count_selected = { fg = "#1d2021", bg = "#f19d1a" }

border_style = { fg = "#1e8bac" }

[tabs]
active = { fg = "#1d2021", bg = "#1e8bac"}
inactive = { fg = "#1e8bac", bg = "#383c3e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1d2021", bg = "#1e8bac", bold = true }
normal_alt = { fg = "#1e8bac", bg = "#53585b" }

select_alt = { fg = "#be4264", bg = "#53585b" }
select_main = { fg = "#1d2021", bg = "#be4264", bold = true }

unset_main = { fg = "#1d2021", bg = "#d72638", bold = true }
unset_alt = { fg = "#d72638", bg = "#53585b" }

[status]
perm_exec = { fg = "#88b92d" }
perm_read = { fg = "#f19d1a" }
perm_sep = { fg = "#1ba595" }
perm_type = { fg = "#1e8bac" }
perm_write = { fg = "#d72638" }

progress_error = { fg = "#d72638", bg = "#1d2021" }
progress_label = { fg = "#d5d5d5", bg = "#1d2021" }
progress_normal = { fg = "#d5d5d5", bg = "#1d2021" }

[pick]
active = { fg = "#be4264" }
border = { fg = "#1e8bac" }
inactive = { fg = "#d5d5d5" }

[task]
title = { fg = "#1e8bac" }
border = { fg = "#1e8bac" }
hovered = { fg = "#d5d5d5", bg = "#53585b" }

[input]
border = { fg = "#1e8bac" }
selected = { bg = "#53585b" }

[help]
desc = { fg = "#d5d5d5" }
on = { fg = "#1ba595" }
run = { fg = "#be4264" }
hovered = { reversed = true, bold = true }
footer = { fg = "#53585b", bg = "#d5d5d5" }

[which]
mask = { bg = "#53585b" }
desc = { fg = "#d5d5d5" }
cand = { fg = "#1ba595" }
rest = { fg = "#c85e0d" }

separator_style = { fg = "#cdcdcd" }

[notify]
title_info = { fg = "#1ba595" }
title_warn = { fg = "#f19d1a" }
title_error = { fg = "#d72638" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1ba595" },
  { mime = "{audio, video}/*", fg = "#f19d1a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#88b92d" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#1e8bac" },
  { mime = "*", fg = "#d5d5d5" },
]

