[mgr]
cwd = { fg = "#dec8a7" }

find_keyword = { bold = true, fg = "#dec8a7" }
find_position = { fg = "#a88c62" }

marker_copied = { fg = "#dec8a7", bg = "#dec8a7" }
marker_cut = { fg = "#a88c62", bg = "#a88c62" }
marker_selected = { fg = "#dec8a7", bg = "#dec8a7" }

count_copied = { fg = "#0f0b05", bg = "#dec8a7" }
count_cut = { fg = "#0f0b05", bg = "#a88c62" }
count_selected = { fg = "#0f0b05", bg = "#dec8a7" }

border_style = { fg = "#c3a983" }

[tabs]
active = { fg = "#0f0b05", bg = "#c3a983"}
inactive = { fg = "#c3a983", bg = #231b0e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#0f0b05", bg = "#c3a983", bold = true }
normal_alt = { fg = "#c3a983", bg = "#2a2012" }

select_alt = { fg = "#a88c62", bg = "#2a2012" }
select_main = { fg = "#0f0b05", bg = "#a88c62", bold = true }

unset_main = { fg = "#0f0b05", bg = "#a88c62", bold = true }
unset_alt = { fg = "#a88c62", bg = "#2a2012" }

[status]
perm_exec = { fg = "#dec8a7" }
perm_read = { fg = "#dec8a7" }
perm_sep = { fg = "#dec8a7" }
perm_type = { fg = "#c3a983" }
perm_write = { fg = "#a88c62" }

progress_error = { fg = "#a88c62", bg = "#0f0b05" }
progress_label = { fg = "#c3a983", bg = "#0f0b05" }
progress_normal = { fg = "#c3a983", bg = "#0f0b05" }

[pick]
active = { fg = "#a88c62" }
border = { fg = "#c3a983" }
inactive = { fg = "#c3a983" }

[task]
title = { fg = "#c3a983" }
border = { fg = "#c3a983" }
hovered = { fg = "#c3a983", bg = "#2a2012" }

[input]
border = { fg = "#c3a983" }
selected = { bg = "#2a2012" }

[help]
desc = { fg = "#c3a983" }
on = { fg = "#dec8a7" }
run = { fg = "#a88c62" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2a2012", bg = "#c3a983" }

[which]
mask = { bg = "#2a2012" }
desc = { fg = "#c3a983" }
cand = { fg = "#dec8a7" }
rest = { fg = "#876e48" }

separator_style = { fg = "#a88c62" }

[notify]
title_info = { fg = "#dec8a7" }
title_warn = { fg = "#dec8a7" }
title_error = { fg = "#a88c62" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#dec8a7" },
  { mime = "{audio, video}/*", fg = "#dec8a7" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#dec8a7" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#c3a983" },
  { mime = "*", fg = "#c3a983" },
]

