[mgr]
cwd = { fg = "#ff7eb6" }

find_keyword = { bold = true, fg = "#e1c697" }
find_position = { fg = "#be95ff" }

marker_copied = { fg = "#3fdaa4", bg = "#3fdaa4" }
marker_cut = { fg = "#ec6a88", bg = "#ec6a88" }
marker_selected = { fg = "#e1c697", bg = "#e1c697" }

count_copied = { fg = "#292a37", bg = "#3fdaa4" }
count_cut = { fg = "#292a37", bg = "#ec6a88" }
count_selected = { fg = "#292a37", bg = "#e1c697" }

border_style = { fg = "#3fc6de" }

[tabs]
active = { fg = "#292a37", bg = "#3fc6de"}
inactive = { fg = "#3fc6de", bg = #343545" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#292a37", bg = "#3fc6de", bold = true }
normal_alt = { fg = "#3fc6de", bg = "#3c3e51" }

select_alt = { fg = "#be95ff", bg = "#3c3e51" }
select_main = { fg = "#292a37", bg = "#be95ff", bold = true }

unset_main = { fg = "#292a37", bg = "#ec6a88", bold = true }
unset_alt = { fg = "#ec6a88", bg = "#3c3e51" }

[status]
perm_exec = { fg = "#3fdaa4" }
perm_read = { fg = "#e1c697" }
perm_sep = { fg = "#ff7eb6" }
perm_type = { fg = "#3fc6de" }
perm_write = { fg = "#ec6a88" }

progress_error = { fg = "#ec6a88", bg = "#292a37" }
progress_label = { fg = "#c0cbe3", bg = "#292a37" }
progress_normal = { fg = "#c0cbe3", bg = "#292a37" }

[pick]
active = { fg = "#be95ff" }
border = { fg = "#3fc6de" }
inactive = { fg = "#c0cbe3" }

[task]
title = { fg = "#3fc6de" }
border = { fg = "#3fc6de" }
hovered = { fg = "#c0cbe3", bg = "#3c3e51" }

[input]
border = { fg = "#3fc6de" }
selected = { bg = "#3c3e51" }

[help]
desc = { fg = "#c0cbe3" }
on = { fg = "#ff7eb6" }
run = { fg = "#be95ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3c3e51", bg = "#c0cbe3" }

[which]
mask = { bg = "#3c3e51" }
desc = { fg = "#c0cbe3" }
cand = { fg = "#ff7eb6" }
rest = { fg = "#8b8da9" }

separator_style = { fg = "#50526b" }

[notify]
title_info = { fg = "#ff7eb6" }
title_warn = { fg = "#e1c697" }
title_error = { fg = "#ec6a88" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#ff7eb6" },
  { mime = "{audio, video}/*", fg = "#e1c697" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#3fdaa4" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3fc6de" },
  { mime = "*", fg = "#c0cbe3" },
]

