[mgr]
cwd = { fg = "#93e0e3" }

find_keyword = { bold = true, fg = "#e0cf9f" }
find_position = { fg = "#dc8cc3" }

marker_copied = { fg = "#5f7f5f", bg = "#5f7f5f" }
marker_cut = { fg = "#dca3a3", bg = "#dca3a3" }
marker_selected = { fg = "#e0cf9f", bg = "#e0cf9f" }

count_copied = { fg = "#383838", bg = "#5f7f5f" }
count_cut = { fg = "#383838", bg = "#dca3a3" }
count_selected = { fg = "#383838", bg = "#e0cf9f" }

border_style = { fg = "#7cb8bb" }

[tabs]
active = { fg = "#383838", bg = "#7cb8bb"}
inactive = { fg = "#7cb8bb", bg = "#404040" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#383838", bg = "#7cb8bb", bold = true }
normal_alt = { fg = "#7cb8bb", bg = "#606060" }

select_alt = { fg = "#dc8cc3", bg = "#606060" }
select_main = { fg = "#383838", bg = "#dc8cc3", bold = true }

unset_main = { fg = "#383838", bg = "#dca3a3", bold = true }
unset_alt = { fg = "#dca3a3", bg = "#606060" }

[status]
perm_exec = { fg = "#5f7f5f" }
perm_read = { fg = "#e0cf9f" }
perm_sep = { fg = "#93e0e3" }
perm_type = { fg = "#7cb8bb" }
perm_write = { fg = "#dca3a3" }

progress_error = { fg = "#dca3a3", bg = "#383838" }
progress_label = { fg = "#dcdccc", bg = "#383838" }
progress_normal = { fg = "#dcdccc", bg = "#383838" }

[pick]
active = { fg = "#dc8cc3" }
border = { fg = "#7cb8bb" }
inactive = { fg = "#dcdccc" }

[task]
title = { fg = "#7cb8bb" }
border = { fg = "#7cb8bb" }
hovered = { fg = "#dcdccc", bg = "#606060" }

[input]
border = { fg = "#7cb8bb" }
selected = { bg = "#606060" }

[help]
desc = { fg = "#dcdccc" }
on = { fg = "#93e0e3" }
run = { fg = "#dc8cc3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#606060", bg = "#dcdccc" }

[which]
mask = { bg = "#606060" }
desc = { fg = "#dcdccc" }
cand = { fg = "#93e0e3" }
rest = { fg = "#000000" }

separator_style = { fg = "#808080" }

[notify]
title_info = { fg = "#93e0e3" }
title_warn = { fg = "#e0cf9f" }
title_error = { fg = "#dca3a3" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#93e0e3" },
  { mime = "{audio, video}/*", fg = "#e0cf9f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5f7f5f" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#7cb8bb" },
  { mime = "*", fg = "#dcdccc" },
]

