[mgr]
cwd = { fg = "#6600ff" }

find_keyword = { bold = true, fg = "#20df6c" }
find_position = { fg = "#007fff" }

marker_copied = { fg = "#ff0066", bg = "#ff0066" }
marker_cut = { fg = "#ffa600", bg = "#ffa600" }
marker_selected = { fg = "#20df6c", bg = "#20df6c" }

count_copied = { fg = "#171517", bg = "#ff0066" }
count_cut = { fg = "#171517", bg = "#ffa600" }
count_selected = { fg = "#171517", bg = "#20df6c" }

border_style = { fg = "#00ffff" }

[tabs]
active = { fg = "#171517", bg = "#00ffff"}
inactive = { fg = "#00ffff", bg = "#1b181b" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#171517", bg = "#00ffff", bold = true }
normal_alt = { fg = "#00ffff", bg = "#1d1b1d" }

select_alt = { fg = "#007fff", bg = "#1d1b1d" }
select_main = { fg = "#171517", bg = "#007fff", bold = true }

unset_main = { fg = "#171517", bg = "#ffa600", bold = true }
unset_alt = { fg = "#ffa600", bg = "#1d1b1d" }

[status]
perm_exec = { fg = "#ff0066" }
perm_read = { fg = "#20df6c" }
perm_sep = { fg = "#6600ff" }
perm_type = { fg = "#00ffff" }
perm_write = { fg = "#ffa600" }

progress_error = { fg = "#ffa600", bg = "#171517" }
progress_label = { fg = "#f5f5f5", bg = "#171517" }
progress_normal = { fg = "#f5f5f5", bg = "#171517" }

[pick]
active = { fg = "#007fff" }
border = { fg = "#00ffff" }
inactive = { fg = "#f5f5f5" }

[task]
title = { fg = "#00ffff" }
border = { fg = "#00ffff" }
hovered = { fg = "#f5f5f5", bg = "#1d1b1d" }

[input]
border = { fg = "#00ffff" }
selected = { bg = "#1d1b1d" }

[help]
desc = { fg = "#f5f5f5" }
on = { fg = "#6600ff" }
run = { fg = "#007fff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#1d1b1d", bg = "#f5f5f5" }

[which]
mask = { bg = "#1d1b1d" }
desc = { fg = "#f5f5f5" }
cand = { fg = "#6600ff" }
rest = { fg = "#df206c" }

separator_style = { fg = "#e7dbdb" }

[notify]
title_info = { fg = "#6600ff" }
title_warn = { fg = "#20df6c" }
title_error = { fg = "#ffa600" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#6600ff" },
  { mime = "{audio, video}/*", fg = "#20df6c" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#ff0066" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#00ffff" },
  { mime = "*", fg = "#f5f5f5" },
]

