[mgr]
cwd = { fg = "#977d7c" }

find_keyword = { bold = true, fg = "#adb4b9" }
find_position = { fg = "#9198a3" }

marker_copied = { fg = "#977d7c", bg = "#977d7c" }
marker_cut = { fg = "#818591", bg = "#818591" }
marker_selected = { fg = "#adb4b9", bg = "#adb4b9" }

count_copied = { fg = "#041523", bg = "#977d7c" }
count_cut = { fg = "#041523", bg = "#818591" }
count_selected = { fg = "#041523", bg = "#adb4b9" }

border_style = { fg = "#977d7c" }

[tabs]
active = { fg = "#041523", bg = "#977d7c"}
inactive = { fg = "#977d7c", bg = "#122339" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#041523", bg = "#977d7c", bold = true }
normal_alt = { fg = "#977d7c", bg = "#003552" }

select_alt = { fg = "#9198a3", bg = "#003552" }
select_main = { fg = "#041523", bg = "#9198a3", bold = true }

unset_main = { fg = "#041523", bg = "#818591", bold = true }
unset_alt = { fg = "#818591", bg = "#003552" }

[status]
perm_exec = { fg = "#977d7c" }
perm_read = { fg = "#adb4b9" }
perm_sep = { fg = "#977d7c" }
perm_type = { fg = "#977d7c" }
perm_write = { fg = "#818591" }

progress_error = { fg = "#818591", bg = "#041523" }
progress_label = { fg = "#5b778c", bg = "#041523" }
progress_normal = { fg = "#5b778c", bg = "#041523" }

[pick]
active = { fg = "#9198a3" }
border = { fg = "#977d7c" }
inactive = { fg = "#5b778c" }

[task]
title = { fg = "#977d7c" }
border = { fg = "#977d7c" }
hovered = { fg = "#5b778c", bg = "#003552" }

[input]
border = { fg = "#977d7c" }
selected = { bg = "#003552" }

[help]
desc = { fg = "#5b778c" }
on = { fg = "#977d7c" }
run = { fg = "#9198a3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#003552", bg = "#5b778c" }

[which]
mask = { bg = "#003552" }
desc = { fg = "#5b778c" }
cand = { fg = "#977d7c" }
rest = { fg = "#977d7c" }

separator_style = { fg = "#6b6977" }

[notify]
title_info = { fg = "#977d7c" }
title_warn = { fg = "#adb4b9" }
title_error = { fg = "#818591" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#977d7c" },
  { mime = "{audio, video}/*", fg = "#adb4b9" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#977d7c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#977d7c" },
  { mime = "*", fg = "#5b778c" },
]

