[mgr]
cwd = { fg = "#226f68" }

find_keyword = { bold = true, fg = "#4f9062" }
find_position = { fg = "#716cae" }

marker_copied = { fg = "#6562a8", bg = "#6562a8" }
marker_cut = { fg = "#777abc", bg = "#777abc" }
marker_selected = { fg = "#4f9062", bg = "#4f9062" }

count_copied = { fg = "#22273b", bg = "#6562a8" }
count_cut = { fg = "#22273b", bg = "#777abc" }
count_selected = { fg = "#22273b", bg = "#4f9062" }

border_style = { fg = "#4d6bb6" }

[tabs]
active = { fg = "#22273b", bg = "#4d6bb6"}
inactive = { fg = "#4d6bb6", bg = #414f60" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#22273b", bg = "#4d6bb6", bold = true }
normal_alt = { fg = "#4d6bb6", bg = "#5a8380" }

select_alt = { fg = "#716cae", bg = "#5a8380" }
select_main = { fg = "#22273b", bg = "#716cae", bold = true }

unset_main = { fg = "#22273b", bg = "#777abc", bold = true }
unset_alt = { fg = "#777abc", bg = "#5a8380" }

[status]
perm_exec = { fg = "#6562a8" }
perm_read = { fg = "#4f9062" }
perm_sep = { fg = "#226f68" }
perm_type = { fg = "#4d6bb6" }
perm_write = { fg = "#777abc" }

progress_error = { fg = "#777abc", bg = "#22273b" }
progress_label = { fg = "#a4a6a9", bg = "#22273b" }
progress_normal = { fg = "#a4a6a9", bg = "#22273b" }

[pick]
active = { fg = "#716cae" }
border = { fg = "#4d6bb6" }
inactive = { fg = "#a4a6a9" }

[task]
title = { fg = "#4d6bb6" }
border = { fg = "#4d6bb6" }
hovered = { fg = "#a4a6a9", bg = "#5a8380" }

[input]
border = { fg = "#4d6bb6" }
selected = { bg = "#5a8380" }

[help]
desc = { fg = "#a4a6a9" }
on = { fg = "#226f68" }
run = { fg = "#716cae" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5a8380", bg = "#a4a6a9" }

[which]
mask = { bg = "#5a8380" }
desc = { fg = "#a4a6a9" }
cand = { fg = "#226f68" }
rest = { fg = "#8c70a7" }

separator_style = { fg = "#87888b" }

[notify]
title_info = { fg = "#226f68" }
title_warn = { fg = "#4f9062" }
title_error = { fg = "#777abc" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#226f68" },
  { mime = "{audio, video}/*", fg = "#4f9062" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6562a8" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#4d6bb6" },
  { mime = "*", fg = "#a4a6a9" },
]

