[mgr]
cwd = { fg = "#8f3f71" }

find_keyword = { bold = true, fg = "#ffcc1b" }
find_position = { fg = "#fabd2f" }

marker_copied = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut = { fg = "#c03900", bg = "#c03900" }
marker_selected = { fg = "#ffcc1b", bg = "#ffcc1b" }

count_copied = { fg = "#282828", bg = "#b8bb26" }
count_cut = { fg = "#282828", bg = "#c03900" }
count_selected = { fg = "#282828", bg = "#ffcc1b" }

border_style = { fg = "#458588" }

[tabs]
active = { fg = "#282828", bg = "#458588"}
inactive = { fg = "#458588", bg = "#212f3d" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#282828", bg = "#458588", bold = true }
normal_alt = { fg = "#458588", bg = "#504945" }

select_alt = { fg = "#fabd2f", bg = "#504945" }
select_main = { fg = "#282828", bg = "#fabd2f", bold = true }

unset_main = { fg = "#282828", bg = "#c03900", bold = true }
unset_alt = { fg = "#c03900", bg = "#504945" }

[status]
perm_exec = { fg = "#b8bb26" }
perm_read = { fg = "#ffcc1b" }
perm_sep = { fg = "#8f3f71" }
perm_type = { fg = "#458588" }
perm_write = { fg = "#c03900" }

progress_error = { fg = "#c03900", bg = "#282828" }
progress_label = { fg = "#d5c7a1", bg = "#282828" }
progress_normal = { fg = "#d5c7a1", bg = "#282828" }

[pick]
active = { fg = "#fabd2f" }
border = { fg = "#458588" }
inactive = { fg = "#d5c7a1" }

[task]
title = { fg = "#458588" }
border = { fg = "#458588" }
hovered = { fg = "#d5c7a1", bg = "#504945" }

[input]
border = { fg = "#458588" }
selected = { bg = "#504945" }

[help]
desc = { fg = "#d5c7a1" }
on = { fg = "#8f3f71" }
run = { fg = "#fabd2f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#504945", bg = "#d5c7a1" }

[which]
mask = { bg = "#504945" }
desc = { fg = "#d5c7a1" }
cand = { fg = "#8f3f71" }
rest = { fg = "#b59b4d" }

separator_style = { fg = "#bdae93" }

[notify]
title_info = { fg = "#8f3f71" }
title_warn = { fg = "#ffcc1b" }
title_error = { fg = "#c03900" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8f3f71" },
  { mime = "{audio, video}/*", fg = "#ffcc1b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#b8bb26" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#458588" },
  { mime = "*", fg = "#d5c7a1" },
]

