[mgr]
cwd = { fg = "#2d9574" }

find_keyword = { bold = true, fg = "#b1951d" }
find_position = { fg = "#a31db1" }

marker_copied = { fg = "#67b11d", bg = "#67b11d" }
marker_cut = { fg = "#f2241f", bg = "#f2241f" }
marker_selected = { fg = "#b1951d", bg = "#b1951d" }

count_copied = { fg = "#1f2022", bg = "#67b11d" }
count_cut = { fg = "#1f2022", bg = "#f2241f" }
count_selected = { fg = "#1f2022", bg = "#b1951d" }

border_style = { fg = "#4f97d7" }

[tabs]
active = { fg = "#1f2022", bg = "#4f97d7"}
inactive = { fg = "#4f97d7", bg = #282828" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1f2022", bg = "#4f97d7", bold = true }
normal_alt = { fg = "#4f97d7", bg = "#444155" }

select_alt = { fg = "#a31db1", bg = "#444155" }
select_main = { fg = "#1f2022", bg = "#a31db1", bold = true }

unset_main = { fg = "#1f2022", bg = "#f2241f", bold = true }
unset_alt = { fg = "#f2241f", bg = "#444155" }

[status]
perm_exec = { fg = "#67b11d" }
perm_read = { fg = "#b1951d" }
perm_sep = { fg = "#2d9574" }
perm_type = { fg = "#4f97d7" }
perm_write = { fg = "#f2241f" }

progress_error = { fg = "#f2241f", bg = "#1f2022" }
progress_label = { fg = "#a3a3a3", bg = "#1f2022" }
progress_normal = { fg = "#a3a3a3", bg = "#1f2022" }

[pick]
active = { fg = "#a31db1" }
border = { fg = "#4f97d7" }
inactive = { fg = "#a3a3a3" }

[task]
title = { fg = "#4f97d7" }
border = { fg = "#4f97d7" }
hovered = { fg = "#a3a3a3", bg = "#444155" }

[input]
border = { fg = "#4f97d7" }
selected = { bg = "#444155" }

[help]
desc = { fg = "#a3a3a3" }
on = { fg = "#2d9574" }
run = { fg = "#a31db1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#444155", bg = "#a3a3a3" }

[which]
mask = { bg = "#444155" }
desc = { fg = "#a3a3a3" }
cand = { fg = "#2d9574" }
rest = { fg = "#b03060" }

separator_style = { fg = "#b8b8b8" }

[notify]
title_info = { fg = "#2d9574" }
title_warn = { fg = "#b1951d" }
title_error = { fg = "#f2241f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2d9574" },
  { mime = "{audio, video}/*", fg = "#b1951d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#67b11d" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#4f97d7" },
  { mime = "*", fg = "#a3a3a3" },
]

