[mgr]
cwd = { fg = "#72b9bf" }

find_keyword = { bold = true, fg = "#fbd461" }
find_position = { fg = "#9989cc" }

marker_copied = { fg = "#99bf52", bg = "#99bf52" }
marker_cut = { fg = "#d07346", bg = "#d07346" }
marker_selected = { fg = "#fbd461", bg = "#fbd461" }

count_copied = { fg = "#061229", bg = "#99bf52" }
count_cut = { fg = "#061229", bg = "#d07346" }
count_selected = { fg = "#061229", bg = "#fbd461" }

border_style = { fg = "#5299bf" }

[tabs]
active = { fg = "#061229", bg = "#5299bf"}
inactive = { fg = "#5299bf", bg = #2a3448" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#061229", bg = "#5299bf", bold = true }
normal_alt = { fg = "#5299bf", bg = "#4d5666" }

select_alt = { fg = "#9989cc", bg = "#4d5666" }
select_main = { fg = "#061229", bg = "#9989cc", bold = true }

unset_main = { fg = "#061229", bg = "#d07346", bold = true }
unset_alt = { fg = "#d07346", bg = "#4d5666" }

[status]
perm_exec = { fg = "#99bf52" }
perm_read = { fg = "#fbd461" }
perm_sep = { fg = "#72b9bf" }
perm_type = { fg = "#5299bf" }
perm_write = { fg = "#d07346" }

progress_error = { fg = "#d07346", bg = "#061229" }
progress_label = { fg = "#b8bbc2", bg = "#061229" }
progress_normal = { fg = "#b8bbc2", bg = "#061229" }

[pick]
active = { fg = "#9989cc" }
border = { fg = "#5299bf" }
inactive = { fg = "#b8bbc2" }

[task]
title = { fg = "#5299bf" }
border = { fg = "#5299bf" }
hovered = { fg = "#b8bbc2", bg = "#4d5666" }

[input]
border = { fg = "#5299bf" }
selected = { bg = "#4d5666" }

[help]
desc = { fg = "#b8bbc2" }
on = { fg = "#72b9bf" }
run = { fg = "#9989cc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4d5666", bg = "#b8bbc2" }

[which]
mask = { bg = "#4d5666" }
desc = { fg = "#b8bbc2" }
cand = { fg = "#72b9bf" }
rest = { fg = "#b08060" }

separator_style = { fg = "#9a99a3" }

[notify]
title_info = { fg = "#72b9bf" }
title_warn = { fg = "#fbd461" }
title_error = { fg = "#d07346" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#72b9bf" },
  { mime = "{audio, video}/*", fg = "#fbd461" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#99bf52" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#5299bf" },
  { mime = "*", fg = "#b8bbc2" },
]

