[mgr]
cwd = { fg = "#4b8093" }

find_keyword = { bold = true, fg = "#f79a0e" }
find_position = { fg = "#96609e" }

marker_copied = { fg = "#538947", bg = "#538947" }
marker_cut = { fg = "#ab4642", bg = "#ab4642" }
marker_selected = { fg = "#f79a0e", bg = "#f79a0e" }

count_copied = { fg = "#f8f8f8", bg = "#538947" }
count_cut = { fg = "#f8f8f8", bg = "#ab4642" }
count_selected = { fg = "#f8f8f8", bg = "#f79a0e" }

border_style = { fg = "#7cafc2" }

[tabs]
active = { fg = "#f8f8f8", bg = "#7cafc2"}
inactive = { fg = "#7cafc2", bg = "#e8e8e8" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f8f8f8", bg = "#7cafc2", bold = true }
normal_alt = { fg = "#7cafc2", bg = "#d8d8d8" }

select_alt = { fg = "#96609e", bg = "#d8d8d8" }
select_main = { fg = "#f8f8f8", bg = "#96609e", bold = true }

unset_main = { fg = "#f8f8f8", bg = "#ab4642", bold = true }
unset_alt = { fg = "#ab4642", bg = "#d8d8d8" }

[status]
perm_exec = { fg = "#538947" }
perm_read = { fg = "#f79a0e" }
perm_sep = { fg = "#4b8093" }
perm_type = { fg = "#7cafc2" }
perm_write = { fg = "#ab4642" }

progress_error = { fg = "#ab4642", bg = "#f8f8f8" }
progress_label = { fg = "#383838", bg = "#f8f8f8" }
progress_normal = { fg = "#383838", bg = "#f8f8f8" }

[pick]
active = { fg = "#96609e" }
border = { fg = "#7cafc2" }
inactive = { fg = "#383838" }

[task]
title = { fg = "#7cafc2" }
border = { fg = "#7cafc2" }
hovered = { fg = "#383838", bg = "#d8d8d8" }

[input]
border = { fg = "#7cafc2" }
selected = { bg = "#d8d8d8" }

[help]
desc = { fg = "#383838" }
on = { fg = "#4b8093" }
run = { fg = "#96609e" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d8d8d8", bg = "#383838" }

[which]
mask = { bg = "#d8d8d8" }
desc = { fg = "#383838" }
cand = { fg = "#4b8093" }
rest = { fg = "#a16946" }

separator_style = { fg = "#585858" }

[notify]
title_info = { fg = "#4b8093" }
title_warn = { fg = "#f79a0e" }
title_error = { fg = "#ab4642" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4b8093" },
  { mime = "{audio, video}/*", fg = "#f79a0e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#538947" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#7cafc2" },
  { mime = "*", fg = "#383838" },
]

