[mgr]
cwd = { fg = "#3ddbd9" }

find_keyword = { bold = true, fg = "#ff6f00" }
find_position = { fg = "#be95ff" }

marker_copied = { fg = "#42be65", bg = "#42be65" }
marker_cut = { fg = "#ee5396", bg = "#ee5396" }
marker_selected = { fg = "#ff6f00", bg = "#ff6f00" }

count_copied = { fg = "#161616", bg = "#42be65" }
count_cut = { fg = "#161616", bg = "#ee5396" }
count_selected = { fg = "#161616", bg = "#ff6f00" }

border_style = { fg = "#33b1ff" }

[tabs]
active = { fg = "#161616", bg = "#33b1ff"}
inactive = { fg = "#33b1ff", bg = "#262626" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#161616", bg = "#33b1ff", bold = true }
normal_alt = { fg = "#33b1ff", bg = "#393939" }

select_alt = { fg = "#be95ff", bg = "#393939" }
select_main = { fg = "#161616", bg = "#be95ff", bold = true }

unset_main = { fg = "#161616", bg = "#ee5396", bold = true }
unset_alt = { fg = "#ee5396", bg = "#393939" }

[status]
perm_exec = { fg = "#42be65" }
perm_read = { fg = "#ff6f00" }
perm_sep = { fg = "#3ddbd9" }
perm_type = { fg = "#33b1ff" }
perm_write = { fg = "#ee5396" }

progress_error = { fg = "#ee5396", bg = "#161616" }
progress_label = { fg = "#f2f4f8", bg = "#161616" }
progress_normal = { fg = "#f2f4f8", bg = "#161616" }

[pick]
active = { fg = "#be95ff" }
border = { fg = "#33b1ff" }
inactive = { fg = "#f2f4f8" }

[task]
title = { fg = "#33b1ff" }
border = { fg = "#33b1ff" }
hovered = { fg = "#f2f4f8", bg = "#393939" }

[input]
border = { fg = "#33b1ff" }
selected = { bg = "#393939" }

[help]
desc = { fg = "#f2f4f8" }
on = { fg = "#3ddbd9" }
run = { fg = "#be95ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#393939", bg = "#f2f4f8" }

[which]
mask = { bg = "#393939" }
desc = { fg = "#f2f4f8" }
cand = { fg = "#3ddbd9" }
rest = { fg = "#82cfff" }

separator_style = { fg = "#dde1e6" }

[notify]
title_info = { fg = "#3ddbd9" }
title_warn = { fg = "#ff6f00" }
title_error = { fg = "#ee5396" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3ddbd9" },
  { mime = "{audio, video}/*", fg = "#ff6f00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#42be65" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#33b1ff" },
  { mime = "*", fg = "#f2f4f8" },
]

