[mgr]
cwd = { fg = "#64b5a7" }

find_keyword = { bold = true, fg = "#b3684f" }
find_position = { fg = "#c173d1" }

marker_copied = { fg = "#76a85d", bg = "#76a85d" }
marker_cut = { fg = "#de5d6e", bg = "#de5d6e" }
marker_selected = { fg = "#b3684f", bg = "#b3684f" }

count_copied = { fg = "#ffffff", bg = "#76a85d" }
count_cut = { fg = "#ffffff", bg = "#de5d6e" }
count_selected = { fg = "#ffffff", bg = "#b3684f" }

border_style = { fg = "#5890f8" }

[tabs]
active = { fg = "#ffffff", bg = "#5890f8"}
inactive = { fg = "#5890f8", bg = #c8c8c8" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#5890f8", bold = true }
normal_alt = { fg = "#5890f8", bg = "#888888" }

select_alt = { fg = "#c173d1", bg = "#888888" }
select_main = { fg = "#ffffff", bg = "#c173d1", bold = true }

unset_main = { fg = "#ffffff", bg = "#de5d6e", bold = true }
unset_alt = { fg = "#de5d6e", bg = "#888888" }

[status]
perm_exec = { fg = "#76a85d" }
perm_read = { fg = "#b3684f" }
perm_sep = { fg = "#64b5a7" }
perm_type = { fg = "#5890f8" }
perm_write = { fg = "#de5d6e" }

progress_error = { fg = "#de5d6e", bg = "#ffffff" }
progress_label = { fg = "#181818", bg = "#ffffff" }
progress_normal = { fg = "#181818", bg = "#ffffff" }

[pick]
active = { fg = "#c173d1" }
border = { fg = "#5890f8" }
inactive = { fg = "#181818" }

[task]
title = { fg = "#5890f8" }
border = { fg = "#5890f8" }
hovered = { fg = "#181818", bg = "#888888" }

[input]
border = { fg = "#5890f8" }
selected = { bg = "#888888" }

[help]
desc = { fg = "#181818" }
on = { fg = "#64b5a7" }
run = { fg = "#c173d1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#888888", bg = "#181818" }

[which]
mask = { bg = "#888888" }
desc = { fg = "#181818" }
cand = { fg = "#64b5a7" }
rest = { fg = "#b3684f" }

separator_style = { fg = "#282828" }

[notify]
title_info = { fg = "#64b5a7" }
title_warn = { fg = "#b3684f" }
title_error = { fg = "#de5d6e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#64b5a7" },
  { mime = "{audio, video}/*", fg = "#b3684f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#76a85d" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#5890f8" },
  { mime = "*", fg = "#181818" },
]

