[mgr]
cwd = { fg = "#85cebc" }

find_keyword = { bold = true, fg = "#ffd204" }
find_position = { fg = "#98005d" }

marker_copied = { fg = "#00853e", bg = "#00853e" }
marker_cut = { fg = "#ee2e24", bg = "#ee2e24" }
marker_selected = { fg = "#ffd204", bg = "#ffd204" }

count_copied = { fg = "#231f20", bg = "#00853e" }
count_cut = { fg = "#231f20", bg = "#ee2e24" }
count_selected = { fg = "#231f20", bg = "#ffd204" }

border_style = { fg = "#009ddc" }

[tabs]
active = { fg = "#231f20", bg = "#009ddc"}
inactive = { fg = "#009ddc", bg = #1c3f95" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#231f20", bg = "#009ddc", bold = true }
normal_alt = { fg = "#009ddc", bg = "#5a5758" }

select_alt = { fg = "#98005d", bg = "#5a5758" }
select_main = { fg = "#231f20", bg = "#98005d", bold = true }

unset_main = { fg = "#231f20", bg = "#ee2e24", bold = true }
unset_alt = { fg = "#ee2e24", bg = "#5a5758" }

[status]
perm_exec = { fg = "#00853e" }
perm_read = { fg = "#ffd204" }
perm_sep = { fg = "#85cebc" }
perm_type = { fg = "#009ddc" }
perm_write = { fg = "#ee2e24" }

progress_error = { fg = "#ee2e24", bg = "#231f20" }
progress_label = { fg = "#d9d8d8", bg = "#231f20" }
progress_normal = { fg = "#d9d8d8", bg = "#231f20" }

[pick]
active = { fg = "#98005d" }
border = { fg = "#009ddc" }
inactive = { fg = "#d9d8d8" }

[task]
title = { fg = "#009ddc" }
border = { fg = "#009ddc" }
hovered = { fg = "#d9d8d8", bg = "#5a5758" }

[input]
border = { fg = "#009ddc" }
selected = { bg = "#5a5758" }

[help]
desc = { fg = "#d9d8d8" }
on = { fg = "#85cebc" }
run = { fg = "#98005d" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5a5758", bg = "#d9d8d8" }

[which]
mask = { bg = "#5a5758" }
desc = { fg = "#d9d8d8" }
cand = { fg = "#85cebc" }
rest = { fg = "#b06110" }

separator_style = { fg = "#959ca1" }

[notify]
title_info = { fg = "#85cebc" }
title_warn = { fg = "#ffd204" }
title_error = { fg = "#ee2e24" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#85cebc" },
  { mime = "{audio, video}/*", fg = "#ffd204" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00853e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#009ddc" },
  { mime = "*", fg = "#d9d8d8" },
]

