[mgr]
cwd = { fg = "#0f9cfd" }

find_keyword = { bold = true, fg = "#f7e203" }
find_position = { fg = "#611fce" }

marker_copied = { fg = "#47f74c", bg = "#47f74c" }
marker_cut = { fg = "#fe3e31", bg = "#fe3e31" }
marker_selected = { fg = "#f7e203", bg = "#f7e203" }

count_copied = { fg = "#f1ecf1", bg = "#47f74c" }
count_cut = { fg = "#f1ecf1", bg = "#fe3e31" }
count_selected = { fg = "#f1ecf1", bg = "#f7e203" }

border_style = { fg = "#2931df" }

[tabs]
active = { fg = "#f1ecf1", bg = "#2931df"}
inactive = { fg = "#2931df", bg = "#e0dee0" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f1ecf1", bg = "#2931df", bold = true }
normal_alt = { fg = "#2931df", bg = "#d8d5d5" }

select_alt = { fg = "#611fce", bg = "#d8d5d5" }
select_main = { fg = "#f1ecf1", bg = "#611fce", bold = true }

unset_main = { fg = "#f1ecf1", bg = "#fe3e31", bold = true }
unset_alt = { fg = "#fe3e31", bg = "#d8d5d5" }

[status]
perm_exec = { fg = "#47f74c" }
perm_read = { fg = "#f7e203" }
perm_sep = { fg = "#0f9cfd" }
perm_type = { fg = "#2931df" }
perm_write = { fg = "#fe3e31" }

progress_error = { fg = "#fe3e31", bg = "#f1ecf1" }
progress_label = { fg = "#515151", bg = "#f1ecf1" }
progress_normal = { fg = "#515151", bg = "#f1ecf1" }

[pick]
active = { fg = "#611fce" }
border = { fg = "#2931df" }
inactive = { fg = "#515151" }

[task]
title = { fg = "#2931df" }
border = { fg = "#2931df" }
hovered = { fg = "#515151", bg = "#d8d5d5" }

[input]
border = { fg = "#2931df" }
selected = { bg = "#d8d5d5" }

[help]
desc = { fg = "#515151" }
on = { fg = "#0f9cfd" }
run = { fg = "#611fce" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d8d5d5", bg = "#515151" }

[which]
mask = { bg = "#d8d5d5" }
desc = { fg = "#515151" }
cand = { fg = "#0f9cfd" }
rest = { fg = "#b16f40" }

separator_style = { fg = "#979598" }

[notify]
title_info = { fg = "#0f9cfd" }
title_warn = { fg = "#f7e203" }
title_error = { fg = "#fe3e31" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0f9cfd" },
  { mime = "{audio, video}/*", fg = "#f7e203" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#47f74c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#2931df" },
  { mime = "*", fg = "#515151" },
]

