[mgr]
cwd = { fg = "#4bb1a7" }

find_keyword = { bold = true, fg = "#c3ba63" }
find_position = { fg = "#b888e2" }

marker_copied = { fg = "#84b97c", bg = "#84b97c" }
marker_cut = { fg = "#dc657d", bg = "#dc657d" }
marker_selected = { fg = "#c3ba63", bg = "#c3ba63" }

count_copied = { fg = "#191919", bg = "#84b97c" }
count_cut = { fg = "#191919", bg = "#dc657d" }
count_selected = { fg = "#191919", bg = "#c3ba63" }

border_style = { fg = "#639ee4" }

[tabs]
active = { fg = "#191919", bg = "#639ee4"}
inactive = { fg = "#639ee4", bg = #202020" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#191919", bg = "#639ee4", bold = true }
normal_alt = { fg = "#639ee4", bg = "#303030" }

select_alt = { fg = "#b888e2", bg = "#303030" }
select_main = { fg = "#191919", bg = "#b888e2", bold = true }

unset_main = { fg = "#191919", bg = "#dc657d", bold = true }
unset_alt = { fg = "#dc657d", bg = "#303030" }

[status]
perm_exec = { fg = "#84b97c" }
perm_read = { fg = "#c3ba63" }
perm_sep = { fg = "#4bb1a7" }
perm_type = { fg = "#639ee4" }
perm_write = { fg = "#dc657d" }

progress_error = { fg = "#dc657d", bg = "#191919" }
progress_label = { fg = "#a7a7a7", bg = "#191919" }
progress_normal = { fg = "#a7a7a7", bg = "#191919" }

[pick]
active = { fg = "#b888e2" }
border = { fg = "#639ee4" }
inactive = { fg = "#a7a7a7" }

[task]
title = { fg = "#639ee4" }
border = { fg = "#639ee4" }
hovered = { fg = "#a7a7a7", bg = "#303030" }

[input]
border = { fg = "#639ee4" }
selected = { bg = "#303030" }

[help]
desc = { fg = "#a7a7a7" }
on = { fg = "#4bb1a7" }
run = { fg = "#b888e2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#303030", bg = "#a7a7a7" }

[which]
mask = { bg = "#303030" }
desc = { fg = "#a7a7a7" }
cand = { fg = "#4bb1a7" }
rest = { fg = "#b888e2" }

separator_style = { fg = "#505050" }

[notify]
title_info = { fg = "#4bb1a7" }
title_warn = { fg = "#c3ba63" }
title_error = { fg = "#dc657d" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4bb1a7" },
  { mime = "{audio, video}/*", fg = "#c3ba63" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#84b97c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#639ee4" },
  { mime = "*", fg = "#a7a7a7" },
]

