[mgr]
cwd = { fg = "#80ff80" }

find_keyword = { bold = true, fg = "#91ccff" }
find_position = { fg = "#0099ff" }

marker_copied = { fg = "#80ff80", bg = "#80ff80" }
marker_cut = { fg = "#fffab1", bg = "#fffab1" }
marker_selected = { fg = "#91ccff", bg = "#91ccff" }

count_copied = { fg = "#141f2e", bg = "#80ff80" }
count_cut = { fg = "#141f2e", bg = "#fffab1" }
count_selected = { fg = "#141f2e", bg = "#91ccff" }

border_style = { fg = "#a2cff5" }

[tabs]
active = { fg = "#141f2e", bg = "#a2cff5"}
inactive = { fg = "#a2cff5", bg = "#1e5c1e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#141f2e", bg = "#a2cff5", bold = true }
normal_alt = { fg = "#a2cff5", bg = "#273e5c" }

select_alt = { fg = "#0099ff", bg = "#273e5c" }
select_main = { fg = "#141f2e", bg = "#0099ff", bold = true }

unset_main = { fg = "#141f2e", bg = "#fffab1", bold = true }
unset_alt = { fg = "#fffab1", bg = "#273e5c" }

[status]
perm_exec = { fg = "#80ff80" }
perm_read = { fg = "#91ccff" }
perm_sep = { fg = "#80ff80" }
perm_type = { fg = "#a2cff5" }
perm_write = { fg = "#fffab1" }

progress_error = { fg = "#fffab1", bg = "#141f2e" }
progress_label = { fg = "#ffcc33", bg = "#141f2e" }
progress_normal = { fg = "#ffcc33", bg = "#141f2e" }

[pick]
active = { fg = "#0099ff" }
border = { fg = "#a2cff5" }
inactive = { fg = "#ffcc33" }

[task]
title = { fg = "#a2cff5" }
border = { fg = "#a2cff5" }
hovered = { fg = "#ffcc33", bg = "#273e5c" }

[input]
border = { fg = "#a2cff5" }
selected = { bg = "#273e5c" }

[help]
desc = { fg = "#ffcc33" }
on = { fg = "#80ff80" }
run = { fg = "#0099ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#273e5c", bg = "#ffcc33" }

[which]
mask = { bg = "#273e5c" }
desc = { fg = "#ffcc33" }
cand = { fg = "#80ff80" }
rest = { fg = "#e7e7e7" }

separator_style = { fg = "#1e5c1e" }

[notify]
title_info = { fg = "#80ff80" }
title_warn = { fg = "#91ccff" }
title_error = { fg = "#fffab1" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#80ff80" },
  { mime = "{audio, video}/*", fg = "#91ccff" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#80ff80" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#a2cff5" },
  { mime = "*", fg = "#ffcc33" },
]

