[mgr]
cwd = { fg = "#7dcfff" }

find_keyword = { bold = true, fg = "#e0af68" }
find_position = { fg = "#bb9af7" }

marker_copied = { fg = "#41a6b5", bg = "#41a6b5" }
marker_cut = { fg = "#f7768e", bg = "#f7768e" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

count_copied = { fg = "#16161e", bg = "#41a6b5" }
count_cut = { fg = "#16161e", bg = "#f7768e" }
count_selected = { fg = "#16161e", bg = "#e0af68" }

border_style = { fg = "#7aa2f7" }

[tabs]
active = { fg = "#16161e", bg = "#7aa2f7"}
inactive = { fg = "#7aa2f7", bg = "#1a1b26" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#16161e", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#2f3549" }

select_alt = { fg = "#bb9af7", bg = "#2f3549" }
select_main = { fg = "#16161e", bg = "#bb9af7", bold = true }

unset_main = { fg = "#16161e", bg = "#f7768e", bold = true }
unset_alt = { fg = "#f7768e", bg = "#2f3549" }

[status]
perm_exec = { fg = "#41a6b5" }
perm_read = { fg = "#e0af68" }
perm_sep = { fg = "#7dcfff" }
perm_type = { fg = "#7aa2f7" }
perm_write = { fg = "#f7768e" }

progress_error = { fg = "#f7768e", bg = "#16161e" }
progress_label = { fg = "#787c99", bg = "#16161e" }
progress_normal = { fg = "#787c99", bg = "#16161e" }

[pick]
active = { fg = "#bb9af7" }
border = { fg = "#7aa2f7" }
inactive = { fg = "#787c99" }

[task]
title = { fg = "#7aa2f7" }
border = { fg = "#7aa2f7" }
hovered = { fg = "#787c99", bg = "#2f3549" }

[input]
border = { fg = "#7aa2f7" }
selected = { bg = "#2f3549" }

[help]
desc = { fg = "#787c99" }
on = { fg = "#7dcfff" }
run = { fg = "#bb9af7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2f3549", bg = "#787c99" }

[which]
mask = { bg = "#2f3549" }
desc = { fg = "#787c99" }
cand = { fg = "#7dcfff" }
rest = { fg = "#d18616" }

separator_style = { fg = "#787c99" }

[notify]
title_info = { fg = "#7dcfff" }
title_warn = { fg = "#e0af68" }
title_error = { fg = "#f7768e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#7dcfff" },
  { mime = "{audio, video}/*", fg = "#e0af68" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#41a6b5" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#7aa2f7" },
  { mime = "*", fg = "#787c99" },
]

