[mgr]
cwd = { fg = "#83c092" }

find_keyword = { bold = true, fg = "#dbbc7f" }
find_position = { fg = "#d699b6" }

marker_copied = { fg = "#a7c080", bg = "#a7c080" }
marker_cut = { fg = "#e67e80", bg = "#e67e80" }
marker_selected = { fg = "#dbbc7f", bg = "#dbbc7f" }

count_copied = { fg = "#2d353b", bg = "#a7c080" }
count_cut = { fg = "#2d353b", bg = "#e67e80" }
count_selected = { fg = "#2d353b", bg = "#dbbc7f" }

border_style = { fg = "#7fbbb3" }

[tabs]
active = { fg = "#2d353b", bg = "#7fbbb3"}
inactive = { fg = "#7fbbb3", bg = #343f44" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2d353b", bg = "#7fbbb3", bold = true }
normal_alt = { fg = "#7fbbb3", bg = "#475258" }

select_alt = { fg = "#d699b6", bg = "#475258" }
select_main = { fg = "#2d353b", bg = "#d699b6", bold = true }

unset_main = { fg = "#2d353b", bg = "#e67e80", bold = true }
unset_alt = { fg = "#e67e80", bg = "#475258" }

[status]
perm_exec = { fg = "#a7c080" }
perm_read = { fg = "#dbbc7f" }
perm_sep = { fg = "#83c092" }
perm_type = { fg = "#7fbbb3" }
perm_write = { fg = "#e67e80" }

progress_error = { fg = "#e67e80", bg = "#2d353b" }
progress_label = { fg = "#d3c6aa", bg = "#2d353b" }
progress_normal = { fg = "#d3c6aa", bg = "#2d353b" }

[pick]
active = { fg = "#d699b6" }
border = { fg = "#7fbbb3" }
inactive = { fg = "#d3c6aa" }

[task]
title = { fg = "#7fbbb3" }
border = { fg = "#7fbbb3" }
hovered = { fg = "#d3c6aa", bg = "#475258" }

[input]
border = { fg = "#7fbbb3" }
selected = { bg = "#475258" }

[help]
desc = { fg = "#d3c6aa" }
on = { fg = "#83c092" }
run = { fg = "#d699b6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#475258", bg = "#d3c6aa" }

[which]
mask = { bg = "#475258" }
desc = { fg = "#d3c6aa" }
cand = { fg = "#83c092" }
rest = { fg = "#9da9a0" }

separator_style = { fg = "#9da9a0" }

[notify]
title_info = { fg = "#83c092" }
title_warn = { fg = "#dbbc7f" }
title_error = { fg = "#e67e80" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#83c092" },
  { mime = "{audio, video}/*", fg = "#dbbc7f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a7c080" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#7fbbb3" },
  { mime = "*", fg = "#d3c6aa" },
]

