[mgr]
cwd = { fg = "#00a3cc" }

find_keyword = { bold = true, fg = "#f2ce00" }
find_position = { fg = "#b3a1e6" }

marker_copied = { fg = "#5ccc96", bg = "#5ccc96" }
marker_cut = { fg = "#e33400", bg = "#e33400" }
marker_selected = { fg = "#f2ce00", bg = "#f2ce00" }

count_copied = { fg = "#16172d", bg = "#5ccc96" }
count_cut = { fg = "#16172d", bg = "#e33400" }
count_selected = { fg = "#16172d", bg = "#f2ce00" }

border_style = { fg = "#7a5ccc" }

[tabs]
active = { fg = "#16172d", bg = "#7a5ccc"}
inactive = { fg = "#7a5ccc", bg = #1b1c36" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#16172d", bg = "#7a5ccc", bold = true }
normal_alt = { fg = "#7a5ccc", bg = "#30365f" }

select_alt = { fg = "#b3a1e6", bg = "#30365f" }
select_main = { fg = "#16172d", bg = "#b3a1e6", bold = true }

unset_main = { fg = "#16172d", bg = "#e33400", bold = true }
unset_alt = { fg = "#e33400", bg = "#30365f" }

[status]
perm_exec = { fg = "#5ccc96" }
perm_read = { fg = "#f2ce00" }
perm_sep = { fg = "#00a3cc" }
perm_type = { fg = "#7a5ccc" }
perm_write = { fg = "#e33400" }

progress_error = { fg = "#e33400", bg = "#16172d" }
progress_label = { fg = "#ecf0c1", bg = "#16172d" }
progress_normal = { fg = "#ecf0c1", bg = "#16172d" }

[pick]
active = { fg = "#b3a1e6" }
border = { fg = "#7a5ccc" }
inactive = { fg = "#ecf0c1" }

[task]
title = { fg = "#7a5ccc" }
border = { fg = "#7a5ccc" }
hovered = { fg = "#ecf0c1", bg = "#30365f" }

[input]
border = { fg = "#7a5ccc" }
selected = { bg = "#30365f" }

[help]
desc = { fg = "#ecf0c1" }
on = { fg = "#00a3cc" }
run = { fg = "#b3a1e6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#30365f", bg = "#ecf0c1" }

[which]
mask = { bg = "#30365f" }
desc = { fg = "#ecf0c1" }
cand = { fg = "#00a3cc" }
rest = { fg = "#ce6f8f" }

separator_style = { fg = "#818596" }

[notify]
title_info = { fg = "#00a3cc" }
title_warn = { fg = "#f2ce00" }
title_error = { fg = "#e33400" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00a3cc" },
  { mime = "{audio, video}/*", fg = "#f2ce00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5ccc96" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#7a5ccc" },
  { mime = "*", fg = "#ecf0c1" },
]

