[mgr]
cwd = { fg = "#76c7b7" }

find_keyword = { bold = true, fg = "#fda331" }
find_position = { fg = "#d381c3" }

marker_copied = { fg = "#a1c659", bg = "#a1c659" }
marker_cut = { fg = "#fb0120", bg = "#fb0120" }
marker_selected = { fg = "#fda331", bg = "#fda331" }

count_copied = { fg = "#000000", bg = "#a1c659" }
count_cut = { fg = "#000000", bg = "#fb0120" }
count_selected = { fg = "#000000", bg = "#fda331" }

border_style = { fg = "#6fb3d2" }

[tabs]
active = { fg = "#000000", bg = "#6fb3d2"}
inactive = { fg = "#6fb3d2", bg = #303030" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#000000", bg = "#6fb3d2", bold = true }
normal_alt = { fg = "#6fb3d2", bg = "#505050" }

select_alt = { fg = "#d381c3", bg = "#505050" }
select_main = { fg = "#000000", bg = "#d381c3", bold = true }

unset_main = { fg = "#000000", bg = "#fb0120", bold = true }
unset_alt = { fg = "#fb0120", bg = "#505050" }

[status]
perm_exec = { fg = "#a1c659" }
perm_read = { fg = "#fda331" }
perm_sep = { fg = "#76c7b7" }
perm_type = { fg = "#6fb3d2" }
perm_write = { fg = "#fb0120" }

progress_error = { fg = "#fb0120", bg = "#000000" }
progress_label = { fg = "#e0e0e0", bg = "#000000" }
progress_normal = { fg = "#e0e0e0", bg = "#000000" }

[pick]
active = { fg = "#d381c3" }
border = { fg = "#6fb3d2" }
inactive = { fg = "#e0e0e0" }

[task]
title = { fg = "#6fb3d2" }
border = { fg = "#6fb3d2" }
hovered = { fg = "#e0e0e0", bg = "#505050" }

[input]
border = { fg = "#6fb3d2" }
selected = { bg = "#505050" }

[help]
desc = { fg = "#e0e0e0" }
on = { fg = "#76c7b7" }
run = { fg = "#d381c3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#505050", bg = "#e0e0e0" }

[which]
mask = { bg = "#505050" }
desc = { fg = "#e0e0e0" }
cand = { fg = "#76c7b7" }
rest = { fg = "#be643c" }

separator_style = { fg = "#d0d0d0" }

[notify]
title_info = { fg = "#76c7b7" }
title_warn = { fg = "#fda331" }
title_error = { fg = "#fb0120" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#76c7b7" },
  { mime = "{audio, video}/*", fg = "#fda331" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a1c659" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6fb3d2" },
  { mime = "*", fg = "#e0e0e0" },
]

