[mgr]
cwd = { fg = "#009a8a" }

find_keyword = { bold = true, fg = "#af8500" }
find_position = { fg = "#6b40c3" }

marker_copied = { fg = "#008400", bg = "#008400" }
marker_cut = { fg = "#bf0000", bg = "#bf0000" }
marker_selected = { fg = "#af8500", bg = "#af8500" }

count_copied = { fg = "#ffffff", bg = "#008400" }
count_cut = { fg = "#ffffff", bg = "#bf0000" }
count_selected = { fg = "#ffffff", bg = "#af8500" }

border_style = { fg = "#0054cf" }

[tabs]
active = { fg = "#ffffff", bg = "#0054cf"}
inactive = { fg = "#0054cf", bg = #ebebeb" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#0054cf", bold = true }
normal_alt = { fg = "#0054cf", bg = "#cdcdcd" }

select_alt = { fg = "#6b40c3", bg = "#cdcdcd" }
select_main = { fg = "#ffffff", bg = "#6b40c3", bold = true }

unset_main = { fg = "#ffffff", bg = "#bf0000", bold = true }
unset_alt = { fg = "#bf0000", bg = "#cdcdcd" }

[status]
perm_exec = { fg = "#008400" }
perm_read = { fg = "#af8500" }
perm_sep = { fg = "#009a8a" }
perm_type = { fg = "#0054cf" }
perm_write = { fg = "#bf0000" }

progress_error = { fg = "#bf0000", bg = "#ffffff" }
progress_label = { fg = "#474747", bg = "#ffffff" }
progress_normal = { fg = "#474747", bg = "#ffffff" }

[pick]
active = { fg = "#6b40c3" }
border = { fg = "#0054cf" }
inactive = { fg = "#474747" }

[task]
title = { fg = "#0054cf" }
border = { fg = "#0054cf" }
hovered = { fg = "#474747", bg = "#cdcdcd" }

[input]
border = { fg = "#0054cf" }
selected = { bg = "#cdcdcd" }

[help]
desc = { fg = "#474747" }
on = { fg = "#009a8a" }
run = { fg = "#6b40c3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#cdcdcd", bg = "#474747" }

[which]
mask = { bg = "#cdcdcd" }
desc = { fg = "#474747" }
cand = { fg = "#009a8a" }
rest = { fg = "#dd0f9d" }

separator_style = { fg = "#878787" }

[notify]
title_info = { fg = "#009a8a" }
title_warn = { fg = "#af8500" }
title_error = { fg = "#bf0000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#009a8a" },
  { mime = "{audio, video}/*", fg = "#af8500" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#008400" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0054cf" },
  { mime = "*", fg = "#474747" },
]

