[mgr]
cwd = { fg = "#76dbd2" }

find_keyword = { bold = true, fg = "#dfe754" }
find_position = { fg = "#a874e0" }

marker_copied = { fg = "#59d678", bg = "#59d678" }
marker_cut = { fg = "#d7586e", bg = "#d7586e" }
marker_selected = { fg = "#dfe754", bg = "#dfe754" }

count_copied = { fg = "#131f1f", bg = "#59d678" }
count_cut = { fg = "#131f1f", bg = "#d7586e" }
count_selected = { fg = "#131f1f", bg = "#dfe754" }

border_style = { fg = "#4ed2d2" }

[tabs]
active = { fg = "#131f1f", bg = "#4ed2d2"}
inactive = { fg = "#4ed2d2", bg = "#213132" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#131f1f", bg = "#4ed2d2", bold = true }
normal_alt = { fg = "#4ed2d2", bg = "#273d3c" }

select_alt = { fg = "#a874e0", bg = "#273d3c" }
select_main = { fg = "#131f1f", bg = "#a874e0", bold = true }

unset_main = { fg = "#131f1f", bg = "#d7586e", bold = true }
unset_alt = { fg = "#d7586e", bg = "#273d3c" }

[status]
perm_exec = { fg = "#59d678" }
perm_read = { fg = "#dfe754" }
perm_sep = { fg = "#76dbd2" }
perm_type = { fg = "#4ed2d2" }
perm_write = { fg = "#d7586e" }

progress_error = { fg = "#d7586e", bg = "#131f1f" }
progress_label = { fg = "#98c1a3", bg = "#131f1f" }
progress_normal = { fg = "#98c1a3", bg = "#131f1f" }

[pick]
active = { fg = "#a874e0" }
border = { fg = "#4ed2d2" }
inactive = { fg = "#98c1a3" }

[task]
title = { fg = "#4ed2d2" }
border = { fg = "#4ed2d2" }
hovered = { fg = "#98c1a3", bg = "#273d3c" }

[input]
border = { fg = "#4ed2d2" }
selected = { bg = "#273d3c" }

[help]
desc = { fg = "#98c1a3" }
on = { fg = "#76dbd2" }
run = { fg = "#a874e0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#273d3c", bg = "#98c1a3" }

[which]
mask = { bg = "#273d3c" }
desc = { fg = "#98c1a3" }
cand = { fg = "#76dbd2" }
rest = { fg = "#c05a8f" }

separator_style = { fg = "#6d9877" }

[notify]
title_info = { fg = "#76dbd2" }
title_warn = { fg = "#dfe754" }
title_error = { fg = "#d7586e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#76dbd2" },
  { mime = "{audio, video}/*", fg = "#dfe754" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#59d678" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#4ed2d2" },
  { mime = "*", fg = "#98c1a3" },
]

