[mgr]
cwd = { fg = "#868686" }

find_keyword = { bold = true, fg = "#a0a0a0" }
find_position = { fg = "#747474" }

marker_copied = { fg = "#8e8e8e", bg = "#8e8e8e" }
marker_cut = { fg = "#7c7c7c", bg = "#7c7c7c" }
marker_selected = { fg = "#a0a0a0", bg = "#a0a0a0" }

count_copied = { fg = "#f7f7f7", bg = "#8e8e8e" }
count_cut = { fg = "#f7f7f7", bg = "#7c7c7c" }
count_selected = { fg = "#f7f7f7", bg = "#a0a0a0" }

border_style = { fg = "#686868" }

[tabs]
active = { fg = "#f7f7f7", bg = "#686868"}
inactive = { fg = "#686868", bg = #e3e3e3" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f7f7f7", bg = "#686868", bold = true }
normal_alt = { fg = "#686868", bg = "#b9b9b9" }

select_alt = { fg = "#747474", bg = "#b9b9b9" }
select_main = { fg = "#f7f7f7", bg = "#747474", bold = true }

unset_main = { fg = "#f7f7f7", bg = "#7c7c7c", bold = true }
unset_alt = { fg = "#7c7c7c", bg = "#b9b9b9" }

[status]
perm_exec = { fg = "#8e8e8e" }
perm_read = { fg = "#a0a0a0" }
perm_sep = { fg = "#868686" }
perm_type = { fg = "#686868" }
perm_write = { fg = "#7c7c7c" }

progress_error = { fg = "#7c7c7c", bg = "#f7f7f7" }
progress_label = { fg = "#464646", bg = "#f7f7f7" }
progress_normal = { fg = "#464646", bg = "#f7f7f7" }

[pick]
active = { fg = "#747474" }
border = { fg = "#686868" }
inactive = { fg = "#464646" }

[task]
title = { fg = "#686868" }
border = { fg = "#686868" }
hovered = { fg = "#464646", bg = "#b9b9b9" }

[input]
border = { fg = "#686868" }
selected = { bg = "#b9b9b9" }

[help]
desc = { fg = "#464646" }
on = { fg = "#868686" }
run = { fg = "#747474" }
hovered = { reversed = true, bold = true }
footer = { fg = "#b9b9b9", bg = "#464646" }

[which]
mask = { bg = "#b9b9b9" }
desc = { fg = "#464646" }
cand = { fg = "#868686" }
rest = { fg = "#5e5e5e" }

separator_style = { fg = "#525252" }

[notify]
title_info = { fg = "#868686" }
title_warn = { fg = "#a0a0a0" }
title_error = { fg = "#7c7c7c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#868686" },
  { mime = "{audio, video}/*", fg = "#a0a0a0" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8e8e8e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#686868" },
  { mime = "*", fg = "#464646" },
]

