[mgr]
cwd = { fg = "#4b8f77" }

find_keyword = { bold = true, fg = "#cfd05d" }
find_position = { fg = "#9c6cd3" }

marker_copied = { fg = "#5de561", bg = "#5de561" }
marker_cut = { fg = "#c4676c", bg = "#c4676c" }
marker_selected = { fg = "#cfd05d", bg = "#cfd05d" }

count_copied = { fg = "#2a3b4d", bg = "#5de561" }
count_cut = { fg = "#2a3b4d", bg = "#c4676c" }
count_selected = { fg = "#2a3b4d", bg = "#cfd05d" }

border_style = { fg = "#1ae1dc" }

[tabs]
active = { fg = "#2a3b4d", bg = "#1ae1dc"}
inactive = { fg = "#1ae1dc", bg = #3d566f" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2a3b4d", bg = "#1ae1dc", bold = true }
normal_alt = { fg = "#1ae1dc", bg = "#4b6988" }

select_alt = { fg = "#9c6cd3", bg = "#4b6988" }
select_main = { fg = "#2a3b4d", bg = "#9c6cd3", bold = true }

unset_main = { fg = "#2a3b4d", bg = "#c4676c", bold = true }
unset_alt = { fg = "#c4676c", bg = "#4b6988" }

[status]
perm_exec = { fg = "#5de561" }
perm_read = { fg = "#cfd05d" }
perm_sep = { fg = "#4b8f77" }
perm_type = { fg = "#1ae1dc" }
perm_write = { fg = "#c4676c" }

progress_error = { fg = "#c4676c", bg = "#2a3b4d" }
progress_label = { fg = "#9fa2a6", bg = "#2a3b4d" }
progress_normal = { fg = "#9fa2a6", bg = "#2a3b4d" }

[pick]
active = { fg = "#9c6cd3" }
border = { fg = "#1ae1dc" }
inactive = { fg = "#9fa2a6" }

[task]
title = { fg = "#1ae1dc" }
border = { fg = "#1ae1dc" }
hovered = { fg = "#9fa2a6", bg = "#4b6988" }

[input]
border = { fg = "#1ae1dc" }
selected = { bg = "#4b6988" }

[help]
desc = { fg = "#9fa2a6" }
on = { fg = "#4b8f77" }
run = { fg = "#9c6cd3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4b6988", bg = "#9fa2a6" }

[which]
mask = { bg = "#4b6988" }
desc = { fg = "#9fa2a6" }
cand = { fg = "#4b8f77" }
rest = { fg = "#bb64a9" }

separator_style = { fg = "#7e90a3" }

[notify]
title_info = { fg = "#4b8f77" }
title_warn = { fg = "#cfd05d" }
title_error = { fg = "#c4676c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4b8f77" },
  { mime = "{audio, video}/*", fg = "#cfd05d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5de561" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#1ae1dc" },
  { mime = "*", fg = "#9fa2a6" },
]

