[mgr]
cwd = { fg = "#96b5b4" }

find_keyword = { bold = true, fg = "#ebcb8b" }
find_position = { fg = "#b48ead" }

marker_copied = { fg = "#a3be8c", bg = "#a3be8c" }
marker_cut = { fg = "#bf616a", bg = "#bf616a" }
marker_selected = { fg = "#ebcb8b", bg = "#ebcb8b" }

count_copied = { fg = "#2b303b", bg = "#a3be8c" }
count_cut = { fg = "#2b303b", bg = "#bf616a" }
count_selected = { fg = "#2b303b", bg = "#ebcb8b" }

border_style = { fg = "#8fa1b3" }

[tabs]
active = { fg = "#2b303b", bg = "#8fa1b3"}
inactive = { fg = "#8fa1b3", bg = #343d46" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2b303b", bg = "#8fa1b3", bold = true }
normal_alt = { fg = "#8fa1b3", bg = "#4f5b66" }

select_alt = { fg = "#b48ead", bg = "#4f5b66" }
select_main = { fg = "#2b303b", bg = "#b48ead", bold = true }

unset_main = { fg = "#2b303b", bg = "#bf616a", bold = true }
unset_alt = { fg = "#bf616a", bg = "#4f5b66" }

[status]
perm_exec = { fg = "#a3be8c" }
perm_read = { fg = "#ebcb8b" }
perm_sep = { fg = "#96b5b4" }
perm_type = { fg = "#8fa1b3" }
perm_write = { fg = "#bf616a" }

progress_error = { fg = "#bf616a", bg = "#2b303b" }
progress_label = { fg = "#c0c5ce", bg = "#2b303b" }
progress_normal = { fg = "#c0c5ce", bg = "#2b303b" }

[pick]
active = { fg = "#b48ead" }
border = { fg = "#8fa1b3" }
inactive = { fg = "#c0c5ce" }

[task]
title = { fg = "#8fa1b3" }
border = { fg = "#8fa1b3" }
hovered = { fg = "#c0c5ce", bg = "#4f5b66" }

[input]
border = { fg = "#8fa1b3" }
selected = { bg = "#4f5b66" }

[help]
desc = { fg = "#c0c5ce" }
on = { fg = "#96b5b4" }
run = { fg = "#b48ead" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4f5b66", bg = "#c0c5ce" }

[which]
mask = { bg = "#4f5b66" }
desc = { fg = "#c0c5ce" }
cand = { fg = "#96b5b4" }
rest = { fg = "#ab7967" }

separator_style = { fg = "#a7adba" }

[notify]
title_info = { fg = "#96b5b4" }
title_warn = { fg = "#ebcb8b" }
title_error = { fg = "#bf616a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#96b5b4" },
  { mime = "{audio, video}/*", fg = "#ebcb8b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a3be8c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#8fa1b3" },
  { mime = "*", fg = "#c0c5ce" },
]

