[mgr]
cwd = { fg = "#41c7b9" }

find_keyword = { bold = true, fg = "#dbb32d" }
find_position = { fg = "#af88eb" }

marker_copied = { fg = "#75b938", bg = "#75b938" }
marker_cut = { fg = "#fa5750", bg = "#fa5750" }
marker_selected = { fg = "#dbb32d", bg = "#dbb32d" }

count_copied = { fg = "#103c48", bg = "#75b938" }
count_cut = { fg = "#103c48", bg = "#fa5750" }
count_selected = { fg = "#103c48", bg = "#dbb32d" }

border_style = { fg = "#4695f7" }

[tabs]
active = { fg = "#103c48", bg = "#4695f7"}
inactive = { fg = "#4695f7", bg = #184956" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#103c48", bg = "#4695f7", bold = true }
normal_alt = { fg = "#4695f7", bg = "#2d5b69" }

select_alt = { fg = "#af88eb", bg = "#2d5b69" }
select_main = { fg = "#103c48", bg = "#af88eb", bold = true }

unset_main = { fg = "#103c48", bg = "#fa5750", bold = true }
unset_alt = { fg = "#fa5750", bg = "#2d5b69" }

[status]
perm_exec = { fg = "#75b938" }
perm_read = { fg = "#dbb32d" }
perm_sep = { fg = "#41c7b9" }
perm_type = { fg = "#4695f7" }
perm_write = { fg = "#fa5750" }

progress_error = { fg = "#fa5750", bg = "#103c48" }
progress_label = { fg = "#adbcbc", bg = "#103c48" }
progress_normal = { fg = "#adbcbc", bg = "#103c48" }

[pick]
active = { fg = "#af88eb" }
border = { fg = "#4695f7" }
inactive = { fg = "#adbcbc" }

[task]
title = { fg = "#4695f7" }
border = { fg = "#4695f7" }
hovered = { fg = "#adbcbc", bg = "#2d5b69" }

[input]
border = { fg = "#4695f7" }
selected = { bg = "#2d5b69" }

[help]
desc = { fg = "#adbcbc" }
on = { fg = "#41c7b9" }
run = { fg = "#af88eb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2d5b69", bg = "#adbcbc" }

[which]
mask = { bg = "#2d5b69" }
desc = { fg = "#adbcbc" }
cand = { fg = "#41c7b9" }
rest = { fg = "#f275be" }

separator_style = { fg = "#72898f" }

[notify]
title_info = { fg = "#41c7b9" }
title_warn = { fg = "#dbb32d" }
title_error = { fg = "#fa5750" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#41c7b9" },
  { mime = "{audio, video}/*", fg = "#dbb32d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#75b938" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#4695f7" },
  { mime = "*", fg = "#adbcbc" },
]

