[mgr]
cwd = { fg = "#aee8f4" }

find_keyword = { bold = true, fg = "#ffca58" }
find_position = { fg = "#a093e2" }

marker_copied = { fg = "#bcdf59", bg = "#bcdf59" }
marker_cut = { fg = "#ff7272", bg = "#ff7272" }
marker_selected = { fg = "#ffca58", bg = "#ffca58" }

count_copied = { fg = "#262427", bg = "#bcdf59" }
count_cut = { fg = "#262427", bg = "#ff7272" }
count_selected = { fg = "#262427", bg = "#ffca58" }

border_style = { fg = "#49cae4" }

[tabs]
active = { fg = "#262427", bg = "#49cae4"}
inactive = { fg = "#49cae4", bg = "#3b393c" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#262427", bg = "#49cae4", bold = true }
normal_alt = { fg = "#49cae4", bg = "#514f52" }

select_alt = { fg = "#a093e2", bg = "#514f52" }
select_main = { fg = "#262427", bg = "#a093e2", bold = true }

unset_main = { fg = "#262427", bg = "#ff7272", bold = true }
unset_alt = { fg = "#ff7272", bg = "#514f52" }

[status]
perm_exec = { fg = "#bcdf59" }
perm_read = { fg = "#ffca58" }
perm_sep = { fg = "#aee8f4" }
perm_type = { fg = "#49cae4" }
perm_write = { fg = "#ff7272" }

progress_error = { fg = "#ff7272", bg = "#262427" }
progress_label = { fg = "#fcfcfc", bg = "#262427" }
progress_normal = { fg = "#fcfcfc", bg = "#262427" }

[pick]
active = { fg = "#a093e2" }
border = { fg = "#49cae4" }
inactive = { fg = "#fcfcfc" }

[task]
title = { fg = "#49cae4" }
border = { fg = "#49cae4" }
hovered = { fg = "#fcfcfc", bg = "#514f52" }

[input]
border = { fg = "#49cae4" }
selected = { bg = "#514f52" }

[help]
desc = { fg = "#fcfcfc" }
on = { fg = "#aee8f4" }
run = { fg = "#a093e2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#514f52", bg = "#fcfcfc" }

[which]
mask = { bg = "#514f52" }
desc = { fg = "#fcfcfc" }
cand = { fg = "#aee8f4" }
rest = { fg = "#ff8787" }

separator_style = { fg = "#7c7b7d" }

[notify]
title_info = { fg = "#aee8f4" }
title_warn = { fg = "#ffca58" }
title_error = { fg = "#ff7272" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#aee8f4" },
  { mime = "{audio, video}/*", fg = "#ffca58" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#bcdf59" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#49cae4" },
  { mime = "*", fg = "#fcfcfc" },
]

