[mgr]
cwd = { fg = "#1abc9c" }

find_keyword = { bold = true, fg = "#f1c40f" }
find_position = { fg = "#9b59b6" }

marker_copied = { fg = "#2ecc71", bg = "#2ecc71" }
marker_cut = { fg = "#e74c3c", bg = "#e74c3c" }
marker_selected = { fg = "#f1c40f", bg = "#f1c40f" }

count_copied = { fg = "#2c3e50", bg = "#2ecc71" }
count_cut = { fg = "#2c3e50", bg = "#e74c3c" }
count_selected = { fg = "#2c3e50", bg = "#f1c40f" }

border_style = { fg = "#3498db" }

[tabs]
active = { fg = "#2c3e50", bg = "#3498db"}
inactive = { fg = "#3498db", bg = "#34495e" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2c3e50", bg = "#3498db", bold = true }
normal_alt = { fg = "#3498db", bg = "#7f8c8d" }

select_alt = { fg = "#9b59b6", bg = "#7f8c8d" }
select_main = { fg = "#2c3e50", bg = "#9b59b6", bold = true }

unset_main = { fg = "#2c3e50", bg = "#e74c3c", bold = true }
unset_alt = { fg = "#e74c3c", bg = "#7f8c8d" }

[status]
perm_exec = { fg = "#2ecc71" }
perm_read = { fg = "#f1c40f" }
perm_sep = { fg = "#1abc9c" }
perm_type = { fg = "#3498db" }
perm_write = { fg = "#e74c3c" }

progress_error = { fg = "#e74c3c", bg = "#2c3e50" }
progress_label = { fg = "#e0e0e0", bg = "#2c3e50" }
progress_normal = { fg = "#e0e0e0", bg = "#2c3e50" }

[pick]
active = { fg = "#9b59b6" }
border = { fg = "#3498db" }
inactive = { fg = "#e0e0e0" }

[task]
title = { fg = "#3498db" }
border = { fg = "#3498db" }
hovered = { fg = "#e0e0e0", bg = "#7f8c8d" }

[input]
border = { fg = "#3498db" }
selected = { bg = "#7f8c8d" }

[help]
desc = { fg = "#e0e0e0" }
on = { fg = "#1abc9c" }
run = { fg = "#9b59b6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#7f8c8d", bg = "#e0e0e0" }

[which]
mask = { bg = "#7f8c8d" }
desc = { fg = "#e0e0e0" }
cand = { fg = "#1abc9c" }
rest = { fg = "#be643c" }

separator_style = { fg = "#bdc3c7" }

[notify]
title_info = { fg = "#1abc9c" }
title_warn = { fg = "#f1c40f" }
title_error = { fg = "#e74c3c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1abc9c" },
  { mime = "{audio, video}/*", fg = "#f1c40f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2ecc71" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3498db" },
  { mime = "*", fg = "#e0e0e0" },
]

