[mgr]
cwd = { fg = "#4fb7ae" }

find_keyword = { bold = true, fg = "#f3b863" }
find_position = { fg = "#8b66d6" }

marker_copied = { fg = "#63b784", bg = "#63b784" }
marker_cut = { fg = "#d3464d", bg = "#d3464d" }
marker_selected = { fg = "#f3b863", bg = "#f3b863" }

count_copied = { fg = "#001c1f", bg = "#63b784" }
count_cut = { fg = "#001c1f", bg = "#d3464d" }
count_selected = { fg = "#001c1f", bg = "#f3b863" }

border_style = { fg = "#568ccf" }

[tabs]
active = { fg = "#001c1f", bg = "#568ccf"}
inactive = { fg = "#568ccf", bg = #002931" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#001c1f", bg = "#568ccf", bold = true }
normal_alt = { fg = "#568ccf", bg = "#003640" }

select_alt = { fg = "#8b66d6", bg = "#003640" }
select_main = { fg = "#001c1f", bg = "#8b66d6", bold = true }

unset_main = { fg = "#001c1f", bg = "#d3464d", bold = true }
unset_alt = { fg = "#d3464d", bg = "#003640" }

[status]
perm_exec = { fg = "#63b784" }
perm_read = { fg = "#f3b863" }
perm_sep = { fg = "#4fb7ae" }
perm_type = { fg = "#568ccf" }
perm_write = { fg = "#d3464d" }

progress_error = { fg = "#d3464d", bg = "#001c1f" }
progress_label = { fg = "#d4e1e8", bg = "#001c1f" }
progress_normal = { fg = "#d4e1e8", bg = "#001c1f" }

[pick]
active = { fg = "#8b66d6" }
border = { fg = "#568ccf" }
inactive = { fg = "#d4e1e8" }

[task]
title = { fg = "#568ccf" }
border = { fg = "#568ccf" }
hovered = { fg = "#d4e1e8", bg = "#003640" }

[input]
border = { fg = "#568ccf" }
selected = { bg = "#003640" }

[help]
desc = { fg = "#d4e1e8" }
on = { fg = "#4fb7ae" }
run = { fg = "#8b66d6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#003640", bg = "#d4e1e8" }

[which]
mask = { bg = "#003640" }
desc = { fg = "#d4e1e8" }
cand = { fg = "#4fb7ae" }
rest = { fg = "#d0658e" }

separator_style = { fg = "#0093a3" }

[notify]
title_info = { fg = "#4fb7ae" }
title_warn = { fg = "#f3b863" }
title_error = { fg = "#d3464d" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4fb7ae" },
  { mime = "{audio, video}/*", fg = "#f3b863" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#63b784" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#568ccf" },
  { mime = "*", fg = "#d4e1e8" },
]

