[mgr]
cwd = { fg = "#89ddff" }

find_keyword = { bold = true, fg = "#ffcb6b" }
find_position = { fg = "#c792ea" }

marker_copied = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut = { fg = "#f07178", bg = "#f07178" }
marker_selected = { fg = "#ffcb6b", bg = "#ffcb6b" }

count_copied = { fg = "#212121", bg = "#c3e88d" }
count_cut = { fg = "#212121", bg = "#f07178" }
count_selected = { fg = "#212121", bg = "#ffcb6b" }

border_style = { fg = "#82aaff" }

[tabs]
active = { fg = "#212121", bg = "#82aaff"}
inactive = { fg = "#82aaff", bg = #303030" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#212121", bg = "#82aaff", bold = true }
normal_alt = { fg = "#82aaff", bg = "#353535" }

select_alt = { fg = "#c792ea", bg = "#353535" }
select_main = { fg = "#212121", bg = "#c792ea", bold = true }

unset_main = { fg = "#212121", bg = "#f07178", bold = true }
unset_alt = { fg = "#f07178", bg = "#353535" }

[status]
perm_exec = { fg = "#c3e88d" }
perm_read = { fg = "#ffcb6b" }
perm_sep = { fg = "#89ddff" }
perm_type = { fg = "#82aaff" }
perm_write = { fg = "#f07178" }

progress_error = { fg = "#f07178", bg = "#212121" }
progress_label = { fg = "#eeffff", bg = "#212121" }
progress_normal = { fg = "#eeffff", bg = "#212121" }

[pick]
active = { fg = "#c792ea" }
border = { fg = "#82aaff" }
inactive = { fg = "#eeffff" }

[task]
title = { fg = "#82aaff" }
border = { fg = "#82aaff" }
hovered = { fg = "#eeffff", bg = "#353535" }

[input]
border = { fg = "#82aaff" }
selected = { bg = "#353535" }

[help]
desc = { fg = "#eeffff" }
on = { fg = "#89ddff" }
run = { fg = "#c792ea" }
hovered = { reversed = true, bold = true }
footer = { fg = "#353535", bg = "#eeffff" }

[which]
mask = { bg = "#353535" }
desc = { fg = "#eeffff" }
cand = { fg = "#89ddff" }
rest = { fg = "#ff5370" }

separator_style = { fg = "#b2ccd6" }

[notify]
title_info = { fg = "#89ddff" }
title_warn = { fg = "#ffcb6b" }
title_error = { fg = "#f07178" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#89ddff" },
  { mime = "{audio, video}/*", fg = "#ffcb6b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#c3e88d" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#82aaff" },
  { mime = "*", fg = "#eeffff" },
]

