[mgr]
cwd = { fg = "#56949f" }

find_keyword = { bold = true, fg = "#d7827e" }
find_position = { fg = "#ea9d34" }

marker_copied = { fg = "#286983", bg = "#286983" }
marker_cut = { fg = "#b4637a", bg = "#b4637a" }
marker_selected = { fg = "#d7827e", bg = "#d7827e" }

count_copied = { fg = "#faf4ed", bg = "#286983" }
count_cut = { fg = "#faf4ed", bg = "#b4637a" }
count_selected = { fg = "#faf4ed", bg = "#d7827e" }

border_style = { fg = "#907aa9" }

[tabs]
active = { fg = "#faf4ed", bg = "#907aa9"}
inactive = { fg = "#907aa9", bg = "#fffaf3" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#faf4ed", bg = "#907aa9", bold = true }
normal_alt = { fg = "#907aa9", bg = "#f2e9de" }

select_alt = { fg = "#ea9d34", bg = "#f2e9de" }
select_main = { fg = "#faf4ed", bg = "#ea9d34", bold = true }

unset_main = { fg = "#faf4ed", bg = "#b4637a", bold = true }
unset_alt = { fg = "#b4637a", bg = "#f2e9de" }

[status]
perm_exec = { fg = "#286983" }
perm_read = { fg = "#d7827e" }
perm_sep = { fg = "#56949f" }
perm_type = { fg = "#907aa9" }
perm_write = { fg = "#b4637a" }

progress_error = { fg = "#b4637a", bg = "#faf4ed" }
progress_label = { fg = "#575279", bg = "#faf4ed" }
progress_normal = { fg = "#575279", bg = "#faf4ed" }

[pick]
active = { fg = "#ea9d34" }
border = { fg = "#907aa9" }
inactive = { fg = "#575279" }

[task]
title = { fg = "#907aa9" }
border = { fg = "#907aa9" }
hovered = { fg = "#575279", bg = "#f2e9de" }

[input]
border = { fg = "#907aa9" }
selected = { bg = "#f2e9de" }

[help]
desc = { fg = "#575279" }
on = { fg = "#56949f" }
run = { fg = "#ea9d34" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f2e9de", bg = "#575279" }

[which]
mask = { bg = "#f2e9de" }
desc = { fg = "#575279" }
cand = { fg = "#56949f" }
rest = { fg = "#cecacd" }

separator_style = { fg = "#797593" }

[notify]
title_info = { fg = "#56949f" }
title_warn = { fg = "#d7827e" }
title_error = { fg = "#b4637a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#56949f" },
  { mime = "{audio, video}/*", fg = "#d7827e" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#286983" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#907aa9" },
  { mime = "*", fg = "#575279" },
]

