[mgr]
cwd = { fg = "#3fc5b7" }

find_keyword = { bold = true, fg = "#dbb32d" }
find_position = { fg = "#a580e2" }

marker_copied = { fg = "#70b433", bg = "#70b433" }
marker_cut = { fg = "#ed4a46", bg = "#ed4a46" }
marker_selected = { fg = "#dbb32d", bg = "#dbb32d" }

count_copied = { fg = "#181818", bg = "#70b433" }
count_cut = { fg = "#181818", bg = "#ed4a46" }
count_selected = { fg = "#181818", bg = "#dbb32d" }

border_style = { fg = "#368aeb" }

[tabs]
active = { fg = "#181818", bg = "#368aeb"}
inactive = { fg = "#368aeb", bg = #252525" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#181818", bg = "#368aeb", bold = true }
normal_alt = { fg = "#368aeb", bg = "#3b3b3b" }

select_alt = { fg = "#a580e2", bg = "#3b3b3b" }
select_main = { fg = "#181818", bg = "#a580e2", bold = true }

unset_main = { fg = "#181818", bg = "#ed4a46", bold = true }
unset_alt = { fg = "#ed4a46", bg = "#3b3b3b" }

[status]
perm_exec = { fg = "#70b433" }
perm_read = { fg = "#dbb32d" }
perm_sep = { fg = "#3fc5b7" }
perm_type = { fg = "#368aeb" }
perm_write = { fg = "#ed4a46" }

progress_error = { fg = "#ed4a46", bg = "#181818" }
progress_label = { fg = "#b9b9b9", bg = "#181818" }
progress_normal = { fg = "#b9b9b9", bg = "#181818" }

[pick]
active = { fg = "#a580e2" }
border = { fg = "#368aeb" }
inactive = { fg = "#b9b9b9" }

[task]
title = { fg = "#368aeb" }
border = { fg = "#368aeb" }
hovered = { fg = "#b9b9b9", bg = "#3b3b3b" }

[input]
border = { fg = "#368aeb" }
selected = { bg = "#3b3b3b" }

[help]
desc = { fg = "#b9b9b9" }
on = { fg = "#3fc5b7" }
run = { fg = "#a580e2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3b3b3b", bg = "#b9b9b9" }

[which]
mask = { bg = "#3b3b3b" }
desc = { fg = "#b9b9b9" }
cand = { fg = "#3fc5b7" }
rest = { fg = "#eb6eb7" }

separator_style = { fg = "#777777" }

[notify]
title_info = { fg = "#3fc5b7" }
title_warn = { fg = "#dbb32d" }
title_error = { fg = "#ed4a46" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3fc5b7" },
  { mime = "{audio, video}/*", fg = "#dbb32d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#70b433" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#368aeb" },
  { mime = "*", fg = "#b9b9b9" },
]

