[mgr]
cwd = { fg = "#b0d5df" }

find_keyword = { bold = true, fg = "#f4ce69" }
find_position = { fg = "#be9db9" }

marker_copied = { fg = "#b2cf87", bg = "#b2cf87" }
marker_cut = { fg = "#f07c82", bg = "#f07c82" }
marker_selected = { fg = "#f4ce69", bg = "#f4ce69" }

count_copied = { fg = "#1d1d1d", bg = "#b2cf87" }
count_cut = { fg = "#1d1d1d", bg = "#f07c82" }
count_selected = { fg = "#1d1d1d", bg = "#f4ce69" }

border_style = { fg = "#8fb2c9" }

[tabs]
active = { fg = "#1d1d1d", bg = "#8fb2c9"}
inactive = { fg = "#8fb2c9", bg = #282828" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1d1d1d", bg = "#8fb2c9", bold = true }
normal_alt = { fg = "#8fb2c9", bg = "#373737" }

select_alt = { fg = "#be9db9", bg = "#373737" }
select_main = { fg = "#1d1d1d", bg = "#be9db9", bold = true }

unset_main = { fg = "#1d1d1d", bg = "#f07c82", bold = true }
unset_alt = { fg = "#f07c82", bg = "#373737" }

[status]
perm_exec = { fg = "#b2cf87" }
perm_read = { fg = "#f4ce69" }
perm_sep = { fg = "#b0d5df" }
perm_type = { fg = "#8fb2c9" }
perm_write = { fg = "#f07c82" }

progress_error = { fg = "#f07c82", bg = "#1d1d1d" }
progress_label = { fg = "#c4cbcf", bg = "#1d1d1d" }
progress_normal = { fg = "#c4cbcf", bg = "#1d1d1d" }

[pick]
active = { fg = "#be9db9" }
border = { fg = "#8fb2c9" }
inactive = { fg = "#c4cbcf" }

[task]
title = { fg = "#8fb2c9" }
border = { fg = "#8fb2c9" }
hovered = { fg = "#c4cbcf", bg = "#373737" }

[input]
border = { fg = "#8fb2c9" }
selected = { bg = "#373737" }

[help]
desc = { fg = "#c4cbcf" }
on = { fg = "#b0d5df" }
run = { fg = "#be9db9" }
hovered = { reversed = true, bold = true }
footer = { fg = "#373737", bg = "#c4cbcf" }

[which]
mask = { bg = "#373737" }
desc = { fg = "#c4cbcf" }
cand = { fg = "#b0d5df" }
rest = { fg = "#b89485" }

separator_style = { fg = "#bdaead" }

[notify]
title_info = { fg = "#b0d5df" }
title_warn = { fg = "#f4ce69" }
title_error = { fg = "#f07c82" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#b0d5df" },
  { mime = "{audio, video}/*", fg = "#f4ce69" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#b2cf87" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#8fb2c9" },
  { mime = "*", fg = "#c4cbcf" },
]

