[mgr]
cwd = { fg = "#1faaaa" }

find_keyword = { bold = true, fg = "#aba800" }
find_position = { fg = "#ad00a1" }

marker_copied = { fg = "#00c918", bg = "#00c918" }
marker_cut = { fg = "#ff0086", bg = "#ff0086" }
marker_selected = { fg = "#aba800", bg = "#aba800" }

count_copied = { fg = "#ffffff", bg = "#00c918" }
count_cut = { fg = "#ffffff", bg = "#ff0086" }
count_selected = { fg = "#ffffff", bg = "#aba800" }

border_style = { fg = "#3777e6" }

[tabs]
active = { fg = "#ffffff", bg = "#3777e6"}
inactive = { fg = "#3777e6", bg = #e0e0e0" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#3777e6", bold = true }
normal_alt = { fg = "#3777e6", bg = "#d0d0d0" }

select_alt = { fg = "#ad00a1", bg = "#d0d0d0" }
select_main = { fg = "#ffffff", bg = "#ad00a1", bold = true }

unset_main = { fg = "#ffffff", bg = "#ff0086", bold = true }
unset_alt = { fg = "#ff0086", bg = "#d0d0d0" }

[status]
perm_exec = { fg = "#00c918" }
perm_read = { fg = "#aba800" }
perm_sep = { fg = "#1faaaa" }
perm_type = { fg = "#3777e6" }
perm_write = { fg = "#ff0086" }

progress_error = { fg = "#ff0086", bg = "#ffffff" }
progress_label = { fg = "#101010", bg = "#ffffff" }
progress_normal = { fg = "#101010", bg = "#ffffff" }

[pick]
active = { fg = "#ad00a1" }
border = { fg = "#3777e6" }
inactive = { fg = "#101010" }

[task]
title = { fg = "#3777e6" }
border = { fg = "#3777e6" }
hovered = { fg = "#101010", bg = "#d0d0d0" }

[input]
border = { fg = "#3777e6" }
selected = { bg = "#d0d0d0" }

[help]
desc = { fg = "#101010" }
on = { fg = "#1faaaa" }
run = { fg = "#ad00a1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d0d0d0", bg = "#101010" }

[which]
mask = { bg = "#d0d0d0" }
desc = { fg = "#101010" }
cand = { fg = "#1faaaa" }
rest = { fg = "#cc6633" }

separator_style = { fg = "#000000" }

[notify]
title_info = { fg = "#1faaaa" }
title_warn = { fg = "#aba800" }
title_error = { fg = "#ff0086" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1faaaa" },
  { mime = "{audio, video}/*", fg = "#aba800" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00c918" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3777e6" },
  { mime = "*", fg = "#101010" },
]

