[mgr]
cwd = { fg = "#39adb5" }

find_keyword = { bold = true, fg = "#ffb62c" }
find_position = { fg = "#7c4dff" }

marker_copied = { fg = "#91b859", bg = "#91b859" }
marker_cut = { fg = "#ff5370", bg = "#ff5370" }
marker_selected = { fg = "#ffb62c", bg = "#ffb62c" }

count_copied = { fg = "#fafafa", bg = "#91b859" }
count_cut = { fg = "#fafafa", bg = "#ff5370" }
count_selected = { fg = "#fafafa", bg = "#ffb62c" }

border_style = { fg = "#6182b8" }

[tabs]
active = { fg = "#fafafa", bg = "#6182b8"}
inactive = { fg = "#6182b8", bg = #e7eaec" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fafafa", bg = "#6182b8", bold = true }
normal_alt = { fg = "#6182b8", bg = "#cceae7" }

select_alt = { fg = "#7c4dff", bg = "#cceae7" }
select_main = { fg = "#fafafa", bg = "#7c4dff", bold = true }

unset_main = { fg = "#fafafa", bg = "#ff5370", bold = true }
unset_alt = { fg = "#ff5370", bg = "#cceae7" }

[status]
perm_exec = { fg = "#91b859" }
perm_read = { fg = "#ffb62c" }
perm_sep = { fg = "#39adb5" }
perm_type = { fg = "#6182b8" }
perm_write = { fg = "#ff5370" }

progress_error = { fg = "#ff5370", bg = "#fafafa" }
progress_label = { fg = "#80cbc4", bg = "#fafafa" }
progress_normal = { fg = "#80cbc4", bg = "#fafafa" }

[pick]
active = { fg = "#7c4dff" }
border = { fg = "#6182b8" }
inactive = { fg = "#80cbc4" }

[task]
title = { fg = "#6182b8" }
border = { fg = "#6182b8" }
hovered = { fg = "#80cbc4", bg = "#cceae7" }

[input]
border = { fg = "#6182b8" }
selected = { bg = "#cceae7" }

[help]
desc = { fg = "#80cbc4" }
on = { fg = "#39adb5" }
run = { fg = "#7c4dff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#cceae7", bg = "#80cbc4" }

[which]
mask = { bg = "#cceae7" }
desc = { fg = "#80cbc4" }
cand = { fg = "#39adb5" }
rest = { fg = "#e53935" }

separator_style = { fg = "#8796b0" }

[notify]
title_info = { fg = "#39adb5" }
title_warn = { fg = "#ffb62c" }
title_error = { fg = "#ff5370" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#39adb5" },
  { mime = "{audio, video}/*", fg = "#ffb62c" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#91b859" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6182b8" },
  { mime = "*", fg = "#80cbc4" },
]

