[mgr]
cwd = { fg = "#00978a" }

find_keyword = { bold = true, fg = "#a78300" }
find_position = { fg = "#825dc0" }

marker_copied = { fg = "#428b00", bg = "#428b00" }
marker_cut = { fg = "#cc1729", bg = "#cc1729" }
marker_selected = { fg = "#a78300", bg = "#a78300" }

count_copied = { fg = "#fbf3db", bg = "#428b00" }
count_cut = { fg = "#fbf3db", bg = "#cc1729" }
count_selected = { fg = "#fbf3db", bg = "#a78300" }

border_style = { fg = "#006dce" }

[tabs]
active = { fg = "#fbf3db", bg = "#006dce"}
inactive = { fg = "#006dce", bg = "#ece3cc" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fbf3db", bg = "#006dce", bold = true }
normal_alt = { fg = "#006dce", bg = "#d5cdb6" }

select_alt = { fg = "#825dc0", bg = "#d5cdb6" }
select_main = { fg = "#fbf3db", bg = "#825dc0", bold = true }

unset_main = { fg = "#fbf3db", bg = "#cc1729", bold = true }
unset_alt = { fg = "#cc1729", bg = "#d5cdb6" }

[status]
perm_exec = { fg = "#428b00" }
perm_read = { fg = "#a78300" }
perm_sep = { fg = "#00978a" }
perm_type = { fg = "#006dce" }
perm_write = { fg = "#cc1729" }

progress_error = { fg = "#cc1729", bg = "#fbf3db" }
progress_label = { fg = "#53676d", bg = "#fbf3db" }
progress_normal = { fg = "#53676d", bg = "#fbf3db" }

[pick]
active = { fg = "#825dc0" }
border = { fg = "#006dce" }
inactive = { fg = "#53676d" }

[task]
title = { fg = "#006dce" }
border = { fg = "#006dce" }
hovered = { fg = "#53676d", bg = "#d5cdb6" }

[input]
border = { fg = "#006dce" }
selected = { bg = "#d5cdb6" }

[help]
desc = { fg = "#53676d" }
on = { fg = "#00978a" }
run = { fg = "#825dc0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d5cdb6", bg = "#53676d" }

[which]
mask = { bg = "#d5cdb6" }
desc = { fg = "#53676d" }
cand = { fg = "#00978a" }
rest = { fg = "#c44392" }

separator_style = { fg = "#909995" }

[notify]
title_info = { fg = "#00978a" }
title_warn = { fg = "#a78300" }
title_error = { fg = "#cc1729" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00978a" },
  { mime = "{audio, video}/*", fg = "#a78300" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#428b00" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#006dce" },
  { mime = "*", fg = "#53676d" },
]

