[mgr]
cwd = { fg = "#5e8c9b" }

find_keyword = { bold = true, fg = "#e5bc84" }
find_position = { fg = "#98a1d8" }

marker_copied = { fg = "#8ca07b", bg = "#8ca07b" }
marker_cut = { fg = "#c06061", bg = "#c06061" }
marker_selected = { fg = "#e5bc84", bg = "#e5bc84" }

count_copied = { fg = "#1d1d1d", bg = "#8ca07b" }
count_cut = { fg = "#1d1d1d", bg = "#c06061" }
count_selected = { fg = "#1d1d1d", bg = "#e5bc84" }

border_style = { fg = "#839ec9" }

[tabs]
active = { fg = "#1d1d1d", bg = "#839ec9"}
inactive = { fg = "#839ec9", bg = "#282828" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1d1d1d", bg = "#839ec9", bold = true }
normal_alt = { fg = "#839ec9", bg = "#373737" }

select_alt = { fg = "#98a1d8", bg = "#373737" }
select_main = { fg = "#1d1d1d", bg = "#98a1d8", bold = true }

unset_main = { fg = "#1d1d1d", bg = "#c06061", bold = true }
unset_alt = { fg = "#c06061", bg = "#373737" }

[status]
perm_exec = { fg = "#8ca07b" }
perm_read = { fg = "#e5bc84" }
perm_sep = { fg = "#5e8c9b" }
perm_type = { fg = "#839ec9" }
perm_write = { fg = "#c06061" }

progress_error = { fg = "#c06061", bg = "#1d1d1d" }
progress_label = { fg = "#c4cbcf", bg = "#1d1d1d" }
progress_normal = { fg = "#c4cbcf", bg = "#1d1d1d" }

[pick]
active = { fg = "#98a1d8" }
border = { fg = "#839ec9" }
inactive = { fg = "#c4cbcf" }

[task]
title = { fg = "#839ec9" }
border = { fg = "#839ec9" }
hovered = { fg = "#c4cbcf", bg = "#373737" }

[input]
border = { fg = "#839ec9" }
selected = { bg = "#373737" }

[help]
desc = { fg = "#c4cbcf" }
on = { fg = "#5e8c9b" }
run = { fg = "#98a1d8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#373737", bg = "#c4cbcf" }

[which]
mask = { bg = "#373737" }
desc = { fg = "#c4cbcf" }
cand = { fg = "#5e8c9b" }
rest = { fg = "#d9cdb4" }

separator_style = { fg = "#bdaead" }

[notify]
title_info = { fg = "#5e8c9b" }
title_warn = { fg = "#e5bc84" }
title_error = { fg = "#c06061" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5e8c9b" },
  { mime = "{audio, video}/*", fg = "#e5bc84" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8ca07b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#839ec9" },
  { mime = "*", fg = "#c4cbcf" },
]

