[mgr]
cwd = { fg = "#6eb958" }

find_keyword = { bold = true, fg = "#e0ac16" }
find_position = { fg = "#bb90e2" }

marker_copied = { fg = "#b7ba53", bg = "#b7ba53" }
marker_cut = { fg = "#d35c5c", bg = "#d35c5c" }
marker_selected = { fg = "#e0ac16", bg = "#e0ac16" }

count_copied = { fg = "#231e18", bg = "#b7ba53" }
count_cut = { fg = "#231e18", bg = "#d35c5c" }
count_selected = { fg = "#231e18", bg = "#e0ac16" }

border_style = { fg = "#88a4d3" }

[tabs]
active = { fg = "#231e18", bg = "#88a4d3"}
inactive = { fg = "#88a4d3", bg = "#302b25" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#231e18", bg = "#88a4d3", bold = true }
normal_alt = { fg = "#88a4d3", bg = "#48413a" }

select_alt = { fg = "#bb90e2", bg = "#48413a" }
select_main = { fg = "#231e18", bg = "#bb90e2", bold = true }

unset_main = { fg = "#231e18", bg = "#d35c5c", bold = true }
unset_alt = { fg = "#d35c5c", bg = "#48413a" }

[status]
perm_exec = { fg = "#b7ba53" }
perm_read = { fg = "#e0ac16" }
perm_sep = { fg = "#6eb958" }
perm_type = { fg = "#88a4d3" }
perm_write = { fg = "#d35c5c" }

progress_error = { fg = "#d35c5c", bg = "#231e18" }
progress_label = { fg = "#cabcb1", bg = "#231e18" }
progress_normal = { fg = "#cabcb1", bg = "#231e18" }

[pick]
active = { fg = "#bb90e2" }
border = { fg = "#88a4d3" }
inactive = { fg = "#cabcb1" }

[task]
title = { fg = "#88a4d3" }
border = { fg = "#88a4d3" }
hovered = { fg = "#cabcb1", bg = "#48413a" }

[input]
border = { fg = "#88a4d3" }
selected = { bg = "#48413a" }

[help]
desc = { fg = "#cabcb1" }
on = { fg = "#6eb958" }
run = { fg = "#bb90e2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#48413a", bg = "#cabcb1" }

[which]
mask = { bg = "#48413a" }
desc = { fg = "#cabcb1" }
cand = { fg = "#6eb958" }
rest = { fg = "#b49368" }

separator_style = { fg = "#b4a490" }

[notify]
title_info = { fg = "#6eb958" }
title_warn = { fg = "#e0ac16" }
title_error = { fg = "#d35c5c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#6eb958" },
  { mime = "{audio, video}/*", fg = "#e0ac16" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#b7ba53" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#88a4d3" },
  { mime = "*", fg = "#cabcb1" },
]

