[mgr]
cwd = { fg = "#00aaaa" }

find_keyword = { bold = true, fg = "#ffff55" }
find_position = { fg = "#ff55ff" }

marker_copied = { fg = "#00aa00", bg = "#00aa00" }
marker_cut = { fg = "#aa0000", bg = "#aa0000" }
marker_selected = { fg = "#ffff55", bg = "#ffff55" }

count_copied = { fg = "#000000", bg = "#00aa00" }
count_cut = { fg = "#000000", bg = "#aa0000" }
count_selected = { fg = "#000000", bg = "#ffff55" }

border_style = { fg = "#5555ff" }

[tabs]
active = { fg = "#000000", bg = "#5555ff"}
inactive = { fg = "#5555ff", bg = #333333" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#000000", bg = "#5555ff", bold = true }
normal_alt = { fg = "#5555ff", bg = "#444444" }

select_alt = { fg = "#ff55ff", bg = "#444444" }
select_main = { fg = "#000000", bg = "#ff55ff", bold = true }

unset_main = { fg = "#000000", bg = "#aa0000", bold = true }
unset_alt = { fg = "#aa0000", bg = "#444444" }

[status]
perm_exec = { fg = "#00aa00" }
perm_read = { fg = "#ffff55" }
perm_sep = { fg = "#00aaaa" }
perm_type = { fg = "#5555ff" }
perm_write = { fg = "#aa0000" }

progress_error = { fg = "#aa0000", bg = "#000000" }
progress_label = { fg = "#aaaaaa", bg = "#000000" }
progress_normal = { fg = "#aaaaaa", bg = "#000000" }

[pick]
active = { fg = "#ff55ff" }
border = { fg = "#5555ff" }
inactive = { fg = "#aaaaaa" }

[task]
title = { fg = "#5555ff" }
border = { fg = "#5555ff" }
hovered = { fg = "#aaaaaa", bg = "#444444" }

[input]
border = { fg = "#5555ff" }
selected = { bg = "#444444" }

[help]
desc = { fg = "#aaaaaa" }
on = { fg = "#00aaaa" }
run = { fg = "#ff55ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#444444", bg = "#aaaaaa" }

[which]
mask = { bg = "#444444" }
desc = { fg = "#aaaaaa" }
cand = { fg = "#00aaaa" }
rest = { fg = "#aa5500" }

separator_style = { fg = "#888888" }

[notify]
title_info = { fg = "#00aaaa" }
title_warn = { fg = "#ffff55" }
title_error = { fg = "#aa0000" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00aaaa" },
  { mime = "{audio, video}/*", fg = "#ffff55" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00aa00" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#5555ff" },
  { mime = "*", fg = "#aaaaaa" },
]

