[mgr]
cwd = { fg = "#47f9f5" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#bd9701" }
find_position = { fg = "#8f6c97" }

marker_copied = { fg = "#5bb66a", bg = "#5bb66a" }
marker_cut = { fg = "#f80059", bg = "#f80059" }
marker_selected = { fg = "#bd9701", bg = "#bd9701" }

tab_inactive = { fg = "#5a496e" }
tab_active = { fg = "#feffff", bg = "#5a496e"}

count_copied = { fg = "#feffff", bg = "#5bb66a" }
count_cut = { fg = "#feffff", bg = "#f80059" }
count_selected = { fg = "#feffff", bg = "#bd9701" }

border_style = { fg = "#5ba2b6" }

[mode]
normal_main = { fg = "#feffff", bg = "#5ba2b6", bold = true }
normal_alt = { fg = "#5ba2b6", bg = "#bdb6c5" }

select_alt = { fg = "#8f6c97", bg = "#bdb6c5" }
select_main = { fg = "#feffff", bg = "#8f6c97", bold = true }

unset_main = { fg = "#feffff", bg = "#f80059", bold = true }
unset_alt = { fg = "#f80059", bg = "#bdb6c5" }

[status]
perm_exec = { fg = "#5bb66a" }
perm_read = { fg = "#bd9701" }
perm_sep = { fg = "#47f9f5" }
perm_type = { fg = "#5ba2b6" }
perm_write = { fg = "#f80059" }

progress_error = { fg = "#f80059", bg = "#feffff" }
progress_label = { fg = "#5a496e", bg = "#feffff" }
progress_normal = { fg = "#5a496e", bg = "#feffff" }

[pick]
active = { fg = "#8f6c97" }
border = { fg = "#5ba2b6" }
inactive = { fg = "#5a496e" }

[task]
title = { fg = "#5ba2b6" }
border = { fg = "#5ba2b6" }
hovered = { fg = "#5a496e", bg = "#bdb6c5" }

[input]
border = { fg = "#5ba2b6" }
selected = { bg = "#bdb6c5" }

[help]
desc = { fg = "#5a496e" }
on = { fg = "#47f9f5" }
run = { fg = "#8f6c97" }
hovered = { reversed = true, bold = true }
footer = { fg = "#bdb6c5", bg = "#5a496e" }

[which]
mask = { bg = "#bdb6c5" }
desc = { fg = "#5a496e" }
cand = { fg = "#47f9f5" }
rest = { fg = "#58425d" }

separator_style = { fg = "#7b6d8b" }

[notify]
title_info = { fg = "#47f9f5" }
title_warn = { fg = "#bd9701" }
title_error = { fg = "#f80059" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#47f9f5" },
  { mime = "{audio, video}/*", fg = "#bd9701" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5bb66a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#5ba2b6" },
  { mime = "*", fg = "#5a496e" },
]


