[mgr]
cwd = { fg = "#81c8be" }

find_keyword = { bold = true, fg = "#e5c890" }
find_position = { fg = "#ca9ee6" }

marker_copied = { fg = "#a6d189", bg = "#a6d189" }
marker_cut = { fg = "#e78284", bg = "#e78284" }
marker_selected = { fg = "#e5c890", bg = "#e5c890" }

count_copied = { fg = "#303446", bg = "#a6d189" }
count_cut = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#e5c890" }

border_style = { fg = "#8caaee" }

[tabs]
active = { fg = "#303446", bg = "#8caaee"}
inactive = { fg = "#8caaee", bg = "#292c3c" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#303446", bg = "#8caaee", bold = true }
normal_alt = { fg = "#8caaee", bg = "#414559" }

select_alt = { fg = "#ca9ee6", bg = "#414559" }
select_main = { fg = "#303446", bg = "#ca9ee6", bold = true }

unset_main = { fg = "#303446", bg = "#e78284", bold = true }
unset_alt = { fg = "#e78284", bg = "#414559" }

[status]
perm_exec = { fg = "#a6d189" }
perm_read = { fg = "#e5c890" }
perm_sep = { fg = "#81c8be" }
perm_type = { fg = "#8caaee" }
perm_write = { fg = "#e78284" }

progress_error = { fg = "#e78284", bg = "#303446" }
progress_label = { fg = "#c6d0f5", bg = "#303446" }
progress_normal = { fg = "#c6d0f5", bg = "#303446" }

[pick]
active = { fg = "#ca9ee6" }
border = { fg = "#8caaee" }
inactive = { fg = "#c6d0f5" }

[task]
title = { fg = "#8caaee" }
border = { fg = "#8caaee" }
hovered = { fg = "#c6d0f5", bg = "#414559" }

[input]
border = { fg = "#8caaee" }
selected = { bg = "#414559" }

[help]
desc = { fg = "#c6d0f5" }
on = { fg = "#81c8be" }
run = { fg = "#ca9ee6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#414559", bg = "#c6d0f5" }

[which]
mask = { bg = "#414559" }
desc = { fg = "#c6d0f5" }
cand = { fg = "#81c8be" }
rest = { fg = "#eebebe" }

separator_style = { fg = "#626880" }

[notify]
title_info = { fg = "#81c8be" }
title_warn = { fg = "#e5c890" }
title_error = { fg = "#e78284" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#81c8be" },
  { mime = "{audio, video}/*", fg = "#e5c890" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a6d189" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#8caaee" },
  { mime = "*", fg = "#c6d0f5" },
]

