[mgr]
cwd = { fg = "#9bc7bf" }

find_keyword = { bold = true, fg = "#c7c691" }
find_position = { fg = "#c594ff" }

marker_copied = { fg = "#acc79b", bg = "#acc79b" }
marker_cut = { fg = "#c79987", bg = "#c79987" }
marker_selected = { fg = "#c7c691", bg = "#c7c691" }

count_copied = { fg = "#2b213c", bg = "#acc79b" }
count_cut = { fg = "#2b213c", bg = "#c79987" }
count_selected = { fg = "#2b213c", bg = "#c7c691" }

border_style = { fg = "#a5aad4" }

[tabs]
active = { fg = "#2b213c", bg = "#a5aad4"}
inactive = { fg = "#a5aad4", bg = "#362b48" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2b213c", bg = "#a5aad4", bold = true }
normal_alt = { fg = "#a5aad4", bg = "#4d4160" }

select_alt = { fg = "#c594ff", bg = "#4d4160" }
select_main = { fg = "#2b213c", bg = "#c594ff", bold = true }

unset_main = { fg = "#2b213c", bg = "#c79987", bold = true }
unset_alt = { fg = "#c79987", bg = "#4d4160" }

[status]
perm_exec = { fg = "#acc79b" }
perm_read = { fg = "#c7c691" }
perm_sep = { fg = "#9bc7bf" }
perm_type = { fg = "#a5aad4" }
perm_write = { fg = "#c79987" }

progress_error = { fg = "#c79987", bg = "#2b213c" }
progress_label = { fg = "#998bad", bg = "#2b213c" }
progress_normal = { fg = "#998bad", bg = "#2b213c" }

[pick]
active = { fg = "#c594ff" }
border = { fg = "#a5aad4" }
inactive = { fg = "#998bad" }

[task]
title = { fg = "#a5aad4" }
border = { fg = "#a5aad4" }
hovered = { fg = "#998bad", bg = "#4d4160" }

[input]
border = { fg = "#a5aad4" }
selected = { bg = "#4d4160" }

[help]
desc = { fg = "#998bad" }
on = { fg = "#9bc7bf" }
run = { fg = "#c594ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4d4160", bg = "#998bad" }

[which]
mask = { bg = "#4d4160" }
desc = { fg = "#998bad" }
cand = { fg = "#9bc7bf" }
rest = { fg = "#c7ab87" }

separator_style = { fg = "#7f7192" }

[notify]
title_info = { fg = "#9bc7bf" }
title_warn = { fg = "#c7c691" }
title_error = { fg = "#c79987" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#9bc7bf" },
  { mime = "{audio, video}/*", fg = "#c7c691" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#acc79b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#a5aad4" },
  { mime = "*", fg = "#998bad" },
]

