[mgr]
cwd = { fg = "#24837b" }

find_keyword = { bold = true, fg = "#ad8301" }
find_position = { fg = "#5e409d" }

marker_copied = { fg = "#66800b", bg = "#66800b" }
marker_cut = { fg = "#af3029", bg = "#af3029" }
marker_selected = { fg = "#ad8301", bg = "#ad8301" }

count_copied = { fg = "#fffcf0", bg = "#66800b" }
count_cut = { fg = "#fffcf0", bg = "#af3029" }
count_selected = { fg = "#fffcf0", bg = "#ad8301" }

border_style = { fg = "#205ea6" }

[tabs]
active = { fg = "#fffcf0", bg = "#205ea6"}
inactive = { fg = "#205ea6", bg = "#f2f0e5" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fffcf0", bg = "#205ea6", bold = true }
normal_alt = { fg = "#205ea6", bg = "#e6e4d9" }

select_alt = { fg = "#5e409d", bg = "#e6e4d9" }
select_main = { fg = "#fffcf0", bg = "#5e409d", bold = true }

unset_main = { fg = "#fffcf0", bg = "#af3029", bold = true }
unset_alt = { fg = "#af3029", bg = "#e6e4d9" }

[status]
perm_exec = { fg = "#66800b" }
perm_read = { fg = "#ad8301" }
perm_sep = { fg = "#24837b" }
perm_type = { fg = "#205ea6" }
perm_write = { fg = "#af3029" }

progress_error = { fg = "#af3029", bg = "#fffcf0" }
progress_label = { fg = "#403e3c", bg = "#fffcf0" }
progress_normal = { fg = "#403e3c", bg = "#fffcf0" }

[pick]
active = { fg = "#5e409d" }
border = { fg = "#205ea6" }
inactive = { fg = "#403e3c" }

[task]
title = { fg = "#205ea6" }
border = { fg = "#205ea6" }
hovered = { fg = "#403e3c", bg = "#e6e4d9" }

[input]
border = { fg = "#205ea6" }
selected = { bg = "#e6e4d9" }

[help]
desc = { fg = "#403e3c" }
on = { fg = "#24837b" }
run = { fg = "#5e409d" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e6e4d9", bg = "#403e3c" }

[which]
mask = { bg = "#e6e4d9" }
desc = { fg = "#403e3c" }
cand = { fg = "#24837b" }
rest = { fg = "#a02f6f" }

separator_style = { fg = "#9f9d96" }

[notify]
title_info = { fg = "#24837b" }
title_warn = { fg = "#ad8301" }
title_error = { fg = "#af3029" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#24837b" },
  { mime = "{audio, video}/*", fg = "#ad8301" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#66800b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#205ea6" },
  { mime = "*", fg = "#403e3c" },
]

