[mgr]
cwd = { fg = "#9ccfd8" }

find_keyword = { bold = true, fg = "#ea9a97" }
find_position = { fg = "#f6c177" }

marker_copied = { fg = "#3e8fb0", bg = "#3e8fb0" }
marker_cut = { fg = "#eb6f92", bg = "#eb6f92" }
marker_selected = { fg = "#ea9a97", bg = "#ea9a97" }

count_copied = { fg = "#232136", bg = "#3e8fb0" }
count_cut = { fg = "#232136", bg = "#eb6f92" }
count_selected = { fg = "#232136", bg = "#ea9a97" }

border_style = { fg = "#c4a7e7" }

[tabs]
active = { fg = "#232136", bg = "#c4a7e7"}
inactive = { fg = "#c4a7e7", bg = #2a273f" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#232136", bg = "#c4a7e7", bold = true }
normal_alt = { fg = "#c4a7e7", bg = "#393552" }

select_alt = { fg = "#f6c177", bg = "#393552" }
select_main = { fg = "#232136", bg = "#f6c177", bold = true }

unset_main = { fg = "#232136", bg = "#eb6f92", bold = true }
unset_alt = { fg = "#eb6f92", bg = "#393552" }

[status]
perm_exec = { fg = "#3e8fb0" }
perm_read = { fg = "#ea9a97" }
perm_sep = { fg = "#9ccfd8" }
perm_type = { fg = "#c4a7e7" }
perm_write = { fg = "#eb6f92" }

progress_error = { fg = "#eb6f92", bg = "#232136" }
progress_label = { fg = "#e0def4", bg = "#232136" }
progress_normal = { fg = "#e0def4", bg = "#232136" }

[pick]
active = { fg = "#f6c177" }
border = { fg = "#c4a7e7" }
inactive = { fg = "#e0def4" }

[task]
title = { fg = "#c4a7e7" }
border = { fg = "#c4a7e7" }
hovered = { fg = "#e0def4", bg = "#393552" }

[input]
border = { fg = "#c4a7e7" }
selected = { bg = "#393552" }

[help]
desc = { fg = "#e0def4" }
on = { fg = "#9ccfd8" }
run = { fg = "#f6c177" }
hovered = { reversed = true, bold = true }
footer = { fg = "#393552", bg = "#e0def4" }

[which]
mask = { bg = "#393552" }
desc = { fg = "#e0def4" }
cand = { fg = "#9ccfd8" }
rest = { fg = "#56526e" }

separator_style = { fg = "#908caa" }

[notify]
title_info = { fg = "#9ccfd8" }
title_warn = { fg = "#ea9a97" }
title_error = { fg = "#eb6f92" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#9ccfd8" },
  { mime = "{audio, video}/*", fg = "#ea9a97" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#3e8fb0" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#c4a7e7" },
  { mime = "*", fg = "#e0def4" },
]

