[mgr]
cwd = { fg = "#42bda7" }

find_keyword = { bold = true, fg = "#d0a543" }
find_position = { fg = "#b799fe" }

marker_copied = { fg = "#95b658", bg = "#95b658" }
marker_cut = { fg = "#ff8782", bg = "#ff8782" }
marker_selected = { fg = "#d0a543", bg = "#d0a543" }

count_copied = { fg = "#1c1e20", bg = "#95b658" }
count_cut = { fg = "#1c1e20", bg = "#ff8782" }
count_selected = { fg = "#1c1e20", bg = "#d0a543" }

border_style = { fg = "#68b0ee" }

[tabs]
active = { fg = "#1c1e20", bg = "#68b0ee"}
inactive = { fg = "#68b0ee", bg = #292b2d" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1c1e20", bg = "#68b0ee", bold = true }
normal_alt = { fg = "#68b0ee", bg = "#37393a" }

select_alt = { fg = "#b799fe", bg = "#37393a" }
select_main = { fg = "#1c1e20", bg = "#b799fe", bold = true }

unset_main = { fg = "#1c1e20", bg = "#ff8782", bold = true }
unset_alt = { fg = "#ff8782", bg = "#37393a" }

[status]
perm_exec = { fg = "#95b658" }
perm_read = { fg = "#d0a543" }
perm_sep = { fg = "#42bda7" }
perm_type = { fg = "#68b0ee" }
perm_write = { fg = "#ff8782" }

progress_error = { fg = "#ff8782", bg = "#1c1e20" }
progress_label = { fg = "#b8b7b6", bg = "#1c1e20" }
progress_normal = { fg = "#b8b7b6", bg = "#1c1e20" }

[pick]
active = { fg = "#b799fe" }
border = { fg = "#68b0ee" }
inactive = { fg = "#b8b7b6" }

[task]
title = { fg = "#68b0ee" }
border = { fg = "#68b0ee" }
hovered = { fg = "#b8b7b6", bg = "#37393a" }

[input]
border = { fg = "#68b0ee" }
selected = { bg = "#37393a" }

[help]
desc = { fg = "#b8b7b6" }
on = { fg = "#42bda7" }
run = { fg = "#b799fe" }
hovered = { reversed = true, bold = true }
footer = { fg = "#37393a", bg = "#b8b7b6" }

[which]
mask = { bg = "#37393a" }
desc = { fg = "#b8b7b6" }
cand = { fg = "#42bda7" }
rest = { fg = "#f382d8" }

separator_style = { fg = "#a8a8a7" }

[notify]
title_info = { fg = "#42bda7" }
title_warn = { fg = "#d0a543" }
title_error = { fg = "#ff8782" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#42bda7" },
  { mime = "{audio, video}/*", fg = "#d0a543" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#95b658" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#68b0ee" },
  { mime = "*", fg = "#b8b7b6" },
]

