[mgr]
cwd = { fg = "#5fd1ff" }

find_keyword = { bold = true, fg = "#f6cd5c" }
find_position = { fg = "#ff84dd" }

marker_copied = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut = { fg = "#4ce587", bg = "#4ce587" }
marker_selected = { fg = "#f6cd5c", bg = "#f6cd5c" }

count_copied = { fg = "#182430", bg = "#c3e88d" }
count_cut = { fg = "#182430", bg = "#4ce587" }
count_selected = { fg = "#182430", bg = "#f6cd5c" }

border_style = { fg = "#82aaff" }

[tabs]
active = { fg = "#182430", bg = "#82aaff"}
inactive = { fg = "#82aaff", bg = "#243c54" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#182430", bg = "#82aaff", bold = true }
normal_alt = { fg = "#82aaff", bg = "#46290a" }

select_alt = { fg = "#ff84dd", bg = "#46290a" }
select_main = { fg = "#182430", bg = "#ff84dd", bold = true }

unset_main = { fg = "#182430", bg = "#4ce587", bold = true }
unset_alt = { fg = "#4ce587", bg = "#46290a" }

[status]
perm_exec = { fg = "#c3e88d" }
perm_read = { fg = "#f6cd5c" }
perm_sep = { fg = "#5fd1ff" }
perm_type = { fg = "#82aaff" }
perm_write = { fg = "#4ce587" }

progress_error = { fg = "#4ce587", bg = "#182430" }
progress_label = { fg = "#c8e1f8", bg = "#182430" }
progress_normal = { fg = "#c8e1f8", bg = "#182430" }

[pick]
active = { fg = "#ff84dd" }
border = { fg = "#82aaff" }
inactive = { fg = "#c8e1f8" }

[task]
title = { fg = "#82aaff" }
border = { fg = "#82aaff" }
hovered = { fg = "#c8e1f8", bg = "#46290a" }

[input]
border = { fg = "#82aaff" }
selected = { bg = "#46290a" }

[help]
desc = { fg = "#c8e1f8" }
on = { fg = "#5fd1ff" }
run = { fg = "#ff84dd" }
hovered = { reversed = true, bold = true }
footer = { fg = "#46290a", bg = "#c8e1f8" }

[which]
mask = { bg = "#46290a" }
desc = { fg = "#c8e1f8" }
cand = { fg = "#5fd1ff" }
rest = { fg = "#bbd2e8" }

separator_style = { fg = "#74afe7" }

[notify]
title_info = { fg = "#5fd1ff" }
title_warn = { fg = "#f6cd5c" }
title_error = { fg = "#4ce587" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5fd1ff" },
  { mime = "{audio, video}/*", fg = "#f6cd5c" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#c3e88d" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#82aaff" },
  { mime = "*", fg = "#c8e1f8" },
]

