[mgr]
cwd = { fg = "#110e06" }

find_keyword = { bold = true, fg = "#110e06" }
find_position = { fg = "#382e1b" }

marker_copied = { fg = "#110e06", bg = "#110e06" }
marker_cut = { fg = "#382e1b", bg = "#382e1b" }
marker_selected = { fg = "#110e06", bg = "#110e06" }

count_copied = { fg = "#cabda0", bg = "#110e06" }
count_cut = { fg = "#cabda0", bg = "#382e1b" }
count_selected = { fg = "#cabda0", bg = "#110e06" }

border_style = { fg = "#251e0f" }

[tabs]
active = { fg = "#cabda0", bg = "#251e0f"}
inactive = { fg = "#251e0f", bg = #bcad8c" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#cabda0", bg = "#251e0f", bold = true }
normal_alt = { fg = "#251e0f", bg = "#af9f7d" }

select_alt = { fg = "#382e1b", bg = "#af9f7d" }
select_main = { fg = "#cabda0", bg = "#382e1b", bold = true }

unset_main = { fg = "#cabda0", bg = "#382e1b", bold = true }
unset_alt = { fg = "#382e1b", bg = "#af9f7d" }

[status]
perm_exec = { fg = "#110e06" }
perm_read = { fg = "#110e06" }
perm_sep = { fg = "#110e06" }
perm_type = { fg = "#251e0f" }
perm_write = { fg = "#382e1b" }

progress_error = { fg = "#382e1b", bg = "#cabda0" }
progress_label = { fg = "#382e1b", bg = "#cabda0" }
progress_normal = { fg = "#382e1b", bg = "#cabda0" }

[pick]
active = { fg = "#382e1b" }
border = { fg = "#251e0f" }
inactive = { fg = "#382e1b" }

[task]
title = { fg = "#251e0f" }
border = { fg = "#251e0f" }
hovered = { fg = "#382e1b", bg = "#af9f7d" }

[input]
border = { fg = "#251e0f" }
selected = { bg = "#af9f7d" }

[help]
desc = { fg = "#382e1b" }
on = { fg = "#110e06" }
run = { fg = "#382e1b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#af9f7d", bg = "#382e1b" }

[which]
mask = { bg = "#af9f7d" }
desc = { fg = "#382e1b" }
cand = { fg = "#110e06" }
rest = { fg = "#4b3e26" }

separator_style = { fg = "#110e06" }

[notify]
title_info = { fg = "#110e06" }
title_warn = { fg = "#110e06" }
title_error = { fg = "#382e1b" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#110e06" },
  { mime = "{audio, video}/*", fg = "#110e06" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#110e06" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#251e0f" },
  { mime = "*", fg = "#382e1b" },
]

