[mgr]
cwd = { fg = "#30dff3" }

find_keyword = { bold = true, fg = "#f0c239" }
find_position = { fg = "#cca4e3" }

marker_copied = { fg = "#8ab361", bg = "#8ab361" }
marker_cut = { fg = "#f9906f", bg = "#f9906f" }
marker_selected = { fg = "#f0c239", bg = "#f0c239" }

count_copied = { fg = "#2d302f", bg = "#8ab361" }
count_cut = { fg = "#2d302f", bg = "#f9906f" }
count_selected = { fg = "#2d302f", bg = "#f0c239" }

border_style = { fg = "#b0a4e3" }

[tabs]
active = { fg = "#2d302f", bg = "#b0a4e3"}
inactive = { fg = "#b0a4e3", bg = #434846" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2d302f", bg = "#b0a4e3", bold = true }
normal_alt = { fg = "#b0a4e3", bg = "#5a605d" }

select_alt = { fg = "#cca4e3", bg = "#5a605d" }
select_main = { fg = "#2d302f", bg = "#cca4e3", bold = true }

unset_main = { fg = "#2d302f", bg = "#f9906f", bold = true }
unset_alt = { fg = "#f9906f", bg = "#5a605d" }

[status]
perm_exec = { fg = "#8ab361" }
perm_read = { fg = "#f0c239" }
perm_sep = { fg = "#30dff3" }
perm_type = { fg = "#b0a4e3" }
perm_write = { fg = "#f9906f" }

progress_error = { fg = "#f9906f", bg = "#2d302f" }
progress_label = { fg = "#e0f0ef", bg = "#2d302f" }
progress_normal = { fg = "#e0f0ef", bg = "#2d302f" }

[pick]
active = { fg = "#cca4e3" }
border = { fg = "#b0a4e3" }
inactive = { fg = "#e0f0ef" }

[task]
title = { fg = "#b0a4e3" }
border = { fg = "#b0a4e3" }
hovered = { fg = "#e0f0ef", bg = "#5a605d" }

[input]
border = { fg = "#b0a4e3" }
selected = { bg = "#5a605d" }

[help]
desc = { fg = "#e0f0ef" }
on = { fg = "#30dff3" }
run = { fg = "#cca4e3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5a605d", bg = "#e0f0ef" }

[which]
mask = { bg = "#5a605d" }
desc = { fg = "#e0f0ef" }
cand = { fg = "#30dff3" }
rest = { fg = "#ca6924" }

separator_style = { fg = "#cad8d2" }

[notify]
title_info = { fg = "#30dff3" }
title_warn = { fg = "#f0c239" }
title_error = { fg = "#f9906f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#30dff3" },
  { mime = "{audio, video}/*", fg = "#f0c239" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8ab361" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#b0a4e3" },
  { mime = "*", fg = "#e0f0ef" },
]

