[mgr]
cwd = { fg = "#00a1de" }

find_keyword = { bold = true, fg = "#f9e300" }
find_position = { fg = "#e27ea6" }

marker_copied = { fg = "#009b3a", bg = "#009b3a" }
marker_cut = { fg = "#c60c30", bg = "#c60c30" }
marker_selected = { fg = "#f9e300", bg = "#f9e300" }

count_copied = { fg = "#1e2a24", bg = "#009b3a" }
count_cut = { fg = "#1e2a24", bg = "#c60c30" }
count_selected = { fg = "#1e2a24", bg = "#f9e300" }

border_style = { fg = "#522398" }

[tabs]
active = { fg = "#1e2a24", bg = "#522398"}
inactive = { fg = "#522398", bg = #2a3b32" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1e2a24", bg = "#522398", bold = true }
normal_alt = { fg = "#522398", bg = "#364c40" }

select_alt = { fg = "#e27ea6", bg = "#364c40" }
select_main = { fg = "#1e2a24", bg = "#e27ea6", bold = true }

unset_main = { fg = "#1e2a24", bg = "#c60c30", bold = true }
unset_alt = { fg = "#c60c30", bg = "#364c40" }

[status]
perm_exec = { fg = "#009b3a" }
perm_read = { fg = "#f9e300" }
perm_sep = { fg = "#00a1de" }
perm_type = { fg = "#522398" }
perm_write = { fg = "#c60c30" }

progress_error = { fg = "#c60c30", bg = "#1e2a24" }
progress_label = { fg = "#a7b8af", bg = "#1e2a24" }
progress_normal = { fg = "#a7b8af", bg = "#1e2a24" }

[pick]
active = { fg = "#e27ea6" }
border = { fg = "#522398" }
inactive = { fg = "#a7b8af" }

[task]
title = { fg = "#522398" }
border = { fg = "#522398" }
hovered = { fg = "#a7b8af", bg = "#364c40" }

[input]
border = { fg = "#522398" }
selected = { bg = "#364c40" }

[help]
desc = { fg = "#a7b8af" }
on = { fg = "#00a1de" }
run = { fg = "#e27ea6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#364c40", bg = "#a7b8af" }

[which]
mask = { bg = "#364c40" }
desc = { fg = "#a7b8af" }
cand = { fg = "#00a1de" }
rest = { fg = "#62361b" }

separator_style = { fg = "#8a9a91" }

[notify]
title_info = { fg = "#00a1de" }
title_warn = { fg = "#f9e300" }
title_error = { fg = "#c60c30" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00a1de" },
  { mime = "{audio, video}/*", fg = "#f9e300" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#009b3a" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#522398" },
  { mime = "*", fg = "#a7b8af" },
]

