[mgr]
cwd = { fg = "#94e2d5" }

find_keyword = { bold = true, fg = "#f9e2af" }
find_position = { fg = "#cba6f7" }

marker_copied = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }
marker_selected = { fg = "#f9e2af", bg = "#f9e2af" }

count_copied = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#f9e2af" }

border_style = { fg = "#89b4fa" }

[tabs]
active = { fg = "#1e1e2e", bg = "#89b4fa"}
inactive = { fg = "#89b4fa", bg = "#181825" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
normal_alt = { fg = "#89b4fa", bg = "#313244" }

select_alt = { fg = "#cba6f7", bg = "#313244" }
select_main = { fg = "#1e1e2e", bg = "#cba6f7", bold = true }

unset_main = { fg = "#1e1e2e", bg = "#f38ba8", bold = true }
unset_alt = { fg = "#f38ba8", bg = "#313244" }

[status]
perm_exec = { fg = "#a6e3a1" }
perm_read = { fg = "#f9e2af" }
perm_sep = { fg = "#94e2d5" }
perm_type = { fg = "#89b4fa" }
perm_write = { fg = "#f38ba8" }

progress_error = { fg = "#f38ba8", bg = "#1e1e2e" }
progress_label = { fg = "#cdd6f4", bg = "#1e1e2e" }
progress_normal = { fg = "#cdd6f4", bg = "#1e1e2e" }

[pick]
active = { fg = "#cba6f7" }
border = { fg = "#89b4fa" }
inactive = { fg = "#cdd6f4" }

[task]
title = { fg = "#89b4fa" }
border = { fg = "#89b4fa" }
hovered = { fg = "#cdd6f4", bg = "#313244" }

[input]
border = { fg = "#89b4fa" }
selected = { bg = "#313244" }

[help]
desc = { fg = "#cdd6f4" }
on = { fg = "#94e2d5" }
run = { fg = "#cba6f7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#313244", bg = "#cdd6f4" }

[which]
mask = { bg = "#313244" }
desc = { fg = "#cdd6f4" }
cand = { fg = "#94e2d5" }
rest = { fg = "#f2cdcd" }

separator_style = { fg = "#585b70" }

[notify]
title_info = { fg = "#94e2d5" }
title_warn = { fg = "#f9e2af" }
title_error = { fg = "#f38ba8" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#94e2d5" },
  { mime = "{audio, video}/*", fg = "#f9e2af" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#89b4fa" },
  { mime = "*", fg = "#cdd6f4" },
]

