[mgr]
cwd = { fg = "#519f50" }

find_keyword = { bold = true, fg = "#ffc66d" }
find_position = { fg = "#b6b3eb" }

marker_copied = { fg = "#a5c261", bg = "#a5c261" }
marker_cut = { fg = "#da4939", bg = "#da4939" }
marker_selected = { fg = "#ffc66d", bg = "#ffc66d" }

count_copied = { fg = "#2b2b2b", bg = "#a5c261" }
count_cut = { fg = "#2b2b2b", bg = "#da4939" }
count_selected = { fg = "#2b2b2b", bg = "#ffc66d" }

border_style = { fg = "#6d9cbe" }

[tabs]
active = { fg = "#2b2b2b", bg = "#6d9cbe"}
inactive = { fg = "#6d9cbe", bg = #272935" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2b2b2b", bg = "#6d9cbe", bold = true }
normal_alt = { fg = "#6d9cbe", bg = "#3a4055" }

select_alt = { fg = "#b6b3eb", bg = "#3a4055" }
select_main = { fg = "#2b2b2b", bg = "#b6b3eb", bold = true }

unset_main = { fg = "#2b2b2b", bg = "#da4939", bold = true }
unset_alt = { fg = "#da4939", bg = "#3a4055" }

[status]
perm_exec = { fg = "#a5c261" }
perm_read = { fg = "#ffc66d" }
perm_sep = { fg = "#519f50" }
perm_type = { fg = "#6d9cbe" }
perm_write = { fg = "#da4939" }

progress_error = { fg = "#da4939", bg = "#2b2b2b" }
progress_label = { fg = "#e6e1dc", bg = "#2b2b2b" }
progress_normal = { fg = "#e6e1dc", bg = "#2b2b2b" }

[pick]
active = { fg = "#b6b3eb" }
border = { fg = "#6d9cbe" }
inactive = { fg = "#e6e1dc" }

[task]
title = { fg = "#6d9cbe" }
border = { fg = "#6d9cbe" }
hovered = { fg = "#e6e1dc", bg = "#3a4055" }

[input]
border = { fg = "#6d9cbe" }
selected = { bg = "#3a4055" }

[help]
desc = { fg = "#e6e1dc" }
on = { fg = "#519f50" }
run = { fg = "#b6b3eb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3a4055", bg = "#e6e1dc" }

[which]
mask = { bg = "#3a4055" }
desc = { fg = "#e6e1dc" }
cand = { fg = "#519f50" }
rest = { fg = "#bc9458" }

separator_style = { fg = "#d4cfc9" }

[notify]
title_info = { fg = "#519f50" }
title_warn = { fg = "#ffc66d" }
title_error = { fg = "#da4939" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#519f50" },
  { mime = "{audio, video}/*", fg = "#ffc66d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a5c261" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6d9cbe" },
  { mime = "*", fg = "#e6e1dc" },
]

