[mgr]
cwd = { fg = "#1c9aa0" }

find_keyword = { bold = true, fg = "#a07e3b" }
find_position = { fg = "#55859b" }

marker_copied = { fg = "#489963", bg = "#489963" }
marker_cut = { fg = "#b16139", bg = "#b16139" }
marker_selected = { fg = "#a07e3b", bg = "#a07e3b" }

count_copied = { fg = "#ecf4ee", bg = "#489963" }
count_cut = { fg = "#ecf4ee", bg = "#b16139" }
count_selected = { fg = "#ecf4ee", bg = "#a07e3b" }

border_style = { fg = "#478c90" }

[tabs]
active = { fg = "#ecf4ee", bg = "#478c90"}
inactive = { fg = "#478c90", bg = #dfe7e2" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ecf4ee", bg = "#478c90", bold = true }
normal_alt = { fg = "#478c90", bg = "#87928a" }

select_alt = { fg = "#55859b", bg = "#87928a" }
select_main = { fg = "#ecf4ee", bg = "#55859b", bold = true }

unset_main = { fg = "#ecf4ee", bg = "#b16139", bold = true }
unset_alt = { fg = "#b16139", bg = "#87928a" }

[status]
perm_exec = { fg = "#489963" }
perm_read = { fg = "#a07e3b" }
perm_sep = { fg = "#1c9aa0" }
perm_type = { fg = "#478c90" }
perm_write = { fg = "#b16139" }

progress_error = { fg = "#b16139", bg = "#ecf4ee" }
progress_label = { fg = "#526057", bg = "#ecf4ee" }
progress_normal = { fg = "#526057", bg = "#ecf4ee" }

[pick]
active = { fg = "#55859b" }
border = { fg = "#478c90" }
inactive = { fg = "#526057" }

[task]
title = { fg = "#478c90" }
border = { fg = "#478c90" }
hovered = { fg = "#526057", bg = "#87928a" }

[input]
border = { fg = "#478c90" }
selected = { bg = "#87928a" }

[help]
desc = { fg = "#526057" }
on = { fg = "#1c9aa0" }
run = { fg = "#55859b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#87928a", bg = "#526057" }

[which]
mask = { bg = "#87928a" }
desc = { fg = "#526057" }
cand = { fg = "#1c9aa0" }
rest = { fg = "#867469" }

separator_style = { fg = "#5f6d64" }

[notify]
title_info = { fg = "#1c9aa0" }
title_warn = { fg = "#a07e3b" }
title_error = { fg = "#b16139" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1c9aa0" },
  { mime = "{audio, video}/*", fg = "#a07e3b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#489963" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#478c90" },
  { mime = "*", fg = "#526057" },
]

