[mgr]
cwd = { fg = "#2dccd3" }

find_keyword = { bold = true, fg = "#fbdd40" }
find_position = { fg = "#d59ed7" }

marker_copied = { fg = "#78d64b", bg = "#78d64b" }
marker_cut = { fg = "#ff585d", bg = "#ff585d" }
marker_selected = { fg = "#fbdd40", bg = "#fbdd40" }

count_copied = { fg = "#072b31", bg = "#78d64b" }
count_cut = { fg = "#072b31", bg = "#ff585d" }
count_selected = { fg = "#072b31", bg = "#fbdd40" }

border_style = { fg = "#4698cb" }

[tabs]
active = { fg = "#072b31", bg = "#4698cb"}
inactive = { fg = "#4698cb", bg = "#00313c" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#072b31", bg = "#4698cb", bold = true }
normal_alt = { fg = "#4698cb", bg = "#003c46" }

select_alt = { fg = "#d59ed7", bg = "#003c46" }
select_main = { fg = "#072b31", bg = "#d59ed7", bold = true }

unset_main = { fg = "#072b31", bg = "#ff585d", bold = true }
unset_alt = { fg = "#ff585d", bg = "#003c46" }

[status]
perm_exec = { fg = "#78d64b" }
perm_read = { fg = "#fbdd40" }
perm_sep = { fg = "#2dccd3" }
perm_type = { fg = "#4698cb" }
perm_write = { fg = "#ff585d" }

progress_error = { fg = "#ff585d", bg = "#072b31" }
progress_label = { fg = "#f4f5f0", bg = "#072b31" }
progress_normal = { fg = "#f4f5f0", bg = "#072b31" }

[pick]
active = { fg = "#d59ed7" }
border = { fg = "#4698cb" }
inactive = { fg = "#f4f5f0" }

[task]
title = { fg = "#4698cb" }
border = { fg = "#4698cb" }
hovered = { fg = "#f4f5f0", bg = "#003c46" }

[input]
border = { fg = "#4698cb" }
selected = { bg = "#003c46" }

[help]
desc = { fg = "#f4f5f0" }
on = { fg = "#2dccd3" }
run = { fg = "#d59ed7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#003c46", bg = "#f4f5f0" }

[which]
mask = { bg = "#003c46" }
desc = { fg = "#f4f5f0" }
cand = { fg = "#2dccd3" }
rest = { fg = "#9b704d" }

separator_style = { fg = "#00778b" }

[notify]
title_info = { fg = "#2dccd3" }
title_warn = { fg = "#fbdd40" }
title_error = { fg = "#ff585d" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2dccd3" },
  { mime = "{audio, video}/*", fg = "#fbdd40" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#78d64b" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#4698cb" },
  { mime = "*", fg = "#f4f5f0" },
]

