[mgr]
cwd = { fg = "#00a2af" }

find_keyword = { bold = true, fg = "#8d9741" }
find_position = { fg = "#9481cc" }

marker_copied = { fg = "#47a477", bg = "#47a477" }
marker_cut = { fg = "#ca736c", bg = "#ca736c" }
marker_selected = { fg = "#8d9741", bg = "#8d9741" }

count_copied = { fg = "#fffdfb", bg = "#47a477" }
count_cut = { fg = "#fffdfb", bg = "#ca736c" }
count_selected = { fg = "#fffdfb", bg = "#8d9741" }

border_style = { fg = "#5794d0" }

[tabs]
active = { fg = "#fffdfb", bg = "#5794d0"}
inactive = { fg = "#5794d0", bg = "#fff7ed" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fffdfb", bg = "#5794d0", bold = true }
normal_alt = { fg = "#5794d0", bg = "#f2e6d4" }

select_alt = { fg = "#9481cc", bg = "#f2e6d4" }
select_main = { fg = "#fffdfb", bg = "#9481cc", bold = true }

unset_main = { fg = "#fffdfb", bg = "#ca736c", bold = true }
unset_alt = { fg = "#ca736c", bg = "#f2e6d4" }

[status]
perm_exec = { fg = "#47a477" }
perm_read = { fg = "#8d9741" }
perm_sep = { fg = "#00a2af" }
perm_type = { fg = "#5794d0" }
perm_write = { fg = "#ca736c" }

progress_error = { fg = "#ca736c", bg = "#fffdfb" }
progress_label = { fg = "#636363", bg = "#fffdfb" }
progress_normal = { fg = "#636363", bg = "#fffdfb" }

[pick]
active = { fg = "#9481cc" }
border = { fg = "#5794d0" }
inactive = { fg = "#636363" }

[task]
title = { fg = "#5794d0" }
border = { fg = "#5794d0" }
hovered = { fg = "#636363", bg = "#f2e6d4" }

[input]
border = { fg = "#5794d0" }
selected = { bg = "#f2e6d4" }

[help]
desc = { fg = "#636363" }
on = { fg = "#00a2af" }
run = { fg = "#9481cc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f2e6d4", bg = "#636363" }

[which]
mask = { bg = "#f2e6d4" }
desc = { fg = "#636363" }
cand = { fg = "#00a2af" }
rest = { fg = "#bc73a4" }

separator_style = { fg = "#8f8f8f" }

[notify]
title_info = { fg = "#00a2af" }
title_warn = { fg = "#8d9741" }
title_error = { fg = "#ca736c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00a2af" },
  { mime = "{audio, video}/*", fg = "#8d9741" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#47a477" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#5794d0" },
  { mime = "*", fg = "#636363" },
]

