[mgr]
cwd = { fg = "#66cccc" }

find_keyword = { bold = true, fg = "#ffcc66" }
find_position = { fg = "#cc99cc" }

marker_copied = { fg = "#99cc99", bg = "#99cc99" }
marker_cut = { fg = "#f2777a", bg = "#f2777a" }
marker_selected = { fg = "#ffcc66", bg = "#ffcc66" }

count_copied = { fg = "#2d2d2d", bg = "#99cc99" }
count_cut = { fg = "#2d2d2d", bg = "#f2777a" }
count_selected = { fg = "#2d2d2d", bg = "#ffcc66" }

border_style = { fg = "#6699cc" }

[tabs]
active = { fg = "#2d2d2d", bg = "#6699cc"}
inactive = { fg = "#6699cc", bg = #393939" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#2d2d2d", bg = "#6699cc", bold = true }
normal_alt = { fg = "#6699cc", bg = "#515151" }

select_alt = { fg = "#cc99cc", bg = "#515151" }
select_main = { fg = "#2d2d2d", bg = "#cc99cc", bold = true }

unset_main = { fg = "#2d2d2d", bg = "#f2777a", bold = true }
unset_alt = { fg = "#f2777a", bg = "#515151" }

[status]
perm_exec = { fg = "#99cc99" }
perm_read = { fg = "#ffcc66" }
perm_sep = { fg = "#66cccc" }
perm_type = { fg = "#6699cc" }
perm_write = { fg = "#f2777a" }

progress_error = { fg = "#f2777a", bg = "#2d2d2d" }
progress_label = { fg = "#cccccc", bg = "#2d2d2d" }
progress_normal = { fg = "#cccccc", bg = "#2d2d2d" }

[pick]
active = { fg = "#cc99cc" }
border = { fg = "#6699cc" }
inactive = { fg = "#cccccc" }

[task]
title = { fg = "#6699cc" }
border = { fg = "#6699cc" }
hovered = { fg = "#cccccc", bg = "#515151" }

[input]
border = { fg = "#6699cc" }
selected = { bg = "#515151" }

[help]
desc = { fg = "#cccccc" }
on = { fg = "#66cccc" }
run = { fg = "#cc99cc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#515151", bg = "#cccccc" }

[which]
mask = { bg = "#515151" }
desc = { fg = "#cccccc" }
cand = { fg = "#66cccc" }
rest = { fg = "#a3685a" }

separator_style = { fg = "#b4b7b4" }

[notify]
title_info = { fg = "#66cccc" }
title_warn = { fg = "#ffcc66" }
title_error = { fg = "#f2777a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#66cccc" },
  { mime = "{audio, video}/*", fg = "#ffcc66" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#99cc99" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6699cc" },
  { mime = "*", fg = "#cccccc" },
]

