[mgr]
cwd = { fg = "#55dbbe" }

find_keyword = { bold = true, fg = "#e6cd69" }
find_position = { fg = "#a074c4" }

marker_copied = { fg = "#9fca56", bg = "#9fca56" }
marker_cut = { fg = "#cd3f45", bg = "#cd3f45" }
marker_selected = { fg = "#e6cd69", bg = "#e6cd69" }

count_copied = { fg = "#151718", bg = "#9fca56" }
count_cut = { fg = "#151718", bg = "#cd3f45" }
count_selected = { fg = "#151718", bg = "#e6cd69" }

border_style = { fg = "#55b5db" }

[tabs]
active = { fg = "#151718", bg = "#55b5db"}
inactive = { fg = "#55b5db", bg = #282a2b" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#151718", bg = "#55b5db", bold = true }
normal_alt = { fg = "#55b5db", bg = "#3b758c" }

select_alt = { fg = "#a074c4", bg = "#3b758c" }
select_main = { fg = "#151718", bg = "#a074c4", bold = true }

unset_main = { fg = "#151718", bg = "#cd3f45", bold = true }
unset_alt = { fg = "#cd3f45", bg = "#3b758c" }

[status]
perm_exec = { fg = "#9fca56" }
perm_read = { fg = "#e6cd69" }
perm_sep = { fg = "#55dbbe" }
perm_type = { fg = "#55b5db" }
perm_write = { fg = "#cd3f45" }

progress_error = { fg = "#cd3f45", bg = "#151718" }
progress_label = { fg = "#d6d6d6", bg = "#151718" }
progress_normal = { fg = "#d6d6d6", bg = "#151718" }

[pick]
active = { fg = "#a074c4" }
border = { fg = "#55b5db" }
inactive = { fg = "#d6d6d6" }

[task]
title = { fg = "#55b5db" }
border = { fg = "#55b5db" }
hovered = { fg = "#d6d6d6", bg = "#3b758c" }

[input]
border = { fg = "#55b5db" }
selected = { bg = "#3b758c" }

[help]
desc = { fg = "#d6d6d6" }
on = { fg = "#55dbbe" }
run = { fg = "#a074c4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3b758c", bg = "#d6d6d6" }

[which]
mask = { bg = "#3b758c" }
desc = { fg = "#d6d6d6" }
cand = { fg = "#55dbbe" }
rest = { fg = "#8a553f" }

separator_style = { fg = "#43a5d5" }

[notify]
title_info = { fg = "#55dbbe" }
title_warn = { fg = "#e6cd69" }
title_error = { fg = "#cd3f45" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#55dbbe" },
  { mime = "{audio, video}/*", fg = "#e6cd69" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#9fca56" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#55b5db" },
  { mime = "*", fg = "#d6d6d6" },
]

