[mgr]
cwd = { fg = "#4c7a5d" }

find_keyword = { bold = true, fg = "#b47109" }
find_position = { fg = "#945e80" }

marker_copied = { fg = "#6c782e", bg = "#6c782e" }
marker_cut = { fg = "#c14a4a", bg = "#c14a4a" }
marker_selected = { fg = "#b47109", bg = "#b47109" }

count_copied = { fg = "#f9f5d7", bg = "#6c782e" }
count_cut = { fg = "#f9f5d7", bg = "#c14a4a" }
count_selected = { fg = "#f9f5d7", bg = "#b47109" }

border_style = { fg = "#45707a" }

[tabs]
active = { fg = "#f9f5d7", bg = "#45707a"}
inactive = { fg = "#45707a", bg = "#fbf1c7" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f9f5d7", bg = "#45707a", bold = true }
normal_alt = { fg = "#45707a", bg = "#e0cfa9" }

select_alt = { fg = "#945e80", bg = "#e0cfa9" }
select_main = { fg = "#f9f5d7", bg = "#945e80", bold = true }

unset_main = { fg = "#f9f5d7", bg = "#c14a4a", bold = true }
unset_alt = { fg = "#c14a4a", bg = "#e0cfa9" }

[status]
perm_exec = { fg = "#6c782e" }
perm_read = { fg = "#b47109" }
perm_sep = { fg = "#4c7a5d" }
perm_type = { fg = "#45707a" }
perm_write = { fg = "#c14a4a" }

progress_error = { fg = "#c14a4a", bg = "#f9f5d7" }
progress_label = { fg = "#654735", bg = "#f9f5d7" }
progress_normal = { fg = "#654735", bg = "#f9f5d7" }

[pick]
active = { fg = "#945e80" }
border = { fg = "#45707a" }
inactive = { fg = "#654735" }

[task]
title = { fg = "#45707a" }
border = { fg = "#45707a" }
hovered = { fg = "#654735", bg = "#e0cfa9" }

[input]
border = { fg = "#45707a" }
selected = { bg = "#e0cfa9" }

[help]
desc = { fg = "#654735" }
on = { fg = "#4c7a5d" }
run = { fg = "#945e80" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e0cfa9", bg = "#654735" }

[which]
mask = { bg = "#e0cfa9" }
desc = { fg = "#654735" }
cand = { fg = "#4c7a5d" }
rest = { fg = "#e78a4e" }

separator_style = { fg = "#c9b99a" }

[notify]
title_info = { fg = "#4c7a5d" }
title_warn = { fg = "#b47109" }
title_error = { fg = "#c14a4a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4c7a5d" },
  { mime = "{audio, video}/*", fg = "#b47109" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6c782e" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#45707a" },
  { mime = "*", fg = "#654735" },
]

