[mgr]
cwd = { fg = "#318495" }

find_keyword = { bold = true, fg = "#826b28" }
find_position = { fg = "#a90d91" }

marker_copied = { fg = "#007400", bg = "#007400" }
marker_cut = { fg = "#c41a15", bg = "#c41a15" }
marker_selected = { fg = "#826b28", bg = "#826b28" }

count_copied = { fg = "#ffffff", bg = "#007400" }
count_cut = { fg = "#ffffff", bg = "#c41a15" }
count_selected = { fg = "#ffffff", bg = "#826b28" }

border_style = { fg = "#0000ff" }

[tabs]
active = { fg = "#ffffff", bg = "#0000ff"}
inactive = { fg = "#0000ff", bg = "#c0c0c0" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#0000ff", bold = true }
normal_alt = { fg = "#0000ff", bg = "#c0c0c0" }

select_alt = { fg = "#a90d91", bg = "#c0c0c0" }
select_main = { fg = "#ffffff", bg = "#a90d91", bold = true }

unset_main = { fg = "#ffffff", bg = "#c41a15", bold = true }
unset_alt = { fg = "#c41a15", bg = "#c0c0c0" }

[status]
perm_exec = { fg = "#007400" }
perm_read = { fg = "#826b28" }
perm_sep = { fg = "#318495" }
perm_type = { fg = "#0000ff" }
perm_write = { fg = "#c41a15" }

progress_error = { fg = "#c41a15", bg = "#ffffff" }
progress_label = { fg = "#404040", bg = "#ffffff" }
progress_normal = { fg = "#404040", bg = "#ffffff" }

[pick]
active = { fg = "#a90d91" }
border = { fg = "#0000ff" }
inactive = { fg = "#404040" }

[task]
title = { fg = "#0000ff" }
border = { fg = "#0000ff" }
hovered = { fg = "#404040", bg = "#c0c0c0" }

[input]
border = { fg = "#0000ff" }
selected = { bg = "#c0c0c0" }

[help]
desc = { fg = "#404040" }
on = { fg = "#318495" }
run = { fg = "#a90d91" }
hovered = { reversed = true, bold = true }
footer = { fg = "#c0c0c0", bg = "#404040" }

[which]
mask = { bg = "#c0c0c0" }
desc = { fg = "#404040" }
cand = { fg = "#318495" }
rest = { fg = "#826b28" }

separator_style = { fg = "#808080" }

[notify]
title_info = { fg = "#318495" }
title_warn = { fg = "#826b28" }
title_error = { fg = "#c41a15" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#318495" },
  { mime = "{audio, video}/*", fg = "#826b28" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#007400" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0000ff" },
  { mime = "*", fg = "#404040" },
]

