[mgr]
cwd = { fg = "#00bab3" }

find_keyword = { bold = true, fg = "#b8a300" }
find_position = { fg = "#9095ff" }

marker_copied = { fg = "#54bc5c", bg = "#54bc5c" }
marker_cut = { fg = "#f5708a", bg = "#f5708a" }
marker_selected = { fg = "#b8a300", bg = "#b8a300" }

count_copied = { fg = "#000000", bg = "#54bc5c" }
count_cut = { fg = "#000000", bg = "#f5708a" }
count_selected = { fg = "#000000", bg = "#b8a300" }

border_style = { fg = "#00aff2" }

[tabs]
active = { fg = "#000000", bg = "#00aff2"}
inactive = { fg = "#00aff2", bg = "#202020" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#000000", bg = "#00aff2", bold = true }
normal_alt = { fg = "#00aff2", bg = "#303030" }

select_alt = { fg = "#9095ff", bg = "#303030" }
select_main = { fg = "#000000", bg = "#9095ff", bold = true }

unset_main = { fg = "#000000", bg = "#f5708a", bold = true }
unset_alt = { fg = "#f5708a", bg = "#303030" }

[status]
perm_exec = { fg = "#54bc5c" }
perm_read = { fg = "#b8a300" }
perm_sep = { fg = "#00bab3" }
perm_type = { fg = "#00aff2" }
perm_write = { fg = "#f5708a" }

progress_error = { fg = "#f5708a", bg = "#000000" }
progress_label = { fg = "#d0d0d0", bg = "#000000" }
progress_normal = { fg = "#d0d0d0", bg = "#000000" }

[pick]
active = { fg = "#9095ff" }
border = { fg = "#00aff2" }
inactive = { fg = "#d0d0d0" }

[task]
title = { fg = "#00aff2" }
border = { fg = "#00aff2" }
hovered = { fg = "#d0d0d0", bg = "#303030" }

[input]
border = { fg = "#00aff2" }
selected = { bg = "#303030" }

[help]
desc = { fg = "#d0d0d0" }
on = { fg = "#00bab3" }
run = { fg = "#9095ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#303030", bg = "#d0d0d0" }

[which]
mask = { bg = "#303030" }
desc = { fg = "#d0d0d0" }
cand = { fg = "#00bab3" }
rest = { fg = "#d47ada" }

separator_style = { fg = "#b0b0b0" }

[notify]
title_info = { fg = "#00bab3" }
title_warn = { fg = "#b8a300" }
title_error = { fg = "#f5708a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00bab3" },
  { mime = "{audio, video}/*", fg = "#b8a300" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#54bc5c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#00aff2" },
  { mime = "*", fg = "#d0d0d0" },
]

