[mgr]
cwd = { fg = "#00afaf" }

find_keyword = { bold = true, fg = "#ffaf00" }
find_position = { fg = "#af87d7" }

marker_copied = { fg = "#5faf5f", bg = "#5faf5f" }
marker_cut = { fg = "#ff5faf", bg = "#ff5faf" }
marker_selected = { fg = "#ffaf00", bg = "#ffaf00" }

count_copied = { fg = "#1c1c1c", bg = "#5faf5f" }
count_cut = { fg = "#1c1c1c", bg = "#ff5faf" }
count_selected = { fg = "#1c1c1c", bg = "#ffaf00" }

border_style = { fg = "#5fafd7" }

[tabs]
active = { fg = "#1c1c1c", bg = "#5fafd7"}
inactive = { fg = "#5fafd7", bg = "#363636" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#1c1c1c", bg = "#5fafd7", bold = true }
normal_alt = { fg = "#5fafd7", bg = "#424242" }

select_alt = { fg = "#af87d7", bg = "#424242" }
select_main = { fg = "#1c1c1c", bg = "#af87d7", bold = true }

unset_main = { fg = "#1c1c1c", bg = "#ff5faf", bold = true }
unset_alt = { fg = "#ff5faf", bg = "#424242" }

[status]
perm_exec = { fg = "#5faf5f" }
perm_read = { fg = "#ffaf00" }
perm_sep = { fg = "#00afaf" }
perm_type = { fg = "#5fafd7" }
perm_write = { fg = "#ff5faf" }

progress_error = { fg = "#ff5faf", bg = "#1c1c1c" }
progress_label = { fg = "#9e9e9e", bg = "#1c1c1c" }
progress_normal = { fg = "#9e9e9e", bg = "#1c1c1c" }

[pick]
active = { fg = "#af87d7" }
border = { fg = "#5fafd7" }
inactive = { fg = "#9e9e9e" }

[task]
title = { fg = "#5fafd7" }
border = { fg = "#5fafd7" }
hovered = { fg = "#9e9e9e", bg = "#424242" }

[input]
border = { fg = "#5fafd7" }
selected = { bg = "#424242" }

[help]
desc = { fg = "#9e9e9e" }
on = { fg = "#00afaf" }
run = { fg = "#af87d7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#424242", bg = "#9e9e9e" }

[which]
mask = { bg = "#424242" }
desc = { fg = "#9e9e9e" }
cand = { fg = "#00afaf" }
rest = { fg = "#af005f" }

separator_style = { fg = "#808080" }

[notify]
title_info = { fg = "#00afaf" }
title_warn = { fg = "#ffaf00" }
title_error = { fg = "#ff5faf" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00afaf" },
  { mime = "{audio, video}/*", fg = "#ffaf00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5faf5f" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#5fafd7" },
  { mime = "*", fg = "#9e9e9e" },
]

