[mgr]
cwd = { fg = "#04d1f9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f1fc79" }
find_position = { fg = "#a48cf2" }

marker_copied = { fg = "#37f499", bg = "#37f499" }
marker_cut = { fg = "#f16c75", bg = "#f16c75" }
marker_selected = { fg = "#f1fc79", bg = "#f1fc79" }

tab_inactive = { fg = "#ebfafa" }
tab_active = { fg = "#212337", bg = "#ebfafa"}

count_copied = { fg = "#212337", bg = "#37f499" }
count_cut = { fg = "#212337", bg = "#f16c75" }
count_selected = { fg = "#212337", bg = "#f1fc79" }

border_style = { fg = "#39ddfd" }

[mode]
normal_main = { fg = "#212337", bg = "#39ddfd", bold = true }
normal_alt = { fg = "#39ddfd", bg = "#3b4261" }

select_alt = { fg = "#a48cf2", bg = "#3b4261" }
select_main = { fg = "#212337", bg = "#a48cf2", bold = true }

unset_main = { fg = "#212337", bg = "#f16c75", bold = true }
unset_alt = { fg = "#f16c75", bg = "#3b4261" }

[status]
perm_exec = { fg = "#37f499" }
perm_read = { fg = "#f1fc79" }
perm_sep = { fg = "#04d1f9" }
perm_type = { fg = "#39ddfd" }
perm_write = { fg = "#f16c75" }

progress_error = { fg = "#f16c75", bg = "#212337" }
progress_label = { fg = "#ebfafa", bg = "#212337" }
progress_normal = { fg = "#ebfafa", bg = "#212337" }

[pick]
active = { fg = "#a48cf2" }
border = { fg = "#39ddfd" }
inactive = { fg = "#ebfafa" }

[task]
title = { fg = "#39ddfd" }
border = { fg = "#39ddfd" }
hovered = { fg = "#ebfafa", bg = "#3b4261" }

[input]
border = { fg = "#39ddfd" }
selected = { bg = "#3b4261" }

[help]
desc = { fg = "#ebfafa" }
on = { fg = "#04d1f9" }
run = { fg = "#a48cf2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3b4261", bg = "#ebfafa" }

[which]
mask = { bg = "#3b4261" }
desc = { fg = "#ebfafa" }
cand = { fg = "#04d1f9" }
rest = { fg = "#f265b5" }

separator_style = { fg = "#a1abe0" }

[notify]
title_info = { fg = "#04d1f9" }
title_warn = { fg = "#f1fc79" }
title_error = { fg = "#f16c75" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#04d1f9" },
  { mime = "{audio, video}/*", fg = "#f1fc79" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#37f499" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#39ddfd" },
  { mime = "*", fg = "#ebfafa" },
]


