[mgr]
cwd = { fg = "#00948b" }

find_keyword = { bold = true, fg = "#bb8801" }
find_position = { fg = "#6a7fd2" }

marker_copied = { fg = "#7f8b00", bg = "#7f8b00" }
marker_cut = { fg = "#f04339", bg = "#f04339" }
marker_selected = { fg = "#bb8801", bg = "#bb8801" }

count_copied = { fg = "#111111", bg = "#7f8b00" }
count_cut = { fg = "#111111", bg = "#f04339" }
count_selected = { fg = "#111111", bg = "#bb8801" }

border_style = { fg = "#008dd1" }

[tabs]
active = { fg = "#111111", bg = "#008dd1"}
inactive = { fg = "#008dd1", bg = "#1b1b1b" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#111111", bg = "#008dd1", bold = true }
normal_alt = { fg = "#008dd1", bg = "#262626" }

select_alt = { fg = "#6a7fd2", bg = "#262626" }
select_main = { fg = "#111111", bg = "#6a7fd2", bold = true }

unset_main = { fg = "#111111", bg = "#f04339", bold = true }
unset_alt = { fg = "#f04339", bg = "#262626" }

[status]
perm_exec = { fg = "#7f8b00" }
perm_read = { fg = "#bb8801" }
perm_sep = { fg = "#00948b" }
perm_type = { fg = "#008dd1" }
perm_write = { fg = "#f04339" }

progress_error = { fg = "#f04339", bg = "#111111" }
progress_label = { fg = "#ababab", bg = "#111111" }
progress_normal = { fg = "#ababab", bg = "#111111" }

[pick]
active = { fg = "#6a7fd2" }
border = { fg = "#008dd1" }
inactive = { fg = "#ababab" }

[task]
title = { fg = "#008dd1" }
border = { fg = "#008dd1" }
hovered = { fg = "#ababab", bg = "#262626" }

[input]
border = { fg = "#008dd1" }
selected = { bg = "#262626" }

[help]
desc = { fg = "#ababab" }
on = { fg = "#00948b" }
run = { fg = "#6a7fd2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#262626", bg = "#ababab" }

[which]
mask = { bg = "#262626" }
desc = { fg = "#ababab" }
cand = { fg = "#00948b" }
rest = { fg = "#e3488e" }

separator_style = { fg = "#919191" }

[notify]
title_info = { fg = "#00948b" }
title_warn = { fg = "#bb8801" }
title_error = { fg = "#f04339" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00948b" },
  { mime = "{audio, video}/*", fg = "#bb8801" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7f8b00" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#008dd1" },
  { mime = "*", fg = "#ababab" },
]

