[mgr]
cwd = { fg = "#c0bcdb" }

find_keyword = { bold = true, fg = "#ffc37a" }
find_position = { fg = "#d8a2b0" }

marker_copied = { fg = "#b6c68a", bg = "#b6c68a" }
marker_cut = { fg = "#f6998f", bg = "#f6998f" }
marker_selected = { fg = "#ffc37a", bg = "#ffc37a" }

count_copied = { fg = "#241d1a", bg = "#b6c68a" }
count_cut = { fg = "#241d1a", bg = "#f6998f" }
count_selected = { fg = "#241d1a", bg = "#ffc37a" }

border_style = { fg = "#b0a4c3" }

[tabs]
active = { fg = "#241d1a", bg = "#b0a4c3"}
inactive = { fg = "#b0a4c3", bg = #362b27" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#241d1a", bg = "#b0a4c3", bold = true }
normal_alt = { fg = "#b0a4c3", bg = "#473933" }

select_alt = { fg = "#d8a2b0", bg = "#473933" }
select_main = { fg = "#241d1a", bg = "#d8a2b0", bold = true }

unset_main = { fg = "#241d1a", bg = "#f6998f", bold = true }
unset_alt = { fg = "#f6998f", bg = "#473933" }

[status]
perm_exec = { fg = "#b6c68a" }
perm_read = { fg = "#ffc37a" }
perm_sep = { fg = "#c0bcdb" }
perm_type = { fg = "#b0a4c3" }
perm_write = { fg = "#f6998f" }

progress_error = { fg = "#f6998f", bg = "#241d1a" }
progress_label = { fg = "#b8a59d", bg = "#241d1a" }
progress_normal = { fg = "#b8a59d", bg = "#241d1a" }

[pick]
active = { fg = "#d8a2b0" }
border = { fg = "#b0a4c3" }
inactive = { fg = "#b8a59d" }

[task]
title = { fg = "#b0a4c3" }
border = { fg = "#b0a4c3" }
hovered = { fg = "#b8a59d", bg = "#473933" }

[input]
border = { fg = "#b0a4c3" }
selected = { bg = "#473933" }

[help]
desc = { fg = "#b8a59d" }
on = { fg = "#c0bcdb" }
run = { fg = "#d8a2b0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#473933", bg = "#b8a59d" }

[which]
mask = { bg = "#473933" }
desc = { fg = "#b8a59d" }
cand = { fg = "#c0bcdb" }
rest = { fg = "#f1ae97" }

separator_style = { fg = "#a78e84" }

[notify]
title_info = { fg = "#c0bcdb" }
title_warn = { fg = "#ffc37a" }
title_error = { fg = "#f6998f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#c0bcdb" },
  { mime = "{audio, video}/*", fg = "#ffc37a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#b6c68a" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#b0a4c3" },
  { mime = "*", fg = "#b8a59d" },
]

