[mgr]
cwd = { fg = "#673ab7" }

find_keyword = { bold = true, fg = "#ff6f00" }
find_position = { fg = "#be95ff" }

marker_copied = { fg = "#42be65", bg = "#42be65" }
marker_cut = { fg = "#ff7eb6", bg = "#ff7eb6" }
marker_selected = { fg = "#ff6f00", bg = "#ff6f00" }

count_copied = { fg = "#f2f4f8", bg = "#42be65" }
count_cut = { fg = "#f2f4f8", bg = "#ff7eb6" }
count_selected = { fg = "#f2f4f8", bg = "#ff6f00" }

border_style = { fg = "#0f62fe" }

[tabs]
active = { fg = "#f2f4f8", bg = "#0f62fe"}
inactive = { fg = "#0f62fe", bg = "#dde1e6" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#f2f4f8", bg = "#0f62fe", bold = true }
normal_alt = { fg = "#0f62fe", bg = "#bec6cf" }

select_alt = { fg = "#be95ff", bg = "#bec6cf" }
select_main = { fg = "#f2f4f8", bg = "#be95ff", bold = true }

unset_main = { fg = "#f2f4f8", bg = "#ff7eb6", bold = true }
unset_alt = { fg = "#ff7eb6", bg = "#bec6cf" }

[status]
perm_exec = { fg = "#42be65" }
perm_read = { fg = "#ff6f00" }
perm_sep = { fg = "#673ab7" }
perm_type = { fg = "#0f62fe" }
perm_write = { fg = "#ff7eb6" }

progress_error = { fg = "#ff7eb6", bg = "#f2f4f8" }
progress_label = { fg = "#525f70", bg = "#f2f4f8" }
progress_normal = { fg = "#525f70", bg = "#f2f4f8" }

[pick]
active = { fg = "#be95ff" }
border = { fg = "#0f62fe" }
inactive = { fg = "#525f70" }

[task]
title = { fg = "#0f62fe" }
border = { fg = "#0f62fe" }
hovered = { fg = "#525f70", bg = "#bec6cf" }

[input]
border = { fg = "#0f62fe" }
selected = { bg = "#bec6cf" }

[help]
desc = { fg = "#525f70" }
on = { fg = "#673ab7" }
run = { fg = "#be95ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#bec6cf", bg = "#525f70" }

[which]
mask = { bg = "#bec6cf" }
desc = { fg = "#525f70" }
cand = { fg = "#673ab7" }
rest = { fg = "#803800" }

separator_style = { fg = "#68788d" }

[notify]
title_info = { fg = "#673ab7" }
title_warn = { fg = "#ff6f00" }
title_error = { fg = "#ff7eb6" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#673ab7" },
  { mime = "{audio, video}/*", fg = "#ff6f00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#42be65" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0f62fe" },
  { mime = "*", fg = "#525f70" },
]

