[mgr]
cwd = { fg = "#468c78" }

find_keyword = { bold = true, fg = "#a67a50" }
find_position = { fg = "#9472b4" }

marker_copied = { fg = "#64c83c", bg = "#64c83c" }
marker_cut = { fg = "#c85a46", bg = "#c85a46" }
marker_selected = { fg = "#a67a50", bg = "#a67a50" }

count_copied = { fg = "#000000", bg = "#64c83c" }
count_cut = { fg = "#000000", bg = "#c85a46" }
count_selected = { fg = "#000000", bg = "#a67a50" }

border_style = { fg = "#5482af" }

[tabs]
active = { fg = "#000000", bg = "#5482af"}
inactive = { fg = "#5482af", bg = #4a806c" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#000000", bg = "#5482af", bold = true }
normal_alt = { fg = "#5482af", bg = "#4a8d7e" }

select_alt = { fg = "#9472b4", bg = "#4a8d7e" }
select_main = { fg = "#000000", bg = "#9472b4", bold = true }

unset_main = { fg = "#000000", bg = "#c85a46", bold = true }
unset_alt = { fg = "#c85a46", bg = "#4a8d7e" }

[status]
perm_exec = { fg = "#64c83c" }
perm_read = { fg = "#a67a50" }
perm_sep = { fg = "#468c78" }
perm_type = { fg = "#5482af" }
perm_write = { fg = "#c85a46" }

progress_error = { fg = "#c85a46", bg = "#000000" }
progress_label = { fg = "#00ff00", bg = "#000000" }
progress_normal = { fg = "#00ff00", bg = "#000000" }

[pick]
active = { fg = "#9472b4" }
border = { fg = "#5482af" }
inactive = { fg = "#00ff00" }

[task]
title = { fg = "#5482af" }
border = { fg = "#5482af" }
hovered = { fg = "#00ff00", bg = "#4a8d7e" }

[input]
border = { fg = "#5482af" }
selected = { bg = "#4a8d7e" }

[help]
desc = { fg = "#00ff00" }
on = { fg = "#468c78" }
run = { fg = "#9472b4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4a8d7e", bg = "#00ff00" }

[which]
mask = { bg = "#4a8d7e" }
desc = { fg = "#00ff00" }
cand = { fg = "#468c78" }
rest = { fg = "#b37c5e" }

separator_style = { fg = "#919893" }

[notify]
title_info = { fg = "#468c78" }
title_warn = { fg = "#a67a50" }
title_error = { fg = "#c85a46" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#468c78" },
  { mime = "{audio, video}/*", fg = "#a67a50" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#64c83c" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#5482af" },
  { mime = "*", fg = "#00ff00" },
]

