[mgr]
cwd = { fg = "#008e8e" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffb627" }
find_position = { fg = "#700f98" }

marker_copied = { fg = "#388e3c", bg = "#388e3c" }
marker_cut = { fg = "#b0151a", bg = "#b0151a" }
marker_selected = { fg = "#ffb627", bg = "#ffb627" }

tab_inactive = { fg = "#232629" }
tab_active = { fg = "#f8f8f2", bg = "#232629"}

count_copied = { fg = "#f8f8f2", bg = "#388e3c" }
count_cut = { fg = "#f8f8f2", bg = "#b0151a" }
count_selected = { fg = "#f8f8f2", bg = "#ffb627" }

border_style = { fg = "#0082c9" }

[mode]
normal_main = { fg = "#f8f8f2", bg = "#0082c9", bold = true }
normal_alt = { fg = "#0082c9", bg = "#deded8" }

select_alt = { fg = "#700f98", bg = "#deded8" }
select_main = { fg = "#f8f8f2", bg = "#700f98", bold = true }

unset_main = { fg = "#f8f8f2", bg = "#b0151a", bold = true }
unset_alt = { fg = "#b0151a", bg = "#deded8" }

[status]
perm_exec = { fg = "#388e3c" }
perm_read = { fg = "#ffb627" }
perm_sep = { fg = "#008e8e" }
perm_type = { fg = "#0082c9" }
perm_write = { fg = "#b0151a" }

progress_error = { fg = "#b0151a", bg = "#f8f8f2" }
progress_label = { fg = "#232629", bg = "#f8f8f2" }
progress_normal = { fg = "#232629", bg = "#f8f8f2" }

[pick]
active = { fg = "#700f98" }
border = { fg = "#0082c9" }
inactive = { fg = "#232629" }

[task]
title = { fg = "#0082c9" }
border = { fg = "#0082c9" }
hovered = { fg = "#232629", bg = "#deded8" }

[input]
border = { fg = "#0082c9" }
selected = { bg = "#deded8" }

[help]
desc = { fg = "#232629" }
on = { fg = "#008e8e" }
run = { fg = "#700f98" }
hovered = { reversed = true, bold = true }
footer = { fg = "#deded8", bg = "#232629" }

[which]
mask = { bg = "#deded8" }
desc = { fg = "#232629" }
cand = { fg = "#008e8e" }
rest = { fg = "#b27701" }

separator_style = { fg = "#60615d" }

[notify]
title_info = { fg = "#008e8e" }
title_warn = { fg = "#ffb627" }
title_warn = { fg = "#b0151a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#008e8e" },
  { mime = "{audio, video}/*", fg = "#ffb627" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#388e3c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0082c9" },
  { mime = "*", fg = "#232629" },
]


