[mgr]
cwd = { fg = "#56b6c2" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#e5c07b" }
find_position = { fg = "#c678dd" }

marker_copied = { fg = "#98c379", bg = "#98c379" }
marker_cut = { fg = "#e06c75", bg = "#e06c75" }
marker_selected = { fg = "#e5c07b", bg = "#e5c07b" }

tab_inactive = { fg = "#abb2bf" }
tab_active = { fg = "#282c34", bg = "#abb2bf"}

count_copied = { fg = "#282c34", bg = "#98c379" }
count_cut = { fg = "#282c34", bg = "#e06c75" }
count_selected = { fg = "#282c34", bg = "#e5c07b" }

border_style = { fg = "#61afef" }

[mode]
normal_main = { fg = "#282c34", bg = "#61afef", bold = true }
normal_alt = { fg = "#61afef", bg = "#3e4451" }

select_alt = { fg = "#c678dd", bg = "#3e4451" }
select_main = { fg = "#282c34", bg = "#c678dd", bold = true }

unset_main = { fg = "#282c34", bg = "#e06c75", bold = true }
unset_alt = { fg = "#e06c75", bg = "#3e4451" }

[status]
perm_exec = { fg = "#98c379" }
perm_read = { fg = "#e5c07b" }
perm_sep = { fg = "#56b6c2" }
perm_type = { fg = "#61afef" }
perm_write = { fg = "#e06c75" }

progress_error = { fg = "#e06c75", bg = "#282c34" }
progress_label = { fg = "#abb2bf", bg = "#282c34" }
progress_normal = { fg = "#abb2bf", bg = "#282c34" }

[pick]
active = { fg = "#c678dd" }
border = { fg = "#61afef" }
inactive = { fg = "#abb2bf" }

[task]
title = { fg = "#61afef" }
border = { fg = "#61afef" }
hovered = { fg = "#abb2bf", bg = "#3e4451" }

[input]
border = { fg = "#61afef" }
selected = { bg = "#3e4451" }

[help]
desc = { fg = "#abb2bf" }
on = { fg = "#56b6c2" }
run = { fg = "#c678dd" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e4451", bg = "#abb2bf" }

[which]
mask = { bg = "#3e4451" }
desc = { fg = "#abb2bf" }
cand = { fg = "#56b6c2" }
rest = { fg = "#be5046" }

separator_style = { fg = "#565c64" }

[notify]
title_info = { fg = "#56b6c2" }
title_warn = { fg = "#e5c07b" }
title_warn = { fg = "#e06c75" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#56b6c2" },
  { mime = "{audio, video}/*", fg = "#e5c07b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#98c379" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#61afef" },
  { mime = "*", fg = "#abb2bf" },
]


