[manager]
cwd = { fg = "#c6c5fe" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffffb6" }
find_position = { fg = "#ff73fd" }

marker_copied = { fg = "#a8ff60", bg = "#a8ff60" }
marker_cut = { fg = "#ff6c60", bg = "#ff6c60" }
marker_selected = { fg = "#ffffb6", bg = "#ffffb6" }

tab_inactive = { fg = "#b5b3aa" }
tab_active = { fg = "#000000", bg = "#b5b3aa"}

count_copied = { fg = "#000000", bg = "#a8ff60" }
count_cut = { fg = "#000000", bg = "#ff6c60" }
count_selected = { fg = "#000000", bg = "#ffffb6" }

border_style = { fg = "#96cbfe" }

[mode]
normal_main = { fg = "#000000", bg = "#96cbfe", bold = true }
normal_alt = { fg = "#96cbfe", bg = "#484844" }

select_alt = { fg = "#ff73fd", bg = "#484844" }
select_main = { fg = "#000000", bg = "#ff73fd", bold = true }

unset_main = { fg = "#000000", bg = "#ff6c60", bold = true }
unset_alt = { fg = "#ff6c60", bg = "#484844" }

[status]
perm_exec = { fg = "#a8ff60" }
perm_read = { fg = "#ffffb6" }
perm_sep = { fg = "#c6c5fe" }
perm_type = { fg = "#96cbfe" }
perm_write = { fg = "#ff6c60" }

progress_error = { fg = "#ff6c60", bg = "#000000" }
progress_label = { fg = "#b5b3aa", bg = "#000000" }
progress_normal = { fg = "#b5b3aa", bg = "#000000" }

[pick]
active = { fg = "#ff73fd" }
border = { fg = "#96cbfe" }
inactive = { fg = "#b5b3aa" }

[task]
title = { fg = "#96cbfe" }
border = { fg = "#96cbfe" }
hovered = { fg = "#b5b3aa", bg = "#484844" }

[input]
border = { fg = "#96cbfe" }
selected = { bg = "#484844" }

[help]
desc = { fg = "#b5b3aa" }
on = { fg = "#c6c5fe" }
run = { fg = "#ff73fd" }
hovered = { reversed = true, bold = true }
footer = { fg = "#484844", bg = "#b5b3aa" }

[which]
mask = { bg = "#484844" }
desc = { fg = "#b5b3aa" }
cand = { fg = "#c6c5fe" }
rest = { fg = "#b18a3d" }

separator_style = { fg = "#918f88" }

[notify]
title_info = { fg = "#c6c5fe" }
title_warn = { fg = "#ffffb6" }
title_warn = { fg = "#ff6c60" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#c6c5fe" },
  { mime = "{audio, video}/*", fg = "#ffffb6" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a8ff60" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#96cbfe" },
  { mime = "*", fg = "#b5b3aa" },
]


