[mgr]
cwd = { fg = "#bed6ff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffd67c" }
find_position = { fg = "#efb3f7" }

marker_copied = { fg = "#beda78", bg = "#beda78" }
marker_cut = { fg = "#ff7f7b", bg = "#ff7f7b" }
marker_selected = { fg = "#ffd67c", bg = "#ffd67c" }

tab_inactive = { fg = "#cccccc" }
tab_active = { fg = "#2d2d2d", bg = "#cccccc"}

count_copied = { fg = "#2d2d2d", bg = "#beda78" }
count_cut = { fg = "#2d2d2d", bg = "#ff7f7b" }
count_selected = { fg = "#2d2d2d", bg = "#ffd67c" }

border_style = { fg = "#90bee1" }

[mode]
normal_main = { fg = "#2d2d2d", bg = "#90bee1", bold = true }
normal_alt = { fg = "#90bee1", bg = "#515151" }

select_alt = { fg = "#efb3f7", bg = "#515151" }
select_main = { fg = "#2d2d2d", bg = "#efb3f7", bold = true }

unset_main = { fg = "#2d2d2d", bg = "#ff7f7b", bold = true }
unset_alt = { fg = "#ff7f7b", bg = "#515151" }

[status]
perm_exec = { fg = "#beda78" }
perm_read = { fg = "#ffd67c" }
perm_sep = { fg = "#bed6ff" }
perm_type = { fg = "#90bee1" }
perm_write = { fg = "#ff7f7b" }

progress_error = { fg = "#ff7f7b", bg = "#2d2d2d" }
progress_label = { fg = "#cccccc", bg = "#2d2d2d" }
progress_normal = { fg = "#cccccc", bg = "#2d2d2d" }

[pick]
active = { fg = "#efb3f7" }
border = { fg = "#90bee1" }
inactive = { fg = "#cccccc" }

[task]
title = { fg = "#90bee1" }
border = { fg = "#90bee1" }
hovered = { fg = "#cccccc", bg = "#515151" }

[input]
border = { fg = "#90bee1" }
selected = { bg = "#515151" }

[help]
desc = { fg = "#cccccc" }
on = { fg = "#bed6ff" }
run = { fg = "#efb3f7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#515151", bg = "#cccccc" }

[which]
mask = { bg = "#515151" }
desc = { fg = "#cccccc" }
cand = { fg = "#bed6ff" }
rest = { fg = "#ff93b3" }

separator_style = { fg = "#b4b7b4" }

[notify]
title_info = { fg = "#bed6ff" }
title_warn = { fg = "#ffd67c" }
title_warn = { fg = "#ff7f7b" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#bed6ff" },
  { mime = "{audio, video}/*", fg = "#ffd67c" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#beda78" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#90bee1" },
  { mime = "*", fg = "#cccccc" },
]


