[manager]
cwd = { fg = "#5aebbc" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f2ff27" }
find_position = { fg = "#ff8080" }

marker_copied = { fg = "#5ceb5a", bg = "#5ceb5a" }
marker_cut = { fg = "#e35142", bg = "#e35142" }
marker_selected = { fg = "#f2ff27", bg = "#f2ff27" }

tab_inactive = { fg = "#736e55" }
tab_active = { fg = "#1c1810", bg = "#736e55"}

count_copied = { fg = "#1c1810", bg = "#5ceb5a" }
count_cut = { fg = "#1c1810", bg = "#e35142" }
count_selected = { fg = "#1c1810", bg = "#f2ff27" }

border_style = { fg = "#489bf0" }

[mode]
normal_main = { fg = "#1c1810", bg = "#489bf0", bold = true }
normal_alt = { fg = "#489bf0", bg = "#3a3527" }

select_alt = { fg = "#ff8080", bg = "#3a3527" }
select_main = { fg = "#1c1810", bg = "#ff8080", bold = true }

unset_main = { fg = "#1c1810", bg = "#e35142", bold = true }
unset_alt = { fg = "#e35142", bg = "#3a3527" }

[status]
perm_exec = { fg = "#5ceb5a" }
perm_read = { fg = "#f2ff27" }
perm_sep = { fg = "#5aebbc" }
perm_type = { fg = "#489bf0" }
perm_write = { fg = "#e35142" }

progress_error = { fg = "#e35142", bg = "#1c1810" }
progress_label = { fg = "#736e55", bg = "#1c1810" }
progress_normal = { fg = "#736e55", bg = "#1c1810" }

[pick]
active = { fg = "#ff8080" }
border = { fg = "#489bf0" }
inactive = { fg = "#736e55" }

[task]
title = { fg = "#489bf0" }
border = { fg = "#489bf0" }
hovered = { fg = "#736e55", bg = "#45475a" }

[input]
border = { fg = "#489bf0" }
selected = { bg = "#3a3527" }

[help]
desc = { fg = "#736e55" }
on = { fg = "#5aebbc" }
run = { fg = "#ff8080" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3a3527", bg = "#736e55" }

[which]
mask = { bg = "#3a3527" }
desc = { fg = "#736e55" }
cand = { fg = "#5aebbc" }
rest = { fg = "#f69be7" }

separator_style = { fg = "#5f5b45" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5aebbc" },
  { mime = "{audio, video}/*", fg = "#f2ff27" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5ceb5a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#489bf0", bold = true },
  { mime = "*", fg = "#736e55" },
]


