[manager]
cwd = { fg = "#60a592" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffc799" }
find_position = { fg = "#d69094" }

marker_copied = { fg = "#5f8787", bg = "#5f8787" }
marker_cut = { fg = "#de6e6e", bg = "#de6e6e" }
marker_selected = { fg = "#ffc799", bg = "#ffc799" }

tab_inactive = { fg = "#b7b7b7" }
tab_active = { fg = "#101010", bg = "#b7b7b7"}

count_copied = { fg = "#101010", bg = "#5f8787" }
count_cut = { fg = "#101010", bg = "#de6e6e" }
count_selected = { fg = "#101010", bg = "#ffc799" }

border_style = { fg = "#8eaaaa" }

[mode]
normal_main = { fg = "#101010", bg = "#8eaaaa", bold = true }
normal_alt = { fg = "#8eaaaa", bg = "#222222" }

select_alt = { fg = "#d69094", bg = "#222222" }
select_main = { fg = "#101010", bg = "#d69094", bold = true }

unset_main = { fg = "#101010", bg = "#de6e6e", bold = true }
unset_alt = { fg = "#de6e6e", bg = "#222222" }

[status]
perm_exec = { fg = "#5f8787" }
perm_read = { fg = "#ffc799" }
perm_sep = { fg = "#60a592" }
perm_type = { fg = "#8eaaaa" }
perm_write = { fg = "#de6e6e" }

progress_error = { fg = "#de6e6e", bg = "#101010" }
progress_label = { fg = "#b7b7b7", bg = "#101010" }
progress_normal = { fg = "#b7b7b7", bg = "#101010" }

[pick]
active = { fg = "#d69094" }
border = { fg = "#8eaaaa" }
inactive = { fg = "#b7b7b7" }

[task]
title = { fg = "#8eaaaa" }
border = { fg = "#8eaaaa" }
hovered = { fg = "#b7b7b7", bg = "#45475a" }

[input]
border = { fg = "#8eaaaa" }
selected = { bg = "#222222" }

[help]
desc = { fg = "#b7b7b7" }
on = { fg = "#60a592" }
run = { fg = "#d69094" }
hovered = { reversed = true, bold = true }
footer = { fg = "#222222", bg = "#b7b7b7" }

[which]
mask = { bg = "#222222" }
desc = { fg = "#b7b7b7" }
cand = { fg = "#60a592" }
rest = { fg = "#876c4f" }

separator_style = { fg = "#999999" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#60a592" },
  { mime = "{audio, video}/*", fg = "#ffc799" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#5f8787" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#8eaaaa", bold = true },
  { mime = "*", fg = "#b7b7b7" },
]


