[manager]
cwd = { fg = "#7fdbff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffdc00" }
find_position = { fg = "#b10dc9" }

marker_copied = { fg = "#2ecc40", bg = "#2ecc40" }
marker_cut = { fg = "#ff4136", bg = "#ff4136" }
marker_selected = { fg = "#ffdc00", bg = "#ffdc00" }

tab_inactive = { fg = "#bbbbbb" }
tab_active = { fg = "#111111", bg = "#bbbbbb"}

count_copied = { fg = "#111111", bg = "#2ecc40" }
count_cut = { fg = "#111111", bg = "#ff4136" }
count_selected = { fg = "#111111", bg = "#ffdc00" }

border_style = { fg = "#0074d9" }

[mode]
normal_main = { fg = "#111111", bg = "#0074d9", bold = true }
normal_alt = { fg = "#0074d9", bg = "#555555" }

select_alt = { fg = "#b10dc9", bg = "#555555" }
select_main = { fg = "#111111", bg = "#b10dc9", bold = true }

unset_main = { fg = "#111111", bg = "#ff4136", bold = true }
unset_alt = { fg = "#ff4136", bg = "#555555" }

[status]
perm_exec = { fg = "#2ecc40" }
perm_read = { fg = "#ffdc00" }
perm_sep = { fg = "#7fdbff" }
perm_type = { fg = "#0074d9" }
perm_write = { fg = "#ff4136" }

progress_error = { fg = "#ff4136", bg = "#111111" }
progress_label = { fg = "#bbbbbb", bg = "#111111" }
progress_normal = { fg = "#bbbbbb", bg = "#111111" }

[pick]
active = { fg = "#b10dc9" }
border = { fg = "#0074d9" }
inactive = { fg = "#bbbbbb" }

[task]
title = { fg = "#0074d9" }
border = { fg = "#0074d9" }
hovered = { fg = "#bbbbbb", bg = "#555555" }

[input]
border = { fg = "#0074d9" }
selected = { bg = "#555555" }

[help]
desc = { fg = "#bbbbbb" }
on = { fg = "#7fdbff" }
run = { fg = "#b10dc9" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555555", bg = "#bbbbbb" }

[which]
mask = { bg = "#555555" }
desc = { fg = "#bbbbbb" }
cand = { fg = "#7fdbff" }
rest = { fg = "#85144b" }

separator_style = { fg = "#999999" }

[notify]
title_info = { fg = "#7fdbff" }
title_warn = { fg = "#ffdc00" }
title_warn = { fg = "#ff4136" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#7fdbff" },
  { mime = "{audio, video}/*", fg = "#ffdc00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2ecc40" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0074d9" },
  { mime = "*", fg = "#bbbbbb" },
]


