[manager]
cwd = { fg = "#89ddff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#b7c5d3" }
find_position = { fg = "#bb9af7" }

marker_copied = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut = { fg = "#f7768e", bg = "#f7768e" }
marker_selected = { fg = "#b7c5d3", bg = "#b7c5d3" }

tab_inactive = { fg = "#d8e2ec" }
tab_active = { fg = "#171d23", bg = "#d8e2ec"}

count_copied = { fg = "#171d23", bg = "#9ece6a" }
count_cut = { fg = "#171d23", bg = "#f7768e" }
count_selected = { fg = "#171d23", bg = "#b7c5d3" }

border_style = { fg = "#7aa2f7" }

[mode]
normal_main = { fg = "#171d23", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#28323a" }

select_alt = { fg = "#bb9af7", bg = "#28323a" }
select_main = { fg = "#171d23", bg = "#bb9af7", bold = true }

unset_main = { fg = "#171d23", bg = "#f7768e", bold = true }
unset_alt = { fg = "#f7768e", bg = "#28323a" }

[status]
perm_exec = { fg = "#9ece6a" }
perm_read = { fg = "#b7c5d3" }
perm_sep = { fg = "#89ddff" }
perm_type = { fg = "#7aa2f7" }
perm_write = { fg = "#f7768e" }

progress_error = { fg = "#f7768e", bg = "#171d23" }
progress_label = { fg = "#d8e2ec", bg = "#171d23" }
progress_normal = { fg = "#d8e2ec", bg = "#171d23" }

[pick]
active = { fg = "#bb9af7" }
border = { fg = "#7aa2f7" }
inactive = { fg = "#d8e2ec" }

[task]
title = { fg = "#7aa2f7" }
border = { fg = "#7aa2f7" }
hovered = { fg = "#d8e2ec", bg = "#28323a" }

[input]
border = { fg = "#7aa2f7" }
selected = { bg = "#28323a" }

[help]
desc = { fg = "#d8e2ec" }
on = { fg = "#89ddff" }
run = { fg = "#bb9af7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#28323a", bg = "#d8e2ec" }

[which]
mask = { bg = "#28323a" }
desc = { fg = "#d8e2ec" }
cand = { fg = "#89ddff" }
rest = { fg = "#bb9af7" }

separator_style = { fg = "#b7c5d3" }

[notify]
title_info = { fg = "#89ddff" }
title_warn = { fg = "#b7c5d3" }
title_warn = { fg = "#f7768e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#89ddff" },
  { mime = "{audio, video}/*", fg = "#b7c5d3" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#9ece6a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7aa2f7" },
  { mime = "*", fg = "#d8e2ec" },
]


