[manager]
cwd = { fg = "#89ddff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffcb6b" }
find_position = { fg = "#c792ea" }

marker_copied = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut = { fg = "#f07178", bg = "#f07178" }
marker_selected = { fg = "#ffcb6b", bg = "#ffcb6b" }

tab_inactive = { fg = "#eeffff" }
tab_active = { fg = "#263238", bg = "#eeffff"}

count_copied = { fg = "#263238", bg = "#c3e88d" }
count_cut = { fg = "#263238", bg = "#f07178" }
count_selected = { fg = "#263238", bg = "#ffcb6b" }

border_style = { fg = "#82aaff" }

[mode]
normal_main = { fg = "#263238", bg = "#82aaff", bold = true }
normal_alt = { fg = "#82aaff", bg = "#314549" }

select_alt = { fg = "#c792ea", bg = "#314549" }
select_main = { fg = "#263238", bg = "#c792ea", bold = true }

unset_main = { fg = "#263238", bg = "#f07178", bold = true }
unset_alt = { fg = "#f07178", bg = "#314549" }

[status]
perm_exec = { fg = "#c3e88d" }
perm_read = { fg = "#ffcb6b" }
perm_sep = { fg = "#89ddff" }
perm_type = { fg = "#82aaff" }
perm_write = { fg = "#f07178" }

progress_error = { fg = "#f07178", bg = "#263238" }
progress_label = { fg = "#eeffff", bg = "#263238" }
progress_normal = { fg = "#eeffff", bg = "#263238" }

[pick]
active = { fg = "#c792ea" }
border = { fg = "#82aaff" }
inactive = { fg = "#eeffff" }

[task]
title = { fg = "#82aaff" }
border = { fg = "#82aaff" }
hovered = { fg = "#eeffff", bg = "#45475a" }

[input]
border = { fg = "#82aaff" }
selected = { bg = "#314549" }

[help]
desc = { fg = "#eeffff" }
on = { fg = "#89ddff" }
run = { fg = "#c792ea" }
hovered = { reversed = true, bold = true }
footer = { fg = "#314549", bg = "#eeffff" }

[which]
mask = { bg = "#314549" }
desc = { fg = "#eeffff" }
cand = { fg = "#89ddff" }
rest = { fg = "#ff5370" }

separator_style = { fg = "#b2ccd6" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#89ddff" },
  { mime = "{audio, video}/*", fg = "#ffcb6b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#c3e88d" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#82aaff", bold = true },
  { mime = "*", fg = "#eeffff" },
]


