[mgr]
cwd = { fg = "#4cbf99" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f2ae49" }
find_position = { fg = "#a37acc" }

marker_copied = { fg = "#6cbf49", bg = "#6cbf49" }
marker_cut = { fg = "#f07171", bg = "#f07171" }
marker_selected = { fg = "#f2ae49", bg = "#f2ae49" }

tab_inactive = { fg = "#5c6166" }
tab_active = { fg = "#f8f9fa", bg = "#5c6166"}

count_copied = { fg = "#f8f9fa", bg = "#6cbf49" }
count_cut = { fg = "#f8f9fa", bg = "#f07171" }
count_selected = { fg = "#f8f9fa", bg = "#f2ae49" }

border_style = { fg = "#399ee6" }

[mode]
normal_main = { fg = "#f8f9fa", bg = "#399ee6", bold = true }
normal_alt = { fg = "#399ee6", bg = "#d2d4d8" }

select_alt = { fg = "#a37acc", bg = "#d2d4d8" }
select_main = { fg = "#f8f9fa", bg = "#a37acc", bold = true }

unset_main = { fg = "#f8f9fa", bg = "#f07171", bold = true }
unset_alt = { fg = "#f07171", bg = "#d2d4d8" }

[status]
perm_exec = { fg = "#6cbf49" }
perm_read = { fg = "#f2ae49" }
perm_sep = { fg = "#4cbf99" }
perm_type = { fg = "#399ee6" }
perm_write = { fg = "#f07171" }

progress_error = { fg = "#f07171", bg = "#f8f9fa" }
progress_label = { fg = "#5c6166", bg = "#f8f9fa" }
progress_normal = { fg = "#5c6166", bg = "#f8f9fa" }

[pick]
active = { fg = "#a37acc" }
border = { fg = "#399ee6" }
inactive = { fg = "#5c6166" }

[task]
title = { fg = "#399ee6" }
border = { fg = "#399ee6" }
hovered = { fg = "#5c6166", bg = "#d2d4d8" }

[input]
border = { fg = "#399ee6" }
selected = { bg = "#d2d4d8" }

[help]
desc = { fg = "#5c6166" }
on = { fg = "#4cbf99" }
run = { fg = "#a37acc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d2d4d8", bg = "#5c6166" }

[which]
mask = { bg = "#d2d4d8" }
desc = { fg = "#5c6166" }
cand = { fg = "#4cbf99" }
rest = { fg = "#e6ba7e" }

separator_style = { fg = "#8a9199" }

[notify]
title_info = { fg = "#4cbf99" }
title_warn = { fg = "#f2ae49" }
title_error = { fg = "#f07171" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4cbf99" },
  { mime = "{audio, video}/*", fg = "#f2ae49" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6cbf49" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#399ee6" },
  { mime = "*", fg = "#5c6166" },
]


