[mgr]
cwd = { fg = "#4cbf99" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f2ae49" }
find_position = { fg = "#a37acc" }

marker_copied = { fg = "#86b300", bg = "#86b300" }
marker_cut = { fg = "#f07178", bg = "#f07178" }
marker_selected = { fg = "#f2ae49", bg = "#f2ae49" }

tab_inactive = { fg = "#5c6773" }
tab_active = { fg = "#fafafa", bg = "#5c6773"}

count_copied = { fg = "#fafafa", bg = "#86b300" }
count_cut = { fg = "#fafafa", bg = "#f07178" }
count_selected = { fg = "#fafafa", bg = "#f2ae49" }

border_style = { fg = "#36a3d9" }

[mode]
normal_main = { fg = "#fafafa", bg = "#36a3d9", bold = true }
normal_alt = { fg = "#36a3d9", bg = "#f8f9fa" }

select_alt = { fg = "#a37acc", bg = "#f8f9fa" }
select_main = { fg = "#fafafa", bg = "#a37acc", bold = true }

unset_main = { fg = "#fafafa", bg = "#f07178", bold = true }
unset_alt = { fg = "#f07178", bg = "#f8f9fa" }

[status]
perm_exec = { fg = "#86b300" }
perm_read = { fg = "#f2ae49" }
perm_sep = { fg = "#4cbf99" }
perm_type = { fg = "#36a3d9" }
perm_write = { fg = "#f07178" }

progress_error = { fg = "#f07178", bg = "#fafafa" }
progress_label = { fg = "#5c6773", bg = "#fafafa" }
progress_normal = { fg = "#5c6773", bg = "#fafafa" }

[pick]
active = { fg = "#a37acc" }
border = { fg = "#36a3d9" }
inactive = { fg = "#5c6773" }

[task]
title = { fg = "#36a3d9" }
border = { fg = "#36a3d9" }
hovered = { fg = "#5c6773", bg = "#f8f9fa" }

[input]
border = { fg = "#36a3d9" }
selected = { bg = "#f8f9fa" }

[help]
desc = { fg = "#5c6773" }
on = { fg = "#4cbf99" }
run = { fg = "#a37acc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f8f9fa", bg = "#5c6773" }

[which]
mask = { bg = "#f8f9fa" }
desc = { fg = "#5c6773" }
cand = { fg = "#4cbf99" }
rest = { fg = "#e6ba7e" }

separator_style = { fg = "#828c99" }

[notify]
title_info = { fg = "#4cbf99" }
title_warn = { fg = "#f2ae49" }
title_warn = { fg = "#f07178" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#4cbf99" },
  { mime = "{audio, video}/*", fg = "#f2ae49" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#86b300" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#36a3d9" },
  { mime = "*", fg = "#5c6773" },
]


