[manager]
cwd = { fg = "#dc3318" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fbe0d9" }
find_position = { fg = "#1d8991" }

marker_copied = { fg = "#94e1b0", bg = "#94e1b0" }
marker_cut = { fg = "#f7939b", bg = "#f7939b" }
marker_selected = { fg = "#fbe0d9", bg = "#fbe0d9" }

tab_inactive = { fg = "#403c3d" }
tab_active = { fg = "#fdf0ed", bg = "#403c3d"}

count_copied = { fg = "#fdf0ed", bg = "#94e1b0" }
count_cut = { fg = "#fdf0ed", bg = "#f7939b" }
count_selected = { fg = "#fdf0ed", bg = "#fbe0d9" }

border_style = { fg = "#da103f" }

[mode]
normal_main = { fg = "#fdf0ed", bg = "#da103f", bold = true }
normal_alt = { fg = "#da103f", bg = "#f9cbbe" }

select_alt = { fg = "#1d8991", bg = "#f9cbbe" }
select_main = { fg = "#fdf0ed", bg = "#1d8991", bold = true }

unset_main = { fg = "#fdf0ed", bg = "#f7939b", bold = true }
unset_alt = { fg = "#f7939b", bg = "#f9cbbe" }

[status]
perm_exec = { fg = "#94e1b0" }
perm_read = { fg = "#fbe0d9" }
perm_sep = { fg = "#dc3318" }
perm_type = { fg = "#da103f" }
perm_write = { fg = "#f7939b" }

progress_error = { fg = "#f7939b", bg = "#fdf0ed" }
progress_label = { fg = "#403c3d", bg = "#fdf0ed" }
progress_normal = { fg = "#403c3d", bg = "#fdf0ed" }

[pick]
active = { fg = "#1d8991" }
border = { fg = "#da103f" }
inactive = { fg = "#403c3d" }

[task]
title = { fg = "#da103f" }
border = { fg = "#da103f" }
hovered = { fg = "#403c3d", bg = "#45475a" }

[input]
border = { fg = "#da103f" }
selected = { bg = "#f9cbbe" }

[help]
desc = { fg = "#403c3d" }
on = { fg = "#dc3318" }
run = { fg = "#1d8991" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f9cbbe", bg = "#403c3d" }

[which]
mask = { bg = "#f9cbbe" }
desc = { fg = "#403c3d" }
cand = { fg = "#dc3318" }
rest = { fg = "#e58c92" }

separator_style = { fg = "#948c8a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#dc3318" },
  { mime = "{audio, video}/*", fg = "#fbe0d9" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#94e1b0" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#da103f", bold = true },
  { mime = "*", fg = "#403c3d" },
]


