[mgr]
cwd = { fg = "#5bc4bf" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fec418" }
find_position = { fg = "#815ba4" }

marker_copied = { fg = "#48b685", bg = "#48b685" }
marker_cut = { fg = "#ef6155", bg = "#ef6155" }
marker_selected = { fg = "#fec418", bg = "#fec418" }

tab_inactive = { fg = "#a39e9b" }
tab_active = { fg = "#2f1e2e", bg = "#a39e9b"}

count_copied = { fg = "#2f1e2e", bg = "#48b685" }
count_cut = { fg = "#2f1e2e", bg = "#ef6155" }
count_selected = { fg = "#2f1e2e", bg = "#fec418" }

border_style = { fg = "#06b6ef" }

[mode]
normal_main = { fg = "#2f1e2e", bg = "#06b6ef", bold = true }
normal_alt = { fg = "#06b6ef", bg = "#4f424c" }

select_alt = { fg = "#815ba4", bg = "#4f424c" }
select_main = { fg = "#2f1e2e", bg = "#815ba4", bold = true }

unset_main = { fg = "#2f1e2e", bg = "#ef6155", bold = true }
unset_alt = { fg = "#ef6155", bg = "#4f424c" }

[status]
perm_exec = { fg = "#48b685" }
perm_read = { fg = "#fec418" }
perm_sep = { fg = "#5bc4bf" }
perm_type = { fg = "#06b6ef" }
perm_write = { fg = "#ef6155" }

progress_error = { fg = "#ef6155", bg = "#2f1e2e" }
progress_label = { fg = "#a39e9b", bg = "#2f1e2e" }
progress_normal = { fg = "#a39e9b", bg = "#2f1e2e" }

[pick]
active = { fg = "#815ba4" }
border = { fg = "#06b6ef" }
inactive = { fg = "#a39e9b" }

[task]
title = { fg = "#06b6ef" }
border = { fg = "#06b6ef" }
hovered = { fg = "#a39e9b", bg = "#4f424c" }

[input]
border = { fg = "#06b6ef" }
selected = { bg = "#4f424c" }

[help]
desc = { fg = "#a39e9b" }
on = { fg = "#5bc4bf" }
run = { fg = "#815ba4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4f424c", bg = "#a39e9b" }

[which]
mask = { bg = "#4f424c" }
desc = { fg = "#a39e9b" }
cand = { fg = "#5bc4bf" }
rest = { fg = "#e96ba8" }

separator_style = { fg = "#8d8687" }

[notify]
title_info = { fg = "#5bc4bf" }
title_warn = { fg = "#fec418" }
title_warn = { fg = "#ef6155" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5bc4bf" },
  { mime = "{audio, video}/*", fg = "#fec418" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#48b685" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#06b6ef" },
  { mime = "*", fg = "#a39e9b" },
]


