[manager]
cwd = { fg = "#0f4b6e" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#8f5e15" }
find_position = { fg = "#5a4a78" }

marker_copied = { fg = "#33635c", bg = "#33635c" }
marker_cut = { fg = "#8c4351", bg = "#8c4351" }
marker_selected = { fg = "#8f5e15", bg = "#8f5e15" }

tab_inactive = { fg = "#28323a" }
tab_active = { fg = "#fbfbfd", bg = "#28323a"}

count_copied = { fg = "#fbfbfd", bg = "#33635c" }
count_cut = { fg = "#fbfbfd", bg = "#8c4351" }
count_selected = { fg = "#fbfbfd", bg = "#8f5e15" }

border_style = { fg = "#34548a" }

[mode]
normal_main = { fg = "#fbfbfd", bg = "#34548a", bold = true }
normal_alt = { fg = "#34548a", bg = "#d8e2ec" }

select_alt = { fg = "#5a4a78", bg = "#d8e2ec" }
select_main = { fg = "#fbfbfd", bg = "#5a4a78", bold = true }

unset_main = { fg = "#fbfbfd", bg = "#8c4351", bold = true }
unset_alt = { fg = "#8c4351", bg = "#d8e2ec" }

[status]
perm_exec = { fg = "#33635c" }
perm_read = { fg = "#8f5e15" }
perm_sep = { fg = "#0f4b6e" }
perm_type = { fg = "#34548a" }
perm_write = { fg = "#8c4351" }

progress_error = { fg = "#8c4351", bg = "#fbfbfd" }
progress_label = { fg = "#28323a", bg = "#fbfbfd" }
progress_normal = { fg = "#28323a", bg = "#fbfbfd" }

[pick]
active = { fg = "#5a4a78" }
border = { fg = "#34548a" }
inactive = { fg = "#28323a" }

[task]
title = { fg = "#34548a" }
border = { fg = "#34548a" }
hovered = { fg = "#28323a", bg = "#d8e2ec" }

[input]
border = { fg = "#34548a" }
selected = { bg = "#d8e2ec" }

[help]
desc = { fg = "#28323a" }
on = { fg = "#0f4b6e" }
run = { fg = "#5a4a78" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d8e2ec", bg = "#28323a" }

[which]
mask = { bg = "#d8e2ec" }
desc = { fg = "#28323a" }
cand = { fg = "#0f4b6e" }
rest = { fg = "#7e5140" }

separator_style = { fg = "#526270" }

[notify]
title_info = { fg = "#0f4b6e" }
title_warn = { fg = "#8f5e15" }
title_warn = { fg = "#8c4351" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0f4b6e" },
  { mime = "{audio, video}/*", fg = "#8f5e15" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#33635c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#34548a" },
  { mime = "*", fg = "#28323a" },
]


