[mgr]
cwd = { fg = "#89b482" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#d8a657" }
find_position = { fg = "#d3869b" }

marker_copied = { fg = "#a9b665", bg = "#a9b665" }
marker_cut = { fg = "#ea6962", bg = "#ea6962" }
marker_selected = { fg = "#d8a657", bg = "#d8a657" }

tab_inactive = { fg = "#ddc7a1" }
tab_active = { fg = "#32302f", bg = "#ddc7a1"}

count_copied = { fg = "#32302f", bg = "#a9b665" }
count_cut = { fg = "#32302f", bg = "#ea6962" }
count_selected = { fg = "#32302f", bg = "#d8a657" }

border_style = { fg = "#7daea3" }

[mode]
normal_main = { fg = "#32302f", bg = "#7daea3", bold = true }
normal_alt = { fg = "#7daea3", bg = "#5a524c" }

select_alt = { fg = "#d3869b", bg = "#5a524c" }
select_main = { fg = "#32302f", bg = "#d3869b", bold = true }

unset_main = { fg = "#32302f", bg = "#ea6962", bold = true }
unset_alt = { fg = "#ea6962", bg = "#5a524c" }

[status]
perm_exec = { fg = "#a9b665" }
perm_read = { fg = "#d8a657" }
perm_sep = { fg = "#89b482" }
perm_type = { fg = "#7daea3" }
perm_write = { fg = "#ea6962" }

progress_error = { fg = "#ea6962", bg = "#32302f" }
progress_label = { fg = "#ddc7a1", bg = "#32302f" }
progress_normal = { fg = "#ddc7a1", bg = "#32302f" }

[pick]
active = { fg = "#d3869b" }
border = { fg = "#7daea3" }
inactive = { fg = "#ddc7a1" }

[task]
title = { fg = "#7daea3" }
border = { fg = "#7daea3" }
hovered = { fg = "#ddc7a1", bg = "#5a524c" }

[input]
border = { fg = "#7daea3" }
selected = { bg = "#5a524c" }

[help]
desc = { fg = "#ddc7a1" }
on = { fg = "#89b482" }
run = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5a524c", bg = "#ddc7a1" }

[which]
mask = { bg = "#5a524c" }
desc = { fg = "#ddc7a1" }
cand = { fg = "#89b482" }
rest = { fg = "#bd6f3e" }

separator_style = { fg = "#bdae93" }

[notify]
title_info = { fg = "#89b482" }
title_warn = { fg = "#d8a657" }
title_warn = { fg = "#ea6962" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#89b482" },
  { mime = "{audio, video}/*", fg = "#d8a657" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a9b665" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7daea3" },
  { mime = "*", fg = "#ddc7a1" },
]


