[mgr]
cwd = { fg = "#88c0d0" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ebcb8b" }
find_position = { fg = "#b48ead" }

marker_copied = { fg = "#a3be8c", bg = "#a3be8c" }
marker_cut = { fg = "#bf616a", bg = "#bf616a" }
marker_selected = { fg = "#ebcb8b", bg = "#ebcb8b" }

tab_inactive = { fg = "#e5e9f0" }
tab_active = { fg = "#2e3440", bg = "#e5e9f0"}

count_copied = { fg = "#2e3440", bg = "#a3be8c" }
count_cut = { fg = "#2e3440", bg = "#bf616a" }
count_selected = { fg = "#2e3440", bg = "#ebcb8b" }

border_style = { fg = "#81a1c1" }

[mode]
normal_main = { fg = "#2e3440", bg = "#81a1c1", bold = true }
normal_alt = { fg = "#81a1c1", bg = "#434c5e" }

select_alt = { fg = "#b48ead", bg = "#434c5e" }
select_main = { fg = "#2e3440", bg = "#b48ead", bold = true }

unset_main = { fg = "#2e3440", bg = "#bf616a", bold = true }
unset_alt = { fg = "#bf616a", bg = "#434c5e" }

[status]
perm_exec = { fg = "#a3be8c" }
perm_read = { fg = "#ebcb8b" }
perm_sep = { fg = "#88c0d0" }
perm_type = { fg = "#81a1c1" }
perm_write = { fg = "#bf616a" }

progress_error = { fg = "#bf616a", bg = "#2e3440" }
progress_label = { fg = "#e5e9f0", bg = "#2e3440" }
progress_normal = { fg = "#e5e9f0", bg = "#2e3440" }

[pick]
active = { fg = "#b48ead" }
border = { fg = "#81a1c1" }
inactive = { fg = "#e5e9f0" }

[task]
title = { fg = "#81a1c1" }
border = { fg = "#81a1c1" }
hovered = { fg = "#e5e9f0", bg = "#434c5e" }

[input]
border = { fg = "#81a1c1" }
selected = { bg = "#434c5e" }

[help]
desc = { fg = "#e5e9f0" }
on = { fg = "#88c0d0" }
run = { fg = "#b48ead" }
hovered = { reversed = true, bold = true }
footer = { fg = "#434c5e", bg = "#e5e9f0" }

[which]
mask = { bg = "#434c5e" }
desc = { fg = "#e5e9f0" }
cand = { fg = "#88c0d0" }
rest = { fg = "#5e81ac" }

separator_style = { fg = "#d8dee9" }

[notify]
title_info = { fg = "#88c0d0" }
title_warn = { fg = "#ebcb8b" }
title_warn = { fg = "#bf616a" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#88c0d0" },
  { mime = "{audio, video}/*", fg = "#ebcb8b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a3be8c" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#81a1c1" },
  { mime = "*", fg = "#e5e9f0" },
]


