[manager]
cwd = { fg = "#755b00" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#755b00" }
find_position = { fg = "#000090" }

marker_copied = { fg = "#730073", bg = "#730073" }
marker_cut = { fg = "#840000", bg = "#840000" }
marker_selected = { fg = "#755b00", bg = "#755b00" }

tab_inactive = { fg = "#000000" }
tab_active = { fg = "#e0e0e0", bg = "#000000"}

count_copied = { fg = "#e0e0e0", bg = "#730073" }
count_cut = { fg = "#e0e0e0", bg = "#840000" }
count_selected = { fg = "#e0e0e0", bg = "#755b00" }

border_style = { fg = "#007300" }

[mode]
normal_main = { fg = "#e0e0e0", bg = "#007300", bold = true }
normal_alt = { fg = "#007300", bg = "#d0d0d0" }

select_alt = { fg = "#000090", bg = "#d0d0d0" }
select_main = { fg = "#e0e0e0", bg = "#000090", bold = true }

unset_main = { fg = "#e0e0e0", bg = "#840000", bold = true }
unset_alt = { fg = "#840000", bg = "#d0d0d0" }

[status]
perm_exec = { fg = "#730073" }
perm_read = { fg = "#755b00" }
perm_sep = { fg = "#755b00" }
perm_type = { fg = "#007300" }
perm_write = { fg = "#840000" }

progress_error = { fg = "#840000", bg = "#e0e0e0" }
progress_label = { fg = "#000000", bg = "#e0e0e0" }
progress_normal = { fg = "#000000", bg = "#e0e0e0" }

[pick]
active = { fg = "#000090" }
border = { fg = "#007300" }
inactive = { fg = "#000000" }

[task]
title = { fg = "#007300" }
border = { fg = "#007300" }
hovered = { fg = "#000000", bg = "#45475a" }

[input]
border = { fg = "#007300" }
selected = { bg = "#d0d0d0" }

[help]
desc = { fg = "#000000" }
on = { fg = "#755b00" }
run = { fg = "#000090" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d0d0d0", bg = "#000000" }

[which]
mask = { bg = "#d0d0d0" }
desc = { fg = "#000000" }
cand = { fg = "#755b00" }
rest = { fg = "#755b00" }

separator_style = { fg = "#202020" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#755b00" },
  { mime = "{audio, video}/*", fg = "#755b00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#730073" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#007300", bold = true },
  { mime = "*", fg = "#000000" },
]


