[mgr]
cwd = { fg = "#8c9785" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ff6565" }
find_position = { fg = "#a45782" }

marker_copied = { fg = "#a68e5a", bg = "#a68e5a" }
marker_cut = { fg = "#c53253", bg = "#c53253" }
marker_selected = { fg = "#ff6565", bg = "#ff6565" }

tab_inactive = { fg = "#aa556f" }
tab_active = { fg = "#0e091d", bg = "#aa556f"}

count_copied = { fg = "#0e091d", bg = "#a68e5a" }
count_cut = { fg = "#0e091d", bg = "#c53253" }
count_selected = { fg = "#0e091d", bg = "#ff6565" }

border_style = { fg = "#6e6080" }

[mode]
normal_main = { fg = "#0e091d", bg = "#6e6080", bold = true }
normal_alt = { fg = "#6e6080", bg = "#4b2054" }

select_alt = { fg = "#a45782", bg = "#4b2054" }
select_main = { fg = "#0e091d", bg = "#a45782", bold = true }

unset_main = { fg = "#0e091d", bg = "#c53253", bold = true }
unset_alt = { fg = "#c53253", bg = "#4b2054" }

[status]
perm_exec = { fg = "#a68e5a" }
perm_read = { fg = "#ff6565" }
perm_sep = { fg = "#8c9785" }
perm_type = { fg = "#6e6080" }
perm_write = { fg = "#c53253" }

progress_error = { fg = "#c53253", bg = "#0e091d" }
progress_label = { fg = "#aa556f", bg = "#0e091d" }
progress_normal = { fg = "#aa556f", bg = "#0e091d" }

[pick]
active = { fg = "#a45782" }
border = { fg = "#6e6080" }
inactive = { fg = "#aa556f" }

[task]
title = { fg = "#6e6080" }
border = { fg = "#6e6080" }
hovered = { fg = "#aa556f", bg = "#4b2054" }

[input]
border = { fg = "#6e6080" }
selected = { bg = "#4b2054" }

[help]
desc = { fg = "#aa556f" }
on = { fg = "#8c9785" }
run = { fg = "#a45782" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4b2054", bg = "#aa556f" }

[which]
mask = { bg = "#4b2054" }
desc = { fg = "#aa556f" }
cand = { fg = "#8c9785" }
rest = { fg = "#984d51" }

separator_style = { fg = "#8c406f" }

[notify]
title_info = { fg = "#8c9785" }
title_warn = { fg = "#ff6565" }
title_warn = { fg = "#c53253" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#8c9785" },
  { mime = "{audio, video}/*", fg = "#ff6565" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a68e5a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6e6080" },
  { mime = "*", fg = "#aa556f" },
]


