[manager]
cwd = { fg = "#79b8ff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffd33d" }
find_position = { fg = "#ea4aaa" }

marker_copied = { fg = "#28a745", bg = "#28a745" }
marker_cut = { fg = "#d73a49", bg = "#d73a49" }
marker_selected = { fg = "#ffd33d", bg = "#ffd33d" }

tab_inactive = { fg = "#2f363d" }
tab_active = { fg = "#fafbfc", bg = "#2f363d"}

count_copied = { fg = "#fafbfc", bg = "#28a745" }
count_cut = { fg = "#fafbfc", bg = "#d73a49" }
count_selected = { fg = "#fafbfc", bg = "#ffd33d" }

border_style = { fg = "#0366d6" }

[mode]
normal_main = { fg = "#fafbfc", bg = "#0366d6", bold = true }
normal_alt = { fg = "#0366d6", bg = "#d1d5da" }

select_alt = { fg = "#ea4aaa", bg = "#d1d5da" }
select_main = { fg = "#fafbfc", bg = "#ea4aaa", bold = true }

unset_main = { fg = "#fafbfc", bg = "#d73a49", bold = true }
unset_alt = { fg = "#d73a49", bg = "#d1d5da" }

[status]
perm_exec = { fg = "#28a745" }
perm_read = { fg = "#ffd33d" }
perm_sep = { fg = "#79b8ff" }
perm_type = { fg = "#0366d6" }
perm_write = { fg = "#d73a49" }

progress_error = { fg = "#d73a49", bg = "#fafbfc" }
progress_label = { fg = "#2f363d", bg = "#fafbfc" }
progress_normal = { fg = "#2f363d", bg = "#fafbfc" }

[pick]
active = { fg = "#ea4aaa" }
border = { fg = "#0366d6" }
inactive = { fg = "#2f363d" }

[task]
title = { fg = "#0366d6" }
border = { fg = "#0366d6" }
hovered = { fg = "#2f363d", bg = "#45475a" }

[input]
border = { fg = "#0366d6" }
selected = { bg = "#d1d5da" }

[help]
desc = { fg = "#2f363d" }
on = { fg = "#79b8ff" }
run = { fg = "#ea4aaa" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d1d5da", bg = "#2f363d" }

[which]
mask = { bg = "#d1d5da" }
desc = { fg = "#2f363d" }
cand = { fg = "#79b8ff" }
rest = { fg = "#a04100" }

separator_style = { fg = "#444d56" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#79b8ff" },
  { mime = "{audio, video}/*", fg = "#ffd33d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#28a745" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0366d6", bold = true },
  { mime = "*", fg = "#2f363d" },
]


