[mgr]
cwd = { fg = "#509c93" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ebcc1a" }
find_position = { fg = "#b870ce" }

marker_copied = { fg = "#7c9f4b", bg = "#7c9f4b" }
marker_cut = { fg = "#db7070", bg = "#db7070" }
marker_selected = { fg = "#ebcc1a", bg = "#ebcc1a" }

tab_inactive = { fg = "#474752" }
tab_active = { fg = "#fafafa", bg = "#474752"}

count_copied = { fg = "#fafafa", bg = "#7c9f4b" }
count_cut = { fg = "#fafafa", bg = "#db7070" }
count_selected = { fg = "#fafafa", bg = "#ebcc1a" }

border_style = { fg = "#6587bf" }

[mode]
normal_main = { fg = "#fafafa", bg = "#6587bf", bold = true }
normal_alt = { fg = "#6587bf", bg = "#acb1b9" }

select_alt = { fg = "#b870ce", bg = "#acb1b9" }
select_main = { fg = "#fafafa", bg = "#b870ce", bold = true }

unset_main = { fg = "#fafafa", bg = "#db7070", bold = true }
unset_alt = { fg = "#db7070", bg = "#acb1b9" }

[status]
perm_exec = { fg = "#7c9f4b" }
perm_read = { fg = "#ebcc1a" }
perm_sep = { fg = "#509c93" }
perm_type = { fg = "#6587bf" }
perm_write = { fg = "#db7070" }

progress_error = { fg = "#db7070", bg = "#fafafa" }
progress_label = { fg = "#474752", bg = "#fafafa" }
progress_normal = { fg = "#474752", bg = "#fafafa" }

[pick]
active = { fg = "#b870ce" }
border = { fg = "#6587bf" }
inactive = { fg = "#474752" }

[task]
title = { fg = "#6587bf" }
border = { fg = "#6587bf" }
hovered = { fg = "#474752", bg = "#acb1b9" }

[input]
border = { fg = "#6587bf" }
selected = { bg = "#acb1b9" }

[help]
desc = { fg = "#474752" }
on = { fg = "#509c93" }
run = { fg = "#b870ce" }
hovered = { reversed = true, bold = true }
footer = { fg = "#acb1b9", bg = "#474752" }

[which]
mask = { bg = "#acb1b9" }
desc = { fg = "#474752" }
cand = { fg = "#509c93" }
rest = { fg = "#509c93" }

separator_style = { fg = "#5e646f" }

[notify]
title_info = { fg = "#509c93" }
title_warn = { fg = "#ebcc1a" }
title_error = { fg = "#db7070" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#509c93" },
  { mime = "{audio, video}/*", fg = "#ebcc1a" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#7c9f4b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6587bf" },
  { mime = "*", fg = "#474752" },
]


