[mgr]
cwd = { fg = "#826d57" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#57826d" }
find_position = { fg = "#6d5782" }

marker_copied = { fg = "#6d8257", bg = "#6d8257" }
marker_cut = { fg = "#576d82", bg = "#576d82" }
marker_selected = { fg = "#57826d", bg = "#57826d" }

tab_inactive = { fg = "#323b43" }
tab_active = { fg = "#d1d6db", bg = "#323b43"}

count_copied = { fg = "#d1d6db", bg = "#6d8257" }
count_cut = { fg = "#d1d6db", bg = "#576d82" }
count_selected = { fg = "#d1d6db", bg = "#57826d" }

border_style = { fg = "#82576d" }

[mode]
normal_main = { fg = "#d1d6db", bg = "#82576d", bold = true }
normal_alt = { fg = "#82576d", bg = "#909aa3" }

select_alt = { fg = "#6d5782", bg = "#909aa3" }
select_main = { fg = "#d1d6db", bg = "#6d5782", bold = true }

unset_main = { fg = "#d1d6db", bg = "#576d82", bold = true }
unset_alt = { fg = "#576d82", bg = "#909aa3" }

[status]
perm_exec = { fg = "#6d8257" }
perm_read = { fg = "#57826d" }
perm_sep = { fg = "#826d57" }
perm_type = { fg = "#82576d" }
perm_write = { fg = "#576d82" }

progress_error = { fg = "#576d82", bg = "#d1d6db" }
progress_label = { fg = "#323b43", bg = "#d1d6db" }
progress_normal = { fg = "#323b43", bg = "#d1d6db" }

[pick]
active = { fg = "#6d5782" }
border = { fg = "#82576d" }
inactive = { fg = "#323b43" }

[task]
title = { fg = "#82576d" }
border = { fg = "#82576d" }
hovered = { fg = "#323b43", bg = "#909aa3" }

[input]
border = { fg = "#82576d" }
selected = { bg = "#909aa3" }

[help]
desc = { fg = "#323b43" }
on = { fg = "#826d57" }
run = { fg = "#6d5782" }
hovered = { reversed = true, bold = true }
footer = { fg = "#909aa3", bg = "#323b43" }

[which]
mask = { bg = "#909aa3" }
desc = { fg = "#323b43" }
cand = { fg = "#826d57" }
rest = { fg = "#575782" }

separator_style = { fg = "#47505a" }

[notify]
title_info = { fg = "#826d57" }
title_warn = { fg = "#57826d" }
title_warn = { fg = "#576d82" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#826d57" },
  { mime = "{audio, video}/*", fg = "#57826d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#6d8257" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#82576d" },
  { mime = "*", fg = "#323b43" },
]


