[manager]
cwd = { fg = "#6b6566" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f28171" }
find_position = { fg = "#a63650" }

marker_copied = { fg = "#806c61", bg = "#806c61" }
marker_cut = { fg = "#c24f57", bg = "#c24f57" }
marker_selected = { fg = "#f28171", bg = "#f28171" }

tab_inactive = { fg = "#a87569" }
tab_active = { fg = "#1c1213", bg = "#a87569"}

count_copied = { fg = "#1c1213", bg = "#806c61" }
count_cut = { fg = "#1c1213", bg = "#c24f57" }
count_selected = { fg = "#1c1213", bg = "#f28171" }

border_style = { fg = "#684c59" }

[mode]
normal_main = { fg = "#1c1213", bg = "#684c59", bold = true }
normal_alt = { fg = "#684c59", bg = "#563837" }

select_alt = { fg = "#a63650", bg = "#563837" }
select_main = { fg = "#1c1213", bg = "#a63650", bold = true }

unset_main = { fg = "#1c1213", bg = "#c24f57", bold = true }
unset_alt = { fg = "#c24f57", bg = "#563837" }

[status]
perm_exec = { fg = "#806c61" }
perm_read = { fg = "#f28171" }
perm_sep = { fg = "#6b6566" }
perm_type = { fg = "#684c59" }
perm_write = { fg = "#c24f57" }

progress_error = { fg = "#c24f57", bg = "#1c1213" }
progress_label = { fg = "#a87569", bg = "#1c1213" }
progress_normal = { fg = "#a87569", bg = "#1c1213" }

[pick]
active = { fg = "#a63650" }
border = { fg = "#684c59" }
inactive = { fg = "#a87569" }

[task]
title = { fg = "#684c59" }
border = { fg = "#684c59" }
hovered = { fg = "#a87569", bg = "#45475a" }

[input]
border = { fg = "#684c59" }
selected = { bg = "#563837" }

[help]
desc = { fg = "#a87569" }
on = { fg = "#6b6566" }
run = { fg = "#a63650" }
hovered = { reversed = true, bold = true }
footer = { fg = "#563837", bg = "#a87569" }

[which]
mask = { bg = "#563837" }
desc = { fg = "#a87569" }
cand = { fg = "#6b6566" }
rest = { fg = "#893f45" }

separator_style = { fg = "#8b5d57" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#6b6566" },
  { mime = "{audio, video}/*", fg = "#f28171" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#806c61" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#684c59", bold = true },
  { mime = "*", fg = "#a87569" },
]


