[manager]
cwd = { fg = "#008080" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#808000" }
find_position = { fg = "#800080" }

marker_copied = { fg = "#008000", bg = "#008000" }
marker_cut = { fg = "#800000", bg = "#800000" }
marker_selected = { fg = "#808000", bg = "#808000" }

tab_inactive = { fg = "#545454" }
tab_active = { fg = "#fcfcfc", bg = "#545454"}

count_copied = { fg = "#fcfcfc", bg = "#008000" }
count_cut = { fg = "#fcfcfc", bg = "#800000" }
count_selected = { fg = "#fcfcfc", bg = "#808000" }

border_style = { fg = "#000080" }

[mode]
normal_main = { fg = "#fcfcfc", bg = "#000080", bold = true }
normal_alt = { fg = "#000080", bg = "#d4d4d4" }

select_alt = { fg = "#800080", bg = "#d4d4d4" }
select_main = { fg = "#fcfcfc", bg = "#800080", bold = true }

unset_main = { fg = "#fcfcfc", bg = "#800000", bold = true }
unset_alt = { fg = "#800000", bg = "#d4d4d4" }

[status]
perm_exec = { fg = "#008000" }
perm_read = { fg = "#808000" }
perm_sep = { fg = "#008080" }
perm_type = { fg = "#000080" }
perm_write = { fg = "#800000" }

progress_error = { fg = "#800000", bg = "#fcfcfc" }
progress_label = { fg = "#545454", bg = "#fcfcfc" }
progress_normal = { fg = "#545454", bg = "#fcfcfc" }

[pick]
active = { fg = "#800080" }
border = { fg = "#000080" }
inactive = { fg = "#545454" }

[task]
title = { fg = "#000080" }
border = { fg = "#000080" }
hovered = { fg = "#545454", bg = "#45475a" }

[input]
border = { fg = "#000080" }
selected = { bg = "#d4d4d4" }

[help]
desc = { fg = "#545454" }
on = { fg = "#008080" }
run = { fg = "#800080" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d4d4d4", bg = "#545454" }

[which]
mask = { bg = "#d4d4d4" }
desc = { fg = "#545454" }
cand = { fg = "#008080" }
rest = { fg = "#54fc54" }

separator_style = { fg = "#7e7e7e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#008080" },
  { mime = "{audio, video}/*", fg = "#808000" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#008000" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#000080", bold = true },
  { mime = "*", fg = "#545454" },
]


