[mgr]
cwd = { fg = "#179299" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#df8e1d" }
find_position = { fg = "#8839ef" }

marker_copied = { fg = "#40a02b", bg = "#40a02b" }
marker_cut = { fg = "#d20f39", bg = "#d20f39" }
marker_selected = { fg = "#df8e1d", bg = "#df8e1d" }

tab_inactive = { fg = "#4c4f69" }
tab_active = { fg = "#eff1f5", bg = "#4c4f69"}

count_copied = { fg = "#eff1f5", bg = "#40a02b" }
count_cut = { fg = "#eff1f5", bg = "#d20f39" }
count_selected = { fg = "#eff1f5", bg = "#df8e1d" }

border_style = { fg = "#1e66f5" }

[mode]
normal_main = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
normal_alt = { fg = "#1e66f5", bg = "#bcc0cc" }

select_alt = { fg = "#8839ef", bg = "#bcc0cc" }
select_main = { fg = "#eff1f5", bg = "#8839ef", bold = true }

unset_main = { fg = "#eff1f5", bg = "#d20f39", bold = true }
unset_alt = { fg = "#d20f39", bg = "#bcc0cc" }

[status]
perm_exec = { fg = "#40a02b" }
perm_read = { fg = "#df8e1d" }
perm_sep = { fg = "#179299" }
perm_type = { fg = "#1e66f5" }
perm_write = { fg = "#d20f39" }

progress_error = { fg = "#d20f39", bg = "#eff1f5" }
progress_label = { fg = "#4c4f69", bg = "#eff1f5" }
progress_normal = { fg = "#4c4f69", bg = "#eff1f5" }

[pick]
active = { fg = "#8839ef" }
border = { fg = "#1e66f5" }
inactive = { fg = "#4c4f69" }

[task]
title = { fg = "#1e66f5" }
border = { fg = "#1e66f5" }
hovered = { fg = "#4c4f69", bg = "#bcc0cc" }

[input]
border = { fg = "#1e66f5" }
selected = { bg = "#bcc0cc" }

[help]
desc = { fg = "#4c4f69" }
on = { fg = "#179299" }
run = { fg = "#8839ef" }
hovered = { reversed = true, bold = true }
footer = { fg = "#bcc0cc", bg = "#4c4f69" }

[which]
mask = { bg = "#bcc0cc" }
desc = { fg = "#4c4f69" }
cand = { fg = "#179299" }
rest = { fg = "#dd7878" }

separator_style = { fg = "#6c6f85" }

[notify]
title_info = { fg = "#179299" }
title_warn = { fg = "#df8e1d" }
title_error = { fg = "#d20f39" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#179299" },
  { mime = "{audio, video}/*", fg = "#df8e1d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#40a02b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#1e66f5" },
  { mime = "*", fg = "#4c4f69" },
]


