[mgr]
cwd = { fg = "#1999b3" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#98981b" }
find_position = { fg = "#ad2bee" }

marker_copied = { fg = "#29a329", bg = "#29a329" }
marker_cut = { fg = "#e6193c", bg = "#e6193c" }
marker_selected = { fg = "#98981b", bg = "#98981b" }

tab_inactive = { fg = "#8ca68c" }
tab_active = { fg = "#131513", bg = "#8ca68c"}

count_copied = { fg = "#131513", bg = "#29a329" }
count_cut = { fg = "#131513", bg = "#e6193c" }
count_selected = { fg = "#131513", bg = "#98981b" }

border_style = { fg = "#3d62f5" }

[mode]
normal_main = { fg = "#131513", bg = "#3d62f5", bold = true }
normal_alt = { fg = "#3d62f5", bg = "#5e6e5e" }

select_alt = { fg = "#ad2bee", bg = "#5e6e5e" }
select_main = { fg = "#131513", bg = "#ad2bee", bold = true }

unset_main = { fg = "#131513", bg = "#e6193c", bold = true }
unset_alt = { fg = "#e6193c", bg = "#5e6e5e" }

[status]
perm_exec = { fg = "#29a329" }
perm_read = { fg = "#98981b" }
perm_sep = { fg = "#1999b3" }
perm_type = { fg = "#3d62f5" }
perm_write = { fg = "#e6193c" }

progress_error = { fg = "#e6193c", bg = "#131513" }
progress_label = { fg = "#8ca68c", bg = "#131513" }
progress_normal = { fg = "#8ca68c", bg = "#131513" }

[pick]
active = { fg = "#ad2bee" }
border = { fg = "#3d62f5" }
inactive = { fg = "#8ca68c" }

[task]
title = { fg = "#3d62f5" }
border = { fg = "#3d62f5" }
hovered = { fg = "#8ca68c", bg = "#5e6e5e" }

[input]
border = { fg = "#3d62f5" }
selected = { bg = "#5e6e5e" }

[help]
desc = { fg = "#8ca68c" }
on = { fg = "#1999b3" }
run = { fg = "#ad2bee" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5e6e5e", bg = "#8ca68c" }

[which]
mask = { bg = "#5e6e5e" }
desc = { fg = "#8ca68c" }
cand = { fg = "#1999b3" }
rest = { fg = "#e619c3" }

separator_style = { fg = "#809980" }

[notify]
title_info = { fg = "#1999b3" }
title_warn = { fg = "#98981b" }
title_warn = { fg = "#e6193c" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1999b3" },
  { mime = "{audio, video}/*", fg = "#98981b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#29a329" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#3d62f5" },
  { mime = "*", fg = "#8ca68c" },
]


