[manager]
cwd = { fg = "#1faaaa" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#aba800" }
find_position = { fg = "#ad00a1" }

marker_copied = { fg = "#00c918", bg = "#00c918" }
marker_cut = { fg = "#ff0086", bg = "#ff0086" }
marker_selected = { fg = "#aba800", bg = "#aba800" }

tab_inactive = { fg = "#d0d0d0" }
tab_active = { fg = "#151515", bg = "#d0d0d0"}

count_copied = { fg = "#151515", bg = "#00c918" }
count_cut = { fg = "#151515", bg = "#ff0086" }
count_selected = { fg = "#151515", bg = "#aba800" }

border_style = { fg = "#3777e6" }

[mode]
normal_main = { fg = "#151515", bg = "#3777e6", bold = true }
normal_alt = { fg = "#3777e6", bg = "#303030" }

select_alt = { fg = "#ad00a1", bg = "#303030" }
select_main = { fg = "#151515", bg = "#ad00a1", bold = true }

unset_main = { fg = "#151515", bg = "#ff0086", bold = true }
unset_alt = { fg = "#ff0086", bg = "#303030" }

[status]
perm_exec = { fg = "#00c918" }
perm_read = { fg = "#aba800" }
perm_sep = { fg = "#1faaaa" }
perm_type = { fg = "#3777e6" }
perm_write = { fg = "#ff0086" }

progress_error = { fg = "#ff0086", bg = "#151515" }
progress_label = { fg = "#d0d0d0", bg = "#151515" }
progress_normal = { fg = "#d0d0d0", bg = "#151515" }

[pick]
active = { fg = "#ad00a1" }
border = { fg = "#3777e6" }
inactive = { fg = "#d0d0d0" }

[task]
title = { fg = "#3777e6" }
border = { fg = "#3777e6" }
hovered = { fg = "#d0d0d0", bg = "#303030" }

[input]
border = { fg = "#3777e6" }
selected = { bg = "#303030" }

[help]
desc = { fg = "#d0d0d0" }
on = { fg = "#1faaaa" }
run = { fg = "#ad00a1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#303030", bg = "#d0d0d0" }

[which]
mask = { bg = "#303030" }
desc = { fg = "#d0d0d0" }
cand = { fg = "#1faaaa" }
rest = { fg = "#cc6633" }

separator_style = { fg = "#b0b0b0" }

[notify]
title_info = { fg = "#1faaaa" }
title_warn = { fg = "#aba800" }
title_warn = { fg = "#ff0086" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1faaaa" },
  { mime = "{audio, video}/*", fg = "#aba800" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#00c918" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#3777e6" },
  { mime = "*", fg = "#d0d0d0" },
]


