[mgr]
cwd = { fg = "#54fcfc" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fcfc54" }
find_position = { fg = "#fc54fc" }

marker_copied = { fg = "#54fc54", bg = "#54fc54" }
marker_cut = { fg = "#fc5454", bg = "#fc5454" }
marker_selected = { fg = "#fcfc54", bg = "#fcfc54" }

tab_inactive = { fg = "#a8a8a8" }
tab_active = { fg = "#000000", bg = "#a8a8a8"}

count_copied = { fg = "#000000", bg = "#54fc54" }
count_cut = { fg = "#000000", bg = "#fc5454" }
count_selected = { fg = "#000000", bg = "#fcfc54" }

border_style = { fg = "#5454fc" }

[mode]
normal_main = { fg = "#000000", bg = "#5454fc", bold = true }
normal_alt = { fg = "#5454fc", bg = "#383838" }

select_alt = { fg = "#fc54fc", bg = "#383838" }
select_main = { fg = "#000000", bg = "#fc54fc", bold = true }

unset_main = { fg = "#000000", bg = "#fc5454", bold = true }
unset_alt = { fg = "#fc5454", bg = "#383838" }

[status]
perm_exec = { fg = "#54fc54" }
perm_read = { fg = "#fcfc54" }
perm_sep = { fg = "#54fcfc" }
perm_type = { fg = "#5454fc" }
perm_write = { fg = "#fc5454" }

progress_error = { fg = "#fc5454", bg = "#000000" }
progress_label = { fg = "#a8a8a8", bg = "#000000" }
progress_normal = { fg = "#a8a8a8", bg = "#000000" }

[pick]
active = { fg = "#fc54fc" }
border = { fg = "#5454fc" }
inactive = { fg = "#a8a8a8" }

[task]
title = { fg = "#5454fc" }
border = { fg = "#5454fc" }
hovered = { fg = "#a8a8a8", bg = "#383838" }

[input]
border = { fg = "#5454fc" }
selected = { bg = "#383838" }

[help]
desc = { fg = "#a8a8a8" }
on = { fg = "#54fcfc" }
run = { fg = "#fc54fc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#383838", bg = "#a8a8a8" }

[which]
mask = { bg = "#383838" }
desc = { fg = "#a8a8a8" }
cand = { fg = "#54fcfc" }
rest = { fg = "#00a800" }

separator_style = { fg = "#7e7e7e" }

[notify]
title_info = { fg = "#54fcfc" }
title_warn = { fg = "#fcfc54" }
title_warn = { fg = "#fc5454" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#54fcfc" },
  { mime = "{audio, video}/*", fg = "#fcfc54" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#54fc54" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#5454fc" },
  { mime = "*", fg = "#a8a8a8" },
]


