[manager]
cwd = { fg = "#3971ed" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fba922" }
find_position = { fg = "#a36ac7" }

marker_copied = { fg = "#198844", bg = "#198844" }
marker_cut = { fg = "#cc342b", bg = "#cc342b" }
marker_selected = { fg = "#fba922", bg = "#fba922" }

tab_inactive = { fg = "#373b41" }
tab_active = { fg = "#ffffff", bg = "#373b41"}

count_copied = { fg = "#ffffff", bg = "#198844" }
count_cut = { fg = "#ffffff", bg = "#cc342b" }
count_selected = { fg = "#ffffff", bg = "#fba922" }

border_style = { fg = "#3971ed" }

[mode]
normal_main = { fg = "#ffffff", bg = "#3971ed", bold = true }
normal_alt = { fg = "#3971ed", bg = "#c5c8c6" }

select_alt = { fg = "#a36ac7", bg = "#c5c8c6" }
select_main = { fg = "#ffffff", bg = "#a36ac7", bold = true }

unset_main = { fg = "#ffffff", bg = "#cc342b", bold = true }
unset_alt = { fg = "#cc342b", bg = "#c5c8c6" }

[status]
perm_exec = { fg = "#198844" }
perm_read = { fg = "#fba922" }
perm_sep = { fg = "#3971ed" }
perm_type = { fg = "#3971ed" }
perm_write = { fg = "#cc342b" }

progress_error = { fg = "#cc342b", bg = "#ffffff" }
progress_label = { fg = "#373b41", bg = "#ffffff" }
progress_normal = { fg = "#373b41", bg = "#ffffff" }

[pick]
active = { fg = "#a36ac7" }
border = { fg = "#3971ed" }
inactive = { fg = "#373b41" }

[task]
title = { fg = "#3971ed" }
border = { fg = "#3971ed" }
hovered = { fg = "#373b41", bg = "#45475a" }

[input]
border = { fg = "#3971ed" }
selected = { bg = "#c5c8c6" }

[help]
desc = { fg = "#373b41" }
on = { fg = "#3971ed" }
run = { fg = "#a36ac7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#c5c8c6", bg = "#373b41" }

[which]
mask = { bg = "#c5c8c6" }
desc = { fg = "#373b41" }
cand = { fg = "#3971ed" }
rest = { fg = "#3971ed" }

separator_style = { fg = "#969896" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3971ed" },
  { mime = "{audio, video}/*", fg = "#fba922" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#198844" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#3971ed", bold = true },
  { mime = "*", fg = "#373b41" },
]


