[manager]
cwd = { fg = "#b4f9f8" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#0db9d7" }
find_position = { fg = "#bb9af7" }

marker_copied = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut = { fg = "#c0caf5", bg = "#c0caf5" }
marker_selected = { fg = "#0db9d7", bg = "#0db9d7" }

tab_inactive = { fg = "#a9b1d6" }
tab_active = { fg = "#24283b", bg = "#a9b1d6"}

count_copied = { fg = "#24283b", bg = "#9ece6a" }
count_cut = { fg = "#24283b", bg = "#c0caf5" }
count_selected = { fg = "#24283b", bg = "#0db9d7" }

border_style = { fg = "#2ac3de" }

[mode]
normal_main = { fg = "#24283b", bg = "#2ac3de", bold = true }
normal_alt = { fg = "#2ac3de", bg = "#343a52" }

select_alt = { fg = "#bb9af7", bg = "#343a52" }
select_main = { fg = "#24283b", bg = "#bb9af7", bold = true }

unset_main = { fg = "#24283b", bg = "#c0caf5", bold = true }
unset_alt = { fg = "#c0caf5", bg = "#343a52" }

[status]
perm_exec = { fg = "#9ece6a" }
perm_read = { fg = "#0db9d7" }
perm_sep = { fg = "#b4f9f8" }
perm_type = { fg = "#2ac3de" }
perm_write = { fg = "#c0caf5" }

progress_error = { fg = "#c0caf5", bg = "#24283b" }
progress_label = { fg = "#a9b1d6", bg = "#24283b" }
progress_normal = { fg = "#a9b1d6", bg = "#24283b" }

[pick]
active = { fg = "#bb9af7" }
border = { fg = "#2ac3de" }
inactive = { fg = "#a9b1d6" }

[task]
title = { fg = "#2ac3de" }
border = { fg = "#2ac3de" }
hovered = { fg = "#a9b1d6", bg = "#45475a" }

[input]
border = { fg = "#2ac3de" }
selected = { bg = "#343a52" }

[help]
desc = { fg = "#a9b1d6" }
on = { fg = "#b4f9f8" }
run = { fg = "#bb9af7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#343a52", bg = "#a9b1d6" }

[which]
mask = { bg = "#343a52" }
desc = { fg = "#a9b1d6" }
cand = { fg = "#b4f9f8" }
rest = { fg = "#f7768e" }

separator_style = { fg = "#787c99" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#b4f9f8" },
  { mime = "{audio, video}/*", fg = "#0db9d7" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#9ece6a" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#2ac3de", bold = true },
  { mime = "*", fg = "#a9b1d6" },
]


