[manager]
cwd = { fg = "#427b58" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#b57614" }
find_position = { fg = "#8f3f71" }

marker_copied = { fg = "#79740e", bg = "#79740e" }
marker_cut = { fg = "#9d0006", bg = "#9d0006" }
marker_selected = { fg = "#b57614", bg = "#b57614" }

tab_inactive = { fg = "#504945" }
tab_active = { fg = "#f2e5bc", bg = "#504945"}

count_copied = { fg = "#f2e5bc", bg = "#79740e" }
count_cut = { fg = "#f2e5bc", bg = "#9d0006" }
count_selected = { fg = "#f2e5bc", bg = "#b57614" }

border_style = { fg = "#076678" }

[mode]
normal_main = { fg = "#f2e5bc", bg = "#076678", bold = true }
normal_alt = { fg = "#076678", bg = "#d5c4a1" }

select_alt = { fg = "#8f3f71", bg = "#d5c4a1" }
select_main = { fg = "#f2e5bc", bg = "#8f3f71", bold = true }

unset_main = { fg = "#f2e5bc", bg = "#9d0006", bold = true }
unset_alt = { fg = "#9d0006", bg = "#d5c4a1" }

[status]
perm_exec = { fg = "#79740e" }
perm_read = { fg = "#b57614" }
perm_sep = { fg = "#427b58" }
perm_type = { fg = "#076678" }
perm_write = { fg = "#9d0006" }

progress_error = { fg = "#9d0006", bg = "#f2e5bc" }
progress_label = { fg = "#504945", bg = "#f2e5bc" }
progress_normal = { fg = "#504945", bg = "#f2e5bc" }

[pick]
active = { fg = "#8f3f71" }
border = { fg = "#076678" }
inactive = { fg = "#504945" }

[task]
title = { fg = "#076678" }
border = { fg = "#076678" }
hovered = { fg = "#504945", bg = "#45475a" }

[input]
border = { fg = "#076678" }
selected = { bg = "#d5c4a1" }

[help]
desc = { fg = "#504945" }
on = { fg = "#427b58" }
run = { fg = "#8f3f71" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d5c4a1", bg = "#504945" }

[which]
mask = { bg = "#d5c4a1" }
desc = { fg = "#504945" }
cand = { fg = "#427b58" }
rest = { fg = "#d65d0e" }

separator_style = { fg = "#665c54" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#427b58" },
  { mime = "{audio, video}/*", fg = "#b57614" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#79740e" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#076678", bold = true },
  { mime = "*", fg = "#504945" },
]


