[manager]
cwd = { fg = "#3a96dd" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c19c00" }
find_position = { fg = "#881798" }

marker_copied = { fg = "#13a10e", bg = "#13a10e" }
marker_cut = { fg = "#c50f1f", bg = "#c50f1f" }
marker_selected = { fg = "#c19c00", bg = "#c19c00" }

tab_inactive = { fg = "#767676" }
tab_active = { fg = "#f2f2f2", bg = "#767676"}

count_copied = { fg = "#f2f2f2", bg = "#13a10e" }
count_cut = { fg = "#f2f2f2", bg = "#c50f1f" }
count_selected = { fg = "#f2f2f2", bg = "#c19c00" }

border_style = { fg = "#0037da" }

[mode]
normal_main = { fg = "#f2f2f2", bg = "#0037da", bold = true }
normal_alt = { fg = "#0037da", bg = "#d9d9d9" }

select_alt = { fg = "#881798", bg = "#d9d9d9" }
select_main = { fg = "#f2f2f2", bg = "#881798", bold = true }

unset_main = { fg = "#f2f2f2", bg = "#c50f1f", bold = true }
unset_alt = { fg = "#c50f1f", bg = "#d9d9d9" }

[status]
perm_exec = { fg = "#13a10e" }
perm_read = { fg = "#c19c00" }
perm_sep = { fg = "#3a96dd" }
perm_type = { fg = "#0037da" }
perm_write = { fg = "#c50f1f" }

progress_error = { fg = "#c50f1f", bg = "#f2f2f2" }
progress_label = { fg = "#767676", bg = "#f2f2f2" }
progress_normal = { fg = "#767676", bg = "#f2f2f2" }

[pick]
active = { fg = "#881798" }
border = { fg = "#0037da" }
inactive = { fg = "#767676" }

[task]
title = { fg = "#0037da" }
border = { fg = "#0037da" }
hovered = { fg = "#767676", bg = "#d9d9d9" }

[input]
border = { fg = "#0037da" }
selected = { bg = "#d9d9d9" }

[help]
desc = { fg = "#767676" }
on = { fg = "#3a96dd" }
run = { fg = "#881798" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d9d9d9", bg = "#767676" }

[which]
mask = { bg = "#d9d9d9" }
desc = { fg = "#767676" }
cand = { fg = "#3a96dd" }
rest = { fg = "#16c60c" }

separator_style = { fg = "#ababab" }

[notify]
title_info = { fg = "#3a96dd" }
title_warn = { fg = "#c19c00" }
title_warn = { fg = "#c50f1f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#3a96dd" },
  { mime = "{audio, video}/*", fg = "#c19c00" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#13a10e" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0037da" },
  { mime = "*", fg = "#767676" },
]


