[manager]
cwd = { fg = "#5485b6" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#a06e3b" }
find_position = { fg = "#8464c4" }

marker_copied = { fg = "#4b8b8b", bg = "#4b8b8b" }
marker_cut = { fg = "#ca4949", bg = "#ca4949" }
marker_selected = { fg = "#a06e3b", bg = "#a06e3b" }

tab_inactive = { fg = "#8a8585" }
tab_active = { fg = "#1b1818", bg = "#8a8585"}

count_copied = { fg = "#1b1818", bg = "#4b8b8b" }
count_cut = { fg = "#1b1818", bg = "#ca4949" }
count_selected = { fg = "#1b1818", bg = "#a06e3b" }

border_style = { fg = "#7272ca" }

[mode]
normal_main = { fg = "#1b1818", bg = "#7272ca", bold = true }
normal_alt = { fg = "#7272ca", bg = "#585050" }

select_alt = { fg = "#8464c4", bg = "#585050" }
select_main = { fg = "#1b1818", bg = "#8464c4", bold = true }

unset_main = { fg = "#1b1818", bg = "#ca4949", bold = true }
unset_alt = { fg = "#ca4949", bg = "#585050" }

[status]
perm_exec = { fg = "#4b8b8b" }
perm_read = { fg = "#a06e3b" }
perm_sep = { fg = "#5485b6" }
perm_type = { fg = "#7272ca" }
perm_write = { fg = "#ca4949" }

progress_error = { fg = "#ca4949", bg = "#1b1818" }
progress_label = { fg = "#8a8585", bg = "#1b1818" }
progress_normal = { fg = "#8a8585", bg = "#1b1818" }

[pick]
active = { fg = "#8464c4" }
border = { fg = "#7272ca" }
inactive = { fg = "#8a8585" }

[task]
title = { fg = "#7272ca" }
border = { fg = "#7272ca" }
hovered = { fg = "#8a8585", bg = "#45475a" }

[input]
border = { fg = "#7272ca" }
selected = { bg = "#585050" }

[help]
desc = { fg = "#8a8585" }
on = { fg = "#5485b6" }
run = { fg = "#8464c4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#585050", bg = "#8a8585" }

[which]
mask = { bg = "#585050" }
desc = { fg = "#8a8585" }
cand = { fg = "#5485b6" }
rest = { fg = "#bd5187" }

separator_style = { fg = "#7e7777" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#5485b6" },
  { mime = "{audio, video}/*", fg = "#a06e3b" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#4b8b8b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7272ca", bold = true },
  { mime = "*", fg = "#8a8585" },
]


