[mgr]
cwd = { fg = "#0e7767" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#876500" }
find_position = { fg = "#7a50c6" }

marker_copied = { fg = "#557300", bg = "#557300" }
marker_cut = { fg = "#b14745", bg = "#b14745" }
marker_selected = { fg = "#876500", bg = "#876500" }

tab_inactive = { fg = "#4e5359" }
tab_active = { fg = "#fff5e5", bg = "#4e5359"}

count_copied = { fg = "#fff5e5", bg = "#557300" }
count_cut = { fg = "#fff5e5", bg = "#b14745" }
count_selected = { fg = "#fff5e5", bg = "#876500" }

border_style = { fg = "#246da5" }

[mode]
normal_main = { fg = "#fff5e5", bg = "#246da5", bold = true }
normal_alt = { fg = "#246da5", bg = "#d9d3c8" }

select_alt = { fg = "#7a50c6", bg = "#d9d3c8" }
select_main = { fg = "#fff5e5", bg = "#7a50c6", bold = true }

unset_main = { fg = "#fff5e5", bg = "#b14745", bold = true }
unset_alt = { fg = "#b14745", bg = "#d9d3c8" }

[status]
perm_exec = { fg = "#557300" }
perm_read = { fg = "#876500" }
perm_sep = { fg = "#0e7767" }
perm_type = { fg = "#246da5" }
perm_write = { fg = "#b14745" }

progress_error = { fg = "#b14745", bg = "#fff5e5" }
progress_label = { fg = "#4e5359", bg = "#fff5e5" }
progress_normal = { fg = "#4e5359", bg = "#fff5e5" }

[pick]
active = { fg = "#7a50c6" }
border = { fg = "#246da5" }
inactive = { fg = "#4e5359" }

[task]
title = { fg = "#246da5" }
border = { fg = "#246da5" }
hovered = { fg = "#4e5359", bg = "#d9d3c8" }

[input]
border = { fg = "#246da5" }
selected = { bg = "#d9d3c8" }

[help]
desc = { fg = "#4e5359" }
on = { fg = "#0e7767" }
run = { fg = "#7a50c6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d9d3c8", bg = "#4e5359" }

[which]
mask = { bg = "#d9d3c8" }
desc = { fg = "#4e5359" }
cand = { fg = "#0e7767" }
rest = { fg = "#a83f92" }

separator_style = { fg = "#5d6065" }

[notify]
title_info = { fg = "#0e7767" }
title_warn = { fg = "#876500" }
title_warn = { fg = "#b14745" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#0e7767" },
  { mime = "{audio, video}/*", fg = "#876500" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#557300" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#246da5" },
  { mime = "*", fg = "#4e5359" },
]


