[manager]
cwd = { fg = "#1fad83" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ae9513" }
find_position = { fg = "#b854d4" }

marker_copied = { fg = "#60ac39", bg = "#60ac39" }
marker_cut = { fg = "#d73737", bg = "#d73737" }
marker_selected = { fg = "#ae9513", bg = "#ae9513" }

tab_inactive = { fg = "#a6a28c" }
tab_active = { fg = "#20201d", bg = "#a6a28c"}

count_copied = { fg = "#20201d", bg = "#60ac39" }
count_cut = { fg = "#20201d", bg = "#d73737" }
count_selected = { fg = "#20201d", bg = "#ae9513" }

border_style = { fg = "#6684e1" }

[mode]
normal_main = { fg = "#20201d", bg = "#6684e1", bold = true }
normal_alt = { fg = "#6684e1", bg = "#6e6b5e" }

select_alt = { fg = "#b854d4", bg = "#6e6b5e" }
select_main = { fg = "#20201d", bg = "#b854d4", bold = true }

unset_main = { fg = "#20201d", bg = "#d73737", bold = true }
unset_alt = { fg = "#d73737", bg = "#6e6b5e" }

[status]
perm_exec = { fg = "#60ac39" }
perm_read = { fg = "#ae9513" }
perm_sep = { fg = "#1fad83" }
perm_type = { fg = "#6684e1" }
perm_write = { fg = "#d73737" }

progress_error = { fg = "#d73737", bg = "#20201d" }
progress_label = { fg = "#a6a28c", bg = "#20201d" }
progress_normal = { fg = "#a6a28c", bg = "#20201d" }

[pick]
active = { fg = "#b854d4" }
border = { fg = "#6684e1" }
inactive = { fg = "#a6a28c" }

[task]
title = { fg = "#6684e1" }
border = { fg = "#6684e1" }
hovered = { fg = "#a6a28c", bg = "#6e6b5e" }

[input]
border = { fg = "#6684e1" }
selected = { bg = "#6e6b5e" }

[help]
desc = { fg = "#a6a28c" }
on = { fg = "#1fad83" }
run = { fg = "#b854d4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#6e6b5e", bg = "#a6a28c" }

[which]
mask = { bg = "#6e6b5e" }
desc = { fg = "#a6a28c" }
cand = { fg = "#1fad83" }
rest = { fg = "#d43552" }

separator_style = { fg = "#999580" }

[notify]
title_info = { fg = "#1fad83" }
title_warn = { fg = "#ae9513" }
title_warn = { fg = "#d73737" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1fad83" },
  { mime = "{audio, video}/*", fg = "#ae9513" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#60ac39" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6684e1" },
  { mime = "*", fg = "#a6a28c" },
]


