[manager]
cwd = { fg = "#83c092" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#dbbc7f" }
find_position = { fg = "#d699b6" }

marker_copied = { fg = "#a7c080", bg = "#a7c080" }
marker_cut = { fg = "#e67e80", bg = "#e67e80" }
marker_selected = { fg = "#dbbc7f", bg = "#dbbc7f" }

tab_inactive = { fg = "#d3c6aa" }
tab_active = { fg = "#272e33", bg = "#d3c6aa"}

count_copied = { fg = "#272e33", bg = "#a7c080" }
count_cut = { fg = "#272e33", bg = "#e67e80" }
count_selected = { fg = "#272e33", bg = "#dbbc7f" }

border_style = { fg = "#7fbbb3" }

[mode]
normal_main = { fg = "#272e33", bg = "#7fbbb3", bold = true }
normal_alt = { fg = "#7fbbb3", bg = "#414b50" }

select_alt = { fg = "#d699b6", bg = "#414b50" }
select_main = { fg = "#272e33", bg = "#d699b6", bold = true }

unset_main = { fg = "#272e33", bg = "#e67e80", bold = true }
unset_alt = { fg = "#e67e80", bg = "#414b50" }

[status]
perm_exec = { fg = "#a7c080" }
perm_read = { fg = "#dbbc7f" }
perm_sep = { fg = "#83c092" }
perm_type = { fg = "#7fbbb3" }
perm_write = { fg = "#e67e80" }

progress_error = { fg = "#e67e80", bg = "#272e33" }
progress_label = { fg = "#d3c6aa", bg = "#272e33" }
progress_normal = { fg = "#d3c6aa", bg = "#272e33" }

[pick]
active = { fg = "#d699b6" }
border = { fg = "#7fbbb3" }
inactive = { fg = "#d3c6aa" }

[task]
title = { fg = "#7fbbb3" }
border = { fg = "#7fbbb3" }
hovered = { fg = "#d3c6aa", bg = "#45475a" }

[input]
border = { fg = "#7fbbb3" }
selected = { bg = "#414b50" }

[help]
desc = { fg = "#d3c6aa" }
on = { fg = "#83c092" }
run = { fg = "#d699b6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#414b50", bg = "#d3c6aa" }

[which]
mask = { bg = "#414b50" }
desc = { fg = "#d3c6aa" }
cand = { fg = "#83c092" }
rest = { fg = "#9da9a0" }

separator_style = { fg = "#9da9a0" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#83c092" },
  { mime = "{audio, video}/*", fg = "#dbbc7f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#a7c080" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#7fbbb3", bold = true },
  { mime = "*", fg = "#d3c6aa" },
]


