[mgr]
cwd = { fg = "#258fc4" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#faaea2" }
find_position = { fg = "#f768a3" }

marker_copied = { fg = "#faaea2", bg = "#faaea2" }
marker_cut = { fg = "#f768a3", bg = "#f768a3" }
marker_selected = { fg = "#faaea2", bg = "#faaea2" }

tab_inactive = { fg = "#606bac" }
tab_active = { fg = "#0a0920", bg = "#606bac"}

count_copied = { fg = "#0a0920", bg = "#faaea2" }
count_cut = { fg = "#0a0920", bg = "#f768a3" }
count_selected = { fg = "#0a0920", bg = "#faaea2" }

border_style = { fg = "#258fc4" }

[mode]
normal_main = { fg = "#0a0920", bg = "#258fc4", bold = true }
normal_alt = { fg = "#258fc4", bg = "#23255a" }

select_alt = { fg = "#f768a3", bg = "#23255a" }
select_main = { fg = "#0a0920", bg = "#f768a3", bold = true }

unset_main = { fg = "#0a0920", bg = "#f768a3", bold = true }
unset_alt = { fg = "#f768a3", bg = "#23255a" }

[status]
perm_exec = { fg = "#faaea2" }
perm_read = { fg = "#faaea2" }
perm_sep = { fg = "#258fc4" }
perm_type = { fg = "#258fc4" }
perm_write = { fg = "#f768a3" }

progress_error = { fg = "#f768a3", bg = "#0a0920" }
progress_label = { fg = "#606bac", bg = "#0a0920" }
progress_normal = { fg = "#606bac", bg = "#0a0920" }

[pick]
active = { fg = "#f768a3" }
border = { fg = "#258fc4" }
inactive = { fg = "#606bac" }

[task]
title = { fg = "#258fc4" }
border = { fg = "#258fc4" }
hovered = { fg = "#606bac", bg = "#23255a" }

[input]
border = { fg = "#258fc4" }
selected = { bg = "#23255a" }

[help]
desc = { fg = "#606bac" }
on = { fg = "#258fc4" }
run = { fg = "#f768a3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#23255a", bg = "#606bac" }

[which]
mask = { bg = "#23255a" }
desc = { fg = "#606bac" }
cand = { fg = "#258fc4" }
rest = { fg = "#f768a3" }

separator_style = { fg = "#4a5293" }

[notify]
title_info = { fg = "#258fc4" }
title_warn = { fg = "#faaea2" }
title_warn = { fg = "#f768a3" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#258fc4" },
  { mime = "{audio, video}/*", fg = "#faaea2" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#faaea2" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#258fc4" },
  { mime = "*", fg = "#606bac" },
]


