[mgr]
cwd = { fg = "#04d1f9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ffc777" }
find_position = { fg = "#b994f1" }

marker_copied = { fg = "#2df4c0", bg = "#2df4c0" }
marker_cut = { fg = "#ff5370", bg = "#ff5370" }
marker_selected = { fg = "#ffc777", bg = "#ffc777" }

tab_inactive = { fg = "#a3ace1" }
tab_active = { fg = "#212337", bg = "#a3ace1"}

count_copied = { fg = "#212337", bg = "#2df4c0" }
count_cut = { fg = "#212337", bg = "#ff5370" }
count_selected = { fg = "#212337", bg = "#ffc777" }

border_style = { fg = "#40ffff" }

[mode]
normal_main = { fg = "#212337", bg = "#40ffff", bold = true }
normal_alt = { fg = "#40ffff", bg = "#596399" }

select_alt = { fg = "#b994f1", bg = "#596399" }
select_main = { fg = "#212337", bg = "#b994f1", bold = true }

unset_main = { fg = "#212337", bg = "#ff5370", bold = true }
unset_alt = { fg = "#ff5370", bg = "#596399" }

[status]
perm_exec = { fg = "#2df4c0" }
perm_read = { fg = "#ffc777" }
perm_sep = { fg = "#04d1f9" }
perm_type = { fg = "#40ffff" }
perm_write = { fg = "#ff5370" }

progress_error = { fg = "#ff5370", bg = "#212337" }
progress_label = { fg = "#a3ace1", bg = "#212337" }
progress_normal = { fg = "#a3ace1", bg = "#212337" }

[pick]
active = { fg = "#b994f1" }
border = { fg = "#40ffff" }
inactive = { fg = "#a3ace1" }

[task]
title = { fg = "#40ffff" }
border = { fg = "#40ffff" }
hovered = { fg = "#a3ace1", bg = "#596399" }

[input]
border = { fg = "#40ffff" }
selected = { bg = "#596399" }

[help]
desc = { fg = "#a3ace1" }
on = { fg = "#04d1f9" }
run = { fg = "#b994f1" }
hovered = { reversed = true, bold = true }
footer = { fg = "#596399", bg = "#a3ace1" }

[which]
mask = { bg = "#596399" }
desc = { fg = "#a3ace1" }
cand = { fg = "#04d1f9" }
rest = { fg = "#ecb2f0" }

separator_style = { fg = "#a1abe0" }

[notify]
title_info = { fg = "#04d1f9" }
title_warn = { fg = "#ffc777" }
title_warn = { fg = "#ff5370" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#04d1f9" },
  { mime = "{audio, video}/*", fg = "#ffc777" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#2df4c0" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#40ffff" },
  { mime = "*", fg = "#a3ace1" },
]


