[manager]
cwd = { fg = "#7bbda4" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#f4bc87" }
find_position = { fg = "#a89bb9" }

marker_copied = { fg = "#beb55b", bg = "#beb55b" }
marker_cut = { fg = "#cb6077", bg = "#cb6077" }
marker_selected = { fg = "#f4bc87", bg = "#f4bc87" }

tab_inactive = { fg = "#d0c8c6" }
tab_active = { fg = "#3b3228", bg = "#d0c8c6"}

count_copied = { fg = "#3b3228", bg = "#beb55b" }
count_cut = { fg = "#3b3228", bg = "#cb6077" }
count_selected = { fg = "#3b3228", bg = "#f4bc87" }

border_style = { fg = "#8ab3b5" }

[mode]
normal_main = { fg = "#3b3228", bg = "#8ab3b5", bold = true }
normal_alt = { fg = "#8ab3b5", bg = "#645240" }

select_alt = { fg = "#a89bb9", bg = "#645240" }
select_main = { fg = "#3b3228", bg = "#a89bb9", bold = true }

unset_main = { fg = "#3b3228", bg = "#cb6077", bold = true }
unset_alt = { fg = "#cb6077", bg = "#645240" }

[status]
perm_exec = { fg = "#beb55b" }
perm_read = { fg = "#f4bc87" }
perm_sep = { fg = "#7bbda4" }
perm_type = { fg = "#8ab3b5" }
perm_write = { fg = "#cb6077" }

progress_error = { fg = "#cb6077", bg = "#3b3228" }
progress_label = { fg = "#d0c8c6", bg = "#3b3228" }
progress_normal = { fg = "#d0c8c6", bg = "#3b3228" }

[pick]
active = { fg = "#a89bb9" }
border = { fg = "#8ab3b5" }
inactive = { fg = "#d0c8c6" }

[task]
title = { fg = "#8ab3b5" }
border = { fg = "#8ab3b5" }
hovered = { fg = "#d0c8c6", bg = "#45475a" }

[input]
border = { fg = "#8ab3b5" }
selected = { bg = "#645240" }

[help]
desc = { fg = "#d0c8c6" }
on = { fg = "#7bbda4" }
run = { fg = "#a89bb9" }
hovered = { reversed = true, bold = true }
footer = { fg = "#645240", bg = "#d0c8c6" }

[which]
mask = { bg = "#645240" }
desc = { fg = "#d0c8c6" }
cand = { fg = "#7bbda4" }
rest = { fg = "#bb9584" }

separator_style = { fg = "#b8afad" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#7bbda4" },
  { mime = "{audio, video}/*", fg = "#f4bc87" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#beb55b" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#8ab3b5", bold = true },
  { mime = "*", fg = "#d0c8c6" },
]


