[manager]
cwd = { fg = "#00ffff" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#ff0099" }
find_position = { fg = "#cc00ff" }

marker_copied = { fg = "#33ff00", bg = "#33ff00" }
marker_cut = { fg = "#ff0000", bg = "#ff0000" }
marker_selected = { fg = "#ff0099", bg = "#ff0099" }

tab_inactive = { fg = "#d0d0d0" }
tab_active = { fg = "#000000", bg = "#d0d0d0"}

count_copied = { fg = "#000000", bg = "#33ff00" }
count_cut = { fg = "#000000", bg = "#ff0000" }
count_selected = { fg = "#000000", bg = "#ff0099" }

border_style = { fg = "#0066ff" }

[mode]
normal_main = { fg = "#000000", bg = "#0066ff", bold = true }
normal_alt = { fg = "#0066ff", bg = "#606060" }

select_alt = { fg = "#cc00ff", bg = "#606060" }
select_main = { fg = "#000000", bg = "#cc00ff", bold = true }

unset_main = { fg = "#000000", bg = "#ff0000", bold = true }
unset_alt = { fg = "#ff0000", bg = "#606060" }

[status]
perm_exec = { fg = "#33ff00" }
perm_read = { fg = "#ff0099" }
perm_sep = { fg = "#00ffff" }
perm_type = { fg = "#0066ff" }
perm_write = { fg = "#ff0000" }

progress_error = { fg = "#ff0000", bg = "#000000" }
progress_label = { fg = "#d0d0d0", bg = "#000000" }
progress_normal = { fg = "#d0d0d0", bg = "#000000" }

[pick]
active = { fg = "#cc00ff" }
border = { fg = "#0066ff" }
inactive = { fg = "#d0d0d0" }

[task]
title = { fg = "#0066ff" }
border = { fg = "#0066ff" }
hovered = { fg = "#d0d0d0", bg = "#45475a" }

[input]
border = { fg = "#0066ff" }
selected = { bg = "#606060" }

[help]
desc = { fg = "#d0d0d0" }
on = { fg = "#00ffff" }
run = { fg = "#cc00ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#606060", bg = "#d0d0d0" }

[which]
mask = { bg = "#606060" }
desc = { fg = "#d0d0d0" }
cand = { fg = "#00ffff" }
rest = { fg = "#3300ff" }

separator_style = { fg = "#c0c0c0" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00ffff" },
  { mime = "{audio, video}/*", fg = "#ff0099" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#33ff00" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#0066ff", bold = true },
  { mime = "*", fg = "#d0d0d0" },
]


