[mgr]
cwd = { fg = "#22a2c9" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#c08b30" }
find_position = { fg = "#6679cc" }

marker_copied = { fg = "#ac9739", bg = "#ac9739" }
marker_cut = { fg = "#c94922", bg = "#c94922" }
marker_selected = { fg = "#c08b30", bg = "#c08b30" }

tab_inactive = { fg = "#5e6687" }
tab_active = { fg = "#f5f7ff", bg = "#5e6687"}

count_copied = { fg = "#f5f7ff", bg = "#ac9739" }
count_cut = { fg = "#f5f7ff", bg = "#c94922" }
count_selected = { fg = "#f5f7ff", bg = "#c08b30" }

border_style = { fg = "#3d8fd1" }

[mode]
normal_main = { fg = "#f5f7ff", bg = "#3d8fd1", bold = true }
normal_alt = { fg = "#3d8fd1", bg = "#979db4" }

select_alt = { fg = "#6679cc", bg = "#979db4" }
select_main = { fg = "#f5f7ff", bg = "#6679cc", bold = true }

unset_main = { fg = "#f5f7ff", bg = "#c94922", bold = true }
unset_alt = { fg = "#c94922", bg = "#979db4" }

[status]
perm_exec = { fg = "#ac9739" }
perm_read = { fg = "#c08b30" }
perm_sep = { fg = "#22a2c9" }
perm_type = { fg = "#3d8fd1" }
perm_write = { fg = "#c94922" }

progress_error = { fg = "#c94922", bg = "#f5f7ff" }
progress_label = { fg = "#5e6687", bg = "#f5f7ff" }
progress_normal = { fg = "#5e6687", bg = "#f5f7ff" }

[pick]
active = { fg = "#6679cc" }
border = { fg = "#3d8fd1" }
inactive = { fg = "#5e6687" }

[task]
title = { fg = "#3d8fd1" }
border = { fg = "#3d8fd1" }
hovered = { fg = "#5e6687", bg = "#979db4" }

[input]
border = { fg = "#3d8fd1" }
selected = { bg = "#979db4" }

[help]
desc = { fg = "#5e6687" }
on = { fg = "#22a2c9" }
run = { fg = "#6679cc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#979db4", bg = "#5e6687" }

[which]
mask = { bg = "#979db4" }
desc = { fg = "#5e6687" }
cand = { fg = "#22a2c9" }
rest = { fg = "#9c637a" }

separator_style = { fg = "#6b7394" }

[notify]
title_info = { fg = "#22a2c9" }
title_warn = { fg = "#c08b30" }
title_warn = { fg = "#c94922" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#22a2c9" },
  { mime = "{audio, video}/*", fg = "#c08b30" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#ac9739" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#3d8fd1" },
  { mime = "*", fg = "#5e6687" },
]


